### PR TITLE
Here's my solution

### PR DESCRIPTION
**Pull request by laz-k**
This is a PR template. If you are adding a solution link to the curriculum, leave this as is. If not, delete it and write the message you wish.

Thank you,

The Odin Project team.

### CODE REVIEW

**Comment by 105ron** [comment]
Hi, there is a merge conflict in this PR. Please either resolve it or allow the maintainers to push commits to your fork so we can resolve and merge this for you. Thank you.

**Comment by laz-k** [comment]
I've allowed edits as I failed to resolve this. I would appreciate it if you could tell me what went wrong. I've just followed the video instructions on the contributing page. Thank you.

**Comment by 105ron** [comment]
Hi, someone has submitted a PR with a solution to this file after you have made your commit. Git then had two changes to the same line and it cannot merge automatically because it doesn't know which one it should use. In this instance we want to keep both but we need to do it manually. For some reason GitHub isn't letting me resolve it at the moment, it's something I'm looking into so I can fix it for you. In the meantime I'm asking students to resolve it but for those in the early stages of the curriculum it will be difficult.

**Comment by laz-k** [comment]
Hi, thanks for your reply. That makes sense now. Can you let me know how could I have fixed it?
Thanks

**Comment by 105ron** [comment]
The is a very button to resolve it towards the bottom of the page or they give you line by line instructions to resolve it via the command line which is pretty good, but the GitHub GUI way is the easiest.

**Pull request closed without merging**
