### PR TITLE
Update alternative video on how the internet works

### PR DESCRIPTION
**Pull request by kennguyen01**
The old BBC short from Vimeo has player issue for a while now and couldn't play the video. I updated the link to a more in depth video on YouTube.

### CODE REVIEW

**Comment by marvingay** [comment]
@kennguyen01 What "issue" with the player has been present for awhile?

It appears to be working on my end.

**Comment by kennguyen01** [comment]
The video is gray with the message “Player error: The player is having trouble." Last time I reviewed the material was a couple months back. Going back over it again and the video still doesn't play.

**Comment by marvingay** [comment]
@kennguyen01 
What browser do you use? 
And which continent are you accessing the website from?

We will look further into this.

Will merge if it's a prevailing issue and not an isolated issue.

**Comment by kennguyen01** [comment]
I'm using Firefox from the U.S.

**Comment by marvingay** [comment]
It's been attempted by several people, on several browsers and in different locations, without the ability to reproduce the issue.

It's possible your particular browser, an extension, or piece of software is inhibiting this functionality from working properly.

Closing.

**Pull request closed without merging**
