### PR TITLE
Git -> Intermediate Git (within JavaScript Course): Correct grammatical error

### PR DESCRIPTION
**Pull request by Slashmyaxl**
## Because

Grammatical error correction.

## This PR

- Within the "Splitting up a commit" section, redundant word "add" and accompanying punctuation removed.

## Issue

N/A

## Additional Information

N/A

## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [x] The `Because` section summarizes the reason for this PR
-   [x] The `This PR` section has a bullet point list describing the changes in this PR
-   [x] If this PR addresses an open issue, it is linked in the `Issue` section
-   [x] If any lesson files are included in this PR, they have been previewed with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure it is formatted correctly
-   [x] If any lesson files are included in this PR, they follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

### CODE REVIEW

**Comment by MaoShizhong** [comment]
@Slashmyaxl Thanks for resolving thr branching issue!

Would you be okay to also fix the lint errors? They should be fairly self explanatory (blank lines/fix the unordered list character). The dollar sign lint errors can be solved by simply removing the dollar signs from the start of each of those commands, as in their context, they're redundant.

**Comment by Slashmyaxl** [comment]
> @Slashmyaxl Thanks for resolving thr branching issue!
> 
> Would you be okay to also fix the lint errors? They should be fairly self explanatory (blank lines/fix the unordered list character). The dollar sign lint errors can be solved by simply removing the dollar signs from the start of each of those commands, as in their context, they're redundant.

Thank _you_ for the heads up and allowing me the chance to practice and correct my blunder. Funny that, just after having completed the very lesson in question regarding Git usage.

I did notice those lint errors, but wasn't sure how relevant they were to the maintainers to have addressed. I would be happy to get this lesson up to standard - look out for another commit by this evening (US time). Would you like me to create another PR, or just go ahead and add to this one (not sure if this is even possible)?

**Comment by MaoShizhong** [comment]
@Slashmyaxl Not a problem!
We're currently just making best judgement on this lint errors as to how we want them fixed if it's an unrelated PR. In this case, there aren't many and they're quite simple.

You can just make those changes on this same local branch, commit then push them as normal. The commit will find its way here automatically :)

No rush at all - take your time.

**Review by MaoShizhong — APPROVED** [review]
Thanks for doing this! :rocket:

**Pull request merged**
