### PR TITLE
Change the link to git tutorials by Atlassian

### PR DESCRIPTION
**Pull request by OlehSliusar**
It looks much better

### CODE REVIEW

**Comment by OlehSliusar** [comment]
Pull request merged, but the file has its previous version. Why?

**Comment by KevinMulhern** [comment]
@OlehSliusar the content is updated on the main site once everyday in a rake task. It usually happens early in the morning 😄

**Comment by OlehSliusar** [comment]
I mean not on the main site, but in the repository on GitHub:

[https://github.com/TheOdinProject/curriculum/blob/master/web_development_101/git_basics.md](https://github.com/TheOdinProject/curriculum/blob/master/web_development_101/git_basics.md)

On the main site it should also be updated, since pull request was 5 days ago.

**Comment by KevinMulhern** [comment]
Hmm did this Pull request have a merge conflict?

**Comment by OlehSliusar** [comment]
@KevinMulhern I don't think so. At least it didn't have when was created.

**Comment by OlehSliusar** [comment]
@KevinMulhern I can create a new pull request with this change.

**Comment by KevinMulhern** [comment]
No problem @OlehSliusar thanks.

**Pull request merged**
