### PR TITLE
Ruby on Rails Databases Course: Improve link text accessiblity

### PR DESCRIPTION
**Pull request by AhmedTheGreatest**
## Because

There were issues with the accessiblity of the link texts in the Databases course of the Ruby on Rails curriculum.

## This PR

- Improve link text accessibility in Databases lesson.
- Improve link text accessibility in Project SQL Zoo.

## Issue

Related to #28290

## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project curriculum contributing guide](https://github.com/TheOdinProject/curriculum/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [x] The `Because` section summarizes the reason for this PR
-   [x] The `This PR` section has a bullet point list describing the changes in this PR
-   [x] If this PR addresses an open issue, it is linked in the `Issue` section
-   [x] If any lesson files are included in this PR, they have been previewed with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure it is formatted correctly
-   [x] If any lesson files are included in this PR, they follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

### CODE REVIEW

**Comment by AhmedTheGreatest** [comment]
Should I fix the markdown lint errors? (The ones that can be auto-fixed)

**Comment by AhmedTheGreatest** [comment]
Most of them didn't get auto fixed I think... If you want let me know and Ill fix them manually. Thanks

**Comment by CouchofTomato** [comment]
If you could fix them it would be appreciated.

**Comment by MaoShizhong** [comment]
@AhmedTheGreatest Sometimes, due to multiple errors affecting the same line or group of lines, you need to run the appropriate fix script more than once to catch all of the autofixable errors.

You'll also need to do the same with the SQL Zoo project, but using the project fix script instead.

**Comment by AhmedTheGreatest** [comment]
Okay, thanks. i'll try to fix them.

**Pull request merged**
