### PR TITLE
Introduction to Flexbox lesson: fix first image

### LINKED ISSUE #27386: <Introduction to Flexbox>: <Introducing concepts not covered in lesson>
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

# Summary

As stated in #26137, there are some concepts like `gap` that aren't referred to or explained anywhere in the current lesson.

Since lessons in the Odin Project do highlight when a concept is introduced that is _not_ in the current lesson, not finding an explanation for the gap confused me.

# Description
image

The above image looked off, so I tried to recreate it only to find out that the given CSS properties don't give the same output.

I then tried to play around with the margins and reached the conclusion that I had to add margins to the item in the middle (and only this item) to get the given output. 

It was after this that I looked up the issues here and found #26137 which mentioned the `gap` property. 

This explained everything.

Hitherto, if there is something that is going to be explained in the upcoming lessons yet is somehow mentioned or referred to in the current lesson, there is always a call-out of some sorts. This set some (good) expectations going ahead. 

You can see an example below from [this lesson](https://www.theodinproject.com/lessons/foundations-the-box-model): 

image

# Suggestions
To improve the learning experience, we should consider either of the following suggestions:
### 1. Edit the image
We can change the CSS in the image and include the gap property. Keen learners can look this up or infer that this is what adds the space between the items when there is no `margin` defined.
### 2. [Preferred] Add a call-out 
Alternatively, we can add a small call-out below the image that mentions the gap property and nudges learners to the issues section as so:

> "...remember, if you don't understand something, feel free to Google or look up issues here..."

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-introduction-to-flexbox

### (Optional) Discord Name

749cake

### (Optional) Additional Comments

_No response_

### PR DESCRIPTION
**Pull request by 749cakeee**
## This PR
- Updates the first image on [this page](https://www.theodinproject.com/lessons/foundations-introduction-to-flexbox).

## Issue
Related to #27386

### CODE REVIEW

**Comment by MaoShizhong** [comment]
@749cakeee you've opened this pull request as a draft, so I cannot review it. I presume you didn't intend to open it as a draft? If so, if you mark it "ready for review" then I can review it.

**Comment by MaoShizhong** [comment]
Also just noticed - could you edit the arrow for `flex-container` so that's it's more obviously pointing to the container itself and not like it's pointing to the first flex item? Just have it end right before the container border should be fine.

You can commit and push the edited image to the same branch here and it'll automatically update this PR.

**Comment by 749cakeee** [comment]
Hey @MaoShizhong, thanks for the pointers!

I opened this PR as a draft so you could take a look at it once before it was marked "ready for review". In retrospect, this seems unnecessary in this situation. But in general software development, is it a good practice to do so? Just curious 😄

Also, I've edited the arrow for flex-container. It now points to the container itself, so there should be no confusion now.

Once again, thanks for all the assistance, and more importantly, the patience you've shown along the way! 😇

I don't know if others point this out, but it's really encouraging for someone who's still learning these workflows/software development in general to have someone that guides them calmly instead of getting irked by their lack of understanding/knowledge.

Have a great weekend! 🫡

**Review by MaoShizhong — APPROVED** [review]
@749cakeee No problem, that's what we're here for. We all started somewhere once (my first PR was changing a single word :shrug:).

Normally, just open a full PR (not a draft). Then any one of the maintainers can review it and any context (e.g. linked issue) and approve/add comments/formally request changes. Can't do that the proper way if it's a draft, which is generally more for "not ready to be reviewed - still in the process of writing up/pushing commits to it".

Thanks for getting the container arrow fixed - looks much better now!

Whenever you're ready, you can go ahead and do the 2nd PR as per the the "statically" part of the [adding images to the curriculum repo](https://github.com/TheOdinProject/curriculum/wiki/Adding-Images-to-the-Curriculum#create-statically-links) instructions to generate the right link and use it to replace the appropriate image link in the lesson.

**Pull request merged**
