### PR TITLE
Ruby Course: Basic Data Types: fix text for booleans

### PR DESCRIPTION
**Pull request by Colo-Codes**
## Because

In Ruby `nil` value shouldn't be considered as a boolean but as a falsy value. Also, as Ruby doesn't have a Boolean class, this word shouldn't be capitalised in order to avoid confusion. Ruby doesn't have a `Boolean` class, it has `TrueClass` and `FalseClass` instead.

## This PR

- Remove `nil` as being included as a boolean.
- Remove boolean capitalisation as it's not a class name.

## Issue

No issue is present.

## Additional Information

No additional information.

## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [x] The `Because` section summarizes the reason for this PR
-   [x] The `This PR` section has a bullet point list describing the changes in this PR
-   [ ] If this PR addresses an open issue, it is linked in the `Issue` section
-   [x] If any lesson files are included in this PR, they have been previewed with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure it is formatted correctly
-   [x] If any lesson files are included in this PR, they follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

### CODE REVIEW

**Comment by ChargrilledChook** [comment]
Thanks for the suggestion @Colo-Codes, but I think there's a bit of nuance here. 

The capitalisation of Boolean is correct due to the term originating from a name.

On the point about `nil` not being a Boolean; while strictly correct under a classical definition  there are systems of 3 state logic where null is the 3rd value. SQL for example allows storing null in a Boolean field; hence the term "tri state Boolean".

Even if it's not strictly correct, I think it's enough of a special case that it makes sense to be introduced where it is. Perhaps a note that it's not a 'real' Boolean could be useful; but I would be cautious to go too deep into it given this is a very introductory lesson. 

Let me know your thoughts or if I've misunderstood your intent

**Review by ChargrilledChook — CHANGES_REQUESTED** [review]
Thanks for the suggestion @Colo-Codes, but I think there's a bit of nuance here. 

The capitalisation of Boolean is correct due to the term originating from a name.

On the point about `nil` not being a Boolean; while strictly correct under a classical definition  there are systems of 3 state logic where null is the 3rd value. SQL for example allows storing null in a Boolean field; hence the term "tri state Boolean".

Even if it's not strictly correct, I think it's enough of a special case that it makes sense to be introduced where it is. Perhaps a note that it's not a 'real' Boolean could be useful; but I would be cautious to go too deep into it given this is a very introductory lesson. 

Let me know your thoughts or if I've misunderstood your intent

**Comment by Colo-Codes** [comment]
Thanks for clarifying this issue, @ChargrilledChook. I wasn't aware of the concept of "tri-state Boolean", and I agree that presenting too much detail early on in the course can create confusion. I wish `nil` could be explained differently at the beginning of the course, though. Still, I guess that treating it as another Boolean value makes sense.

Even better, maybe a more accurate treatment of these boolean values could be achieved by explaining "truthy" and "falsy" values, and how `nil` is included in the "falsy" group.

Off-topic: it's nice to be interacting with another person from Australia and discussing Ruby concepts with them :D

**Comment by KevinMulhern** [comment]
Hey @Colo-Codes, @ChargrilledChook, is there a next action to be done with this one or can it be closed?

**Pull request closed without merging**
