### PR TITLE
Arrays Lesson: Add extra info about `Array#first` and `Array#last`

### PR DESCRIPTION
**Pull request by Samuelodan**
This is in the "Accessing Elements" section.
having this info helped me when working on one of the exercises that followed this lesson, so I thought it'd be nice to have it mentioned.

## Because
Having this info helped me when working on one of the exercises that followed this lesson, so I thought it'd be nice to have it mentioned.

## This PR
- adds extra info about the behaviour of the `#last` and `#first` Array methods.

## Issue

Closes #XXXXX

## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [x] The `Because` section summarizes the reason for this PR
-   [x] The `This PR` section has a bullet point list describing the changes in this PR
-   [x] If this PR addresses an open issue, it is linked in the `Issue` section
-   [x] If any lesson files are included in this PR, they have been previewed with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure it is formatted correctly
-   [x] If any lesson files are included in this PR, they follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

### CODE REVIEW

**Comment by KevinMulhern** [comment]
Hi @Samuelodan, thanks once again for contributing. Which exercise did this help you with?

**Comment by Samuelodan** [comment]
Hi @KevinMulhern , it was this exercise:

```
def last_three_elements(array)
  # return the last 3 elements of the array
  if array.size < 3
    return array[0..-1]
  end
  array[-3, 3]
end
```
With my solution from that time.

I didn't know how the method worked, so I thought I had to guard for when the array size is less than 3.

But with that extra info, I think more people will be inclined to do

```
def last_three_elements(array)
  # return the last 3 elements of the array
  array.last(3)
end
```
without writing defensive code.

**Comment by Samuelodan** [comment]
Oh, it was the array exercise from the `ruby-exercise` repo.

**Comment by Samuelodan** [comment]
Okay, fair enough @KevinMulhern since there's many more methods with less obvious behavior like this.

Linking to the docs on the methods sounds fine. It'll prolly help expose learners to the docs more often, and it'll be up to them to notice these nuanced details in the method implementation.

Thanks for taking this PR into consideration and providing such detailed feedback.

**Comment by KevinMulhern** [comment]
Thanks for understanding @Samuelodan, I really appreciate all the PR's you've been making mate.

**Pull request closed without merging**
