### PR TITLE
Updated merge conflicts

### PR DESCRIPTION
**Pull request by jtcaovan**
- [x] You have read [The Odin Projects Contributing Guide](https://github.com/TheOdinProject/curriculum/blob/main/CONTRIBUTING.md).
 - [x] The PR title summarizes the change and where it happened, for example: "Fixes punctuation in Clean Code lesson".
 
#### 1.Describe the changes made and include why they are necessary or important:

Updated knowledge checks for OOP Principles - JavaScript

#### 2. If this PR is related to an open issue please reference it with the `#` operator and the issue number below:

#22472

### CODE REVIEW

**Comment by twalton83** [comment]
Hey, you can solve merge conflicts in the same PR. Last time I said you can make a new PR because you did something incorrectly. The one I just mentioned, you can follow the instructions Github provides.

**Comment by twalton83** [comment]
Actually, what’s the difference between this and #22770

**Comment by jtcaovan** [comment]
I apologize, the previous force push issue had me confused and something went wrong again. Not sure why the commit messages are the same, but #22769 resolves the previous merge conflict issues I was having (Object Constructors - JavaScript). This (#22770) adds the knowledge check for a new section (OOP Principles - JavaScript). Sorry! Thanks for your patience.

**Comment by twalton83** [comment]
Closed by #22769. If you're in our Discord feel free to always drop by and ask about Git stuff.

**Pull request merged**
