### PR TITLE
Update setting_up_git.md

### PR DESCRIPTION
**Pull request by G-O-J-O-U-S-A-T-O-R-U**
## Because

This command prompt would be useful for those with legacy system since they can't generate a SSH key with the previous command.

## This PR

Able to generate SSH keys for legacy system users. 
Easy method and helps those people who are confused.

## Issue

Closes #XXXXX
`<Manon removed related to PR>`
## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [x] The `Because` section summarizes the reason for this PR
-   [x] The `This PR` section has a bullet point list describing the changes in this PR
-   [x] If this PR addresses an open issue, it is linked in the `Issue` section
-   [x] If any lesson files are included in this PR, they have been previewed with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure it is formatted correctly
-   [x] If any lesson files are included in this PR, they follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

### CODE REVIEW

**Comment by G-O-J-O-U-S-A-T-O-R-U** [comment]
The article and the lesson does not address the issue with not being able to create an SSH key for legacy system users. I guess a lot students who are learning are legacy system users. The edited command prompt would be helpful for them to generate a SSH key.

**Comment by ManonLef** [comment]
I have not seen any issues surrounding this come up to be honest and wonder if legacy systems don't have bigger problems like meeting homebrew requirements etc. That SSH lesson has been updated to `ed25519` over a year ago now I believe. However, I'm not an expert on these installations so will ask the other maintainers.

@TheOdinProject/foundations any opinions

**Comment by ManonLef** [comment]
This issue does not seem related to the PR you linked. Please leave the section empty when unrelated to anything.

**Comment by thatblindgeye** [comment]
If we do want to add this to the lesson, we should use a note box instead of the "Note:" text.

**Comment by xandora** [comment]
I'm going close this one based on the same reasoning from #26022 , we can't provide instructions for users that aren't using our recommended versions. It would be impossible to cater to everyone.

Again, if you can provide a situation where a user that is following along with our curriculum and is using our recommended versions of software needs to have these instructions, we can reconsider this PR.

**Comment by G-O-J-O-U-S-A-T-O-R-U** [comment]
> I'm going close this one based on the same reasoning from #26022 , we can't provide instructions for users that aren't using our recommended versions. It would be impossible to cater to everyone.

It might not affect the users that has Ubuntu, but mostly students who learn from various parts seem to have windows with them as default and since the obtaining of the public key would be a little different for them it would be really helpful for users who are learning from windows. Since this is the beginning for a new learner to set up git, and most students from various countries have windows it makes a little harder for them to set up git or obtain the SSH key with these command prompts. A beginner won't be aware of his system completely and upon using the CMD for ubuntu will confuse them and will be blocking their progress to the next stage. The rest of the CMD works fine in the Windows, except for the CMD required for obtaining and to copy the SSH key. Hope this explanation would be really helpful in reviewing the issue once again. :)

**Comment by codyloyd** [comment]
We explicitly tell students in our lessons that we do not support windows.  If students choose to try to use it anyway, they are on their own when it comes to debugging issues.

**Pull request closed without merging**
