### PR TITLE
Adding my Active record project

### PR DESCRIPTION
**Pull request by mohamedosamaeltayeb**
This is an Active record project no front end

This is a PR template. If you are adding a solution link to the curriculum, leave this as is. If not, delete it and write the message you wish.

Thank you,

The Odin Project team.

### CODE REVIEW

**Comment by ZachBaird** [comment]
Hey @mohamedosamaeltayeb ! It looks like your changes accidentally remove another student's submission. Could you revert that change so we only get your link?

**Comment by ZachBaird** [comment]
@mohamedosamaeltayeb I've gone ahead and re-added the missing student submission. In the future, you can preview your pull requests changes (and potentially catch accidental inclusions) by checking the "Files Changed" tab to the right on the pull request :)

**Comment by mohamedosamaeltayeb** [comment]
Hey Zach I’m so sorry for what happened , it was all by mistake and thanks for taking careThanks again Sent from Mail for Windows 10 From: Zach BairdSent: Saturday, May 9, 2020 7:20 PMTo: TheOdinProject/curriculumCc: mohamedosamaeltayeb; MentionSubject: Re: [TheOdinProject/curriculum] Adding my Active record project (#16876) Merged #16876 into master.—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by ZachBaird** [comment]
@mohamedosamaeltayeb No worries! It happens :)

**Comment by mohamedosamaeltayeb** [comment]
Hey Zach
i believe my solution didn't appear in the Odin project web page / Active
record project section
Thanks

**Comment by ZachBaird** [comment]
Hello @mohamedosamaeltayeb ! I just checked and it's there at the top now. Here's the [link](https://www.theodinproject.com/courses/ruby-on-rails/lessons/building-with-active-record-ruby-on-rails)!

You might have checked before the updates were deployed. Student solutions are uploaded to the site right away, they get updated nightly :)

**Comment by mohamedosamaeltayeb** [comment]
thanks

**Pull request merged**
