### PR TITLE
Update rbenv ruby install to 2.7.2

### PR DESCRIPTION
**Pull request by LrdVnz**
- [ ] You have read [The Odin Projects Contributing Guide](https://github.com/TheOdinProject/curriculum/blob/master/CONTRIBUTING.md).

#### 1.Describe the changes made:

Latest stable ruby version is 2.7.2 (rubocop currently puts a warning if using 2.7.0 also I think it has incompatibility issues)
change to rbenv install 2.7.2 and rbenv global 2.7.2

#### 2. If this PR is related to an open issue please reference it with the `#` operator and the issue number below:

#XXXXX

### CODE REVIEW

**Comment by I3uckwheat** [comment]
@LrdVnz Has this been tested with the rails version we suggest in TOP?

**Comment by LrdVnz** [comment]
> @LrdVnz Has this been tested with the rails version we suggest in TOP?

@I3uckwheat No, does it need to be tested ? If I try to install rails its enough as a test ?

**Comment by I3uckwheat** [comment]
@LrdVnz Of course it needs to be tested. If this breaks our instructions, it means that thousands of students will be effected.

**Review by marvingay — APPROVED** [review]
Verified the warnings with Core.
There isn't anything immediately concerning in the release notes or commit log.

Will make appropriate change in Ruby exercises.

Thank you for the contribution.

**Comment by LrdVnz** [comment]
Thanks, couldn't do it as I didn't know how to do this exactly.

**Pull request merged**
