### PR TITLE
Add Luchillo's project_building_blocks solutions

### PR DESCRIPTION
**Pull request by Luchillo**
```
This is a PR template, If you are adding a solution link to the curriculum leave this as is. If you are not, then delete it and write the message you wish.
Thank you,
The Odin Project team.
```

### CODE REVIEW

**Comment by KevinMulhern** [comment]
Hi @Luchillo can you add your solutions to the bottom of the lists please, thanks

**Comment by Luchillo** [comment]
Oh ok, i will.

**Comment by Luchillo** [comment]
Updated and added next project solutions in same patch, also at end of solutions.

**Comment by KevinMulhern** [comment]
👍 thanks @Luchillo, other solutions have been added to the same file since you opened this pull request so there is a merge conflict. No big deal though I will fix it as soon as I get a chance.

**Comment by Luchillo** [comment]
Thanks to you, btw how would i pull the changes to the fork in such cases?, basically how would i pull the most recent changes of the original repo?.

**Comment by KevinMulhern** [comment]
On your fork on your local machine you would first need to ensure that you have set the original curriculum repo as a remote. Check your remotes with `git remote -v`.

If you only have one remote it's probably your forked repo on github.

To add the original as a remote you would simply do this on your local machine: `git remote add upstream git@github.com:TheOdinProject/curriculum.git`

With that done you can pull down any changes to your forked version with: `git pull upstream master`

**Comment by Luchillo** [comment]
Ok what if i made the changes online through github? in such case i need to clone my repo, add the original repo as remote and then pull the changes?

**Comment by KevinMulhern** [comment]
if you made changes to your forked version of the repo or the original repo through github?

**Comment by Luchillo** [comment]
Yes, i did the changes online through github page to my forked copy of the original repo.

**Comment by KevinMulhern** [comment]
ah ok, you made your changes on a branch https://github.com/Luchillo/curriculum/branches

**Comment by Luchillo** [comment]
When i edit using github, it forks, creates a branch named `patch-#` an let me edit the file i wanted to with one click, i guess i would have to clone my repo, checkout the master, pull changes, merge master into patch-1, push to github and then it would have my changes as well as the updated ones right?, so do i do that or you will fix the conflicts?

**Comment by KevinMulhern** [comment]
Exactly right 👍

**Comment by Luchillo** [comment]
Sorry, which one, do i pull the changes or you fix the conflicts?

**Comment by KevinMulhern** [comment]
It's really up to you, if you want to do it I wont mind if you want to do it 😉

**Pull request merged**
