### PR TITLE
Objects and Object Constructors: Fix ellipsis formatting

### PR DESCRIPTION
**Pull request by hafiz-muhammad**
## Because

There is supposed to be an ellipsis that consists of a set of three periods, not two.
> At first glance, the first doesn’t seem so bad.. 

## This PR

- Fixes incorrect ellipsis formatting in the [Objects as a design pattern](https://www.theodinproject.com/lessons/node-path-javascript-objects-and-object-constructors#objects-as-a-design-pattern) section.

## Issue

Closes #XXXXX

## Pull Request Requirements

-   [x ] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
-   [x ] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [x ] The `Because` section summarizes the reason for this PR
-   [x ] The `This PR` section has a bullet point list describing the changes in this PR
-   [ ] If this PR addresses an open issue, it is linked in the `Issue` section
-   [ ] If any lesson files are included in this PR, they have been previewed with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure it is formatted correctly
-   [ ] If any lesson files are included in this PR, they follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

### CODE REVIEW

**Review by MaoShizhong — APPROVED** [review]
Subtle but great spot! :eagle: :eyes:

**Comment by MaoShizhong** [comment]
Just noticed that you made this PR from your fork's `main` branch.
For any future PRs, best would be to follow the [contributing guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md#working-on-an-issue)'s instructions to create a new branch off main, then commit/push changes in that branch.

That way, if you were to start working on a separate thing before the first branch's work has been completed, you can checkout back to main and make a second branch to make sure your separate work's changes don't interfere with the first.
If you do everything in main, you can end up with a lot of issues with unrelated commits in different PRs, rather than keeping things separate.

**Comment by hafiz-muhammad** [comment]
> Just noticed that you made this PR from your fork's `main` branch. For any future PRs, best would be to follow the [contributing guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md#working-on-an-issue)'s instructions to create a new branch off main, then commit/push changes in that branch.
> 
> That way, if you were to start working on a separate thing before the first branch's work has been completed, you can checkout back to main and make a second branch to make sure your separate work's changes don't interfere with the first. If you do everything in main, you can end up with a lot of issues with unrelated commits in different PRs, rather than keeping things separate.

I apologize about that. I will remember that for future pull requests.

**Comment by MaoShizhong** [comment]
No need to apologise! Just trying to avoid a headache in the future, mainly for you.
It also means it's easy to sync your fork's main with upstream main without messing up anything in your open branches.
If you had unmerged changes in your fork's main, then tried to sync it with upstream main, you'd likely have a very rough time trying to fix it all.

**Pull request merged**
