### PR TITLE
try to fix the list bug

### PR DESCRIPTION
**Pull request by vladthelittleone**
Снимок экрана 2019-11-11 в 21 37 47

### CODE REVIEW

**Comment by vladthelittleone** [comment]
the same bug in blog project
Снимок экрана 2019-11-11 в 21 41 46

**Comment by mindovermiles262** [comment]
There needs to be an extra line between the two bullet points.

You can set up the dev environment of TOP by following the instructions in the [wiki](https://github.com/TheOdinProject/theodinproject/wiki) to verify that your changes take the effect you want.

You'll have to set up the dev environment and then change the rails app to pull from your local repository. All instructions are in the wiki

[Setup Instructions](https://github.com/TheOdinProject/theodinproject/wiki/Linux-Installation-Guide)
There's also a guide for mac if that's what you use

[Pulling lessons from your own fork](https://github.com/TheOdinProject/theodinproject/wiki/Updating-Lessons-from-your-own-fork)

Let me know if you have any problems.

**Comment by vladthelittleone** [comment]
@mindovermiles262 tnx, i'll try.

**Comment by mindovermiles262** [comment]
Closed due to inactivity

**Pull request closed without merging**
