### PR TITLE
Add Railscasts videos to additional resources

### PR DESCRIPTION
**Pull request by lujanfernaud**
Add Railscasts videos about authentication from scratch, remember session, and password reset.

### CODE REVIEW

**Comment by arun1595** [comment]
@lujanfernaud Railscasts PRO episodes are free now. How about linking the students to Railscasts instead of Youtube?

**Comment by KevinMulhern** [comment]
I agree with @arun1595, we might as well link to the videos on the official railscasts site now that they are free.

**Comment by lujanfernaud** [comment]
Yes, I think it's better to link directly to the official website. Shall I open a new pull request?

**Comment by KevinMulhern** [comment]
👍 LGTM

**Pull request merged**
