### PR TITLE
DOM_manipulation_and_events.md: Add two semicolons

### PR DESCRIPTION
**Pull request by nearmint**
- [ x ] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
- [ x ] The title of this PR follows the `where the change occurs: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`

- [ ] I have previewed all lesson file(s) included in this PR with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure the Markdown content is formatted correctly.
- [ ] If one exists, I have linked a related open issue to this PR in Step 2 below
- [ ] If changes were requested, I have made them and re-requested a review from the maintainer (top of the right sidebar)

**1. Description of the Changes**
 

I have read DOM Enlightenment's section on CSS Style rules that is linked in the lesson. As I expected there were semicolons missing in our lesson content. I added them  

**2. Related Issue**

Closes #XXXXX

### CODE REVIEW

**Review by 01zulfi — CHANGES_REQUESTED** [review]
Thanks for doing this. Can you also add a semi-colon on line 120:

```js
div.style.cssText = "background-color: white" // ok in a string
```

**Comment by 01zulfi** [comment]
@nearmint Checking in to see if you're still available for making the requested change?

**Comment by nearmint** [comment]
Hi @01zulfi, I've made the requested change I think. Please check thanks :)

**Review by 01zulfi — APPROVED** [review]
Thanks for doing this! 🚀

**Pull request merged**
