### PR TITLE
A Deeper Look at Git: Expanded upon when it would be appropriate to use git reset

### LINKED ISSUE #25330: A Deeper Look At Git JavaScript Course:  Provide example or expand upon when it would be appropriate to use `git reset --soft`
### Describe your suggestion

`What would be an example of where we want to move the HEAD but not touch the staging area --- from this paragraph in https://www.theodinproject.com/lessons/javascript-a-deeper-look-at-git

> Now let’s say we want to move where HEAD points to but don’t want to touch the staging area. If we want to leave the index alone, you can use git reset --soft. This would only perform the first part of git reset where the HEAD is moved to point somewhere else.

I found this from Eduardo06sp git-help which links to this SO question

> "also, there's a much more elaborate answer for using git reset,
> my answer was very ominous so I think it's best you're informed as to what it's really doing:
> https://stackoverflow.com/questions/3528245/whats-the-difference-between-git-reset-mixed-soft-and-hard
> (the accepted answer is amazing)

I'm just not seeing why we care / what are the benefits of leaving the index alone on a reset.  

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/javascript-a-deeper-look-at-git

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### (Optional) Discord Name

Wave#4186

### (Optional) Additional Comments

_No response_

### PR DESCRIPTION
**Pull request by roy9495**
## Because

- For `git reset --soft`, the index was left alone with examples.
- There was no documentation regarding `git reset --mixed`
- No index documentation for `git reset --hard` mentioned 

## This PR

In the [A Deeper Look at Git](https://www.theodinproject.com/lessons/javascript-a-deeper-look-at-git#changing-history) lesson
-> Added the index documentation for `git reset --soft` with examples.
->  Added the index documentation for `git reset --mixed` with examples.
->  Added the index documentation for `git reset --hard` with examples.

## Issue

Closes #25330 

## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [x] The `Because` section summarizes the reason for this PR
-   [x] The `This PR` section has a bullet point list describing the changes in this PR
-   [x] If this PR addresses an open issue, it is linked in the `Issue` section
-   [x] If any lesson files are included in this PR, they have been previewed with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure it is formatted correctly

### CODE REVIEW

**Review by KevinMulhern — CHANGES_REQUESTED** [review]
Sorry for the delay @roy9495.

I think we might be going into too much detail with this. This lesson is set up so users can follow along  and this is a sizeable excursion from that. It may break the flow of the lesson. 

We're also covering `--mixed` and `--hard` but learners won't have covered that in the previous content.

Going back to [original issue](https://github.com/TheOdinProject/curriculum/issues/25330):
> I'm just not seeing why we care / what are the benefits of leaving the index alone on a reset.

This is the problem we need to solve, we can ignore `--mixed` and `--hard` and focus on giving a short explanation of why `--soft` is useful.

Maybe something like:

"You can think of `git reset --soft` as a more powerful amend. Instead of changing the last commit, you can go back multiple commits and combine all the changes included in them into one commit."

**Comment by roy9495** [comment]
Absolutely, I completely agree that bringing up --mixed and --hard could interrupt the flow of the lesson. Therefore, I'll focus solely on introducing git reset --soft. 

Regarding your suggestion, in the initial problem, I believe he intended for the index to be highlighted alongside git reset --soft. As a result, I incorporated examples using branch names to address this.

**Comment by KevinMulhern** [comment]
Sorry I keep dropping the ball with this @roy9495 😓 

I don't think we need an example for this. We haven't had any more activity on the issue and this lesson is a follow along so any examples that don't conform to the overall example will be confusing. A little bit of explaining text should be enough.

To get this over the line, can this just be added to the bottom of the `git reset --soft` paragraph please?

"You can think of git reset --soft as a more powerful amend. Instead of changing the last commit, you can go back multiple commits and combine all the changes included in them into one commit."

**Review by KevinMulhern — APPROVED** [review]
Thanks @roy9495 💪

**Comment by roy9495** [comment]
Thanks

**Pull request merged**
