### PR TITLE
Update project_linked_lists.md

### PR DESCRIPTION
**Pull request by Ichenn92**
This is a PR template. If you are adding a solution link to the curriculum, leave this as is. If not, delete it and write the message you wish.

Thank you,

The Odin Project team.

### CODE REVIEW

**Comment by ZachBaird** [comment]
@Ichenn92 It looks like the link you've used for your project submission 404's can you make sure your pull request has the correct link to your code.

While you're at it, would you please change the name of the pull request? It's important for us to be able to see what added content is in a pull request, and unfortunately this title doesn't allude that this is a student submission at all :)

**Comment by Ichenn92** [comment]
oh, I wasn't awake, clearly ! 👍 

Thanks for the warning !

**Comment by Ichenn92** [comment]
Is it okay @ZachBaird ?
It's the first time I try to edit a pull request.

**Comment by ZachBaird** [comment]
@Ichenn92 Yep, great work :)

**Pull request merged**
