### PR TITLE
Update turbo.md

### PR DESCRIPTION
**Pull request by sapienfrom2000s**
## Because
It is a hands on tutorial on turbo frames and turbo stream

## This PR
Allows students to actively engage with turbo frames and turbo streams. One of the best resources on the internet in my opinion to get started with hotwire.

## Issue

Closes #XXXXX

## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [x] The `Because` section summarizes the reason for this PR
-   [x] The `This PR` section has a bullet point list describing the changes in this PR
-   [x] If this PR addresses an open issue, it is linked in the `Issue` section
-   [x] If any lesson files are included in this PR, they have been previewed with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure it is formatted correctly
-   [x] If any lesson files are included in this PR, they follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

### CODE REVIEW

**Comment by CouchofTomato** [comment]
@sapienfrom2000s 

I'm concerned how long this resource is. Could we add it as an additional resource instead?

**Comment by sapienfrom2000s** [comment]
I would argue that this is a good prelude to the official docs. Although this is long, but it requires active engagement from students. Its like doing _getting started_ part of rails. Its far better than _skimming_ through the docs. Maybe we can push the official docs to additional resource. What do you think?

**Comment by CouchofTomato** [comment]
Your PR links only to chapter 4. The entire course is huge https://www.hotrails.dev/turbo-rails and we can't realistically include that as a required activity.

Our aim is to get people proficient and they can then go and explore these topics in a deeper way. If we tried to deep dive into every topic we cover people would never get close to finishing.

What you've linked is a great resource, and one we've explored in the past... but it's too big.

**Comment by sapienfrom2000s** [comment]
@CouchofTomato You are right. We need to be practical. I guess, we can add it to the additional resource.

**Comment by ManonLef** [comment]
@sapienfrom2000s would you like to make the change to move this to additional resources?

**Review by sapienfrom2000s — COMMENTED** [review]
Pushed the resource to Additional Resources as instructed by maintainers

**Comment by sapienfrom2000s** [comment]
in order to start the tutorial right away, User need to create a project with _rails new quote-editor_ and then generate a scaffold __rails scaffold g quotes__ and in the migration, add a column __t.string :name__ and then __rails db:migrate__. Do I need to add it as well?

**Comment by sapienfrom2000s** [comment]
Updated @CouchofTomato

**Comment by sapienfrom2000s** [comment]
Should I close this PR or is it still under review?

**Review by CouchofTomato — APPROVED** [review]
I'm happy to approve for now. I'm not entirely convinced those instructions will not confuse anyone but if we receive any feedback on it we can address it then.

**Pull request merged**
