### PR TITLE
Changed link for resource #2

### PR DESCRIPTION
**Pull request by ibsavage**
JQuery removed their javascript 101 section, I propose simply linking directly to where they suggest readers go for information, as seen in https://github.com/jquery/learn.jquery.com/issues/257.

### CODE REVIEW

**Comment by kriox26** [comment]
Seems good to me. I dont't remember exactly what `learn.jquery.com` had in their article, but if It was only about HTML, CSS and Javascript, we could specify that they should only read the sections on HTML, CSS and Javscript of the new resource. What do you think @KevinMulhern ?

**Comment by KevinMulhern** [comment]
Sounds good to me :+1:

**Comment by kriox26** [comment]
@ibsavage could you add after the link that readers should only go through: `Dealing with files`, `HTML basics`, `CSS basics` and `Javascript basics` ?

**Comment by ibsavage** [comment]
Added!

**Comment by kriox26** [comment]
Awesome @ibsavage !!!

**Pull request merged**
