### PR TITLE
recommit binary search tree

### PR DESCRIPTION
**Pull request by hiendinhngoc**

### CODE REVIEW

**Comment by KevinMulhern** [comment]
@hiendinhngoc this has the same problem as your last commit.

**This is the current binary search tree project page:** https://github.com/TheOdinProject/curriculum/blob/master/ruby/project_data_structures_algorithms.md

**This is the one you are trying to commit to the project:**
https://github.com/hiendinhngoc/curriculum/blob/master/ruby/project_data_structures_algorithms.md

Look at the difference in the **student submissions**, there are lots more student submissions in the page that is currently part of the curriculum than your submitted page update. This is because your forked version of the project is old and had any of the updates pulled into it since it was forked.

You need to run **git pull** in your forked curriculum directory to update your version of the project before you can submit another solution.

**Comment by KevinMulhern** [comment]
Or to make life easier for yourself, submit your solutions the way most people do so you wont have to worry about pulling updates to your forked project. The method is explained in this video:
https://www.youtube.com/watch?v=V74l_zS1x8E

**Comment by hiendinhngoc** [comment]
Thank you so much for your suggestion. To be honest, with all the commits in the past, I did `git pull` and then I saw the message:`the repository up-to-date`, after that I make the change by adding my solution to `.md` files then I pushed it to my fork repo, making pull request. All my work have done before and I didn't know exactly where I got error because I really saw `the repository up-to-date` before make the commit. Anyway, I will fix my error and pull the request, thanks again!

**Comment by KevinMulhern** [comment]
Closed due to 14 days of inactivity.

**Pull request closed without merging**
