### PR TITLE
Added biko's solution Javascript Basics

### PR DESCRIPTION
**Pull request by biko1982**
```
This is a PR template, If you are adding a solution link to the curriculum leave this as is. If you are not, then delete it and write the message you wish.
Thank you,
The Odin Project team.

```

### CODE REVIEW

**Comment by csrail** [comment]
Hey @biko1982 ,

Not sure what's happening with the commit... but did you delete Robert's solution before adding your own?

**Comment by biko1982** [comment]
Hi csrail,

If so, not intentionally. Learned an important lesson though: Always check before you commit ;-)
What happens now? You deny the pull request and I make a new commit?

**Comment by csrail** [comment]
Hey @biko1982 ,

Hm. I'm not actually sure how you managed that. I don't think it's your fault though. It doesn't seem logical that you deleted something at the top and then added something at the bottom. I think it might be a synchronisation error somewhere...

You can make a new commit and submit a new pull request on this pull request and then I can merge :D)

**Comment by biko1982** [comment]
Thanks for you quick reply. I will make it so ;-)

**Comment by csrail** [comment]
Merged at #4595. :)

**Pull request closed without merging**
