### PR TITLE
Update project_js_jquery.md

### PR DESCRIPTION
**Pull request by tnt007tarun**
Hi!

Just adding my solution to the JS/JQuery project in Web Development 101.

Thanks.

### CODE REVIEW

**Comment by muzfuz** [comment]
Hey thanks for adding!

Could you please check the link formatting - it would be nicer to make it match the other links on the page, i.e. remove the `(with random colours)` text.

**Comment by tnt007tarun** [comment]
Sorry, will do!

**Comment by muzfuz** [comment]
No worries.  I have reopened this - you can just submit a new commit to this request.

**Comment by tnt007tarun** [comment]
Thank you!

**Pull request merged**
