### PR TITLE
Update handle_inputs_and_render_lists.md

### PR DESCRIPTION
**Pull request by jakemadash**
I don't see reportWebVitals mentioned in the first react lesson's body nor in the linked articles. Maybe it's covered in the additional resources, but this is a little confusing.

## Issue

Closes #XXXXX

## Pull Request Requirements

-   [ ] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [ ] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [ ] The `Because` section summarizes the reason for this PR
-   [ ] The `This PR` section has a bullet point list describing the changes in this PR
-   [ ] If this PR addresses an open issue, it is linked in the `Issue` section
-   [ ] If any lesson files are included in this PR, they have been previewed with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure it is formatted correctly
-   [ ] If any lesson files are included in this PR, they follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

### CODE REVIEW

**Comment by thatblindgeye** [comment]
@jakemadash Just as an FYI, you should only submit PRs if you have a change you want to request be merged in. Something like this would be better as an issue.

That said, do you want to make the update requested above?

**Comment by jakemadash** [comment]
Got it, I'll keep that in mind going forward. I don't think the proposed
change addresses my issue. This section asks you to clean up
ReportWebVitals and to go back to the first lesson if you don't know what's
being referred to. But the first lesson, nor any of the linked articles in
that lesson, mention ReportWebVitals.

If anything, this might be brought up in one of the supplemental videos in
that lesson, but not everyone watches those so the request is confusing.
See below what I have in mind for possible solutions.

1. Provide a link back to whatever resource goes over ReportWebVitals in
the 'handle inputs and render lists' lesson.
2. Update the first React lesson to make more explicit mention of this
concept or make the relevant resource 'required' instead of supplemental.
3. Change the language of this section if this whole thing isn't that big
of a deal.

Thanks!

**Comment by jakemadash** [comment]
Hi Maisel,That sounds good to me. You can go ahead and assign or whatever needs to be done.Thanks,JakeOn Mar 10, 2023, at 12:09 PM, MacDaniel Maisel ***@***.***> wrote:﻿
@jakemadash I see what you mean. That said the easiest change that comes to mind out of your suggestions is #1. This is the resource link right here https://create-react-app.dev/docs/measuring-performance/. If it isn't there it makes sense to me to add the link in that step and add a line mentioning web vitals in the react introduction in the react developer tools paragraph of the first react section. More than happy to create the issue and just assign you just let me know if your available for it since it's been a while since this issue has been touched.

**Comment by linkonsat** [comment]
Awesome. I'll write up the issue and give you a ping when I finish it up!

**Comment by linkonsat** [comment]
@jakemadash You can find the issue here https://github.com/TheOdinProject/curriculum/issues/25199. I'm going to poke around at seeing why it won't let me assign on the issues but feel free to make the pr! Just add "closes #25199" so the corresponding issue gets closed.

**Comment by ChargrilledChook** [comment]
> @jakemadash You can find the issue here https://github.com/TheOdinProject/curriculum/issues/25199. I'm going to poke around at seeing why it won't let me assign on the issues but feel free to make the pr! Just add "closes #25199" to the issue section when making the PR so the corresponding issue gets closed.

@jakemadash if you comment on the issue, @linkonsat should be able to assign you 🙂

**Comment by linkonsat** [comment]
Given the another PR has been added to address the issue. I'm going to go ahead and close this PR.

**Pull request closed without merging**
