### PR TITLE
Codecademy changed it so you can no longer link to a specific course,…

### PR DESCRIPTION
**Pull request by JonathanYiv**
… it just reverts you to where you left off. They also added two more segments under refactoring that you have to go through to access Blocks, Procs, and Lambdas.

```
This is a PR template, If you are adding a solution link to the curriculum leave this as is. If you are not, then delete it and write the message you wish.
Thank you,
The Odin Project team.

```

### CODE REVIEW

**Comment by KevinMulhern** [comment]
Thanks for this @JonathanYiv 😄 the remaining Ruby lessons on are on https://www.theodinproject.com/courses/ruby-programming/lessons/object-oriented-programming

Do you want to do fix those as well?

**Comment by KevinMulhern** [comment]
LGTM 👍

**Comment by JonathanYiv** [comment]
Yessir. I'll fix it when I get there later today!

**Comment by JonathanYiv** [comment]
Hmm, conceptually, the "Zen of Ruby" and "Refactor Factory" fit more into the Object-Oriented Programming lesson.
Do you still want me to move it?

**Comment by KevinMulhern** [comment]
@JonathanYiv I agree that refactoring fits in with OOP more. Looking at what the has to be done for the refactoring lessons on Codecademy though, theres no OOP involved. I think its safe to leave the refactor lessons in advanced building blocks.

**Pull request merged**
