### PR TITLE
Fix typo (I think)

### PR DESCRIPTION
**Pull request by ted-dino**
- [x] You have read [The Odin Projects Contributing Guide](https://github.com/TheOdinProject/curriculum/blob/main/CONTRIBUTING.md).

#### 1.Describe the changes made:

change hards to hard

#### 2. If this PR is related to an open issue please reference it with the `#` operator and the issue number below:

#XXXXX

### CODE REVIEW

**Review by rustyxlol — COMMENTED** [review]
Maybe an apostrophe? Interneting is **hard's** treatment..

**Comment by ted-dino** [comment]
> Maybe an apostrophe? Interneting is **hard's** treatment..

yeah, I think. should I change my pull request?

**Comment by ted-dino** [comment]
> Maybe an apostrophe? Interneting is **hard's** treatment..

oh yeah, you're right.(oh my god im sorry). never mind my pull request. have a great day!

**Review by rustyxlol — APPROVED** [review]
LGTM 👍

**Review by harked — APPROVED** [review]

**Comment by CatQueenCodes** [comment]
Thank you for your contribution

**Pull request merged**
