### PR TITLE
Add codeymason's solution to Web Development 101 HTML/CSS project

### PR DESCRIPTION
**Pull request by codeymason**
This is a PR template. If you are adding a solution link to the curriculum, leave this as is. If not, delete it and write the message you wish.

Thank you,

The Odin Project team.

### CODE REVIEW

**Comment by mindovermiles262** [comment]
Hi @codeymason 👋 

In your links there should not be a space between the closing `]` and opening `(`

Could you please change this so the links work properly?

Thanks :smile:

**Comment by codeymason** [comment]
On it! Thanks for pointing that out.

**Comment by codeymason** [comment]
Because the pull request has already been initiated, I imagine I've done all I'm supposed to? Or am I missing a step? I see that my second commit with the spacing correction you requested is being reflected here.

**Comment by KevinMulhern** [comment]
👍 LGTM

Thanks @codeymason

**Pull request merged**
