### PR TITLE
How This Course Will Work lesson: Fix annotations

### PR DESCRIPTION
**Pull request by lizandreina**
## Because
Fix Lint annotations

## This PR
- Headings structure
- Trailing spaces
- Unordered list styles

Related to #28435

## Pull Request Requirements
-   [x] I have thoroughly read and understand [The Odin Project curriculum contributing guide](https://github.com/TheOdinProject/curriculum/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [x] The `Because` section summarizes the reason for this PR
-   [x] The `This PR` section has a bullet point list describing the changes in this PR
-   [x] If this PR addresses an open issue, it is linked in the `Issue` section
-   [x] If any lesson files are included in this PR, they have been previewed with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure it is formatted correctly
-   [x] If any lesson files are included in this PR, they follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

### CODE REVIEW

**Comment by lizandreina** [comment]
@MaoShizhong Just opened a new PR with all the fixes except the TOP004 one

**Comment by MaoShizhong** [comment]
> @MaoShizhong Just opened a new PR with all the fixes except the TOP004 one

No need to open a new PR to apply changes, you can just commit and push to this branch (this PR's just tracking your `patch-5` branch).

If you have your clone of your fork and want to pull your `patch-5` branch to your local machine, you can run
```bash
git checkout --track origin/patch-5
```
That will create a local copy of your `patch-5` branch that you can apply the changes to, commit then push via `git push origin patch-5` and it'll all automatically show up here.

**Comment by lizandreina** [comment]
@MaoShizhong I tried to pull it and it says `fatal: 'origin/patch-5' is not a commit and a branch 'patch-5' cannot be created from it`

**Comment by MaoShizhong** [comment]
> @MaoShizhong I tried to pull it and it says `fatal: 'origin/patch-5' is not a commit and a branch 'patch-5' cannot be created from it`

I made a booboo and forgot to say you need to `git fetch origin` first to make sure your clone is aware of the `patch-5` branch on your remote fork (origin) :sweat_smile: 
Once you've done that, you should be able to `git checkout --track patch-5` as above.

**Comment by lizandreina** [comment]
I think it's fixed. Should I now delete the `patch-5` branch from my local repo?

**Review by MaoShizhong — CHANGES_REQUESTED** [review]
Don't delete anything until after the PR has been closed by a maintainer (whether that's from approving and merging, or closing for other reasons), then you're free to delete the branch in your clone and in your remote fork too. If you keep the cloned branch around otherwise, if further changes are required, you can just commit and push to this same branch and it'll automatically update here. No need to delete and re-clone.

I don't see the latest commit actually having made any changes to the document. You should be able to fix them with a single run of the `fix:lesson` script.

Make sure you're in the root of the curriculum repo (the same directory as `package.json` and the various `.markdownlint-cli2.jsonc` files) - don't navigate to a subdirectory, else it won't pick up the right config files.

Then you can run
```bash
npm run fix:lesson -- "ruby/introduction/how_this_course_will_work.md"
```
Which should fix almost everything, leaving only a single TOP004 error about "Required heading structure" (which you can ignore).
You can then commit and push which should update here immediately.

**Comment by lizandreina** [comment]
I already ran `npm run fix:lesson -- "ruby/introduction/how_this_course_will_work.md"` yesterday so I don't understand why it isn't showing up. I also made the changes locally for the PR I submitted yesterday and thought they would be reflected in this commit as well...

**Review by MaoShizhong — APPROVED** [review]
:tada:

**Pull request merged**
