### PR TITLE
Foundations: unify descriptions replacing WSL with WSL2 to be specific

### LINKED ISSUE #27082: <Foundations>: Unify description of instruction sections for WSL2
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

There is a discrepancy between how the WSL2 instructions are called between the [Installations lesson](https://www.theodinproject.com/lessons/foundations-installations#os-installation) where the section is called `WSL2` and the [Text Editors lesson](https://www.theodinproject.com/lessons/foundations-text-editors#vscode-installation) where it is called `WSL`. It most likely should be `WSL2` everywhere since the bit in `Installations` says:
> WSL2 and Linux instructions
> Because WSL2 is a full-fledged Linux distribution, almost everything that the curriculum teaches about Linux is also applicable to WSL2. In future lessons, whenever there are instructions that differ by OS, you should follow the Linux instructions, unless the lesson includes **WSL2-specific instructions**.

There are probably more places where making sure WSL is called WSL2 where it matters, for example it is called WSL2 in [Installing PostgreSQL lesson](https://www.theodinproject.com/lessons/ruby-on-rails-installing-postgresql).

This is to avoid confusion as to whether the curriculum is giving instructions for *any* WSL version or WSL2 specifically which is actually the case.

### Path

Foundations, Ruby / Rails, Node / JS, Other / NA

### Lesson Url

Most important seems to be https://www.theodinproject.com/lessons/foundations-text-editors

### (Optional) Discord Name

_No response_

### (Optional) Additional Comments

_No response_

### PR DESCRIPTION
**Pull request by Jaytpa01**
## Because

Unifies all descriptions, replacing most occurences of `WSL` with `WSL2` to avoid confusion as to whether the curriculum is giving instructions for any WSL version or WSL2 specifically which is actually the case.

## This PR

- Replaces most occurences of `WSL` to `WSL2`
 
## Issue

Closes #27082 

## Additional Information

There were a few places that weren't changed to WSL2, namely:
- where the differences between WSL and WSL2 are explicitly mentioned [here](https://www.theodinproject.com/lessons/foundations-installation-overview#:~:text=We%27ll%20be%20using%20version%202%20of%20WSL%2C%20commonly%20known%20as%20WSL2%2C%20within%20the%20curriculum)
- telling you how to install WSL2 using the `wsl --install` command [here](https://www.theodinproject.com/lessons/foundations-installations#step-1-installations). (**quick edit**: the link doesn't take you to heading, probably because it needs to be expanded first, but its the `Step 1.1: Installing WSL2` heading when you expand the `WSL2` section)
- and when [describing how to install the WSL VSCode Extension](https://www.theodinproject.com/lessons/foundations-text-editors#:~:text=Step%204%3A%20Install%20WSL%20Extension), as [the extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-wsl) itself is just called **WSL**

If you believe any of these should be changed to `WSL2`, please let me know and I'll update the PR accordingly

## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [x] The `Because` section summarizes the reason for this PR
-   [x] The `This PR` section has a bullet point list describing the changes in this PR
-   [x] If this PR addresses an open issue, it is linked in the `Issue` section
-   [x] If any lesson files are included in this PR, they have been previewed with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure it is formatted correctly
-   [x] If any lesson files are included in this PR, they follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

### CODE REVIEW

**Review by JoshDevHub — CHANGES_REQUESTED** [review]
Looks awesome. Thank you for doing this.

Unfortunately, we'll have to deal with a little problem before I can merge. PR #26663 has added a Markdown linting action to this repo to ensure standard formatting across the curriculum's files. The files you've made changes in have a few errors that it's complaining about (which is why this PR isn't passing CI)

This has nothing to do with anything you've done, but you'll have to fix those formatting errors and pass CI before I can merge this. If you click the "Files changed" tab at the top and then browse the right column of the diff, you'll see the different problems to fix.

Let me know if you need any help or have any questions about that. Sorry for the inconvenience.

**Comment by Jaytpa01** [comment]
Hey @JoshDevHub, I've gone through and fixed all the linting errors that are syntax related (excpet for one that I'll mention below), but the rest are content related and I'm not sure how I should proceed with this.

Syntax error remaining is `Proper names should have the correct capitalization [Expected: HTML; Actual: html]`, however, its referencing a filename `index.html`. As far as I'm aware, the convention for filename extensions is to be in lowercase and I wanted to flag this instead of changing it just to keep the linter happy

As for the `Required heading structure` errors, I've rearranged the sections if the content was available, but if not I've just left it as is

The last error is `Multiple headings with the same content`, but in the context of [the lesson](https://www.theodinproject.com/lessons/foundations-text-editors#vscode-installation) it makes sense. The headings are instructions fow how to download VS Code for different operating systems, i.e Linux, MacOS, WSL2

I'd be happy to work on the content for this but I figure its a bit beyond the scope of this pr/issue, and that it might be worth opening other issues

 Let me know your thoughts on these issues and how I should proceed!

**Review by JoshDevHub — COMMENTED** [review]
Hey @Jaytpa01 

Thank you for the detailed reply. And thanks for giving consideration to each change. I'll definitely get back to the team on the multiple headings one, as it absolutely makes sense to repeat the headings on an installation lesson.

For the filename one, I think we should change the plain "index.html" to `index.html` (so wrap the filename in backticks). This is generally our style for referencing filenames, and it should also allow you to type "html" in lowercase that way.

We'll be good to merge this in after that change.

**Review by JoshDevHub — APPROVED** [review]
Thanks for doing this :raised_hands:

**Pull request merged**
