### PR TITLE
Passing Data Between Components lesson: Fix typo in example quote

### PR DESCRIPTION
**Pull request by ImmaCheetah**
## Because

This solves a typo in the Passing Data Between Components lesson with an example that uses a single quote instead of a double quote. This improves the readability of said example.

## This PR

- Fixes a typo in the Passing Data Between Components lesson by changing "Don’t Click Me!' to "Don’t Click Me!"

## Issue

Closes https://github.com/TheOdinProject/curriculum/issues/28248

## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project curriculum contributing guide](https://github.com/TheOdinProject/curriculum/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [x] The `Because` section summarizes the reason for this PR
-   [x] The `This PR` section has a bullet point list describing the changes in this PR
-   [x] If this PR addresses an open issue, it is linked in the `Issue` section
-   [x] If any lesson files are included in this PR, they have been previewed with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure it is formatted correctly
-   [x] If any lesson files are included in this PR, they follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

### CODE REVIEW

**Review by MaoShizhong — CHANGES_REQUESTED** [review]
Somehow some unrelated changes made their way in. Please revert the unrelated changes, then we can merge the actual fix.

**Comment by ImmaCheetah** [comment]
Oh sorry about that, I see what the issue is. I made a change when following along with an example previously. How can I revert those?

**Comment by MaoShizhong** [comment]
Simplest in this case would just be to change those unrelated bits back to how they should be, then commit and push those changes. They'll then be removed from the diff because no changes would be detected between your branch and upstream main.

**Comment by ImmaCheetah** [comment]
Let me know if that's what you were looking for and if it was done right, if not I can try again

**Review by MaoShizhong — APPROVED** [review]
All good :rocket: congrats on your first PR here!

**Pull request merged**
