### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by shermix**
Replaced "AND" to "and"

### CODE REVIEW

**Comment by 105ron** [comment]
Should we also replace json with JSON whilst we are at it?

**Comment by shermix** [comment]
Yeah that would be better. As later in the article all json's are expressed in uppercase as JSON. So yeah, good to go. :+1:

**Comment by CouchofTomato** [comment]
@shermix 

It still appears to be `views and json`.

Are you going to submit a commit for it to be JSON?

**Comment by shermix** [comment]
> @shermix
> 
> It still appears to be `views and json`.
> 
> Are you going to submit a commit for it to be JSON?

I fear this is my first contribution and experience with pull requests in general. I can't figure out how I make commit on this patch-2 branch from the forked repo.

**Comment by 105ron** [comment]
You managed to fix it on the second commit. Merged, thank you.

**Pull request merged**
