### PR TITLE
Ruby: Refactor #times, #upto, #downto to #.times, #.upto, #.downto in the loops lesson

### PR DESCRIPTION
**Pull request by agentblack6000**
## Because

In the [Ruby Loops lesson](https://www.theodinproject.com/lessons/ruby-loops), the syntax for the `times`, `upto`, and `downto` loop is written as `#times`, `#upto`, and `#downto`, but in actual code, the loops are used like this:
```ruby
5.times do
  # code
end

0.upto(10) { # code } 

10.downto(0) { # code }   
```

This can be better expressed in the lesson as `#.times`, `#.upto`, and `#.downto`
## This PR

- Refactor `#times`, `#upto`, `#downto` to `#.times`, `#.upto`, `#.downto`

## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [x] The `Because` section summarizes the reason for this PR
-   [x] The `This PR` section has a bullet point list describing the changes in this PR
-   [x] If this PR addresses an open issue, it is linked in the `Issue` section
-   [x] If any lesson files are included in this PR, they have been previewed with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure it is formatted correctly
-   [x] If any lesson files are included in this PR, they follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

### CODE REVIEW

**Comment by linkonsat** [comment]
While I can definitely understand why it might seem syntactically incorrect. In this case, were not showing it in the code but talking about the concept of the "upto" for example. You can see on the documentation how it doesn't use the times https://docs.ruby-lang.org/en/3.1/Integer.html#method-i-upto. That said a potential change _I do see here_ is getting rid of the "#" for the keywords you were adding the "." to.

**Comment by linkonsat** [comment]
@KevinMulhern makes sense. That said we do have a methods lesson in the Ruby basics section. Adding a paragraph after the bang methods section could help with making it clear the difference.

**Comment by KevinMulhern** [comment]
@linkonsat, I'm just remembering we do have something about this, the third assignment in the [first lesson](https://www.theodinproject.com/lessons/ruby-how-this-course-will-work). Links to [this bit about](https://launchschool.com/books/ruby/read/preparations#readingdocumentation) it.

**Comment by linkonsat** [comment]
@KevinMulhern Ah. I was looking in the wrong spot for it lol. In that case, I'll go ahead and close the PR since were keeping it the same. Thanks again however for taking the time to do this @agentblack6000 .

**Pull request closed without merging**
