### PR TITLE
Update oop-concepts.md

### PR DESCRIPTION
**Pull request by Hamad-98**
Complete the following REQUIRED checkboxes:

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`

Complete the following checkboxes ONLY IF they are applicable to your PR. You can complete them later if they are not currently applicable:
-   [x] I have previewed all lesson files included in this PR with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure the Markdown content is formatted correctly
-   [x] I have ensured all lesson files included in this PR follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

<hr>

**1. Because:**

Closes #XXXXX

**2. This PR:**

- Link for assignment#2 had been removed from medium.
-  Removed the assignment 2 block

**3. Additional Information:**

### CODE REVIEW

**Comment by LeoKirasic** [comment]
@Hamad-98 can you go to web archive and switch the link with the one from a web archive? I dont think we really want to be removing resources.

**Comment by Hamad-98** [comment]
Sorry, where is the web archive?

**Comment by LeoKirasic** [comment]
@Hamad-98
My Bad for not clarifying. 

Go to the [Web Archive](https://web.archive.org/), input the URL of the broken link and find a snapshot of it where it was working. Replace the current link anywhere where applicable with the one provided by the web archive website.

**Comment by LeoKirasic** [comment]
Are you interested in doing this? @Hamad-98

There's an issue currently open addressing this. #23730

**Review by LeoKirasic — APPROVED** [review]
Looks good now. Thanks!

**Pull request merged**
