### PR TITLE
Installations paste copy note

### LINKED ISSUE #27390: Installations: Add a note, for the paste shortcut
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

Hello, for the past few months I've been active on the discord especially in the tech support channels. 

I've noticed that a lot of users  are making spelling mistakes with `wget` command when downloading `chrome` or `vscode`. Would it be a good idea to maybe add somekind of note for the users just to inform them that they can also paste the commands from the browser to the terminal with `Ctrl + Shift + V` or `Command + V` on Mac? 

I know that I'm suggesting for this to be added before the `Command Line Basics` lesson but I think that it would be a good idea to make users aware of this option. 

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-installations

### (Optional) Discord Name

Uki

### (Optional) Additional Comments

_No response_

### PR DESCRIPTION
**Pull request by AirDevil188**
## Because
I've done this PR because I've noticed that a lot of users on the Discord tech channels are making spelling mistakes with `wget` command when downloading `vscode` or `chrome` and that's because they don't seem to be awere of copy/paste shortcuts for terminal. 

## This PR
- I've added a simple note in Installations lesson in the Foundations course, that will inform users about these shortcuts I've added this in Google Chrome installation process under Linux category. 

## Issue

Closes #27390 https://github.com/TheOdinProject/curriculum/issues/27390

## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [x] The `Because` section summarizes the reason for this PR
-   [x] The `This PR` section has a bullet point list describing the changes in this PR
-   [x] If this PR addresses an open issue, it is linked in the `Issue` section
-   [x] If any lesson files are included in this PR, they have been previewed with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure it is formatted correctly
-   [x] If any lesson files are included in this PR, they follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

### CODE REVIEW

**Comment by MaoShizhong** [comment]
@AirDevil188 Looks great!
There are a couple of linting errors (your probably got a notification when the linting check failed) that I'm sure won't be much of a hassle for you to fix, such as the `####` instead of `###` and extra blank line etc.

You can leave the errors for accessible link text alone - these are more suitably handled in separate issues specifically to fix those.

In the [contribution guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md#repo-specific-instructions) under `Repo Specific Instructions` there are instructions for how to set up automatic and manual lint checking (some issues will only be captured when running the manual check). If you could follow this and fix the style-based linting errors, leaving only the accessible link text errors, then that'd be great and I can merge if all good after that.

Let me know if you encounter any issues doing this!

**Comment by AirDevil188** [comment]
> @AirDevil188 Looks great!
> There are a couple of linting errors (your probably got a notification when the linting check failed) that I'm sure won't be much of a hassle for you to fix, such as the `####` instead of `###` and extra blank line etc.
> 
> You can leave the errors for accessible link text alone - these are more suitably handled in separate issues specifically to fix those.
> 
> In the [contribution guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md#repo-specific-instructions) under `Repo Specific Instructions` there are instructions for how to set up automatic and manual lint checking (some issues will only be captured when running the manual check). If you could follow this and fix the style-based linting errors, leaving only the accessible link text errors, then that'd be great and I can merge if all good after that.
> 
> Let me know if you encounter any issues doing this!

I'll be sure to fix that as soon as I get home I'll report back.

**Comment by AirDevil188** [comment]
@MaoShizhong can you check now? I pushed my commit for fixnig litting errors with double blank spaces and with `####`

**Review by MaoShizhong — APPROVED** [review]
There are still some other heading-based linting issues but looking into it further, there are *a lot* more that only reveal themselves one by one when you fix the previous. So those'll be something for a separate issue.

Otherwise, the relevant changes look good to me - great job and thank you for doing this!

**Comment by AirDevil188** [comment]
I will have more free time on the weekend so I could do them. If you want I could open a new issue  until the weekend. And sorry about the sloppiness with `lint errors` but, this is the first time that I have done this. It will only get better as I do them more.

**Pull request merged**
