### PR TITLE
Foundations/Revisiting Rock Paper Scissors: Update ordered list as per style guide

### PR DESCRIPTION
**Pull request by roopxx**
## Because
The ordered lists in the lesson need to be updated to comply with the style guide.

## This PR
- Updates all ordered list items to use lazy numbering format instead of incrementing numbers.

## Issue
Related to #27119 

## Pull Request Requirements
-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [x] The `Because` section summarizes the reason for this PR
-   [x] The `This PR` section has a bullet point list describing the changes in this PR
-   [x] If this PR addresses an open issue, it is linked in the `Issue` section
-   [x] If any lesson files are included in this PR, they have been previewed with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure it is formatted correctly
-   [x] If any lesson files are included in this PR, they follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

### CODE REVIEW

**Review by thatblindgeye — COMMENTED** [review]
Thanks for making these updates! Looks like there's a couple of errors being flagged. Would you mind opening up 2 issues regarding them?

One issue should be to update the structure of the "Revisiting RPS" lesson. Since it isn't a conventional project, it should follow the lesson structure and include a "lesson overview" section.

The other issue should be to add the `pre` tag to the allowed list of HTML element in our config file. If you'd like to make this update yourself it's pretty straight forward and I can help guide you, and we won't need an issue opened. Just let me know!

**Comment by roopxx** [comment]
@thatblindgeye, I would definitely need some help as I am first time contributor.

Regarding Issue 2, adding the `pre` tag to the allowed HTML elements in the config file, are there any considerations I should keep in mind when making this update? Guide me here.

Thank you.

**Comment by thatblindgeye** [comment]
@roopxx not a problem! Some instructions on how to move forward below, let me know if anything isn't clear!

To open a new issue, you would go to our "Issues" tab at the top of this page, and you should see a button that says "New issue":

Github menubar

(you may not see exactly what that screenshot shows, but it should be similar).

Then you'd click the "Get started" button next to the item titled, " Suggest an Improvement to Curriculum Content", and from there you'd just fill out the issue template with as much info that is applicable. Which in this case the suggestion would be restructuring the "Revisiting RPS" lesson since it isn't a project and is missing required sections (you can also copy+paste the link to this PR in the issue for reference).

<hr/>

For the config file update, we don't really need an issue for that if you would want to make the update yourself; if not I can put up a quick PR to do so. But basically you would go to our [markdownlint config file](https://github.com/TheOdinProject/curriculum/blob/main/.markdownlint-cli2.jsonc) which is at the root of the repo and you would update the "allowed_elements" array starting at line 38 of that file to include `"pre"` as an array item:

Allowed elements array from markdownlint config file

So we should end up with something like the following:

```javascript
"allowed_elements": [
  "p",
  "a",
  "div",
  "span",
  "kbd",
  "script",
  "iframe",
  "details",
  "summary",
  "pre"
]
```

**Comment by roopxx** [comment]
Oh! Thank you @thatblindgeye for the detailed reply :-) I finished the 2nd issue with the config file, was waiting for your thumbs up :+1: to commit the changes.

Just reached home from work. It seems you have merged this PR. Can I commit and push the changes now?

**Comment by thatblindgeye** [comment]
@roopxx Ah sorry about that, I've had a lot of tabs opened and may have merged this one prematurely 🤦🏼 

If you'd like you can commit your changes to a new branch and open a new PR for that.

**Comment by roopxx** [comment]
No worries at all! I understand, it happens. I'll go ahead and commit my changes to a new branch and open a new PR for that. Thanks for the heads up!

**Pull request merged**
