### PR TITLE
Foundations Inspecting HTML/CSS: Removed images and verbiage requiring the user to visit TOP homepage

### LINKED ISSUE #24305: Bug - Foundations/Inspecting HTML and CSS: Different style applied to h1 than shown in the lesson's screenshot
Complete the following REQUIRED checkboxes:
-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `Bug - location of bug: brief description of bug` format, e.g. `Bug - React section: Knowledge Checks don't link to resource`

The following checkbox is OPTIONAL:

-   [ ] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Bug:**

In the "Inspecting Elements" part of the lesson, there is a screenshot showing what should be displayed to the user when inspecting TOP's homepage. Imo it should be something else there.

**2. How To Reproduce:**

1. Log in
2. Visit the Inspecting HTML and CSS lesson page from the Foundations Course
3. Go to the "Inspecting Elements" part of this lesson
4. Note [this screenshot](https://cdn.statically.io/gh/TheOdinProject/curriculum/594984d7c9f9e744577f19ea475b3864e8cc7c91/html_css/v2/foundations/inspecting-html-and-css/imgs/02.png)
5. Visit the TOP homepage in incognito mode and inspect the same part of the page with Chrome Dev Tools.
6. [The following will be shown (at least in my case)](https://i.imgur.com/H0CC80p.png)
7. The style applied to h1 is completely different than in the screenshot from the lesson

**3. Expected Behavior:**

I'd say that "my" version should be shown in the lesson.

**4. Desktop/Device:**

-   Device:  Lenovo Thinkpad T590
-   OS:  Windows 10 (yup, I know it's not Linux, but does it matter in this case?)
-   Browser:  Chrome
-   Version:  102

**5. Additional Information:**

**Acceptance Criteria (added by @thatblindgeye )**
- In the "The Inspector" section, remove the verbiage about going to the TOP homepage and instead ask users to inspect the lesson page itself and use that to follow along
- In the "The Inspector" section, remove the image
- In the "Inspecting Elements" section, remove the second image (the one that shows the devtools and homepage side by side; we should only need the 3rd image that shows overwritten styles and applied styles)
- In the "Testing Styles in the Inspector" section, update the verbiage and remove the image. We should just explain what updating styles in dev tools does and what it doesn't do ("...the webpage responds with the changes in real-time. This won’t affect the source code in your text editor, but it is extremely useful for quickly testing out various attributes and values without needing to reload the page over and over again.")

### PR DESCRIPTION
**Pull request by alleizon**
## Because

Closes #24305 

## This PR

- Removes the verbiage asking the user to visit the TOP Homepage and use inspect there
- Removes the images showing the opened inspector on the TOP Homepage
- Added verbiage asking the user to instead open the inspector on the lesson page, and explaining what adding updating styles in dev tools does

## Additional Information

Modified the files as instructed by @thatblindgeye in the acceptance criteria from the opened issue.

## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [x] The `Because` section summarizes the reason for this PR
-   [x] The `This PR` section has a bullet point list describing the changes in this PR
-   [ ] If this PR addresses an open issue, it is linked in the `Issue` section
-   [x] If any lesson files are included in this PR, they have been previewed with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure it is formatted correctly
-   [x] If any lesson files are included in this PR, they follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

### CODE REVIEW

**Review by wise-king-sullyman — CHANGES_REQUESTED** [review]
This looks great, thanks for doing it!

One request: can you delete the corresponding images out of the repo as well?

**Comment by alleizon** [comment]
Well, I removed the images but I'm guessing I messed up the workflow quite badly and at this point I'm pretty lost. Would appreciate some tips.

**Comment by wise-king-sullyman** [comment]
Everything looks right to me? What do you think is wrong?

**Comment by alleizon** [comment]
I thought I messed it up by creating multiple commits (somehow managed to duplicate them) and by not squashing the commits created by pulling from upstream (so as to not push "meaningless" commits). 

I guess I was a little confused, but if everything is fine then it's all good.

**Comment by wise-king-sullyman** [comment]
Ah, yeah I see what you mean. No need to worry about squashing them though, we generally favor not making history changes once a PR has been opened anyways.

**Review by wise-king-sullyman — APPROVED** [review]
Thanks again for taking the time to do this!

**Pull request merged**
