### PR TITLE
JavaScript>Computer Science>Knights Travails(project): Add the term 'graph'

### PR DESCRIPTION
**Pull request by ajoygp**
## Because

 The project requires you to use a graph, and even links to a relevant resource.  But it never mentions the term graph anywhere on the page.

## This PR

Added the term graph to the lesson Knights Travails in the Javascript section.

## Issue

Closes #XXXXX

## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [x] The `Because` section summarizes the reason for this PR
-   [X] The `This PR` section has a bullet point list describing the changes in this PR
-   [ ] If this PR addresses an open issue, it is linked in the `Issue` section
-   [x] If any lesson files are included in this PR, they have been previewed with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure it is formatted correctly
-   [x] If any lesson files are included in this PR, they follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

### CODE REVIEW

**Review by 01zulfi — COMMENTED** [review]
I might be hesitant to make this change. The project doesn't limit the learner to use a graph to complete this project. They can use any data structure here. I'd love to hear your thoughts.

**Comment by ajoygp** [comment]
>The project doesn't limit the learner to use a graph to complete this project. They can use any data structure here.

I didn't know that. When I saw "... you’ll need to use a data structure that’s similar (but not identical) to a binary tree." followed by a link to graphs, I thought graphs were the only solution. 

Would it make sense to mention the important data structures that can be used here (unless they are covered in an upcoming session that is).  Would it be distracting?

**Comment by 01zulfi** [comment]
There's an opportunity to improve the instructions for sure. But I'm hesitant on mentioning the important data structures. Do you have any specific data structures in mind? Or any other way we can improve the instructions?

**Comment by ajoygp** [comment]
I too thought there might be an opportunity to improve it. But the how-to would be beyond my current expertise😅. Might be better to leave it as is for the moment.

**Comment by 01zulfi** [comment]
@ajoygp Thanks for wanting to contribute! :fire:

**Pull request closed without merging**
