### PR TITLE
Add async/await for click operation test function

### PR DESCRIPTION
**Pull request by lnicepei**
userEvent.click(button) is an asynchronous operation, and the test fails without await/async wrapper

## Issue

Closes #XXXXX

## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [x] The `Because` section summarizes the reason for this PR
-   [x] The `This PR` section has a bullet point list describing the changes in this PR
-   [ ] If this PR addresses an open issue, it is linked in the `Issue` section
-   [x] If any lesson files are included in this PR, they have been previewed with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure it is formatted correctly
-   [x] If any lesson files are included in this PR, they follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

### CODE REVIEW

**Review by thatblindgeye — CHANGES_REQUESTED** [review]
It'd be worth putting in a quick summary of why async/await are added for the userEvent.click call

**Comment by thatblindgeye** [comment]
@lnicepei would you be interested in updating this PR per the comment above?

**Comment by lnicepei** [comment]
I created a sandbox to demonstrate the problem in detail. Here it is 
https://codesandbox.io/s/autumn-snowflake-ti1149?file=/src/App.test.js
(Open the Tests tab on the top right and see the test failing)

**Comment by lnicepei** [comment]
@thatblindgeye any ideas?

**Comment by thatblindgeye** [comment]
@lnicepei Sorry, I just meant that in the lesson around where this test is placed we should mention why we're using async/await. Could just be a quick:

> Due to the `userEvent.click` call being an asynchronous operation, we need to utilize the `async`/`await` syntax in order for the test to pass.

Or something along those lines.

**Comment by KevinMulhern** [comment]
Closing due to no activity

**Pull request closed without merging**
