### PR TITLE
Foundations / Flexbox Growing and Shrinking lesson: Assignment section creation

### PR DESCRIPTION
**Pull request by aaronlrv**
Complete the following REQUIRED checkboxes:

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`

Complete the following checkboxes ONLY IF they are applicable to your PR. You can complete them later if they are not currently applicable:
-   [x] I have previewed all lesson files included in this PR with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure the Markdown content is formatted correctly
-   [x] I have ensured all lesson files included in this PR follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

<hr>

**1. Because:**

Closes #XXXXX

**2. This PR:**

**3. Additional Information:**

Related to  #24177 specified not to close
Link : https://github.com/TheOdinProject/curriculum/issues/24177

### CODE REVIEW

**Review by dm-murphy — CHANGES_REQUESTED** [review]
Hi @aaronlrv 👋 

Saw your message in the linked issue. No worries, just request a re-review on this PR after you've been able to remove those other commits. No rush and thanks again for your help on this issue!

**Comment by aaronlrv** [comment]
@dm-murphy  Hey! Requested the rereview and deleted the unrelated commit files from this current pr as I was unable to figure out a way to remove commits themselves

Please do have a check and let me know!

**Comment by dm-murphy** [comment]
> @dm-murphy Hey! Requested the rereview and deleted the unrelated commit files from this current pr as I was unable to figure out a way to remove commits themselves
> 
> Please do have a check and let me know!

Hi @aaronlrv, this PR would actually delete those files from the repository, which we wouldn't want to do. 

You could restore the original files to this PR or if it is easier you could close out this PR and just make a fresh one as long as your branch includes the original files. Also if you happen to be part of our Discord community you can seek help in our #git-help channel.

Sorry for the troubles and thanks again for working on this! 🙏

**Comment by aaronlrv** [comment]
Hey Daniel,
Just seen this my apologies, I didn't get a notification. I will work on this tommorow and open a new PR hopefully with the proper changes.

Apologies for the inconveniences!

**Comment by aaronlrv** [comment]
Hey! @dm-murphy  Managed to get the PR going with only the assignment section

Here's the link to the PR https://github.com/TheOdinProject/curriculum/pull/24440 .  I'll also mention it in the original issue for your reference

My apologies for the inconvenience once again, Feel free to close this existing PR

**Comment by dm-murphy** [comment]
Thanks @aaronlrv and no worries! I will close this PR and check out the new one you opened. Thanks again for your efforts on all this 🙏

**Pull request closed without merging**
