### PR TITLE
React Revamp: Add Using NodeJS For Your Backend lesson

### PR DESCRIPTION
**Pull request by 01zulfi**
## Because

https://github.com/TheOdinProject/top-meta/issues/270

## This PR

Adds Using NodeJS For Your Backend lesson

## Issue

Closes https://github.com/TheOdinProject/top-meta/issues/270

## Pull Request Requirements

-   [ ] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [ ] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [ ] The `Because` section summarizes the reason for this PR
-   [ ] The `This PR` section has a bullet point list describing the changes in this PR
-   [ ] If this PR addresses an open issue, it is linked in the `Issue` section
-   [ ] If any lesson files are included in this PR, they have been previewed with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure it is formatted correctly
-   [ ] If any lesson files are included in this PR, they follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

### CODE REVIEW

**Comment by codyloyd** [comment]
This is a good addition, but I think we need to state even more clearly up front that we are not learning NodeJS just yet... otherwise, why are we mentioning it here?  This lesson feels like it's saying this.

> Alright so you're ready to start using node for your backend, it's gonna be great! LocalStorage is fine... but it's not good enough for REAL apps.
> You ready??
> Good... now let's _NOT_ learn node until later.

😆 

obviously i'm exaggerating.. but I think we can manage expectations a little bit by starting this section with a phrase like 
> "you've probably been wondering how you make apps that can actually store data... that requires the use of NodeJS, which is something you'll learn in depth in a later course."

**Comment by 01zulfi** [comment]
@codyloyd Sounds reasonable, but I'm finding it difficult to incorporate this suggestion. It would be amazing if you can be more specific on what changes to make

**Comment by codyloyd** [comment]
let me put more thought into it haha.

ping me on Monday if I don't get back to you.

**Comment by codyloyd** [comment]
@01zulfi Here's my attempt... please feel free to take or leave as much as you want and/or change the wording entirely.  Basically I added a few more "we're doing this later" qualifiers to the text you already had.


### NodeJS to the rescue! 

`We aren't quite ready to leave the frontend to learn all about how to store persistent data, but this question comes up often enough that we thought it was worth leaving a note here about it.` NodeJS is a JavaScript runtime environment which will let you build an entire backend with JavaScript. We'll learn all about it `later` in our [NodeJS course](https://www.theodinproject.com/paths/full-stack-javascript/courses/nodejs). With Node, we'll be able to add a bunch of cool features to our React apps like user authentication, data persistence, and more. 

For now, `just keep in mind that this _is_ something we'll be discussing in depth later` and head over to the next lesson and continue working through the curriculum. We'll soon be back to building powerful React frontends in the Node.js course! Good luck on your learning journey!

**Comment by codyloyd** [comment]
on your branch running `git reset --hard origin/main` will wipe out _all_ changes on your branch and make it identical to our current origin/main branch... then you can re-add your paragraph and push your branch up.  that should fix the merge conflict.

**Comment by 01zulfi** [comment]
Great, just stole what you have :smile:

**Pull request merged**
