### PR TITLE
Google Project

### PR DESCRIPTION
**Pull request by calandraz**

### CODE REVIEW

**Comment by craftykate** [comment]
@calandraz You need to add the link to your code. Here's a short video on exactly how to do this for the odin project: http://bit.ly/odin-solutions. Let me know if you need help!

**Comment by craftykate** [comment]
Closing this - link added with later pull request.

**Comment by calandraz** [comment]
Oh, ok. I've struggled quite a bit with git. The only way I was able to get
anything onto the site was by copying and pasting. Thank you for the video
link, it was very helpful.

**Comment by craftykate** [comment]
@calandraz You're welcome! Don't worry about git. It can be confusing at first. You'll get the hang of it as you use it.

**Pull request closed without merging**
