### PR TITLE
CSS Foundations: add embedded scrims

### PR DESCRIPTION
**Pull request by webfliccy**
## Because
Interactive embeds from [Scrimba](https://www.scrimba.com/) for CSS Foundations section.

## This PR
Added [Intro To CSS](https://scrimba.com/scrim/co12d4cf99cf2776f19e84a9d) scrim to Intro to CSS lesson.
Added [The Cascade](https://scrimba.com/scrim/cof994391b86aefab81df8cba) scrim to The Cascade lesson.
Added [The Box Model](https://scrimba.com/scrim/cof3d488184abe24ec6258ab4) scrim to The Box Model lesson.
Added [Block and Inline](https://scrimba.com/scrim/co5024997a7e46c232d9abe55) scrim to Block and Inline lesson.

## Issue

Closes #XXXXX

## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x]  The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [x] The `Because` section summarizes the reason for this PR
-   [x] The `This PR` section has a bullet point list describing the changes in this PR
-   [x] If this PR addresses an open issue, it is linked in the `Issue` section
-   [x] If any lesson files are included in this PR, they have been previewed with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure it is formatted correctly
-   [x] If any lesson files are included in this PR, they follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

### CODE REVIEW

**Comment by linkonsat** [comment]
So typically, we want to avoid code-along video type resources. One of the biggest skills to learn while doing the Odin Project is problem solving, asking questions, etc. Code-along resources type resources aren't typically used because rather than per say ask a question, utilize the problem solving techniques earlier in the curriculum it can be tempting to just skip to the answer instead of working through the roadblock. If you have any other ideas feel free to make PR's however!

**Comment by webfliccy** [comment]
Hi @linkonsat - This PR was requested by @perborgen who has a prior agreement to add these interactive screencasts, see this lesson for an example: https://www.theodinproject.com/lessons/javascript-objects-and-object-constructors

**Comment by linkonsat** [comment]
No worries. I just got a heads up about it! @webfliccy looks like there is just conflicting files/merge conflict. If you can just resolve those i'll be more than happy to go ahead and merge it.

**Comment by webfliccy** [comment]
The merge conflicts were caused by this commit: 25575(https://github.com/TheOdinProject/curriculum/pull/25575) which restructured folders. Rather than trying to resolve the conflicts I created a new branch with a corresponding PR.  Closing this PR.

**Pull request closed without merging**
