### PR TITLE
What is JSX?: Remove ordered list from examples to prevent a markdown issue

### LINKED ISSUE #27737: What Is JSX?: Links to anchors in lesson contents not working
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

Links to Assignment, knowledge check and Additional resources in [What is JSX?](https://www.theodinproject.com/lessons/react-new-what-is-jsx#converting-html-to-jsx) are pointing to the top of the page instead of jumping to the proper section.
this is caused by the fact these three sections are simple divs nested inside the previous section:  "Converting HTML to JSX", they should be sections with proper ids.

I'd like to fix it but I'll need some guidance, the MD file looks just fine for me, so I don't know what is causing the problem.

### Path

Other / NA

### Lesson Url

https://www.theodinproject.com/lessons/react-new-what-is-jsx

### (Optional) Discord Name

_No response_

### (Optional) Additional Comments

_No response_

### PR DESCRIPTION
**Pull request by Darknab**
## Because

Missing closing tags on li elements were causing a problem with the links in the "Lesson content" section.

## This PR

- Removed the ol lists from the examples as the closing tags issue in JSX files is covered by input tag in the same example.
- Modified the text accordingly to the removal of the list.
- Add line breaks inside the form  to keep consistency accross all examples, and corrected the indentation of the circle elements as it was suggested in the issue discussion.

## Issue

Closes #27737

## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [x] The `Because` section summarizes the reason for this PR
-   [x] The `This PR` section has a bullet point list describing the changes in this PR
-   [x] If this PR addresses an open issue, it is linked in the `Issue` section
-   [x] If any lesson files are included in this PR, they have been previewed with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure it is formatted correctly
-   [x] If any lesson files are included in this PR, they follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

### CODE REVIEW

**Review by MaoShizhong — CHANGES_REQUESTED** [review]
Thanks for doing this @Darknab.
I can't add individual comments below since they're not part of the diff, but we'd also need to change 175 do not mention the `class` bit, as we now only have to deal with changing `stroke-width` to `strokeWidth`.

Side request while we're at it, on line 45 there's a comment. Could you move that comment to above the `return` please?
i.e.
````md
   ```jsx
   function App() {
     // Could replace <></> with <div></div>
     return (
       <>
         <h1>Example h1</h1>
         <h2>Example h2</h2>
       </>
     );
   }
   ```
````

**Comment by Darknab** [comment]
Ok @MaoShizhong, I'm on it!

**Comment by Darknab** [comment]
Can someone help me on solving this lint error please?
Running linter locally don't throw any error, I'm running: `markdownlint-cli2 react/getting_started_with_react/what_is_jsx.md`
what did I miss?

**Comment by MaoShizhong** [comment]
> Can someone help me on solving this lint error please? Running linter locally don't throw any error, I'm running: `markdownlint-cli2 react/getting_started_with_react/what_is_jsx.md` what did I miss?

Likely would be because those rules were added after your created the branch for this PR.
In this instance, manually fixing them would be easiest.
image
If you go to the lint action details, you can see the 4 errors and you can just replace the respective links with the markdown versions (as shown in the `Expected` bit).

**Review by MaoShizhong — CHANGES_REQUESTED** [review]
Thanks for fixing up the KC links.
Just noticed that your previous commit converted the 3-space indentation for the ordered list children to 2 spaces.
Could you please revert these to 3 spaces?

Ordered list items that take up multiple lines need all lines to start with a 3-space indent as per our [layout style guide], else they won't be considered part of the same item.

If you put your markdown into the [markdown preview tool](https://www.theodinproject.com/lessons/preview), you'll notice that the relevant ordered list is only `1.` instead of `1. 2. 3.`, because of the 2-space indent.

Reverting them back to a 3-space indent will fix this.

**Review by MaoShizhong — APPROVED** [review]
:rocket:

**Pull request merged**
