### PR TITLE
Added descriptive links to the following lessons. Related to #28290

### PR DESCRIPTION
**Pull request by Preslav977**
## Because
Added descriptive links text to the following lessons.

## This PR
* Updated links are in the following lessons: Bubble Sort, Object-Oriented Programming, and File and Serialization.

## Issue

Related to #28290

## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project curriculum contributing guide](https://github.com/TheOdinProject/curriculum/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [x] The `Because` section summarizes the reason for this PR
-   [x] The `This PR` section has a bullet point list describing the changes in this PR
-   [x] If this PR addresses an open issue, it is linked in the `Issue` section
-   [x] If any lesson files are included in this PR, they have been previewed with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure it is formatted correctly
-   [x] If any lesson files are included in this PR, they follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

### CODE REVIEW

**Review by MaoShizhong — CHANGES_REQUESTED** [review]
Looks like your fork is out of sync with TOP's repo (upstream), so you were editing older versions of these lessons than what we currently have. Therefore, there are a few merge conflicts to resolve with all three files.

You can either resolve them yourself, or if you're not sure how best to resolve them, you could checkout back to `main` in your clone, update your clone's `main` branch via `git fetch upstream main &&  git merge upstream/main`, then create a new branch off `main` (which will now be up to date). You can do your changes in that branch and open a fresh PR.

Do whichever you're more comfortable with. Whenever you make a new branch off `main` for a new PR, you should always checkout to `main` and update it before making the branch ([refresher from "Using Git in the Real World"](https://www.theodinproject.com/lessons/javascript-using-git-in-the-real-world#ongoing-workflow)).

**Comment by Preslav977** [comment]
Just say what would be easier — probably doing it again from the start.

I don't know how I keep messing it up.

So I need to close the PR and do it again.

**Comment by MaoShizhong** [comment]
You just didn't realise that your existing fork hadn't been updated with TOP's latest changes, hence the merge conflicts since a lot of changes were made to the three lesson files since, and your changes clash with the current versions.

In this case, easier would be to close this PR and open a new one after updating your local fork.

1. Checkout back to `main`
2. You may have already done this but just in case you hadn't, run `git remote add upstream https://github.com/TheOdinProject/curriculum.git` to connect your clone to TOP's repo.
3. Run `git fetch upstream main` then `git merge upstream/main` to update your clone's `main` branch with TOP's latest changes.
4. Now you can make your new branch and do your changes there, then open the new PR from that.

**Comment by Preslav977** [comment]
Ah. Okay. I have been doing it backwards. My bad.

**Comment by MaoShizhong** [comment]
No need to worry about it. People are bound to make mistakes when unfamiliar. I've had my fair share, that's for sure.

**Comment by Preslav977** [comment]
Hello. So I forked and then cloned the repository.

Then I connected to the repository and used the commands to update my clone's main branch.

I created the branch and made the changes. I followed the lessons, but I am confused. I should be able to push changes from my branch, right?

Because I understand I can't, but I should open a PR. Unfortunately,  I don't remember what I did yesterday.

I reread the lessons multiple times, but in my opinion, I should be able to push to open a PR like yesterday.

**Comment by MaoShizhong** [comment]
You need to push your changes in your branch. Then you can come to GH and open a PR from that branch to TOP's repo, but yiu need to push first. After pushing, if you go to your fork on GH, you'll see a notification to compare and open a PR, which will allow you to do that. Alternatively, you can go to TOP's repo's PR page and manually open a new PR from there.

**Comment by Preslav977** [comment]
I am trying, but it says it doesn't have those rights. This is really hard.

I made sure that I was on the same branch, and I followed what you said yesterday. I basically did it twice just to make sure, but I can't wrap my head around why I am stuck with this.

**Comment by MaoShizhong** [comment]
I'm at a PC now - feel free to DM me on Discord since it'll make it easier to diagnose and share screenshots etc.

**Pull request closed without merging**
