### PR TITLE
CSS Units lesson: Add reminder for learners to test their skills before moving on

### PR DESCRIPTION
**Pull request by DevVivan**
## Because

I have added a reminder for learners to test their skills, and as a result, consolidate their learnings after reading the documentation.

## This PR

- A reminder recommending learners to test their skills

## Issue

Closes #XXXXX

## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [x] The `Because` section summarizes the reason for this PR
-   [x] The `This PR` section has a bullet point list describing the changes in this PR
-   [x] If this PR addresses an open issue, it is linked in the `Issue` section
-   [x] If any lesson files are included in this PR, they have been previewed with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure it is formatted correctly
-   [x] If any lesson files are included in this PR, they follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

### CODE REVIEW

**Comment by ManonLef** [comment]
I have a feeling this lesson was perhaps written with an introduction / overview of units in mind. I'm not sure if the "test your skills" section is needed at this point in the curriculum and for this lesson. I hope @codyloyd can shed some light on this.

**Comment by DevVivan** [comment]
Hmmm, from my viewpoint, I had made this commit as some new concepts such as the difference between em & rem, viewport units and some other values were covered. I would say this content would be fairly new for the student and so I believe asking them to test their skills could be useful.

**Comment by ManonLef** [comment]
While I do agree that these units are newly introduced, I don't feel that the "test your skills" section reflects the `understanding` of these units you have mentioned. 

At this point learners should feel quite comfortable with css syntax which I think is what this section is mainly testing or putting in practice.

**Comment by DevVivan** [comment]
Alright, I guess we can close this PR then.

**Comment by ManonLef** [comment]
@DevVivan thanks either way for all the work you're putting in these days!

**Pull request closed without merging**
