### PR TITLE
Update time_complexity.md (#1)

### PR DESCRIPTION
**Pull request by damon314159**
Time Complexity Lesson: Add detail to O(N log N) explanation

## Because
The section regarding O(N log N) mentions merge sort in a way that could imply all N log N complexities are of the format of an algorithm of O(log N) steps, with a nested algorithm of O(N) steps. While this is true for the merge sort, is it not the only way in which O(N log N) can arise.
The inverse could also occur, where you would have an algorithm of O(N) steps, with a nested algorithm of O(log N) steps. Or even an algorithm that doesn't use such a "divide into two and conquer" approach, which may have an N log N complexity without nesting algorithms in such a neatly explainable way.
The example I have chosen to highlight this is the algorithm for constructing a Cartesian tree from a given array. In short it works as follows
- Initialize an empty stack and an empty tree.
- Traverse the input array from left to right.
- For each element in the array, pop elements from the stack until the top element is larger than the current element. Each popped element becomes the right child of the previous element.
- Push the current element onto the stack.
It leverages the properties of a stack and a binary tree to achieve this complexity compared to the clear-cut nature of merge sorts two distinct component algorithms.

I think it is important to note, even very briefly, that there are other ways this sort of complexity can arise, as the current lesson does not paint a complete picture.

## This PR
- Add extra detail to the subsection regarding another example of an algorithm with such a complexity, but achieved in a different way.

## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [x] The `Because` section summarizes the reason for this PR
-   [x] The `This PR` section has a bullet point list describing the changes in this PR
-   [x] If this PR addresses an open issue, it is linked in the `Issue` section
-   [x] If any lesson files are included in this PR, they have been previewed with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure it is formatted correctly
-   [x] If any lesson files are included in this PR, they follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

### CODE REVIEW

**Comment by codyloyd** [comment]
This seems legit to me, but it is outside of my area of expertise.  tagging @CouchofTomato who might be able to confirm that this is a disclaimer we want to add here.

**Comment by CouchofTomato** [comment]
@damon314159 

Thanks for the edit. Agree we need to clarify here.

We do try to avoid introducing concepts that are never explained so in order to accept this how about we do the following.

1) We can make a very small change to the first paragraph. In the second sentence we can state that This notation *usually* implies. That will lead better into your edit.
2) Can you change where you write Cartesian tree to be a link to a source which describes what it is. Just so learners can take a peek to get a basic understanding if they wish.

**Comment by damon314159** [comment]
I have made the requested changes and clarified that the article is only if they're curious. I hope I did that right, but let me know if not. Its my first PR! :)

**Review by CouchofTomato — APPROVED** [review]
Thanks @damon314159

**Pull request merged**
