### PR TITLE
add tbmreza's solution

### PR DESCRIPTION
**Pull request by tbmreza**
This is a PR template. If you are adding a solution link to the curriculum, leave this as is. If not, delete it and write the message you wish.

Thank you,

The Odin Project team.

### CODE REVIEW

**Comment by ryanford-frontend** [comment]
Nice work, but as this requires a nodejs backend, if you want to show a live demo, try REPLit or heroku. Github pages doesn't allow you to show what the exercise is demonstrating.

**Comment by tbmreza** [comment]
@ryanford-frontend Thanks for taking the time to check my work.

I saw the previously added [solution](https://github.com/TheOdinProject/curriculum/pull/11263/files) (it used github.io) and thought that it's template. I also tested navigating the sites (mine and Carmine's) the same way and it's fine. I have one experience deploying at heroku but I think I will prefer to remove my 'View in browser' altogether this time.

Can you help direct what I should do now? Thanks!

**Comment by ryanford-frontend** [comment]
Ok so I *can* just remove it. But if you still want to submit a demo, it's pretty easy with [repl.it](https://repl.it). To create a demo: 
1. go there and click the "+ new repl" button at the top. 
2. choose nodejs as the language
3. enter your solution repo as the github url and click "Import from GitHub"
4. in the repl, it looks to `index.js` as the entry point, so you can just copy your `server.js` code into `index.js` if you don't want to make changes to your repo.
5. click run and it should load all the dependencies and show your your index.html in the web view.

The url for your demo will be in the url bar for the web view.

**Comment by ryanford-frontend** [comment]
Nice work. Thanks for helping us to improve the course :trophy:

**Pull request merged**
