### PR TITLE
README and Contributing: Update files based on new guides

### PR DESCRIPTION
**Pull request by thatblindgeye**
- [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
- [x] The title of this PR follows the `where the change occurs: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
- [ ] I have previewed any Markdown file(s) in the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure the Markdown content is formatted correctly.

- [ ] If one exists, I have linked a related open issue to this PR in Step 2 below
- [ ] If changes were requested, I have made them and re-requested a review from the maintainer (top of the right sidebar)

**1. Description of the Changes**
 
Related to https://github.com/TheOdinProject/theodinproject/pull/2641

I've moved both the old README and Contributing guide files to the archive folder. The old README file I wanted to preserve fo rnow since it is currently being viewed internally, and the Contributing guide I've archived due to us using a single source of truth moving forward.

I also added an updated README file for this repo itself, removing some things that aren't necessary any more and updating some verbiage. I made this README more focused on the content of this repo, while still linking to our main repo for the actual app and fron-end/back-end code.

**2. Related Issue**

Closes #XXXXX

### CODE REVIEW

**Comment by 01zulfi** [comment]
I have a question regarding the contributing file. I see you've linked the website repo's contributing guide in the README and removed this repo's guide. 

Do you see any merit in having a `CONTRIBUTING.md` for this repository just for it to link the website repo's guide?

**Comment by thatblindgeye** [comment]
So the reason for deleting it was partially it already being in the README and partially to just avoid having to click into it only to click a link leading to another repo.

That said, if you think it would be beneficial to have a contributing file that informs users that "the guide can be found at <insert link here>", I can add it back in as it's not something I feel strongly about either way.

**Comment by 01zulfi** [comment]
The new README is much more digestible and I hope the README's contributing section would be easier to find. I don't think we _need_ a contributing file for this repository.

**Review by 01zulfi — APPROVED** [review]
:rocket:

**Pull request merged**
