### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by sapienfrom2000s**
## Because
Studying about routing, controllers and models is useless without having the idea of whole picture.

## This PR
It puts the blog project before introducing the critical MVC and routing. The cool thing about blog project is that it contains, getting started with rails from the official documentation. It does an excellent job of skimming through the MVC + routing without going into detail and explaining through a practical example.
Directly reading MVC in detail leads to tunnel vision where freshers can't see anything. In discord, this issue comes up again and again where they complain they can't understand a thing in MVC. I guess that's becoz they are unable to see the bigger picture. So, https://guides.rubyonrails.org/getting_started.html till 8.4 would be a great light start.

## Issue

Closes #XXXXX

## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [x] The `Because` section summarizes the reason for this PR
-   [x] The `This PR` section has a bullet point list describing the changes in this PR
-   [x] If this PR addresses an open issue, it is linked in the `Issue` section
-   [x] If any lesson files are included in this PR, they have been previewed with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure it is formatted correctly
-   [x] If any lesson files are included in this PR, they follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

### CODE REVIEW

**Comment by codyloyd** [comment]
i'm not sure we really need to work on the flow of our documentation here.. since we already maintain a full course for learning rails lol.

Even so.. if this is an improvement, why not?

I'll leave it for the members of the @TheOdinProject/rails-path team to take a look

**Comment by linkonsat** [comment]
Just taking a glance at the structure of the overall courses we do discuss MVC in the Railsy Web Refresher right before the start of Rails basics and just comparing the Rails section on MVC versus this [resource](https://betterexplained.com/articles/intermediate-rails-understanding-models-views-and-controllers/) in the previous lesson. i'm not entirely sure what the benefit would be of making the rails blog project come first. As the project is supposed to utilize what you learn in the previous lessons. Putting the project first _before_ the lessons would make them less likely to stick imo versus having a project at the end that brings it together and then you move onto a new conceptual area. Always open to discussion _but_ given we have a resource on MVC in the lesson right before the Rails basics section and the project is meant to bring together the concepts from previous lessons which moving the project up first would go against that.  I don't quite see the benefit of re-arranging it. As the Rails basics is pretty early on and I would expect folks to not quite get it perfectly that early as well.

**Comment by sapienfrom2000s** [comment]
Well, most of the "blog project" is just following getting started with rails documentation. The resource you mentioned gives a glimpse of MVC model but that's it. In every documentation there is a 'getting started' section from which you can code along and it gives a good overview for what's coming. I still think that routing, views and controllers chapter is too deep, especially if someone who is new to web dev. Following the "big 3" after getting started with rails doc would be great in my opinion.

**Comment by linkonsat** [comment]
Sure, but the lessons aren't teaching technology as much as focused on teaching the concept behind the technology. I.E. Rails routes are a medium to explain how routing works rather than solely ruby on rails routing. I can sort of see where you're coming from in that they are tougher concepts, but I don't think difficulty alone is enough to sway me since it can vary from person to person. Some may get it to click earlier and others later. The people with the toughest time with the lesson are always going to ask question. Which asking good questions is a important skill in and of itself.

**Pull request closed without merging**
