### PR TITLE
adds Sander Schepens's solutions for ruby projects

### PR DESCRIPTION
**Pull request by schepens83**
Attempt 2 with a new pull request. Still don't see a dev branch in your upstream repository, though. Not sure if that was the problem?

### CODE REVIEW

**Comment by KevinMulhern** [comment]
@schepens83, We don't have a dev branch. We really don't have any need for one as most of the pull requests are just submission links to students projects or typo fixes. You need to create a pull request to master. can you follow the guide below to submit your solutions please.

https://www.youtube.com/watch?v=V74l_zS1x8E

**Comment by KevinMulhern** [comment]
Also are you on odin's slack channel?

**Comment by kriox26** [comment]
Hi @schepens83 , are you trying to follow along these tut: http://www.theodinproject.com/ruby-programming/using-git-in-the-real-world ??

**Comment by schepens83** [comment]
Hello.
Yes exactly, that is what I was trying. I had a old fork though, but I think I updated those before I did the solution additions. Maybe something went wrong? I see it says I want to add a lot of commits...

I didn't use slack. I just requested it and am on now.

**Pull request closed without merging**
