### PR TITLE
Add links in knowledge checks to basic ruby

### PR DESCRIPTION
**Pull request by linkonsat**
- [x] You have read [The Odin Projects Contributing Guide](https://github.com/TheOdinProject/curriculum/blob/main/CONTRIBUTING.md).
 - [x] The PR title summarizes the change and where it happened, for example: "Fixes punctuation in Clean Code lesson".
 
#### 1.Describe the changes made and include why they are necessary or important:

Added knowledge check links for the numbers section in the basic data types. 
#### 2. If this PR is related to an open issue please reference it with the `#` operator and the issue number below:

#22467

### CODE REVIEW

**Review by wise-king-sullyman — CHANGES_REQUESTED** [review]
Thanks for submitting this :slightly_smiling_face: but it looks like you've got some formatting issues. To fix you will need to:

* move the `*` back to the beginning of each line to make them all bullet points again
* get rid of the spaces on either side of the equals sign
* add a closing quotation mark at the end of the class name
* change the links you're giving to leverage our section headers, or add spans to the lesson with id's if/where needed.

See [this issue](https://github.com/TheOdinProject/curriculum/issues/22805) for some examples of how to format things, might clear things up better than my explanation here.

**Comment by linkonsat** [comment]
Should be formatted properly now. Looked at other accepted pull requests to make sure the format was acceptable.

**Review by wise-king-sullyman — CHANGES_REQUESTED** [review]
Check my suggested change for a shortening to the first link and a fix to the others. If you'd like you can click "commit suggestion" and it will automatically be added to your branch.

If you'd rather do it manually yourself that's fine too of course, but we do want to follow this format so that the links are shorter, and the last three links didn't seem to work at all for me when I tested them.

**Comment by linkonsat** [comment]
Thank you. Going forward I will double check to make sure the format guide is followed according to issue #22467.

**Review by wise-king-sullyman — APPROVED** [review]
Looks great now, thanks for your contribution!

**Pull request merged**
