### PR TITLE
My Google Homepage Solution

### PR DESCRIPTION
**Pull request by anonRegions**
From the HTML/CSS section

### CODE REVIEW

**Comment by craftykate** [comment]
@anonRegions Do you want to add a "View in Browser" link so people can see what it looks like? This is the link to add: https://htmlpreview.github.io/?https://github.com/anonRegions/google-homepage/blob/master/index.html

**Comment by anonRegions** [comment]
Kate--

Yes, that would be nice. I'm sorry if I was a klutz in setting it up.

Thanks!

Ethan

**Comment by craftykate** [comment]
@anonRegions Do you need help doing that? Do you want me to do it for you?

**Comment by anonRegions** [comment]
Kate--

Forgive me, but I'm not sure what you're asking me. What do I need to do?
I'm happy to do it.

Thanks.

Ethan

**Comment by craftykate** [comment]
@anonRegions Sorry! I was thinking you could modify your pull request to add the view in browser link. If you know how to modify it you can do it yourself, otherwise I can add the link by hand and merge your link.

**Comment by anonRegions** [comment]
Kate--

Here's a two-part answer:
1. Please go ahead.
2. Please explain to me how to modify a pull request to add the view in
browser link. I imagine I'm supposed to know what the view in browser link
is--maybe I'm just getting stupid at this point--but I could use some info
on that.

Thanks.

Ethan

**Comment by craftykate** [comment]
@anonRegions Okay, this is totally my fault for not being clear!

This is the link you submitted: `* [Ethan Rips's solution](https://github.com/anonRegions/google-homepage)` That links to just your code. But if you go to the page with your html on it (`https://github.com/anonRegions/google-homepage/blob/master/index.html`) and then add this to the front of the link: `https://htmlpreview.github.io/?` so your link is now `https://htmlpreview.github.io/?https://github.com/anonRegions/google-homepage/blob/master/index.html` you'll be able to "render" your html code and see what it would look like as a real web page. Many people who submit links to projects that have this visual part to it also add on the link to see it live. 

So I'm going to change your link to now be: ` [Ethan Rips's solution](https://github.com/anonRegions/google-homepage) | [View in browser](https://htmlpreview.github.io/?https://github.com/anonRegions/google-homepage/blob/master/index.html)` so people can see both your code and see how it renders. 

I have this process spelled out in a short video on adding links to the odin project which might make things a little clearer: http://bit.ly/odin-solutions

Does that help?

**Comment by anonRegions** [comment]
Kate--

I think your explanation is very clear.

Thanks a lot!

Ethan

**Comment by anonRegions** [comment]
Truly, you are a goddess!   ;-)

**Comment by craftykate** [comment]
Haha you're welcome @anonRegions

**Pull request merged**
