### PR TITLE
A bit computer science: change the video of explanation of recursion in the assignment

### PR DESCRIPTION
**Pull request by nmcev**
## Because

when i were exploring the computer science curriculum for first time i get into ``Recursive Methods  `` lesson 
  , when i doing the assignment i watched the video of the explanation of recursion by web dev simplified and it was some complicated , frankly when  my own search  i found [this explanation](https://youtu.be/LteNqj4DFD8)  about recursion it is more easy to understand than before one, check it by yourself too,
The reason behind this PR is to become the explanation of recursion more easy and clear to help the people to understand what is  the recursion 

## This PR

- change the link of the [last video by Web Dev Simplified](https://youtu.be/6oDQaB2one8) to the [new one by DevSage](https://youtu.be/LteNqj4DFD8)

## Issue

Closes #XXXXX

## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [x] The `Because` section summarizes the reason for this PR
-   [x] The `This PR` section has a bullet point list describing the changes in this PR
-   [x] If this PR addresses an open issue, it is linked in the `Issue` section
-   [x] If any lesson files are included in this PR, they have been previewed with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure it is formatted correctly
-   [x] If any lesson files are included in this PR, they follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

### CODE REVIEW

**Comment by LeoKirasic** [comment]
@nmcev thank you for making this suggestion! I think that it's great, but could you make another PR that includes both web dev simplified and what you included as well. Ty :)

**Review by LeoKirasic — CHANGES_REQUESTED** [review]
comment above :)

**Comment by nmcev** [comment]
@LeoKirasic  yeah sure i can do another PR that include both videos

**Comment by rlmoser99** [comment]
Closing this PR because it was handled in another PR.
https://github.com/TheOdinProject/curriculum/pull/25786

**Pull request closed without merging**
