### PR TITLE
Intermediate HTML and CSS lessons adding descriptive link text

### PR DESCRIPTION
**Pull request by sasidharan19**
## Because

Provided descriptive link text to the Intermediate HTML and CSS lessons "Creating a Grid && Advanced Grid Properties && Using Flexbox and Grid".

## This PR

- Replaced text with their updated versions as per the [suggested link text changes spreadsheet](https://docs.google.com/spreadsheets/d/1E1OJqUfBODvjdFMNgFMY_GvOLrOzV4ujL9o7Nxzg2zk/edit?usp=sharing).
- Fixed other issues mentioned in the notes column in the above link.

## Issue

Related to #27819

## Additional Information

NA

## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project curriculum contributing guide](https://github.com/TheOdinProject/curriculum/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [x] The `Because` section summarizes the reason for this PR
-   [x] The `This PR` section has a bullet point list describing the changes in this PR
-   [x] If this PR addresses an open issue, it is linked in the `Issue` section
-   [x] If any lesson files are included in this PR, they have been previewed with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure it is formatted correctly
-   [ ] If any lesson files are included in this PR, they follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

### CODE REVIEW

**Review by MaoShizhong — COMMENTED** [review]
Many thanks @sasidharan19 for getting these links fixed up, they all look great!

Would you mind fixing up the remaining lint errors in both files? They should be pretty self explanatory.
Most should be fixable by following the [curriculum repo's contributing guide](https://github.com/TheOdinProject/curriculum/blob/main/CONTRIBUTING.md) to use the npm scripts for fixing. There will still be a few errors that can't be auto-fixed, e.g. the default section content, and ordered list prefixes. So if after running the fixer, you could manually fix the remaining ones, that'd be awesome!
**You can ignore any TOP004 rule errors ("required heading structure") - these errors are something to address in a separate issue.** 

Let me know if you run into any issues!

**Comment by sasidharan19** [comment]
Hello @MaoShizhong, I'm trying to run the npm scripts for fixing the lint errors. However, I'm getting this below error while running the command: 

'project.markdownlint-cli2.jsonc' is unrecognized; its name should be (or end with) one of the supported types (e.g., ".markdownlint.json" or "example.markdownlint-cli2.jsonc").

Screenshot 2024-04-27 024725

This is the command I used:  npm run lint:lesson -- ".\intermediate_html_css\grid\creating_a_grid.md"

Please let me know what should I do to resolve this. 

Thanks.

**Comment by MaoShizhong** [comment]
@sasidharan19 This is throwing an error because you are currently using Windows and Powershell. If you're following the TOP curriculum and you've been using Windows so far, all of us would **highly** recommend revisiting the [installations lesson](https://www.theodinproject.com/lessons/foundations-installations) and using one of the supported options there, which we have full instructions for setting up. While contributing here technically isn't a part of the curriculum directly, continuing to use Windows will very likely result in something similar happening in the future with a curriculum instruction, whereby the fix won't be so simple. You won't be able to get assistance in the TOP community if that ends up being related to the use of Windows, or another unsupported OS.

In this specific scenario, you can use the command
```bash
markdownlint-cli2 --config lesson.markdownlint-cli2.jsonc ".\path\to\file"
```
Replace the name of the config file as necessary (lesson or project), and add the `--fix` option in if you want to apply the fixes.

**Comment by sasidharan19** [comment]
Hello @MaoShizhong, Thanks for your instructions. I have installed a Ubuntu VM and will be continuing the TOP curriculum on ubuntu OS.

And I have run the npm script which fixed most of the lint errors, and for the remaining default section content, and ordered list prefixes error, I have updated them manually.

Please review the changes and let me know if anything I need to change.

Thanks for your assistance.

**Review by MaoShizhong — APPROVED** [review]
Awesome, thank you for getting all of the stylistic lint errors fixed up too! Looks great! :rocket:

**Comment by sasidharan19** [comment]
Thank you Mao, Thanks for the opportunity to contribute!

**Pull request merged**
