### PR TITLE
Project - Sign-up form: Fix ordering of instructions in step 1

### PR DESCRIPTION
**Pull request by DevVivan**
## Because

I have moved the second instruction in the section titled 'Step 1: Set up and planning` to precede the first instruction as it would make more sense to a student. Previously, the first instruction asked to set up HTML & CSS files before setting up a repository. However, this is not possible. So to make more sense, I have moved the second instruction above the first so it is more clear to the student that they should create the repository first and then work on setting up their HTML & CSS files.

## This PR

- Moved the second instruction to precede the first instruction in the section titled 'Step 1: Set up and planning` 

## Issue

Closes #XXXXX

## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [x] The `Because` section summarizes the reason for this PR
-   [x] The `This PR` section has a bullet point list describing the changes in this PR
-   [x] If this PR addresses an open issue, it is linked in the `Issue` section
-   [x] If any lesson files are included in this PR, they have been previewed with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure it is formatted correctly
-   [x] If any lesson files are included in this PR, they follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

### CODE REVIEW

**Comment by CouchofTomato** [comment]
Why is it not possible?

**Comment by DevVivan** [comment]
The user is asked to first set up the HTML & CSS files and then, move onto setting up their repository. How is it possible to setup files on a repository before creating the repository itself?

**Comment by ManonLef** [comment]
@DevVivan you can "initialise" a local folder into a git repository (might be worth a google for yourself :) ). So you could indeed first create the files and then turn the folder they're in into a git repo.

Up to this point however, I believe TOP follows the steps of: creating a repo on GH, then clone that to local. I don't think `git init` is covered anywhere. 

Considering that, it does make sense to me to turn those two steps around.

**Comment by DevVivan** [comment]
Oh wow! That is totally my bad, however, if TOP doesn't teach this at this point, this swapping of instructions could be useful then in my opinion

**Comment by CouchofTomato** [comment]
Maybe we should consider covering attaching a repository to an existing local project folder somewhere though since this may come up.

@ManonLef If you're happy with this then feel free to merge

**Comment by ManonLef** [comment]
Thanks again for your contribution @DevVivan 🎉

**Pull request merged**
