### PR TITLE
added missing knowledge check section and the corresponding links to NodeJS/Intro to Express

### LINKED ISSUE #22954: Add missing Knowledge Checks, Learning Outcomes, and Knowledge Check links to NodeJS/Introduction to Express
Related to #22473

This task is to go through the Introduction to Express lesson in the NodeJS course and (as applicable):

- Add missing Learning Outcomes
- Add missing Knowledge Checks
- Add answer links in the Knowledge Checks

If the lesson already has Learning Outcomes or Knowledge Checks they do not need to be added to. Many lessons only need answer links added.

Knowledge check links should consist of an `<a>` tag which adds the `knowledge-check-link` class and links to the part of the lesson (or the external resource that is linked in the lesson) where the answer to the Knowledge Check can be found. Knowledge Check links should **not** point to external resources that weren't linked to as part of the lesson content or assignment. You can link to a specific line in the lesson like so:

```html
Lorem ipsum dolor sit amet, <span id='example-knowledge-check'>consectetur adipiscing elit</span>, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua

...
<!-- This a tag just goes to the page where the span with this id lives -->
<a class='knowledge-check-link' href='#example-knowledge-check'>How do you return a value from a function?</a>
```
Or you can link to just a section of the lesson by just linking to the section heading and following [these](https://github.com/TheOdinProject/curriculum/wiki/Contributing-to-Wiki#anchor-linking) rules for determining how to format the link. Example:

```html
### Lorem ipsum dolor sit amet

sed do eiusmod tempor incididunt ut labore et dolore magna aliqua

...
<!-- This a tag just goes to a heading on the page-->
<a class='knowledge-check-link' href='#lorem-ipsum-dolor-sit-amet'>How do you return a value from a function?</a>
```

### Acceptance Criteria

- [ ] Lesson referenced in the title has Learning Outcomes, Knowledge Checks, and Knowledge Check links
- [ ] Knowledge Check links all link to the proper place in the lesson, or the proper external resource that was linked to earlier in the lesson
- [ ] Knowledge Check styling should **not** change

Please do not start work on this unless you've been assigned to it. Comment on this issue and ping me @wise-king-sullyman if you would like to be assigned to it.

Additionally, we would like for contributors to only take on one of these issues at a time. Please only request assignment for (and begin work on) an issue after the Learning Outcome/Knowledge Check/Knowledge Check link issue you're currently assigned to has been approved and merged.

### PR DESCRIPTION
**Pull request by eneamuskaj**
- [x] You have read [The Odin Projects Contributing Guide](https://github.com/TheOdinProject/curriculum/blob/main/CONTRIBUTING.md).
 - [x] The PR title summarizes the change and where it happened, for example: "Fixes punctuation in Clean Code lesson".
 
#### 1.Describe the changes made and include why they are necessary or important:

Ive added the missing knowledge check section and the corresponding links. 

#### 2. If this PR is related to an open issue please reference it with the `#` operator and the issue number (and any [relevant keywords](https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests)) below:

closes #22954

### CODE REVIEW

**Review by twalton83 — COMMENTED** [review]
Honestly, I think we only want a small handful. As in, no more than 5.

**Comment by eneamuskaj** [comment]
Ive reduced the amount to five. Let me know if there is something more i should do. Thank you!

**Review by twalton83 — APPROVED** [review]

**Comment by wise-king-sullyman** [comment]
@eneamuskaj going forward please use the `closes` keyword before referencing the issue number if the PR you're submitting will close the related issue. Also please reference the lesson name in the PR title.

I've updated this PR for both of these items, so just something to be aware of for the future.

**Comment by wise-king-sullyman** [comment]
@twalton83 is there something holding up merging this or is it good to go in?

**Comment by twalton83** [comment]
Nope, had to run Codespell is all.

**Comment by eneamuskaj** [comment]
@wise-king-sullyman It was my first contribution, I'll make sure not to forget it next time. Thank you! :)

**Pull request merged**
