### PR TITLE
Foundations Flexbox growing and shrinking lesson: Knowledge Check Addition

### PR DESCRIPTION
**Pull request by aaronlrv**
Complete the following REQUIRED checkboxes:

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`

Complete the following checkboxes ONLY IF they are applicable to your PR. You can complete them later if they are not currently applicable:
-   [x] I have previewed all lesson files included in this PR with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure the Markdown content is formatted correctly
-   [x] I have ensured all lesson files included in this PR follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

<hr>

**1. Because:**

Closes #XXXXX

**2. This PR:**

**3. Additional Information:**

Specified not to close from https://github.com/TheOdinProject/curriculum/issues/24177

### CODE REVIEW

**Comment by aaronlrv** [comment]
@dm-murphy  Hey! Apologies for the long wait, Life got busy with my new internship.

Let me know your thoughts on this, But currently i'm a bit iffy on the knowledge point added at the moment as the answer is given right above with the knowledge point before it specifying `flex: 1 1 auto`. However we didn't add any new content besides the flex:auto section to cover as a new knowledge point.

**Comment by dm-murphy** [comment]
> @dm-murphy Hey! Apologies for the long wait, Life got busy with my new internship.
> 
> Let me know your thoughts on this, But currently i'm a bit iffy on the knowledge point added at the moment as the answer is given right above with the knowledge point before it specifying `flex: 1 1 auto`. However we didn't add any new content besides the flex:auto section to cover as a new knowledge point.

No worries at all @aaronlrv and I've been unavailable myself. I agree with your take here that this question is too similar to the existing Knowledge Check.

Feel free to work on another solution if you'd like. Best wishes with the new internship! Sure you will do great! 🙂

**Comment by aaronlrv** [comment]
> > @dm-murphy Hey! Apologies for the long wait, Life got busy with my new internship.
> > Let me know your thoughts on this, But currently i'm a bit iffy on the knowledge point added at the moment as the answer is given right above with the knowledge point before it specifying `flex: 1 1 auto`. However we didn't add any new content besides the flex:auto section to cover as a new knowledge point.
> 
> No worries at all @aaronlrv and I've been unavailable myself. I agree with your take here that this question is too similar to the existing Knowledge Check.
> 
> Feel free to work on another solution if you'd like. Best wishes with the new internship! Sure you will do great! slightly_smiling_face

Hey thanks on all the wishes, I've been pondering for about 2 days and I can't seem to find a new knowledge point for the new content though that differentiates itself from the first one. Do you have any ideas on what we could ask to solidify the brand new concepts?

**Review by zachmmeyer — APPROVED** [review]
I'm going to go ahead and approve this and merge it in. Thanks for contributing.

**Pull request merged**
