### PR TITLE
Add Google Homepage EASY version

### PR DESCRIPTION
**Pull request by briantuju**
This is a PR template. If you are adding a solution link to the curriculum, leave this as is. If not, delete it and write the message you wish.

Thank you,

The Odin Project team.

### CODE REVIEW

**Comment by briantuju** [comment]
Good morning. I see my commit has a label of awaiting changes. What am I supposed to change to make it complete?

**Comment by 105ron** [comment]
Hi @briantuju,
You have included the github pages link on line 2190 of this file. The student solutions are between lines `91` and `2179`. Each student solution has the same formatting. If you follow this formatting and place it above the first student solution at around line `91` then I can merge it. This file is parsed via our web application and turned into `html` once a day, if you do not use the correct syntax and place the solution in the right position our website will look strange. I have included a similar comment  on another PR. Thanks.

**Comment by briantuju** [comment]
Okay, thank you. I will do as recommended. Quick question, do i have to close this pull request in order to do make the recommended changes?

**Comment by 105ron** [comment]
No, you do not need to close this PR. You can just click the files changed tab above, then click the three dots to the right of the file, click edit and edit the file in GitHub's online IDE.

**Comment by briantuju** [comment]
I have done as instructed, but now there's a merge conflict. Kindly review my changes, thank you.

**Comment by 105ron** [comment]
Thanks @briantuju,
the merge conflict is because other people have contributed on that same line since you made your pull request. Either of us can fix it, but I'll do it for you this time. You'll see your solution on the site within the next 24 hours. Thanks, Rhys.

**Pull request merged**
