### PR TITLE
asset_pipeline.md: Removed a outdated learning objective

### LINKED ISSUE #28064: The Asset Pipeline: <learning overview item with no reference in lesson>
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

It looks like third third lesson overview item, 'How to display raw HTML-code in your app', is a reference to a removed part of the lesson. Suggest either removal of the learning objective or inclusion of explanatory content

Note - there's already [a stale issue](https://github.com/TheOdinProject/curriculum/issues/25588) re. this lesson. Not sure if it's relevant but I thought it's worth linking here.

### Path

Ruby / Rails

### Lesson Url

https://www.theodinproject.com/lessons/ruby-on-rails-the-asset-pipeline

### (Optional) Discord Name

_No response_

### (Optional) Additional Comments

_No response_

### PR DESCRIPTION
**Pull request by theSamyak**
Removed a outdated learning objective - How to display raw HTML code in asset_pipeline.md in reference to issue #28064

## Because

This PR removes an outdated learning objective from the "Ruby on Rails - The Asset Pipeline" lesson. The objective referenced displaying raw HTML code in the app, but this section was removed from the lesson content in the past. This update ensures the curriculum accurately reflects the current lesson structure.

## Issue

Closes #28064

## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project curriculum contributing guide](https://github.com/TheOdinProject/curriculum/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [x] The `Because` section summarizes the reason for this PR
-   [x] The `This PR` section has a bullet point list describing the changes in this PR
-   [x] If this PR addresses an open issue, it is linked in the `Issue` section
-   [x] If any lesson files are included in this PR, they have been previewed with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure it is formatted correctly
-   [x] If any lesson files are included in this PR, they follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

### CODE REVIEW

**Review by MaoShizhong — APPROVED** [review]
Thanks for doing this, @theSamyak.

If you're happy to fix the rest of the linting errors, you can best do this by working with a local clone of your fork and branch since there are so many, where you can follow our [local linting instructions](https://github.com/TheOdinProject/curriculum/blob/main/CONTRIBUTING.md). Two passes of the `fix:lesson` script *should* result in one h3/h4 error left that can only be fixed manually.

Let me know if you're comfortable doing this. If so, go ahead and hit the "re-request review" button as shown below to let me know when you're done with those fixes. Feel free to ask any question if you run into issues.

image

Conversely, if you're not comfortable with fixing these here, let me know and I'll be happy to merge this PR as is, since it does resolve the linked issue. The lint errors can be solved separately another time.

**Comment by theSamyak** [comment]
> Thanks for doing this, @theSamyak.
> 
> If you're happy to fix the rest of the linting errors, you can best do this by working with a local clone of your fork and branch since there are so many, where you can follow our [local linting instructions](https://github.com/TheOdinProject/curriculum/blob/main/CONTRIBUTING.md). Two passes of the `fix:lesson` script _should_ result in one h3/h4 error left that can only be fixed manually.
> 
> Let me know if you're comfortable doing this. If so, go ahead and hit the "re-request review" button as shown below to let me know when you're done with those fixes. Feel free to ask any question if you run into issues.
> 
> image
> 
> Conversely, if you're not comfortable with fixing these here, let me know and I'll be happy to merge this PR as is, since it does resolve the linked issue. The lint errors can be solved separately another time.

Hi @MaoShizhong ,

Thank you for the clear instructions. I would gladly fix the remaining linting errors. I'll follow your suggestions and re-request a review when I'm done.
You can merge this PR as it would be more efficient for me to work on a separate branch dedicated to resolving these issues.

I plan to start working on this by tomorrow or the day after. If I encounter any issues, I'll reach out for guidance. I hope you have a great day!

**Comment by MaoShizhong** [comment]
Sure thing. I'll merge this one, then you can work on a separate PR for the remaining lint issues. In that PR, you can add `Related to #28295` in the PR form to provide context for it.

**Comment by theSamyak** [comment]
> Sure thing. I'll merge this one, then you can work on a separate PR for the remaining lint issues. In that PR, you can add `Related to #28295` in the PR form to provide context for it.

Gotcha! Thanks for merging this PR!

**Pull request merged**
