### PR TITLE
Update problem_solving.md

### PR DESCRIPTION
**Pull request by dm-murphy**
Trying to resolve issue #18528 (Pseudo code in ruby problem solving lesson is formatted poorly)

The 2 sections of pseudo code here both render correctly in the Git preview with appropriate line breaks, but on the actual TOP page they do not show any line breaks. I replaced the use of 3 backticks with 3 tildes instead to see if that will fix it. If that doesn't work I could also try using 4 spaces to indent each line or use 2 carriage returns to force the line break.

### CODE REVIEW

**Comment by ZachBaird** [comment]
Hey @dm-murphy , there's a similar issue over on [The Javascript version as well](https://www.theodinproject.com/courses/javascript/lessons/problem-solving-javascript). Do you want to add that to this PR to see if it fixes both?

**Comment by dm-murphy** [comment]
Hey @ZachBaird, thanks for pointing that out. Yes I will go ahead and make the same change on the JS version from 3 backticks to 3 tildes and we'll see how that goes. For the Ruby page I had already fixed a number of typos, grammatical and clarity errors. And @marvingay had me change the output terms for Fizz, Buzz and FizzBuzz from double quotes to backticks. I can go ahead and make all those same changes manually on the JS page, unless there is an easier way to migrate the same fixes from the new Ruby page over that I'm not sure about. I'm still learning the Git process here. Thanks!

**Comment by ZachBaird** [comment]
@dm-murphy I'm afraid it'll have to be manual :\ Thanks for contributing!

**Comment by dm-murphy** [comment]
@ZachBaird No worries and happy to help! I'll go ahead and make all the JS page changes now and then we can see how the new code blocks turn out.

**Pull request merged**
