### PR TITLE
Minor grammar edits and added npx to webpack command

### PR DESCRIPTION
**Pull request by AJMcDee**
This is a PR template. If you are adding a solution link to the curriculum, leave this as is. If not, delete it and write the message you wish.

Thank you,

The Odin Project team.

### CODE REVIEW

**Comment by I3uckwheat** [comment]
@AJMcDee 

Are the directions to run `webpack` without `npx` still relevant? Can we remove those?

**Comment by AJMcDee** [comment]
Well they're for outdated versions so unless someone is running an old npm
they shouldn't be relevant.

**Comment by I3uckwheat** [comment]
@AJMcDee Sweet, can you update this and remove the old commands? Then I'll merge :)

**Comment by AJMcDee** [comment]
Done!

**Pull request merged**
