### PR TITLE
NodeJS Course, Getting Started lesson: Add link to http.createServer 

### PR DESCRIPTION
**Pull request by RushilJalal**
Lesson Link : https://www.theodinproject.com/lessons/nodejs-getting-started

## Because
Previous link provided was for `http` module, not `http.createServer`

## This PR

- Add a link to `http.createServer` docs

image

## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project curriculum contributing guide](https://github.com/TheOdinProject/curriculum/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [x] The `Because` section summarizes the reason for this PR
-   [x] The `This PR` section has a bullet point list describing the changes in this PR
-   [x] If this PR addresses an open issue, it is linked in the `Issue` section
-   [x] If any lesson files are included in this PR, they have been previewed with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure it is formatted correctly
-   [x] If any lesson files are included in this PR, they follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

### CODE REVIEW

**Comment by MaoShizhong** [comment]
Thanks for this PR @RushilJalal 

The current link to the http module only is intentional. We want people to be aware of the whole http module doc, and at this point in the curriculum, people should have no issues searching it for a specific method. Having a link to the method then also linking the module doc as a whole is redundant in my honest opinion.

**Comment by RushilJalal** [comment]
@MaoShizhong I get your point. But the docs page doesn't have a search option. I know one could just `Ctrl + F` it tho.
If you want the users to be aware of the `http` module the link should be 
https://nodejs.org/api/http.html#http
not 
https://nodejs.org/api/http.html
What do you think?

**Comment by MaoShizhong** [comment]
> @MaoShizhong I get your point. But the docs page doesn't have a search option. I know one could just `Ctrl + F` it tho. If you want the users to be aware of the `http` module the link should be https://nodejs.org/api/http.html#http not https://nodejs.org/api/http.html What do you think?

The original link is fine as it's all one page, and the original link is the top of the page with the full table of contents. Everything there is part of the `http` module.

I would be up for rewording that assignment step's first sentence to something like this to better reflect its intent:
```md
    - Check out the docs for [Node's http module](https://nodejs.org/api/http.html). In particular, check out `http.createServer`.
```

**Review by MaoShizhong — APPROVED** [review]
Thanks for contributing!

**Pull request merged**
