### PR TITLE
Fix punctuation and grammar links and images

### PR DESCRIPTION
**Pull request by msespos**
- [x] You have read [The Odin Projects Contributing Guide](https://github.com/TheOdinProject/curriculum/blob/main/CONTRIBUTING.md).
 - [x] The PR title summarizes the change and where it happened, for example: "Fixes punctuation in Clean Code lesson".
 
#### 1.Describe the changes made and include why they are necessary or important:

Fix punctuation and grammar links and images

#### 2. If this PR is related to an open issue please reference it with the `#` operator and the issue number below:

Not related to an open issue

### CODE REVIEW

**Review by wise-king-sullyman — CHANGES_REQUESTED** [review]
I would like to see either all list items end with periods, or none of them end with periods. I don't have a strong say on which is "better" here, but I think they should be consistent across the lesson.

That being said, in researching this I'm seeing a bunch of different assertions on what the proper usage of punctuation is with lists. I'm no English expert and could be way off base here. If there's some widely recognized list punctuation structure that you followed in doing this please just let me know.

**Comment by msespos** [comment]
I had no recognized structure. and did not strive for consistency across the lessons, just within lists. I've been trying to keep my changes as minimal as possible so I just made sure each list all either ended with periods or didn't. If you'd like I can standardize the lists in this lesson, although then the obvious next task is to standardize list punctuation across the site... let me know what you'd like me to do here though! :)

**Comment by wise-king-sullyman** [comment]
Yeah I would like some kind of consistent style or structure for all lists in the lesson. Some lists are full sentences and others are mostly fragments though, so that will be an issue. I'm sure you can come up with a good approach. As long as it's either consistent in appearance, or consistent in following a known set of rules, I'll be happy :slightly_smiling_face:.

As far as the next step of standardizing across the whole curriculum I don't disagree, but that will involve some conversations that we need to have on the maintainer team so that we are all in agreement and pulling in the same direction.

**Comment by msespos** [comment]
I botched something with my branches and commits and ended up putting the commit "Edit lists in CSS Foundations" in both this PR and the "Fix punctuation and grammar in CSS Foundations" PR (also from today). Let me know if I should start over with this PR; I'm happy to. Sorry about that.

**Comment by msespos** [comment]
As to the lists themselves, I decide edit them according to the following guidelines I got from https://www.grammarly.com/blog/bullet-points/:

"Punctuation with bullet points

If the text of your bullet point is a complete sentence (or multiple sentences), use capital letters and punctuation. If your points are not structured as proper sentences, you don’t need to end with punctuation. Capitalization is a style choice—with sentence fragments, you can choose to start each with either upper- or lower-case letters."

As you can see, this does not enforce consistency across an entire lesson, but rather consistency depending on the type of list, and leaves some options open. I decided was to use capitalization for the first word of all list entries. I then followed the guideline of ending entries with a period if the entries were complete sentences, and without a period if they weren't.

Let me know what you think! I'm a fan of grammarly and I do like adding a period to be context-dependent, as I think it makes it more readable. But I'm open to other suggestions.

**Comment by wise-king-sullyman** [comment]
I'm fully on board with anything that's consistent haha. Whether that be consistency in how it *looks* or how it *works*!

You shouldn't need to start over. Worst case scenario everything is fixable through Git :slightly_smiling_face:

**Comment by msespos** [comment]
OK so at this point this should be ready to go, including the accidental commit :-o which renders my other PR redundant. Let me know if you need me to do anything else!

**Comment by wise-king-sullyman** [comment]
Ok so it looks like you did some history-changing and did a force push, that will make things more difficult.

Which commit(s) should be in this PR and which ones shouldn't?

**Comment by msespos** [comment]
Yeah, that's why I was concerned. Sorry about that.

1) "Merge branch 'main' of https://github.com/TheOdinProject/curriculum into fix-punctuation-and-grammar-css-foundations" (commit 438c15c) should NOT be in this PR.
2) "Edit lists in CSS Foundations" (commit fee8fd7) should NOT be in this PR.

3) "Edit lists in Links and Images" (commit 5b4d299) - SHOULD be in this PR.
4) "Merge branch 'main' of https://github.com/TheOdinProject/curriculum into fix-punctuation-and-grammar-css-links-and-images" (commit b68acb3) SHOULD be in this PR.

1) and 2) above are in the other PR and should stay there.

My apologies again about the force push - I should have figured it out without that and should have pointed it out earlier.

I hope this isn't too hard to resolve. Thanks!

**Comment by wise-king-sullyman** [comment]
I thought this would be a really nice moment to apply doing a rebase, but since the other one has already been merged in that's no longer necessary, I should've been quicker on the draw! :smile:

Just for future context though, doing an interactive rebase is how I would've suggested approaching this, and just dropping all of the commits that weren't supposed to be in there. All water under the fridge now that, we're going to merge city.

**Review by wise-king-sullyman — APPROVED** [review]

**Pull request merged**
