### PR TITLE
Modify verbiage regarding images in links-and-images.md

### PR DESCRIPTION
**Pull request by yogeshwarbari**
We just display an existing image using the  tag and do not create any new image using it. The word "create" gives the wrong sense that we are generating an image. That's why I think the "display" word can properly convey the use of  tag i.e. just to display an existing image.

 - [x] You have read [The Odin Projects Contributing Guide](https://github.com/TheOdinProject/curriculum/blob/main/CONTRIBUTING.md).
 - [ ] The title summarizes the change and where it happened, for example: "Fixes punctuation in Clean Code lesson".
 - [ ] If the PR is related to an open issue, use a [relevant keyword](https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests) and reference it with the `#` sign and the issue number.
 - [x] You have previewed your markdown (if any) in the [Odin Markdown Preview Tool](https://www.theodinproject.com/lessons/preview)
 - [ ] If changes are requested, please make the changes in a timely manner. After you submit the changes, request another review from the maintainer (top right).

#### 1. Describe the changes made and include why they are necessary or important:

...your text here

#### 2. Related Issue

Closes #XXXXX

### CODE REVIEW

**Review by zachmmeyer — APPROVED** [review]
This makes sense to me. Thanks for submitting this!
For next: time make the title of your PR not the last commit you made, and properly fill out the PR template. You should move your description to where it calls for it.
You can make this change even after the PR is merged for a cleaner history.

**Comment by yogeshwarbari** [comment]
Thanks, onwards I'll keep that in mind and follow the same. It'll be very helpful if you can give more clarification on part "For next: time make the title of your PR not the last commit you made".

**Comment by zachmmeyer** [comment]
> Thanks @zachmmeyer , now onwards I'll keep that in mind and follow the same. It'll be very helpful if you can give more clarification on part "For next: time make the title of your PR not the last commit you made".

image

This title you had was the commit message.

**Comment by yogeshwarbari** [comment]
> > Thanks @zachmmeyer , now onwards I'll keep that in mind and follow the same. It'll be very helpful if you can give more clarification on part "For next: time make the title of your PR not the last commit you made".
> 
> image
> 
> This title you had was the commit message.

Got it now, thank you so much for guiding me through my mistakes. I'll keep note of these corrections and follow onwards.

**Pull request merged**
