### PR TITLE
React Testing Part 1: Update simulating user events section

### PR DESCRIPTION
**Pull request by matthewnolancintron**
Added information about using the act function

## Because

Added information about using the act function to ensure proper flushing of updates during testing. Updated the code provided in the lesson to include importing act from react testing library and wrapping userEvent.click(button) in act to prevent test failures. This change is aimed at preventing inconvenience to other students following the lesson and sharing knowledge gained from personal experience.

## This PR

- Added information about using the act function in the simulating user events section
- Updated the code provided in the lesson specifically App.test.js to include importing act from react testing library and wrapping userEvent.click(button) in act.

## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [x] The `Because` section summarizes the reason for this PR
-   [x] The `This PR` section has a bullet point list describing the changes in this PR
-   [ ] If this PR addresses an open issue, it is linked in the `Issue` section
-   [x] If any lesson files are included in this PR, they have been previewed with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure it is formatted correctly
-   [x] If any lesson files are included in this PR, they follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

### CODE REVIEW

**Comment by wise-king-sullyman** [comment]
Thanks for taking the time to make this change, but the[ RTL team suggests staying away from using `act()` when possible.](https://testing-library.com/docs/react-testing-library/migrate-from-enzyme/#using-act-and-wrapperupdate) 

Are you seeing test failures that appear to be caused by not having `act()`?

**Comment by matthewnolancintron** [comment]
This is the output I get when I don't wrap userEvent.click(button); in act()

 ``` console.error
    Warning: An update to App inside a test was not wrapped in act(...).
    When testing, code that causes React state updates should be wrapped into act(...):
    
    
    act(() => {
      /* fire events that update state */
    });
    /* assert on the output */

  This ensures that you're testing the behavior the user would see in the browser. 
  Learn more at https://reactjs.org/link/wrap-tests-with-act
       5 |
       6 |   const clickHandler = () => {
    >  7 |     setHeading("Radical Rhinos");
         |     ^
       8 |   };
       9 |
      10 |   return(


 FAIL  src/App.test.js
  App component
    ✓ renders magnificent monkeys (125 ms)
    ✕ renders radical rhinos after button click (338 ms)

  ● App component › renders radical rhinos after button click

    expect(received).toMatch(expected)

    Expected pattern: /Radical Rhinos/i
    Received string:  "Magnificent Monkeys"

      25 |     // });
      26 |
    > 27 |     expect(screen.getByRole("heading").textContent).toMatch(/Radical Rhinos/i)
         |                                                     ^
      28 |   });
      29 | });
      30 |

      at Object.<anonymous> (src/App.test.js:27:53)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 passed, 2 total
Snapshots:   1 passed, 1 total
Time:        5.264 s, estimated 7 s
Ran all test suites matching /App.test.js/i.

**Comment by wise-king-sullyman** [comment]
So we'll actually be updating everything here to reflect that the newer version of userEvent which is asynchronous which would resolve that particular issue, but beyond that I would suggest checking out [this article which outlines some more about act](https://davidwcai.medium.com/react-testing-library-and-the-not-wrapped-in-act-errors-491a5629193b). We actually recently made a push to get away from using `act()` at my work for some of the reasons outlined in it.

**Comment by matthewnolancintron** [comment]
Thanks for the information.
I will read that article and retake the lesson when it gets updated.

**Pull request closed without merging**
