### PR TITLE
Form Basics:  Fixes grammatical error

### LINKED ISSUE #28855: Intermediate HTML and CSS: Minor grammar error in the "Form Basics" lesson
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

In the assignment section of the Form Basics lesson, the instructions say to, "Read and follow along to..." when it should be "Read and follow along with..."

### Path

Ruby / Rails, Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-intermediate-html-and-css-form-basics#assignment

### (Optional) Discord Name

_No response_

### (Optional) Additional Comments

_No response_

### PR DESCRIPTION
**Pull request by june062**
## Because

This PR corrects a small grammar mistake in the assignment section of the "Form Basic," lesson.

## This PR

- Changed all instances of the phrase "Read and follow along to..." to "Read and follow along with..." within the assignment section. 

## Issue

Closes #28855

## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project curriculum contributing guide](https://github.com/TheOdinProject/curriculum/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [x] The `Because` section summarizes the reason for this PR
-   [x] The `This PR` section has a bullet point list describing the changes in this PR
-   [x] If this PR addresses an open issue, it is linked in the `Issue` section
-   [x] If any lesson files are included in this PR, they have been previewed with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure it is formatted correctly
-   [x] If any lesson files are included in this PR, they follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

### CODE REVIEW

**Review by MaoShizhong — CHANGES_REQUESTED** [review]
Thanks for the grammar fixes. It looks like you have Prettier running on save - we use a different style guide to Prettier, which has caused it to change a lot more than you intended. We will need all of the changes reverted except of course the intended grammar fixes. So that includes all the HTML changes like spacing, self-closing tags etc.

You should get used to using "save without formatting" when working with external projects as they may not always use the same rules as your local auto-formatter, like in this case.

**Comment by MaoShizhong** [comment]
@june062 You don't need to close a PR and make a new one if changes are required. A PR just tracks a branch so you can just commit and push changes to that branch and it'll auto update here.

**Comment by june062** [comment]
Ok, sorry about that. I'm getting so confused trying to revert my fork to how it was before I pushed my changes lol

**Comment by MaoShizhong** [comment]
No worries - just a heads up because a few times people have thought PRs are one-shot only and didn't realise it's just tracking a branch they can commit changes to :)

**Comment by june062** [comment]
Okay, I believe it's correct now

**Review by MaoShizhong — APPROVED** [review]
:rocket:

**Pull request merged**
