### PR TITLE
Add Code Simplicity blog link.

### PR DESCRIPTION
**Pull request by nhquiroz**

### CODE REVIEW

**Comment by craftykate** [comment]
@hgducharme @eriktrautman Care to weigh in? I'm not familiar with this one.

**Comment by nhquiroz** [comment]
Max Kanat-Alexander is a Google Engineer, author of the eponymous book, [Code Simplicity](author of the eponymous book). It's a blog about software engineering and software development.

**Comment by eriktrautman** [comment]
Definitely not as well known but seems valuable and not sure where else to put it

**Comment by craftykate** [comment]
Thanks @eriktrautman!

**Pull request merged**
