### PR TITLE
line 61 - article issues

### PR DESCRIPTION
**Pull request by fgostev**
#### 1. Describe the changes made and include why they are necessary or important:

When you open the link on line 61 - "What is the difference between a block element and an inline element? " the article has issues. The article doesn't display the examples properly. The suggestion is to replace the article with another one.

#### 2. Related Issue

Not related issue

### CODE REVIEW

**Comment by zachmmeyer** [comment]
- Your PR title does not match contributing guidelines
- What is wrong with the article? It looks weird, but it appears to be correct.

**Comment by fgostev** [comment]
> 

Sorry, doing for the first time.

The wrong part of the article is the examples. Instead of visual examples (which it looks it is supposed to show them) - it has HTML code showing on the page. I found it to be confusing, but that's perhaps is just my perspective.

**Comment by twalton83** [comment]
You should probably check your extensions or check with another browser. I don't see any HTML code.

**Comment by fgostev** [comment]
Shows up now, perhaps was a glitch. Thank for checking!

**Pull request closed without merging**
