### PR TITLE
Update git_basics.md: Adding Git Cheat Sheet Links

### PR DESCRIPTION
**Pull request by rafaover**
Addition of GIT cheat sheets links.

Complete the following REQUIRED checkboxes:

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`

Complete the following checkboxes ONLY IF they are applicable to your PR. You can complete them later if they are not currently applicable:
-   [x] I have previewed all lesson files included in this PR with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure the Markdown content is formatted correctly
-   [ ] I have ensured all lesson files included in this PR follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

<hr>

**1. Because:**

Closes #XXXXX

**2. This PR: 
- Addind links to GIT Cheat Sheets at the end of this lesson that helped me during course progress**

**3. Additional Information:**

### CODE REVIEW

**Review by SauravJalui — COMMENTED** [review]
Hey @rafaover,

Thank you for suggesting these changes.

The cheatsheets you've added contain commands that we've not covered in the [git basics](https://www.theodinproject.com/paths/foundations/courses/foundations#git-basics) section.

A more suitable place to add these cheatsheets would be in the [intermediate git](https://www.theodinproject.com/paths/full-stack-javascript/courses/javascript#intermediate-git) section.

The Atlassian cheatsheet is already added in the additional references section of [A deeper look at git](https://www.theodinproject.com/lessons/javascript-a-deeper-look-at-git#additional-resources). You can add the rest of the cheatsheets there.

Best,
Saurav

**Comment by LeoKirasic** [comment]
@SauravJalui

Hey, your willingness to contribute is appreciated, but we really don't want people who aren't in our organization reviewing issues and pull requests.
Please refrain from doing that in the future.

**Comment by SauravJalui** [comment]
Hey @LeoKirasic,

Thank you for your appreciation. I understand your concern, I won't review any issues/pull requests until I'm a part of TOP.

Let me know if I can help with anything else.

~Saurav

**Comment by wise-king-sullyman** [comment]
@rafaover thank you for taking the time to put this PR together!

Unfortunately, I also don't believe that these resources are appropriate for the git basics lesson, and I don't really see the other cheatsheets adding much value to the intermediate git lesson since the Atlassian cheatsheet is already linked there and covers most of the same material.

For those reasons, I'm going to close this PR, but thank you again for taking the time to try and contribute!

**Pull request closed without merging**
