### PR TITLE
Update project_data_structures_algorithms.md

### PR DESCRIPTION
**Pull request by craftykate**

### CODE REVIEW

**Comment by eriktrautman** [comment]
Way to go Kate!

**Comment by craftykate** [comment]
Thanks Erik! I've been working hard!

**Comment by hgducharme** [comment]
I'm curious to know when you started Odin?

**Comment by craftykate** [comment]
I'd say September? Or October? I got conditionally accepted to App Academy, then during my research on the school I found this site. I learn SO well on my own (I'm entirely self-taught and have been doing pretty darn well on my own) so I figured I might as well give Odin a shot and save myself some hassle - and dough. I figured if it didn't go well I could always finish my application to AA and go there, but I LOVE Odin and I'm almost done with the course (halfway through the JavaScrip/jQuery chapter right now) so I'd say I picked the right path. =)

**Comment by eriktrautman** [comment]
I’m glad you’ve found it useful!  That’s great progress.

                                                           
Erik S. Trautman
Founder,  Viking Code School
The premier online program for learning professional web development

**Comment by hgducharme** [comment]
Awesome job, you're hauling butt!

**Comment by craftykate** [comment]
Thanks! I'm really looking forward to getting a dev job somewhere and doing this for reals! I quit my job (yikes!) at the beginning of November so I could focus on Odin and it has been REALLY fun doing this full time.

**Comment by hgducharme** [comment]
Lol, talk about risky!! But by the looks of it, it's seriously paid off and I doubt you'll have any trouble finding one. Good luck!

**Comment by craftykate** [comment]
Thank you! The getting-a-job part of this is definitely the scariest for me, so I appreciate the encouragement!

**Pull request merged**
