### PR TITLE
A Bit of Computer Science: Update second assignment watch instruction.

### LINKED ISSUE #28849: JavaScript: Clarify Coursera's Algorithm course video watch time
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

I was going through the resources linked in the assignment box of the Common Data Structures and Algorithm lesson in the JavaScript course. In the second assignment, it was written as so: 

Screenshot from 2024-09-23 15-36-56

`Learn about basic algorithms from [Coursera’s Algorithms course](https://www.youtube.com/watch?v=u2TwK3fED8A). The first 10 minutes are really the meat of the introduction to algorithms, the rest gets more mathematical (if you’re so inclined).`

Based on the wording, I thought that learners were supposed to watch the entire course playlist on YouTube, only to have found out that learners only need to watch at least the first 10 minutes of the video, thanks to clarification coming from @takinabradley
from our TOP discord. The miswording on this lesson might lead learners to watch the entire playlist, which is unintentional because the goal of this lesson is to introduce learners to the importance of Algorithm in programming. 

I would like to suggest some clearer wording here, which is to simply say to only watch the linked video (most importantly the first 10 minutes), not the entire course playlist, but they can if they are so inclined. 

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/javascript-common-data-structures-and-algorithms

### (Optional) Discord Name

vietanhhoang2507

### (Optional) Additional Comments

_No response_

### PR DESCRIPTION
**Pull request by ZackHoang**
## Because

This PR adjusted the watch instruction for the second assignment in the Common Data Structures and Algorithms lesson in the CS section of the JavaScript course in NodeJS/JS path. The previous wording might make learners think that they were supposed to follow along the entire Coursera Algorithm course, which is not the focus of TOP. A more detailed wording was provided to prevent any misunderstanding. 

## This PR

- Change wording in the second assignment of Common Data Structures and Algorithm lesson in CS section of NodeJS/JS path. 

## Issue

Closes #28849 

## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project curriculum contributing guide](https://github.com/TheOdinProject/curriculum/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [x] The `Because` section summarizes the reason for this PR
-   [x] The `This PR` section has a bullet point list describing the changes in this PR
-   [x] If this PR addresses an open issue, it is linked in the `Issue` section
-   [x] If any lesson files are included in this PR, they have been previewed with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure it is formatted correctly
-   [x] If any lesson files are included in this PR, they follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

### CODE REVIEW

**Comment by MaoShizhong** [comment]
I don't think we need to be that wordy for the assignment step, and we could probably make it terser with a better link text label to be honest.

E.g.
> Watch the first 10 minutes of ["Why Study Algorithms?"](http://www.youtube.com/watch?v=u2TwK3fED8A) (the rest is more mathematical if you're interested).

Then if the user personally wishes to watch more, they can.

Could you also make the same change to the Ruby version of this lesson?
The file path is `ruby/computer_science/common_data_structures_algorithms.md`

**Comment by ZackHoang** [comment]
> I don't think we need to be that wordy for the assignment step, and we could probably make it terser by linking to the video only (without the playlist) and using a better link text label to be honest.
> 
> E.g.
> 
> > Watch the first 10 minutes of ["Why Study Algorithms?"](https://youtu.be/u2TwK3fED8A) (the rest is more mathematical if you're interested).
> 
> Then if the user personally wishes to watch more, they can.
> 
> Could you also make the same change to the Ruby version of this lesson? The file path is `ruby/computer_science/common_data_structures_algorithms.md`

Got it! Yeah I think that was rather long. Should I make a seperate pull request or should I work directly on this one? This is my first time contrbuting so I'm not quite sure and I don't know how to make any further change on this one.

**Comment by damon314159** [comment]
The `t` at the start of the second sentence in both lessons should probably be capitalised

**Comment by MaoShizhong** [comment]
If we capitalise the "The" in the parens, we should get rid of the parens. Otherwise, we can get rid of the full stop before the parens.

Either is completely fine

**Review by MaoShizhong — DISMISSED** [review]

**Comment by MaoShizhong** [comment]
Good ol' trailing spaces. I'll merge once they're removed

**Review by MaoShizhong — APPROVED** [review]

**Pull request merged**
