### PR TITLE
Solution added!

### PR DESCRIPTION
**Pull request by neelotpal97**
```
This is a PR template, If you are adding a solution link to the curriculum leave this as is. If you are not, then delete it and write the message you wish.
Thank you,
The Odin Project team.

```

### CODE REVIEW

**Comment by KevinMulhern** [comment]
Hey @neelotpal97, you seem to have git merge conflict markers included with this. https://github.com/TheOdinProject/curriculum/pull/5717/files

**Comment by neelotpal97** [comment]
What can I do to fix it? I'm just a beginner.

On 31-Jan-2017 6:43 PM, "Kevin Mulhern" <notifications@github.com> wrote:

Hey @neelotpal97 <https://github.com/neelotpal97>, you seem to have git
merge conflict markers included with this. https://github.com/
TheOdinProject/curriculum/pull/5717/files

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/TheOdinProject/curriculum/pull/5717#issuecomment-276359491>,
or mute the thread

**Comment by KevinMulhern** [comment]
If you open up this file in your fork locally and delete all lines which look like the following:
`<<<<<<< HEAD`
`=======`
`>>>>>>> f99eb3bef8fa9724d3f02feb5f53d75fa866205d`

and then add, commit and push up to your fork again it should update this PR automatically with them removed.

**Comment by neelotpal97** [comment]
I did a git add,commit and push after deleting the following lines from my
fork :

<<<<<<< HEAD
=======
>>>>>>> f99eb3bef8fa9724d3f02feb5f53d75fa866205d

is the issue now resolved?
Thanks, I really appreciate your help.

**Comment by KevinMulhern** [comment]
Perfect thanks @neelotpal97

**Comment by neelotpal97** [comment]
I really feel like a part of the community. Thanks.

**Pull request merged**
