### PR TITLE
Sam Greaves' solution

### PR DESCRIPTION
**Pull request by Yoippari-Evrae**
This is my solution to the google homepage project. https://github.com/Yoippari-Evrae/google-homepage

This is a PR template. If you are adding a solution link to the curriculum, leave this as is. If not, delete it and write the message you wish.

Thank you,

The Odin Project team.

### CODE REVIEW

**Comment by ZachBaird** [comment]
Your two links point to the same URL @Yoippari-Evrae . Do you have a live URL of your project up on Github pages or anything?

**Comment by ZachBaird** [comment]
@Yoippari-Evrae It also looks like there's some funky conflicts in Github with the merge. Can you `git pull` the curriculum (the original, not your forked) repo and merge locally to make sure your code is up to date?

**Comment by Yoippari-Evrae** [comment]
@ZachBaird Hi Zach, to do this do I do git pull into my google-homepage folder, then a git push? Thanks.

**Comment by marvingay** [comment]
@Yoippari-Evrae You would`git pull` from the `remote` pointing towards the original curriculum repository into your fork. Resolve the merge conflicts (if any) and then push back to your fork.

For your convenience, it was taken care of this time. It's imperative to pull from the `upstream` or original remote to make sure your fork is up to date before making pull requests.

**Pull request merged**
