### PR TITLE
Fixed grammar error on JS Basics - REVISITING ROCK PAPER SCISSORS

### PR DESCRIPTION
**Pull request by magnusmagnus**
- [x] You have read [The Odin Projects Contributing Guide](https://github.com/TheOdinProject/curriculum/blob/main/CONTRIBUTING.md).
 - [x] The title summarizes the change and where it happened, for example: "Fixes punctuation in Clean Code lesson".
 - [x] If the PR is related to an open issue, use a [relevant keyword](https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests) and reference it with the `#` sign and the issue number.
 - [x] You have previewed your markdown (if any) in the [Odin Markdown Preview Tool](https://www.theodinproject.com/lessons/preview)
 - [x] If changes are requested, please make the changes in a timely manner. After you submit the changes, request another review from the maintainer (top right).

#### 1. Describe the changes made and include why they are necessary or important:

Updated text for the lesson as the sentence was grammatically incorrect. 

#### 2. Related Issue

None

### CODE REVIEW

**Comment by wise-king-sullyman** [comment]
Your change seems good but you'll need to resolve the existing merge conflict in order for this PR to be merged. If you need help with how to do that process let me know.

**Comment by magnusmagnus** [comment]
Hello, thanks for checking, this is my first contribution to an open source
project.I think that somebody updated the lesson at the same time as me
which caused a conflict. I did some research on how to resolve the conflict
and I believe I have done it. If not please let me know and I'll try and
figure it out. Thanks again.

**Comment by magnusmagnus** [comment]
> Your change seems good but you'll need to resolve the existing merge conflict in order for this PR to be merged. If you need help with how to do that process let me know.

Hello, thanks for checking, this is my first contribution to an open source
project.I think that somebody updated the lesson at the same time as me
which caused a conflict. I did some research on how to resolve the conflict
and I believe I have done it. If not please let me know and I'll try and
figure it out. Thanks again.

**Review by kashura — APPROVED** [review]

**Review by wise-king-sullyman — CHANGES_REQUESTED** [review]
It looks like your original change is gone now.

**Comment by wise-king-sullyman** [comment]
@magnusmagnus it looks like your original change was actually addressed already in the PR that caused the merge conflict (which was merged in yesterday).

Also, I'm not sure why you added the additional newlines that you did or indented step four of the assignment in a way that looks incorrect to me, but I'm guessing those were artifacts of resolving the merge conflict.

If I'm right and those things were just artifacts of the merge conflict I think the only path forward is to close this PR, since your original change was already done. If I'm incorrect and these changes were intentional please let me know and I'll be happy to discuss them :slightly_smiling_face:

**Comment by magnusmagnus** [comment]
I don't really know what happened. I think when I saved the file in Visual Studio Code it added the spaces, like it auto formatted it. I'll try and avoid that in future contributions. Sorry about that. I'll close this PR. Thanks for your guidance.

**Comment by wise-king-sullyman** [comment]
@magnusmagnus it's all good! It's really easy for things to get funky when resolving merge conflicts.

Thank you for trying to improve our curriculum and taking the time to not only make a PR, but try and resolve merge conflicts, and taking it well when your PR changes were merged in by a different PR right after you made yours 😄 

Sorry that things didn't work out to be able to merge your changes!

**Pull request closed without merging**
