### PR TITLE
Add section for adding to remote

### PR DESCRIPTION
**Pull request by KevinMulhern**
This adds a new section at the beginning of the tutorial for connecting github
with the folder the user creates.

### CODE REVIEW

**Comment by KevinMulhern** [comment]
@csrail I've added a part about setting up on github first or on the users machine first when using git. Let me know what you think of that approach. I know we talked about it before. But I think that the student should be aware of the git init approach like you originally said 👍

**Comment by KevinMulhern** [comment]
Feel free to merge if you want to make changes. The only part that remains of the tutorial now is uploading to a remote at the end.

**Comment by csrail** [comment]
Issues:

 * Line 65 - You're mid sentence through something?

* Are we still including screenshots?

* I think it's definitely good to talk about `git init` but the file looks so bloated already. 
From a user's perspective, including both local and remote is setting up a divergent point in the learning process since setting up locally adds no additional information to the entirety but more than likely obscures understanding. The only reason I could think of someone using `git init` at this stage is if they knew all the other important commands related to branching or if they don't have internet.
Any way to tuck it in somewhere as extra credit or a task to do once people are comfortable with the workflow / understand local and remote well?

* I think the add and commit explanations need a little more work with regards to adding groups of files thematically (so all files related to aesthetics together, all files related to deployment etc - try to find relevant newbie examples). But at this point for a newbie adding all the files will be convenient (but very costly if a mistake occurs and they need to revert) 
Also the importance of atomic commits maybe (which actually ties in to how you think about adding files in or not). Still, this may be a little verbose.

Looks good otherwise :)

**Comment by csrail** [comment]
@KevinMulhern 

Issues:

 * Line 65 - You're mid sentence through something?

* Are we still including screenshots?

* I think it's definitely good to talk about `git init` but the file looks so bloated already. 
From a user's perspective, including both local and remote is setting up a divergent point in the learning process since setting up locally adds no additional information to the entirety but more than likely obscures understanding. The only reason I could think of someone using `git init` at this stage is if they knew all the other important commands related to branching or if they don't have internet.
Any way to tuck it in somewhere as extra credit or a task to do once people are comfortable with the workflow / understand local and remote well?

* I think the add and commit explanations need a little more work with regards to adding groups of files thematically (so all files related to aesthetics together, all files related to deployment etc - try to find relevant newbie examples). But at this point for a newbie adding all the files will be convenient (but very costly if a mistake occurs and they need to revert) 
Also the importance of atomic commits maybe (which actually ties in to how you think about adding files in or not). Still, this may be a little verbose.

Looks good otherwise :)

**Comment by csrail** [comment]
I can't remember what article mentions this xkcd comic but it will be relevant to the atomic commits section if we choose to include it.

https://xkcd.com/1296/

**Comment by KevinMulhern** [comment]
@csrail 
* doh, yes I was.
* Yeah I was thinking about putting them in when I finished the tutorial
* Great points, maybe extracting it to a md file stored somewhere in the curriculum repo and linking it somewhere would be better.
* I think you have a good idea of what you want there, so if you want to merge this and refactor those parts to match your vision for them that would be 👍 with me.

**Pull request merged**
