### PR TITLE
Html foundations,chapter 5 Links: Deleted a sentence about Internet

### PR DESCRIPTION
**Pull request by NiteeshPutla**
The internet is essentially a web of HTML pages connected to one another with links.

Complete the following REQUIRED checkboxes:

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`

Complete the following checkboxes ONLY IF they are applicable to your PR. You can complete them later if they are not currently applicable:
-   [x] I have previewed all lesson files included in this PR with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure the Markdown content is formatted correctly
-   [x] I have ensured all lesson files included in this PR follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

<hr>

**1. Because:**

Closes #XXXXX

**2. This PR:**

**3. Additional Information:**

### CODE REVIEW

**Comment by LeoKirasic** [comment]
Hey @NiteeshPutla

Please fully fill out the PR template.
I'm not sure why that part of the lesson needs to be removed. Can you provide an explanation as well, please?

**Comment by NiteeshPutla** [comment]
I have deleted that sentence as it is misleading about the Internet .World Wide Web is is an interconnected system of public webpages accessible through the Internet.Author says that "The internet is essentially a web of HTML pages connected to one another with links." which is not true.

**Comment by NiteeshPutla** [comment]
Please refer to the below attached links for further clarification:
[WorldWideWeb](https://developer.mozilla.org/en-US/docs/Glossary/World_Wide_Web) 
[Internet](https://developer.mozilla.org/en-US/docs/Learn/Common_questions/How_does_the_Internet_work)

**Review by LeoKirasic — APPROVED** [review]
Thanks for looking into this!

**Pull request merged**
