### PR TITLE
Time Complexity lesson: Improve text in Quadratic/Cubic sections.

### LINKED ISSUE #25465: Ruby Course: Improve explanation of quadratic complexity in Time Complexity lesson
### Describe your suggestion

I suggest this paragraph be reworded to be more precise, as I feel that the mix of words “iterations” and “steps” here might not make sense to those that are new to the concept of time complexity.
Perhaps an example of an array of size 2 being increased by 1, 2, and 3 elements can help with clarity. If the number of steps added are to be left in the explanation, then it should clear what those “steps” are describing. Generally speaking, adding 3 items adds **(3 * (n + 3)) + (n * 3)** steps to the original **n^2** number of steps.

```
"Therefore, when the number of items in the data increases by 1, it requires 2 extra iterations. 2 extra items requires 4 extra iterations (2 in the outer loop and two in the inner loop). 3 extra items adds 9 steps, and 4 adds 16 extra steps."
```

Change suggestions:
- `"increases by 1, it requires 2 extra iterations"` to `”increases by 1, it requires 1 extra iteration in both the outer loop and the inner loop”`
- Same thing for explaining the addition of 2 or 3 items (remove the use of words steps): `”2 extra items requires 2 extra iteration in both the outer loop and the inner loop”` and so on

### Path

Ruby / Rails

### Lesson Url

https://www.theodinproject.com/lessons/ruby-time-complexity

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### (Optional) Discord Name

wwrk22#3187

### (Optional) Additional Comments

_No response_

### PR DESCRIPTION
**Pull request by MKMaths22**
## Because

As explained in the issue raised at "Ruby Course: Improve explanation of quadratic complexity in Time Complexity lesson #25465", the word 'steps' was used ambiguously in the explanations of Quadratic and Cubic Complexity in the Time Complexity lesson. 
The benefit is now that the extra sub-steps added when an array increases in size, are distinguished from the total number of sub-steps, which is n squared for quadratic and n cubed for the cubic case. 

## This PR

- After 'Therefore, when the number of items in the data increases by 1...' the text is changed.
- Now refers more clearly to 'iterations' and 'sub-steps' in both Quadratic and Cubic sections.
- Also describes the numbers of extra sub-steps required when data structure being looped over increases in size.
- Does the above while otherwise being consistent with the style of the lesson as a whole.
## Issue

Closes #25465

## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [x] The `Because` section summarizes the reason for this PR
-   [x] The `This PR` section has a bullet point list describing the changes in this PR
-   [x] If this PR addresses an open issue, it is linked in the `Issue` section
-   [x] If any lesson files are included in this PR, they have been previewed with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure it is formatted correctly
-   [x] If any lesson files are included in this PR, they follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

### CODE REVIEW

**Comment by CouchofTomato** [comment]
Hey @MKMaths22,

Thanks for the contribution. 

The lesson is aimed at beginners to the topic. Are you sure they'll easily grasp phrases like 2n (n + 2)?

I do agree the way it's written can be ambiguous, but that was to keep it approachable.

I'm not totally convinced this change will make the lesson better but happy to hear you out if you want to explain how this will help learners to the topic better understand it.

**Comment by MKMaths22** [comment]
Thanks Manon for reviewing the change so quickly. Yes, I understand that the formulae for extra steps can be hard to grasp so numerical examples will make it more accessible. About this lesson also featuring in the JS-CS section, does that mean two separate changes need to be made?
Also, I notice that I am no longer assigned, how can I go about making revisions to the text?

**Comment by ManonLef** [comment]
@MKMaths22 I'm not a maintainer so I'm not entirely sure how the assigning works. It could be that they unassigned you while waiting for a verdict and will reassign you once the discussion comes to a good resolution that the maintainer team agrees on. But I'm not entirely sure. 

Either way, as a fellow learner, thanks for your observations! I went through that lesson not even noticing that some of the explanation wasn't correct. I enjoy seeing some accurate math even though I also see the value in not overcomplicating it from a pedagogical standpoint. :)

**Comment by CouchofTomato** [comment]
> Thanks Manon for reviewing the change so quickly. Yes, I understand that the formulae for extra steps can be hard to grasp so numerical examples will make it more accessible. About this lesson also featuring in the JS-CS section, does that mean two separate changes need to be made? Also, I notice that I am no longer assigned, how can I go about making revisions to the text?

You don't need to be assigned to do anything, you should just push up your changes to the same branch you made a PR from. I've assigned you anyway.

**Comment by MKMaths22** [comment]
Thanks for clarifying, CouchofTomato, and reassigning me anyway. I will push more changes up to the quadratic-explanation branch on MKMaths22/curriculum.

**Comment by CouchofTomato** [comment]
@ManonLef 

Do you have any thoughts on the changes made before I review them?

**Comment by ManonLef** [comment]
@CouchofTomato thanks for the ping.

Some feedback I have which you can (both) decide on:

## quadratic
I still think the use of the `extra` can be interpreted wrongly. The word `extra` still could be interpreted as for example adding 2 items increases the amount of steps required with 4. Which as explained above and with the changes is not correct (nested loop of 2 equals 4 steps, nested loop of 4 equals 16 steps, so 2 extra items in that case requires 12(!) extra steps). The main problem being that that one extra item also has to loop over the unknown amount of items that were already there. 

In my opinion it could be simplified by removing the lined trough part:
>You've probably written code with a Quadratic Complexity on your programming journey. It's commonly seen when you loop over a data set and within each loop you loop over it again. 
~~Therefore, when the number of items in the data increases by 1, it requires 1 extra iteration in both the outer loop and the inner loop. 2 extra items requires 2 extra iterations in the outer loop and 2 extra in the inner loop. If we are looping through an array with n items and, within each loop, looping over it again, this involves a total of n&#178; sub-steps.~~
For example, if our array has 3 items, the nested loops require 3² = 9 sub-steps. Adding just one more item to the array almost doubles this number to 4² = 16. Adding a 5th item takes us to 5² = 25 sub-steps. Then doubling the array size to 10 items increases the sub-steps from 25 to 100, so 4 times as much work needed! We hope you can see where we're going with this...

to:
>You've probably written code with a Quadratic Complexity on your programming journey. It's commonly seen when you loop over a data set and within each loop you loop over it again. 
For example, if our array has 3 items, the nested loops require 3² = 9 sub-steps. Adding just one more item to the array almost doubles this number to 4² = 16. Adding a 5th item takes us to 5² = 25 sub-steps. Then doubling the array size to 10 items increases the sub-steps from 25 to 100, so 4 times as much work needed! We hope you can see where we're going with this...

## Cubic
Because of the above I think the below section actually removing the extra steps part on Cubic complexity is the way it should be and I have no feedback on it besides that it looks great!
>Think triple nested loops baby. If looping over an array with n items, 1 extra item adds an extra outer loop, an extra middle loop, and an extra innermost loop. When using such triply nested loops on an array of size n, we require a total of n³ sub-steps.
For example, if our array has 3 items, the triply-nested loops require a total of 3³ = 27 sub-steps. Adding one more item more than doubles this number to 4³ = 64 sub-steps. The task almost doubles again for 5 items, with 5³ = 125 sub-steps. Doubling our array size to 10 items means we require 10³ = 1000 sub-steps in total, 8 times as many as before! 100 items in the array require a total of 1,000,000 sub-steps. Ouch!

**Comment by ManonLef** [comment]
@MKMaths22 Thanks for all the work you've put into this. I forgot to ping you in the above comment so would love to hear your opinion on it as well.

**Comment by MKMaths22** [comment]
Thanks for the feedback, @ManonLef. I agree that the Quadratic section reads very well with the suggested removal of lined-through text. Shall I go ahead and make that update to the PR?

**Comment by CouchofTomato** [comment]
Hey @MKMaths22 

If you're happy with the proposed changes suggested then go ahead and make them and then we can assess everything and hopefully merge.

**Comment by ManonLef** [comment]
@MKMaths22 I don't mean to rush you, but wanted to ask if you're still willing to make these changes?

**Comment by MKMaths22** [comment]
Hello @ManonLef, thanks for your message. I expect to be making those changes within the next week.

**Review by CouchofTomato — APPROVED** [review]

**Review by CouchofTomato — COMMENTED** [review]
We also need to make the same changes to the JS course once we approve the Ruby one.

**Comment by MKMaths22** [comment]
I've removed the lined-through sentences from the Quadratic section.

**Comment by CouchofTomato** [comment]
This looks ok to me. @ManonLef do you have anything to add?

**Comment by ManonLef** [comment]
LGTM! We then also need to edit the same lesson for the JS path @MKMaths22 :)

**Comment by CouchofTomato** [comment]
Thanks @ManonLef 

@MKMaths22 As mentioned above if you could just make the same edits to the JS path version of this lesson we can go ahead and get this merged.

**Comment by MKMaths22** [comment]
I have made the corresponding changes to the Javascript Time Complexity lesson.

**Review by CouchofTomato — APPROVED** [review]

**Comment by CouchofTomato** [comment]
Thanks for patience with this @MKMaths22 

Really appreciate your time to help improve the curriculum for our learners.

**Pull request merged**
