### PR TITLE
Project Landing Page: Add link to recipe project

### PR DESCRIPTION
**Pull request by ra-mint**
Complete the following REQUIRED checkboxes:

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`

Complete the following checkboxes ONLY IF they are applicable to your PR. You can complete them later if they are not currently applicable:
-   [x] I have previewed all lesson files included in this PR with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure the Markdown content is formatted correctly
-   [x] I have ensured all lesson files included in this PR follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

<hr>

**1. Because:**

Page references recipe project to refresh on how to create a new repository without linking the project  

**2. This PR:**

Add link to recipe project for efficient navigation and fix grammar/capitalization

**3. Additional Information:**

[Discord discussion](https://discord.com/channels/505093832157691914/540903304046182425/958254235571585064)

### CODE REVIEW

**Review by LeoKirasic — CHANGES_REQUESTED** [review]
Can you please change the text to "recipes project" so it matches the project name?

**Comment by LeoKirasic** [comment]
@ra-mint Left a comment, just need a small change. Looks good though!

**Comment by ra-mint** [comment]
> Can you please change the text to "recipes project" so it matches the project name?

I also see that "Recipes" is capitalized earlier in the paragraph, but is not on its second occurrence. For formatting purposes, should the latter also be capitalized?

**Review by LeoKirasic — APPROVED** [review]
Looks good now!

**Pull request merged**
