### PR TITLE
Add a guideline on commit messages

### PR DESCRIPTION
**Pull request by snakecase**
Also, fix the lesson's commit messages according to the guideline.

### CODE REVIEW

**Comment by snakecase** [comment]
I think it's better to teach good conventions right from the beginning.
A few screenshots need to be changed in accordance with edited text. I'm on PowerShell right now and I don't know whether it is a good idea or not to show examples under Windows. Can someone comment on it? Or if @KevinMulhern still has the same environment, maybe he can reproduce these screenshots?

**Comment by 105ron** [comment]
LGTM @snakecase . I think the commit messages you edited don't follow best practice. I can remake the images for this lesson if needed to fix it @KevinMulhern

**Comment by KevinMulhern** [comment]
👍 LGTM
I agree the messages are better 😄 
@105ron would you mind remaking the images? 😄 I was thinking we could add a new image to the end of the tutorial as well showing the files on github after being pushed, we forgot about that when we were making this lesson.

**Comment by 105ron** [comment]
I will do it on the weekend @KevinMulhern and make them look the same as the other git tutorials I made. I should really finish that undo project I just haven't come up with a plan for the repository the user will fork.

**Comment by KevinMulhern** [comment]
Thanks @105ron 👍 
Yeah its been tough to come up with a good project for it. I should hopefully have more time after the redesign is finished to link up with you on it.

**Comment by KevinMulhern** [comment]
👍 LGTM
Lets ship it.

**Pull request merged**
