### PR TITLE
Remove unused query

### PR DESCRIPTION
**Pull request by OmarNaguib**
## Because

Button is query and not used
The query implicitly tests that a button is there but we already explicitly test that.

## This PR

Removes unused button query

## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [x] The `Because` section summarizes the reason for this PR
-   [x] The `This PR` section has a bullet point list describing the changes in this PR
-   [x] If this PR addresses an open issue, it is linked in the `Issue` section
-   [x] If any lesson files are included in this PR, they have been previewed with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure it is formatted correctly
-   [x] If any lesson files are included in this PR, they follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

### CODE REVIEW

**Comment by codyloyd** [comment]
ah, cool.  You're probably right then.  Let's wait for confirmation from the react team before merging, though.

**Review by wise-king-sullyman — APPROVED** [review]
Yeah I don't think having the button query is needed here, I'll leave the final look to @01zulfi though.

**Review by 01zulfi — APPROVED** [review]
The query is definitely not needed. Thanks for fixing this 💪

**Comment by OmarNaguib** [comment]
> The query is definitely not needed. Thanks for fixing this muscle

you're welcome!

**Pull request merged**
