### PR TITLE
Update join_the_odin_community.md

### PR DESCRIPTION
**Pull request by tmsagarofficial**
## Because
This file had some typos.
Removing these would make the content more clear to understand

## This PR

- Small typos fixed
- Links to Additional resources added

## Issue

Closes #XXXXX

## Pull Request Requirements

-   [ x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [x] The `Because` section summarizes the reason for this PR
-   [x] The `This PR` section has a bullet point list describing the changes in this PR
-   [x] If this PR addresses an open issue, it is linked in the `Issue` section
-   [x] If any lesson files are included in this PR, they have been previewed with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure it is formatted correctly
-   [x] If any lesson files are included in this PR, they follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

### CODE REVIEW

**Comment by KevinMulhern** [comment]
Thanks for contributing @tmsagarofficial, however these do not seem like typos and can you explain what value the extra resources add to the lesson please?

**Comment by tmsagarofficial** [comment]
@KevinMulhern 
sorry if they didn't feel like typos,.

and The extra resources added to this lesson throws light on how and why online communities whichever may be are really helpful for all the people to grow together and also to build interaction and helps in guiding the project to a more inclusive manner.

**Comment by KevinMulhern** [comment]
Thanks for explaining @tmsagarofficial, can you expand a bit more please? why do we need these extra links? are the reasons about why the community is helpful to learners in the lesson content not good enough? - if they aren't, can we improve the lesson content instead of linking to somewhere else?

**Comment by tmsagarofficial** [comment]
sure @KevinMulhern ,

What i feel is the resources already in the lesson about why the community is helpful in a bit too short and also just tells it from the ODIN's side. So i thought adding these resources will be a very good way for people to understand about communities in a new angle.

nevertheless we can always improve the lesson content

**Comment by KevinMulhern** [comment]
I understand what you're saying, but the purpose of the lesson is to explain why it is beneficial for learners to join and partake in Odin's community and not teach about online communities in general.

We appreciate the contribution, but this isn't the direction we want to take this lesson in.

**Comment by tmsagarofficial** [comment]
Thanks for the review but what about the grammatical corrections .....? @KevinMulhern

**Comment by KevinMulhern** [comment]
Those aren't corrections, both are grammatically correct already.

**Pull request closed without merging**
