### PR TITLE
Nodejs project_blog_api.md : Remove mention of Thunderclient due to move to freemium model

### PR DESCRIPTION
**Pull request by JustWaveThings**
## Because

- Change would not suggest freemium options where avoidable

## This PR

- Remove mention of ThunderClient for VSCode in additional resources, as a good chunk of the functionality is behind a paywall now.

## Issue

n/a

## Additional Information

 For more information, see this comment from their support - https://github.com/rangav/thunder-client-support/issues/1292#issuecomment-1688247786

## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [x] The `Because` section summarizes the reason for this PR
-   [x] The `This PR` section has a bullet point list describing the changes in this PR
-   [ ] If this PR addresses an open issue, it is linked in the `Issue` section
-   [ ] If any lesson files are included in this PR, they have been previewed with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure it is formatted correctly
-   [ ] If any lesson files are included in this PR, they follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

### CODE REVIEW

**Comment by JustWaveThings** [comment]
It might be worth adding that Postman has a vscode extension as well now, might have not been the case back then. Personally, I use the postman desktop client because of the real estate the extension requires in vscode.

I don't remember what it was that I was trying to do that was behind a subscription, but it wasn't crazy. I am not advanced.

**Comment by ManonLef** [comment]
I have requested input from other maintainers on this. I also read about Postman as an option but my research seems to conclude that it’s quite a bit more elaborate / less light weight :).

**Comment by ManonLef** [comment]
(Wrong button sorry!)

**Comment by ManonLef** [comment]
@TheOdinProject/javascript 
Are there any essential options for API testing missing from the [Thunderclient free version options](https://www.thunderclient.com/pricing) here that are needed for testing routes?

**Review by 01zulfi — APPROVED** [review]
lgtm 🚀 

We have Postman in the additional resources in the lesson. I believe it has all the features (and more) our learners would need to test APIs.

**Pull request merged**
