### PR TITLE
Fundamentals Part 5: Remove unnecessary header (Introduction)

### PR DESCRIPTION
**Pull request by Naoufal-Aziane**
There is nothing under the 'Introduction' header

## Because
There is nothing under the 'Introduction' header : Just an 'h3' without any text underneath of it.

## Issue

Closes #XXXXX

## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [x] The `Because` section summarizes the reason for this PR
-   [ ] The `This PR` section has a bullet point list describing the changes in this PR
-   [ ] If this PR addresses an open issue, it is linked in the `Issue` section
-   [ ] If any lesson files are included in this PR, they have been previewed with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure it is formatted correctly
-   [ ] If any lesson files are included in this PR, they follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

### CODE REVIEW

**Review by thatblindgeye — COMMENTED** [review]
Rather than removing it, we want to keep this and add content for the section. Would you want to take a shot at adding that content as part of this PR?

**Comment by Naoufal-Aziane** [comment]
That's what i though as well, but when i checked the previous lessons. I found that [Fundamentals Part 4](https://www.theodinproject.com/lessons/foundations-fundamentals-part-4) has no introduction section. That's why i suggested to delete it on "Fundamentals Part 5"  as well to keep it consistent.
So we can either add introduction section to both of them or delete the introduction section from the fundamentals part 5.

**Comment by Naoufal-Aziane** [comment]
> Rather than removing it, we want to keep this and add content for the section. Would you want to take a shot at adding that content as part of this PR?

That's what i though as well, but when i checked the previous lessons. I found that [Fundamentals Part 4](https://www.theodinproject.com/lessons/foundations-fundamentals-part-4) has no introduction section. That's why i suggested to delete it on "Fundamentals Part 5" as well to keep it consistent.
So we can either add introduction section to both of them or delete the introduction section from the fundamentals part 5.

**Comment by thatblindgeye** [comment]
Yeah having the lesson layouts as consistent as possible is a work in progress. Any lesson that doesn't have an "Introduction" section will eventually have it added in.

**Comment by thatblindgeye** [comment]
@Naoufal-Aziane would you be interested in adding Introduction sections to this lesson?

**Comment by thatblindgeye** [comment]
Closing due to inactivity, and will be covered when the lesson format is updated to match our style guide.

**Pull request closed without merging**
