### PR TITLE
fixed a typo in web-dev-101 -> installations -> prerequisites

### PR DESCRIPTION
**Pull request by w1ll37**
changed "step 3.1" to "step 3.2" (incorrectly named)

### CODE REVIEW

**Comment by marvingay** [comment]
Good catch! Thank you so much for your contribution.

**Comment by w1ll37** [comment]
Hi Marvin,

Thanks for the reply! However, I noticed that it isn't updated on the
website yet. I'm quite new to this so I was wondering: when exactly do
updates from the GitHub repository go to the website?

[image: image.png]

Thanks,
William

**Comment by marvingay** [comment]
@w1ll37 The view of the curriculum updates once a day. I believe it's typically in the early morning in the United States timezones.

**Comment by w1ll37** [comment]
Thanks for the information!

Take care,
William

**Pull request merged**
