### PR TITLE
Remove HTML DOG add FreeCodeCamp

### PR DESCRIPTION
**Pull request by codyloyd**
... HTMLDOG is outdated.. FCC is not.

### CODE REVIEW

**Comment by bycdiaz** [comment]
Looks good to me. 👍

**Comment by 105ron** [comment]
🤔

**Comment by codyloyd** [comment]
@105ron have any more detailed thoughts on the matter?

**Comment by 105ron** [comment]
Is the thinking emoji not enough? I'll have a look through FCC and compare, then get back you you. I think it's probably a good idea.

**Comment by codyloyd** [comment]
nice @105ron 

the big issue this should solve is that after doing HTMLDog almost everyone we get in the chatrooms lately have been trying to do the google homepage assignment with absolute positioning and floats... they know nothing about flexbox 😬

**Comment by I3uckwheat** [comment]
Looks good to me, though we may want to suggest skipping the project at the end. Doing the google homepage will be redundant at that point. @codyloyd

**Pull request merged**
