### PR TITLE
Update to installations.md

### PR DESCRIPTION
**Pull request by man-to-man**
## Because

 i updated an instraction because an answer i saw in the #wsl-help chat at the by Scheals. it works

## This PR

in line 343 i have added the text in round brackets

## Issue

Closes #XXXXX

## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project curriculum contributing guide](https://github.com/TheOdinProject/curriculum/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [x] The `Because` section summarizes the reason for this PR
-   [x] The `This PR` section has a bullet point list describing the changes in this PR
-   [x] If this PR addresses an open issue, it is linked in the `Issue` section
-   [x] If any lesson files are included in this PR, they have been previewed with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure it is formatted correctly
-   [x] If any lesson files are included in this PR, they follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

### CODE REVIEW

**Review by xandora — COMMENTED** [review]
Unfortunately, the answer here isn't quite this simple. On my fresh Windows 10 install, my only Ubuntu option in Terminal has the Ubuntu icon. This could be confusing for someone if they were expecting to click the Penguin icon, and they only saw an Ubuntu icon.

**Comment by man-to-man** [comment]
so should we find what is done on win8 and edit acordingly or is it just not a worthwhile commit?

**Comment by MaoShizhong** [comment]
@xandora is this PR something that still needs further action? Or is it something we can close and leave the lesson content as is?

**Comment by xandora** [comment]
I think we'd probably get more questions about what to do if you don't have the Penguin icon. We should leave the lesson as it is.

**Pull request closed without merging**
