### PR TITLE
Javascript basics, fundamentals 4 lesson: updated style of lists

### PR DESCRIPTION
**Pull request by thatsthat**
## Because

Updated the style of lists

## This PR

- Replaced asterisks by hyphens for unordered lists
- Changed to lazy numbering schema for ordered lists
- Ensured only a single space before content for all lists items
- Double check punctuation according to google style guide for all lists items

## Issue

Related to #27119

## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [x] The `Because` section summarizes the reason for this PR
-   [x] The `This PR` section has a bullet point list describing the changes in this PR
-   [x] If this PR addresses an open issue, it is linked in the `Issue` section
-   [x] If any lesson files are included in this PR, they have been previewed with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure it is formatted correctly
-   [x] If any lesson files are included in this PR, they follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

### CODE REVIEW

**Review by CouchofTomato — APPROVED** [review]

**Comment by CouchofTomato** [comment]
Hey @thatsthat 

There's some other issues being flagged by the linter. Are you happy to address them?

**Comment by thatsthat** [comment]
> Hey @thatsthat
> 
> There's some other issues being flagged by the linter. Are you happy to address them?

Yes I'll take a look!

**Comment by thatsthat** [comment]
The error I get by the linter (_Expected: asterisk; Actual: underscore_) doesn't seem related to the changes I have introduced, I a confused :-/

**Comment by thatsthat** [comment]
OK, I have pushed an extra 'commit' to my PR branch, is that taken into account automatically?

**Review by thatblindgeye — COMMENTED** [review]
There's a couple other quick updates that can be made. One is just replacing the underscore syntax for emphasis with asterisks, and the other is updating an ordered list so that all list items are prefixed with `1.`. Would you mind making these updates?

**Comment by thatsthat** [comment]
> There's a couple other quick updates that can be made. One is just replacing the underscore syntax for emphasis with asterisks, and the other is updating an ordered list so that all list items are prefixed with `1.`. Would you mind making these updates?

Yes I had missed a couple of cases, it should be now complete.

**Review by thatblindgeye — APPROVED** [review]

**Pull request merged**
