### PR TITLE
Add my solution to HTML/CSS project

### PR DESCRIPTION
**Pull request by JMurphyWeb**
I cannot work out how to view the solution in the browser

### CODE REVIEW

**Comment by JMurphyWeb** [comment]
Hi,
I am a little confused as to how to view my solution in the browser.  The files
are saved in a repository in GitHub, but i dont know how to open/preview
them in webpage format.  Is there a button i can press when in github when
i am in my repository?

Thanks again for any assistance,
Jack

**Comment by KevinMulhern** [comment]
To get your solution to be viewable in your browser its really all about how you format your link for your Github repo where your project resides.

**Comment by JMurphyWeb** [comment]
Hi Kevin,
Really appreciate the response. i will take a look over it this evening. I am looking forward to feeling a lot more comfortable with GitHub in the near future!

Cheers,
Jack

**Comment by KevinMulhern** [comment]
No problem @JMurphyWeb, it definitely is a matter of getting comfortable with it with more practice.

**Comment by KevinMulhern** [comment]
Closing due to no activity in 14 days.

**Pull request closed without merging**
