### PR TITLE
Testing basics & More Testing lesson: Clarify instruction

### PR DESCRIPTION
**Pull request by mekbibDev**
## Because

The purpose of this pull request is to prevent learners from installing unnecessary packages and configuring unnecessary configurations. The original instruction tells users to simply follow the getting started guide on the Jest website but the instruction on that website has info that is irrelevant to learners at this stage. One of them is [Generate a basic configuration file](https://jestjs.io/docs/getting-started#generate-a-basic-configuration-file) which helps users configure their jest setup. However, the setup is unnecessary and may lead to confusion for learners. For example, it asks questions  whether they want to use typescript or not, and whether or not it should clear up mock calls and context. For the latter example take in mind that learners have never written a single mock test so far and might actually take a way their chance to use beforeEach/AfterEach jest code. The other configuration are also unnecessary at this stage. I have also clarified that they should install and configure babel so they can use ES6 modules since learners have so far never used commonJS modules which further on might lead them to mistakenly mix both when doing projects.

The other confusion that learners might come across is the using webpack with jest section in the getting started guide. Learners might be misled into thinking they need to follow this instruction to use jest when testing their upcoming project. However the instruction in that section, talks about how you would set up jest with webpack for CSS and static assets, which is again irrelevant for learners at this stage because they are only going to be doing unit testing and have not been taught about integration testing. This is also the reason that I have removed using jest with webpack in the more testing section.

## This PR

- Adds a sentence to clarify instruction
- Removes a resource form the additional resource section

## Issue

Closes #XXXXX

## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [x] The `Because` section summarizes the reason for this PR
-   [x] The `This PR` section has a bullet point list describing the changes in this PR
-   [x] If this PR addresses an open issue, it is linked in the `Issue` section
-   [x] If any lesson files are included in this PR, they have been previewed with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure it is formatted correctly
-   [x] If any lesson files are included in this PR, they follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

### CODE REVIEW

**Comment by mekbibDev** [comment]
I know this is yet to be reviewed but I want to let you know that I made a mistake on one of the points. I forgotten that instructions for using babel with jest is mentioned in the testing practice. so the part about using jest with babel is redundant.

**Comment by rlmoser99** [comment]
> I know this is yet to be reviewed but I want to let you know that I made a mistake on one of the points. I had forgotten that instructions for using babel with jest are mentioned in the testing practice. so the part about using jest with babel that I've added is redundant.

@mekbibDev If you know part of the changes are no longer needed, you should change them back.

**Comment by mekbibDev** [comment]
alright. I was worried that it might interfere with the review flow or that maybe I need to do a whole new pull request.

**Comment by mekbibDev** [comment]
@rlmoser99 @codyloyd  I have made the changes

**Review by codyloyd — APPROVED** [review]

**Pull request merged**
