### PR TITLE
Remove redundant words : Entire curriculum

### PR DESCRIPTION
**Pull request by Mclilzee**
## Because

The words simply and simple, has been heavily used throughout the curriculum with little to no meaning to them. The word simply does not contribute to any sentence more than being noise, removing the word entirely will in fact enhance the readability of the sentences.

When it comes to the word Simple, then it is a little different, especially when it comes to explaining concepts inside lessons. If a lesson is simple then it does not require explanation, and if it does and the student still doesn't understand what we are trying to teach them, then adding the word "this is simple" then we are insulting their intelligence implying that they are not smart enough to understand such simple concepts.

Any concept is new and have the potential to confuse a new learner, even things that trivial to experience people like `let x = 5` is confusing to beginners.

## This PR

- Remove the word `simply` from almost all sentences and lessons.
- Replace the word `simple` with other keywords, such as:
  - Basic, to refer to structures, such as projects, functions and so on, implying they are not complex but not necessary simple to implement or understand,
  - Beginner friendly, to refer to concepts and wording that are made so that people who are new to programming can understand, but still does not mean they are simple.
  - Straightforward, mostly for the lack of better words to fill in the gap without having to change the whole structure of a paragraph, things like setting up your `github` and so on is straightforward by following instructions.

## Issue

Closes #XXXXX

## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [x] The `Because` section summarizes the reason for this PR
-   [x] The `This PR` section has a bullet point list describing the changes in this PR
-   [x] If this PR addresses an open issue, it is linked in the `Issue` section
-   [x] If any lesson files are included in this PR, they have been previewed with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure it is formatted correctly
-   [x] If any lesson files are included in this PR, they follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

### CODE REVIEW

**Comment by rlmoser99** [comment]
@Mclilzee Thank you for taking the time to update this wording. However this PR is really massive, which makes it a big burden to put on one person. Typically, we prefer having PRs that touch a lot of files broken down into separate PRs for each section, so that we can review it in a timely manner. This approach would have been discussed if you would have made an issue before creating a PR, which is one of the reasons we ask for an issue to be made before a PR for significant changes.
https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md#how-to-contribute

Would you please take these changes and make separate PRs, for each different course or section in the curriculum.

**Comment by Mclilzee** [comment]
@rlmoser99 I understand your concerns, and that is true this PR is massive however the changes in each file is just a word have been removed, and felt that making 172 PR for that is too much. Would you explore using GitHub's viewed method to tick each file that has been read, I do not expect anyone to go through this PR in one day, but taking multiple days is still possible even in one PR.

**Comment by rlmoser99** [comment]
@Mclilzee I am not asking for 172 PRs. I am asking for like a dozen different ones, like all the React lessons ones in a PR and all the Git ones in a PR. This PR is too big to expect any 1 person to do it, even using the GitHub tools to help manage what files have been viewed.

**Comment by Mclilzee** [comment]
@rlmoser99 That is more reasonable, and I will happily work with. counting the sections that would be 11 PR for each section namely:
- advanced_html_css
- databses
- foundations
- getting_hired
- git
- intermediate_html_css
- javascript
- nodeJS
- react
- ruby
- ruby_on_rail

I believe I can copy the changes that I have already made and separate them into their own branches and PRs, so that wouldn't require me to re-do all the changes from scratch.

**Comment by rlmoser99** [comment]
Thank you for taking the time to put these changes in smaller PRs. Looks like the most that 1 person will have to review is 28 files, so that is a lot more manageable then 172. Will be closing this PR, since we will not be reviewing this one.

**Pull request closed without merging**
