### PR TITLE
I couldn't figure out how to use Firebase. This series cleared things up for me.

### PR DESCRIPTION
**Pull request by PlayingOnGitHub**
Firebase has a lot of information for different things you can do. There was so much information available about Firebase that I quickly became overwhelmed by all of the different features. This series helped me understand how to get started.

### CODE REVIEW

**Comment by marvingay** [comment]
@PlayingOnGitHub What does this series do that the current resources failed to, for you? Or, how is this series an improvement upon what's presently available?

**Comment by PlayingOnGitHub** [comment]
The first link "https://firebase.google.com/docs/?authuser=0" took me to everything I can do with Firebase. This was overwhelming. I wasn't sure where to start. I tried clicking "Get started for Web." That pointed me in the right direction; although, I ended up installing a whole bunch of other features that weren't needed for this project. If you continue to scroll down, the article tells you how to use cloud functions and how to use hosting. The hosting feature quickly became very confusing for me.

The video "Getting Started with the Firebase Realtime Database on the Web, Part 1 - Firecasts" showed me a very specific way to pull data from one object. I was able to create my project by creating multiple items in my database. I learned more about how to delete items from my database and how to add items to my database by following the series I linked in my commit.

I also found this documentation very helpful and it took me awhile to find it: "https://firebase.google.com/docs/firestore/quickstart?authuser=0." This is a great starting place for beginners! A brief tutorial would help beginners quickly navigate through the process. Something along the lines of: "
-> First, view step 2 and only attach the two scripts at the bottom of your body tag.
-> Next, skip down to where it says 'Initialize Cloud Firestore.' Make sure you are under the 'Web' tab. Copy the code inside of the code block and place this code underneath the two scripts you just pasted into your body tag.
-> Now, you can use your db variable to access everything inside of your database!
-> Read through "https://firebase.google.com/docs/firestore/manage-data/structure-data?authuser=0."
-> You will particularily find the tabbed sections 'Add data'and 'Delete data' very helpful. You will also want to read through the first couple of articles under the tab 'Read data.'
"

**Comment by PlayingOnGitHub** [comment]
Back to your question. This series taught me how to delete and add items to my database. The series went into a bunch of other things I could do too, but I didn't need to view the entire series to understand how to use Firebase.

**Comment by marvingay** [comment]
Revisited this today.

The current resources lend themselves to getting acclimated with the documentation, as well as linking to their official introductory video to Firebase. It isn't entirely practical to make this additional series compulsory, especially given that they aren't __necessary__. Further, at this stage googling for additional resources should be in the toolkit.

Closing.

**Pull request closed without merging**
