### PR TITLE
add additional resources

### PR DESCRIPTION
**Pull request by Alucard2169**
added a additional resource in the additional resources section

Complete the following REQUIRED checkboxes:

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`

Complete the following checkboxes ONLY IF they are applicable to your PR. You can complete them later if they are not currently applicable:
-   [x] I have previewed all lesson files included in this PR with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure the Markdown content is formatted correctly
-   [x] I have ensured all lesson files included in this PR follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

<hr>

**1. Because:**

Closes #XXXXX

**2. This PR:**

**3. Additional Information:**

### CODE REVIEW

**Comment by Alucard2169** [comment]
added a resource link in the additional resources section of Git Basics

**Review by SauravJalui — COMMENTED** [review]
Hey @Alucard2169,

Thanks for helping by adding supplementary resources.

The playlist however would be a bit too advanced for [git basics](https://www.theodinproject.com/paths/foundations/courses/foundations#git-basics) section.

You can maybe add it in the [intermediate git](https://www.theodinproject.com/paths/full-stack-javascript/courses/javascript#intermediate-git) section resources

~Saurav

**Comment by wise-king-sullyman** [comment]
@Alucard2169 can you tell me what all information is covered in this playlist that we don't cover in the curriculum at the moment?

**Comment by zachmmeyer** [comment]
Closing out, no response from author.

**Pull request closed without merging**
