### PR TITLE
Block and inline: Foundations/CSS Foundations: Update lists per layout style guide

### PR DESCRIPTION
**Pull request by rosecodez**
## Because

- This PR changes [Block and Inline lesson](https://www.theodinproject.com/lessons/foundations-block-and-inline) lists according to TOP layout style.

## This PR

- asterisks `*` are replaced with a hyphen ` -`
- removes spaces in front of list items
- changes list items to lazy numbering
## Issue

Related to #27118 

## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [x] The `Because` section summarizes the reason for this PR
-   [x] The `This PR` section has a bullet point list describing the changes in this PR
-   [x] If this PR addresses an open issue, it is linked in the `Issue` section
-   [x] If any lesson files are included in this PR, they have been previewed with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure it is formatted correctly
-   [x] If any lesson files are included in this PR, they follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

### CODE REVIEW

**Comment by rosecodez** [comment]
Not entirely sure about the last error, the linter wants to change the `html` in the `index.html` into `HTML`. Pretty sure it should be just `.html` since it's a file extension.

**Review by JoshDevHub — CHANGES_REQUESTED** [review]
Looking good, but there's a small thing we can do to clean up that "HTML" error.

> Not entirely sure about the last error, the linter wants to change the `html` in the `index.html` into `HTML`. Pretty sure it should be just `.html` since it's a file extension.

You want to make the filename into inline code (so wrap "index.html" in single backticks).
```markdown
like this: `index.html`
```
This will get rid of the warning about how it should be "HTML", and it's how the [style guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md#inline) specifies we should handle filenames.

**Comment by rosecodez** [comment]
Thanks, Josh! Just made the changes.

**Review by JoshDevHub — APPROVED** [review]
Looks great!

**Pull request merged**
