### PR TITLE
Foundations/Growing and Shrinking/Provide descriptive link text

### PR DESCRIPTION
**Pull request by Rllopez0410**
## Because
Links in the lesson should be sufficiently descriptive to improve accessibility. As per the link text, it should both concisely describe its purpose.

## This PR
- Changed the text on line 81.
- Change the text on line 96.

## Issue
Related to [#27681](https://github.com/TheOdinProject/curriculum/issues/27681).

## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [x] The `Because` section summarizes the reason for this PR
-   [x] The `This PR` section has a bullet point list describing the changes in this PR
-   [x] If this PR addresses an open issue, it is linked in the `Issue` section
-   [x] If any lesson files are included in this PR, they have been previewed with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure it is formatted correctly
-   [x] If any lesson files are included in this PR, they follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

### CODE REVIEW

**Review by MaoShizhong — COMMENTED** [review]
Thanks, @Rllopez0410. Mind fixing up the lint errors while you're at it? They should be pretty self-explanatory.

**Comment by Rllopez0410** [comment]
Hello @MaoShizhong, I'm not sure if I'm on going about fixing these linting errors correctly; can you see if this is correct when you get the chance?

**Comment by MaoShizhong** [comment]
@Rllopez0410 The most recent commit ([5b347e6](https://github.com/TheOdinProject/curriculum/pull/27784/commits/5b347e6e61e40814773ba56cfe66caf81ffc1388)) ended up removing a bunch of `` ` `` that need to be put back, as the inline code blocks were needed for all of them, do differentiate the code values/keywords from normal words in the sentence.

As for the lint errors in general, you can view the errors in the action details:
image

Or in the `Files changed` tab:
image

Linting becomes a lot easier to check and resolve when you do changes locally, as you can run `markdownlint` with the appropriate configuration on your local machine. So you won't have to keep pushing commits then checking the lint action outcome.

**Comment by MaoShizhong** [comment]
Lines 64-70 currently look like this:

```md
> #### Important note about flex-basis:
>
> There is a difference between the default value of `flex-basis` and the way the `flex` shorthand defines it if no `flex-basis` is given. The actual default value for `flex-basis` is `auto`, but when you specify `flex: 1` on an element, it interprets that as `flex: 1 1 0`. If you want to _only_ adjust an item's `flex-grow` you can do so directly, without the shorthand. Or you can be more verbose and use the full 3 value shorthand `flex: 1 1 auto`, which is also equivalent to using `flex: auto`.

> #### What is flex: auto?
>
> If you noticed, we mentioned a new flex shorthand `flex: auto` in the previous note. However we didn't fully introduce it. `flex: auto` is one of the shorthands of flex. When `auto` is defined as a flex keyword it is equivalent to the values of `flex-grow: 1`, `flex-shrink: 1` and `flex-basis: auto` or to `flex: 1 1 auto` using the flex shorthand. Note that `flex: auto` is not the default value when using the flex shorthand despite the name being "auto" which may be slightly confusing at first. You will encounter and learn more about `flex: auto` and its potential use-cases when reading through the assignment section.
```

Could you replace those lines with the following?

```md
<div class="lesson-note" markdown="1">

#### Important note about flex-basis

There is a difference between the default value of flex-basis and the way the flex shorthand defines it if no flex-basis is given. The actual default value for flex-basis is auto, but when you specify flex: 1 on an element, it interprets that as flex: 1 1 0. If you want to only adjust an item's flex-grow, you can do so directly, without the shorthand. Or you can be more verbose and use the full 3-value shorthand flex: 1 1 auto, which is also equivalent to using flex: auto.

</div>

#### What is flex: auto?

If you noticed, we mentioned a new flex shorthand `flex: auto` in the previous note. However we didn't fully introduce it. `flex: auto` is one of the shorthands of flex. When `auto` is defined as a flex keyword it is equivalent to the values of `flex-grow: 1`, `flex-shrink: 1` and `flex-basis: auto` or to `flex: 1 1 auto` using the flex shorthand. Note that `flex: auto` is not the default value when using the flex shorthand despite the name being "auto" which may be slightly confusing at first. You will encounter and learn more about `flex: auto` and its potential use-cases when reading through the assignment section.
```

**Comment by MaoShizhong** [comment]
@Rllopez0410 Please see above regarding how to see the linting errors and how to resolve them, as well as the fix require for the blockquote error on line 67, as it'd be better to not use blockquotes for those bits anyway.

It might be a bit awkward trying to transfer this to your local machine to work on right now, but for future PRs, you'll likely find it far easier to do lint checks/fixes and make bigger changes to multiple files (in the same branch and PR!) if you work locally.

For reference, our [general contributing guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md) has instructions for setting up your local fork (and keeping your main branch up to date), and creating branches off main where you'll do your actual work.
The [curriculum repo-specific contributing guide](https://github.com/TheOdinProject/curriculum/blob/main/CONTRIBUTING.md) has instructions for how to run lint checks and fixes (for some of the rules) locally.

**Comment by Rllopez0410** [comment]
@MaoShizhong, understood. I'll look into the docs before my next PR. I appreciate you guiding me to the appropriate resources! I'll finish this PR ASAP.

**Review by MaoShizhong — CHANGES_REQUESTED** [review]
Thanks for sorting out the emphasis markers. There are still some blank line lint errors to resolve, some of which look to be caused by lines looking blank but actually containing some number of spaces. There are also the default section content for the knowledge check and additional resources to fix, which would just be replacing the opening text to what the error says it expects instead.

You can view any linting errors to go in either the `Files changed` tab, or via the action details - shown in one of the images above.

When you push commits, the action will rerun and notify you if it fails. If it passes, you'll see a big green tick here saying all checks passed.

**Comment by MaoShizhong** [comment]
@Rllopez0410 Just checking in if you've seen the above - no rush at all (genuinely) if you've been busy with other things. There's also a new.merge conflict to resolve which should be straightforward (get rid of line starting with `*` and keep your one starting with `-`)

**Comment by Rllopez0410** [comment]
Hey @MaoShizhong I've just seen the new merge conflict; I'll be able to get back to working on this PR tomorrow. I appreciate the patience you've had with me during this contribution 🙏.

**Comment by MaoShizhong** [comment]
No problem at all! Just a courtesy check in because I know recently a few review change requests haven't sent out notifications (has happened to me too)

**Comment by MaoShizhong** [comment]
@Rllopez0410 Just checking in again on the status of this PR

**Comment by Rllopez0410** [comment]
Hey @MaoShizhong I should be able to work on this again. My apologies, to take some time off for work. I'll be able to start working on this tomorrow EOD.

**Comment by MaoShizhong** [comment]
All good, just making sure all is well

**Review by MaoShizhong — APPROVED** [review]

**Pull request merged**
