### PR TITLE
jQuery for codecademy is offline

### PR DESCRIPTION
**Pull request by JoeyRobertson**
Hey,
I made a change on the intro to jquery site letting people know that jQuery is offline and that it should be back up sometime this month

```
This is a PR template, If you are adding a solution link to the curriculum leave this as is. If you are not, then delete it and write the message you wish.
Thank you,
The Odin Project team.

```

### CODE REVIEW

**Comment by KevinMulhern** [comment]
Thanks for reporting this @JoeyRobertson, Its unfortunate they didn't wait until the new course was released before removing the old one :(

But I think the best solution for this right now is to remove the assignment entirely and put it back in when they release the new course. A lot of students prefer the codeschool course anyway.

**Comment by JoeyRobertson** [comment]
Hey, that makes sense. Way less complicated than what I wrote!

**Comment by KevinMulhern** [comment]
Do you want to do that in this pull request @JoeyRobertson? 😄

**Comment by JoeyRobertson** [comment]
Sure! Doing it now!

**Comment by KevinMulhern** [comment]
Brilliant, thanks @JoeyRobertson 
LGTM 👍

**Comment by JoeyRobertson** [comment]
Okay, I have removed the codecademy track for jQuery from the course! I will keep an eye on it and will revert it with any link changes once they update it.

**Comment by KevinMulhern** [comment]
Just seeing your last message @JoeyRobertson, thanks again 😄

**Pull request merged**
