### PR TITLE
Added a course to learn commands quicker.

### PR DESCRIPTION
**Pull request by WeAreSystems**
I made a small course on Memrise's website to help embed simple commands into long-term memory faster.

### CODE REVIEW

**Comment by KevinMulhern** [comment]
Hey @WeAreSystems, thanks for the pull request. Im going to hold off merging this for a week. This lesson is next up on my list for improving. I'll review the flash cards some evening this week and let you know what I think.

**Comment by KevinMulhern** [comment]
Hey @WeAreSystems, I just reviewed the cards. Some of the commands are a little bit too advanced for this part of the course I'm afraid. This lesson focuses on navigating around directories and creating and removing files and directories. At least it will be when I am done with it lol. Is it possible to create levels on memrise?

**Comment by WeAreSystems** [comment]
Hey @KevinMulhern, no worries, yes it is possible to add levels to the the memrise course.  I'll look at it again in the future at some point to update it to make it a bit more accessible for folks starting out.  I think it is a great resourse (memrise) for drum things into your brain.

**Comment by KevinMulhern** [comment]
Yeah I love the gamified aspect of it.

**Pull request closed without merging**
