### PR TITLE
Add my Caesar Cipher solution into project building block

### PR DESCRIPTION
**Pull request by saroar**
```
This is a PR template, If you are adding a solution link to the curriculum leave this as is. If you are not, then delete it and write the message you wish.
Thank you,
The Odin Project team.

```

### CODE REVIEW

**Comment by csrail** [comment]
Hey @saroar

This commit you're wanting to put through would remove your stock picker solution.
Could you please pull the changes in from upstream?

Thanks.

**Comment by saroar** [comment]
@csrail what does it means upstream?

**Comment by csrail** [comment]
Upstream is a remote branch of the original "The Odin Project" repository. You need to pull these changes in to your own forked repository so that you can get the new changes for your file.

Click on [Files changed](https://github.com/TheOdinProject/curriculum/pull/4613/files) and you will see you've deleted your own solution.

**Comment by csrail** [comment]
Merged at #4624

**Pull request closed without merging**
