### PR TITLE
Add youtube series to additional resources

### PR DESCRIPTION
**Pull request by EmilioAK**
- [x] You have read [The Odin Projects Contributing Guide](https://github.com/TheOdinProject/curriculum/blob/master/CONTRIBUTING.md).

#### 1.Describe the changes made:

I found this series really made things click for me in a way that other articles and resources did not. For people who prefer video I think this will be really helpful

#### 2. If this PR is related to an open issue please reference it with the `#` operator and the issue number below:

#XXXXX

### CODE REVIEW

**Comment by EmilioAK** [comment]
Apologies, I didn't change the branch name to be `feature`. I can take this down and start over if necessary

**Comment by KevinMulhern** [comment]
Hey @EmilioAK, thanks for taking the time to do this. 

Do you think we should state that only the first video will be applicable instead of the full series? Just because The first video seems to be about plain Ruby and the rest seem to be about testing Rails. Which won't be applicable to students yet.

**Comment by EmilioAK** [comment]
Sure, I could say that instead. I felt like the examples in the other videos helped cement the concepts though

**Comment by I3uckwheat** [comment]
> Hey @EmilioAK, thanks for taking the time to do this.
> 
> Do you think we should state that only the first video will be applicable instead of the full series? Just because The first video seems to be about plain Ruby and the rest seem to be about testing Rails. Which won't be applicable to students yet.

If we're going to do that, then we should only post the first video. I do agree that we don't want to overwhelm students too early for sure.

**Comment by EmilioAK** [comment]
I've changed it to only include the first video. Perhaps I could mention the others afterwards and link the playlist. Something like "the other videos go over more advanced topics, but the examples could still help cement the basic concepts"

**Comment by KevinMulhern** [comment]
Which others one's did you watch and what did you get from them @EmilioAK?

**Comment by EmilioAK** [comment]
@KevinMulhern I rewatched the series and now realize the rest is probably of limited value compared to the first video. I think its best to add the first video, like the current commit shows, and then let students watch the rest if they feel like it

**Comment by rlmoser99** [comment]
@EmilioAK Thanks for taking the time to share the video. I just watched it and I can see how a video walk through could be helpful in this lesson. It reminded me of a resource that we removed from the curriculum because the corresponding repo was outdated and hard to set up.

However, if we only point students to watch one video here, I think this video has more practical example and a really good walk through as well. 
https://thoughtbot.com/upcase/videos/red-green-refactor-by-example

I'd love to know what everyone thinks of this video versus the other video before we decide which one to place in the curriculum.

**Comment by EmilioAK** [comment]
@rlmoser99 Personally I really like that video as well, but I would say that its more simple and doesn't clear up the same confusions for me. I think this video would be great to have almost at the top of the article, before you read up on the other stuff. I think it helps a lot to have a video like this at the start since it helps give context and feel for a lot of the stuff that comes after, and I think if this video would have been at the start it would have clicked for me a lot faster!

**Comment by rlmoser99** [comment]
I just took the time to re-watch both videos to compare them better. I do not think this lesson needs both videos, so this proposed addition is fine with me. 

@KevinMulhern do you have any concerns about adding this video as an additional resource?

**Comment by KevinMulhern** [comment]
looks good to me @rlmoser99 👍

**Review by rlmoser99 — APPROVED** [review]
This will be a great additional resource. Thank you for taking the time to create and update this PR.

**Pull request merged**
