### PR TITLE
Update project_flickr_api.md

### PR DESCRIPTION
**Pull request by sapienfrom2000s**
## Because
Using gem and env variable is a bit outdated. Rails credentials is the new way to go for storing credentials.

## This PR
Introduces rails credentials to store keys.

## Issue

Closes #XXXXX

## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [x] The `Because` section summarizes the reason for this PR
-   [x] The `This PR` section has a bullet point list describing the changes in this PR
-   [x] If this PR addresses an open issue, it is linked in the `Issue` section
-   [x] If any lesson files are included in this PR, they have been previewed with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure it is formatted correctly
-   [x] If any lesson files are included in this PR, they follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

### CODE REVIEW

**Review by CouchofTomato — CHANGES_REQUESTED** [review]
While I'm in favour of this change generally I'm not 100% sure by the article. It is a nice introduction but I wonder if some of the ideas in there are a little dated. https://guides.rubyonrails.org/security.html#environmental-security uses examples of accessing credentials all as method calls in a chain, whereas the article makes use of the `dig` method.

We could perhaps link to both and maybe highlight they show different ways to access the credential values.

What are your thoughts?

**Comment by sapienfrom2000s** [comment]
_In an object-oriented fashion the call to Rails.application.credentials.stripe returns a hash of the key-value pairs we just added._
This is mentioned just before he said that he likes to use _dig_ to access nested values. Although I would like to link docs, it will lead to addition of one more document. I am not sure if it would not make the paragraph more crowded. 
Also, now, students will have 3 resources to add credentials. Do you think we can drop one of them to keep the lesson slim?

**Comment by CouchofTomato** [comment]
@sapienfrom2000s 

Because the links are shortened in the lesson I'm not sure how much overhead it will add.

Perhaps a middle ground is to add a note as you suggested, but instead of giving an example we just link to the docs. Something like...

Although not mentioned in the article, the value of each key can also be accessed by chaining keys as methods as shown in the [Rails Guides](https://guides.rubyonrails.org/security.html#environmental-security) examples

Do you think this is a good middle ground?

**Review by sapienfrom2000s — COMMENTED** [review]
Yes it's a good middle ground. Are you cool with the current commit, or do you want me to make some changes.

**Review by CouchofTomato — APPROVED** [review]

**Comment by CouchofTomato** [comment]
Thanks @sapienfrom2000s 

Looks good to me 🥳

**Pull request merged**
