### PR TITLE
Update fundamentals-2.md

### PR DESCRIPTION
**Pull request by dsmchen**
Clarify instructions.

### CODE REVIEW

**Comment by ryanford-frontend** [comment]
Reading it as it is now, I think the intention was to say "there are benefits to signing up, but it's not required for TOP"

**Comment by leila-alderman** [comment]
I worked on making this phrasing a bit better overall. 

@dsmchen Please let me know if this looks better to you.

**Comment by dsmchen** [comment]
Sorry, my first comment should've been:

Edit instructions as viewing the lessons without logging in / signing up shows a blank page.

**Comment by ryanford-frontend** [comment]
Just tested with same results. I sent them a notice, but in the mean time we should definitely implement @dsmchen 's rewording so they can access the problems.

**Comment by leila-alderman** [comment]
Thanks for the clarification @dsmchen and for confirming this @ryanford-frontend! I changed the phrasing to make it clear that signing in is required for the lessons and merged in the change.

**Pull request merged**
