### PR TITLE
Advanced Grid Properties: Add Josh Comeau's article about grid as an extra resource

### PR DESCRIPTION
**Pull request by nikitarevenco**
## Because

I found an awesome guide to Grid that really helped me solidify understanding about Grid when I first did those lessons, I feel that this resource would help people struggling with Grid.

## This PR

Adds an interactive article about Grid as an additional resource for the Advanced Grid Properties section, covering everything learnt up to that point and some more too.

Edit: Additionally I fixed the linting errors, but I can undo this if required.  
For some reason not all lint errors showed up at once, I would fix some, reload and more would show up. This kept repeating. I would do everything in 1 commit if this didn't happen. 
## Issue

Closes #XXXXX

## Additional Information

This PR is a copy of a PR I recently created, but it was closed automatically when I deleted my fork of TOP's repository, I didn't know it would delete, so I re-made this PR.

## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [x] The `Because` section summarizes the reason for this PR
-   [x] The `This PR` section has a bullet point list describing the changes in this PR
-   [x] If this PR addresses an open issue, it is linked in the `Issue` section
-   [x] If any lesson files are included in this PR, they have been previewed with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure it is formatted correctly
-   [x] If any lesson files are included in this PR, they follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

### CODE REVIEW

**Comment by ManonLef** [comment]
This link is already proposed in this older PR but I like the placement better in this lesson as opposed to the intro lesson. https://github.com/TheOdinProject/curriculum/pull/27104

**Comment by thatblindgeye** [comment]
@ManonLef did we want the other PR to update its placement, or do we want to close that PR and merge this one in?

**Comment by amaginn** [comment]
Hey @ManonLef and @thatblindgeye I think it would be a better fit here!  So a merge is cool with me.  Sorry for the delayed reply.

**Comment by ManonLef** [comment]
@nikitarevenco I figured that could be the issues. I've not been maintaining for the past two months so I have to get back into the loop a bit! Thanks for the update :) I appreciate it

**Comment by ManonLef** [comment]
Thanks so much for responding @amaginn I will close your PR after this comment.

**Review by ManonLef — APPROVED** [review]

**Comment by ManonLef** [comment]
@nikitarevenco thanks a lot for not only adding the link, but also making this lesson in line with the style guide! You rock 💪

**Pull request merged**
