### PR TITLE
Add my solution to HTML/CSS   easy google page

### PR DESCRIPTION
**Pull request by cihatdev**
This is a PR template. If you are adding a solution link to the curriculum, leave this as is. If not, delete it and write the message you wish.

Thank you,

The Odin Project team.

### CODE REVIEW

**Comment by marvingay** [comment]
@cihatdev  Hello. The markdown for your solution submission is not consistent with the other submissions in the file. Be sure to look at the other solution's and format yours accordingly. Once that's done we can display your solution!

Thank you!

**Comment by cihatdev** [comment]
I do not know exactly, github, I'm sorry, there are other projects in my repo so it was wrong.Thank you... Kimden: Marvin GayGönderilme: 22 June 2020 17:55Kime: TheOdinProject/curriculumBilgi: Cihat Salik; MentionKonu: Re: [TheOdinProject/curriculum] Add my solution to HTML/CSS easy google page (#18397) @cihatdev Hello. The markdown for your solution submission is not consistent with the other submissions in the file. Be sure to look at the other solution's and format yours accordingly. Once that's done we can display your solution!Thank you!—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by ZachBaird** [comment]
Hey @cihatdev , it still doesn't look quite right. It should just be the line with the other solutions with your name and no comments or headers saying this particular link is your solution.

**Comment by ZachBaird** [comment]
@cihatdev I fixed the layout of your submission markdown but the link you provided for your repo on Github 404s.

**Comment by marvingay** [comment]
@cihatdev  The repository that you linked here still doesn't exist. If you wish to have it displayed, make the appropriate changes and submit a new pull request.

This one will be closed for your convenience. (Lack of response)

Thank you.

**Pull request closed without merging**
