### PR TITLE
Advanced Selectors: adding a disclaimer on the usage of single colon vs double

### LINKED ISSUE #26466: Advanced Selectors: <add notes to the assignment>
### Describe your suggestion

This assignment article [Shay Howe’s article on Complex Selectors](https://learn.shayhowe.com/advanced-html-css/complex-selectors/) still uses ":" to write pseudo-elements, while it's recommended to use "::" currently. It would be nice to mention that in the assignment.

### Path

Node / JS

### Lesson Url

https://learn.shayhowe.com/advanced-html-css/complex-selectors/#pseudo-elements

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### (Optional) Discord Name

_No response_

### (Optional) Additional Comments

_No response_

### PR DESCRIPTION
**Pull request by ht-l1**
## Because

Adding two sentences to clarify the updated use of double colon. 

## This PR

In the Lesson Advanced Selector and under Assignment section Bullet two: adding two sentences to clarify the updated use of double colon. 

## Issue

Closes #26466 

## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [x] The `Because` section summarizes the reason for this PR
-   [x] The `This PR` section has a bullet point list describing the changes in this PR
-   [x] If this PR addresses an open issue, it is linked in the `Issue` section
-   [x] If any lesson files are included in this PR, they have been previewed with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure it is formatted correctly
-   [x] If any lesson files are included in this PR, they follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

### CODE REVIEW

**Review by wise-king-sullyman — CHANGES_REQUESTED** [review]
It looks like you may have accidentally run your formatter on this, the bullet changes are alright but the code blocks need to stay tildes rather than backticks.

The actual sentence you added looks good though!

**Comment by ht-l1** [comment]
Thank you @wise-king-sullyman for you review. Sorry I have been going back and forth trying to redo this - trying to overwrite my branch with the main branch here so I can start over but it doesn't seem to work. I tried various git commands like git rebase and git reset. Should I just delete my branch and do another pull request from the new branch or what's the best way to go about it?

**Comment by wise-king-sullyman** [comment]
The easiest way (without just starting over with a new branch) would probably be to just do a `git revert HEAD`, which will add a new commit undoing your previous commit. There are other ways to do it, but most of them require changing history you've pushed which can always be tricky.

**Comment by ht-l1** [comment]
Thank you! I tried `git revert HEAD` and it still didn't work. Then I just go back to main to `git pull` the latest update and started a new branch and re-committed and end up with auto formatter running again lol. I am thinking it perhaps is some extension I installed to my local vs code. So I end up just doing it in codespace and it works so I am replacing with a new pull request [#26499 ](https://github.com/TheOdinProject/curriculum/pull/26499), sorry for the back and forth!

**Comment by ManonLef** [comment]
@ht-l1 this usually happens when you have an extension like prettier set to auto-format on save for example.

**Pull request closed without merging**
