### PR TITLE
my solution

### PR DESCRIPTION
**Pull request by evabanegacom**
THis is my blog app first rails project

This is a PR template. If you are adding a solution link to the curriculum, leave this as is. If not, delete it and write the message you wish.

Thank you,

The Odin Project team.

### CODE REVIEW

**Comment by ZachBaird** [comment]
@evabanegacom Going to your repo and browser URL, all I see is an empty repo. Your browser URL points to your heroku dashboard, and the herokuapp you have doesn't have an app on it regardless. Did you deploy your Rails code to heroku and push to Github?

**Comment by evabanegacom** [comment]
that's because i haven't merged the branches and there's a problem with the
path right i can't submit it

**Comment by ZachBaird** [comment]
Hey @evabanegacom , I'm going to close this PR for now. If you've done the project, you just need to get it up on Github as it's own repo and make sure it's deployed to Heroku.

After that, you just need to make some minor changes to the forked curriculum repo and submit the pull request for that. [This](https://github.com/TheOdinProject/curriculum/blob/master/contributing.md) should help you out with getting your solution on the curriculum.

**Comment by evabanegacom** [comment]
heroku says i have reached the maximum submission limit for, i think they
allow just 5 max or i have to upgrade my account which involves money

**Pull request closed without merging**
