### PR TITLE
WIP: Tracks refactor

### PR DESCRIPTION
**Pull request by I3uckwheat**
Modularizing the installations:

This is a WIP Please do not merge yet.

### CODE REVIEW

**Comment by KevinMulhern** [comment]
Nothing sticks out
LGTM 👍, nice work @I3uckwheat

**Comment by I3uckwheat** [comment]
This needs to be reviewed before final acceptance.

**Comment by I3uckwheat** [comment]
I'm trying to fix the mess-up HOLD OFF

**Comment by I3uckwheat** [comment]
Whew, there we go, it's all ready to merge when the seeds file is merged in.

**Comment by I3uckwheat** [comment]
NOPE Still messed up

**Comment by I3uckwheat** [comment]
#11060 
This is the new one, I give up

**Pull request closed without merging**
