### PR TITLE
Add note that devtools resources are for chrome

### PR DESCRIPTION
**Pull request by CatQueenCodes**
Students seem to be trying to follow chrome tutorials in FireFox devtools. Added a note saying resources are to be followed in Chrome DevTools.

### CODE REVIEW

**Review by rlmoser99 — CHANGES_REQUESTED** [review]
I don't love adding important/clarifying notes like this, instead I like to see where that information would be the most useful and place it there. 

For the first lesson, the warning is before 2 videos & then looking at documentation. So I wonder if adding a note to the first video would be sufficient. Something like "If you want to follow along, be sure to use the same browser as indicated in the video."

For the second lesson, I would look at clarifying the assignment (Open your Chrome browser and head to the Chrome Dev Tool) and remove the "Opening Dev Tools" mention of Firefox. I think any mention of Firefox should come after the assignment, because I see this is the root cause of the confusion.

Both of my ideas are open to discussion since I may not have the complete picture.

**Comment by CatQueenCodes** [comment]
@rlmoser99 I like your idea! I think we actually discussed in discord adding chrome to the installations and try and get everyone on chrome.

**Comment by CatQueenCodes** [comment]
*I will get to this* I have to make a plan to change it in multiple places and add install chrome directions in the installations sections

**Comment by marvingay** [comment]
Are we still continuing forward this change?

**Comment by CatQueenCodes** [comment]
> Are we still continuing forward this change?

I do still need to do something with this. I will close it out as I think it needs a bit more thought

**Pull request closed without merging**
