### PR TITLE
Mention the usage of Node's LTS version to avoid errors in React course

### LINKED ISSUE #26351: React: Vite not running
### Describe your suggestion

In the current lts version of node, the latest vite version throws an error.
as stated in [this issue](https://github.com/vitejs/vite/issues/14299), vite can be run on node version 20.6.1.
Easily fixed it by running `nvm install node`.
Maybe add a temporary notice?

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-react-new-setting-up-a-react-environment

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### (Optional) Discord Name

_No response_

### (Optional) Additional Comments

_No response_

### PR DESCRIPTION
**Pull request by ScaxCodes**
## Because
If students are using the newest Node version 20.x, the commands in the lesson will throw an error. The usage of Node's LTS version prevents that, so we added a little reminder to this lesson.

## This PR
- mention the usage of the LTS version of Node in the lesson

## Issue

Closes #26351

## Additional Information
- none

## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [x] The `Because` section summarizes the reason for this PR
-   [x] The `This PR` section has a bullet point list describing the changes in this PR
-   [x] If this PR addresses an open issue, it is linked in the `Issue` section
-   [x] If any lesson files are included in this PR, they have been previewed with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure it is formatted correctly
-   [x] If any lesson files are included in this PR, they follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

### CODE REVIEW

**Comment by ScaxCodes** [comment]
Please let me know if this worked out, its my first PR.

**Comment by xandora** [comment]
I think you have this backwards. The bug is due to an interaction with LTS node and Vite. The fix is to install 20.x, not LTS.

**Review by xandora — APPROVED** [review]
Looks okay to me.

**Comment by ScaxCodes** [comment]
@xandora thank you michael, is it okay if i PR other "good first issues", or is it really only for the first one ever?
do you have any recommendations for my next PRs?

**Pull request merged**
