### PR TITLE
Update my html_css project solution

### PR DESCRIPTION
**Pull request by niyorich**
Here are the results of my html and css project

This is a PR template. If you are adding a solution link to the curriculum, leave this as is. If not, delete it and write the message you wish.

Thank you,

The Odin Project team.

### CODE REVIEW

**Comment by niyorich** [comment]
@marvingay which file should I edit and what do you mean by the markdown is not consistent with you standard?

**Comment by marvingay** [comment]
@niyorich You attempted to submit the "Google Homepage" assignment which is the `project_html_css.md`, if memory serves me correct, whereas you edited the calculator markdown file.

Solutions are in the format of:
`[niyorich's Solution](https://www.github.com/niyorich/repository)`

You can optionally include the `View in browser`, refer to the actual file you are editing to see an example.

**Comment by niyorich** [comment]
OK. can you give me the link to the google homepage solution. I tried to look for it but I could not.
Thank you

**Comment by marvingay** [comment]
@niyorich https://github.com/TheOdinProject/curriculum/blob/master/web_development_101/the_front_end/project_html_css.md

In the future, the link to the appropriate file is listed in the _Solutions section_ of the corresponding lesson.

**Comment by niyorich** [comment]
Thank you

**Comment by niyorich** [comment]
(Sorry about that, but we can’t show files that are this big right now.) This link is showing this since yesterday that's why I could not edit it

**Comment by marvingay** [comment]
It appears the filesize of the markdown file is problematic to Github. If you could paste your repository link (and Github pages link, if you wish) I'll take care of it for you this time.

**Comment by niyorich** [comment]
The repository link is" https://github.com/niyorich/google-homepage/blob/master/index.html" and my page link is "https://niyorich.github.io/google-homepage/" 
I would really appreciate your Help.

**Comment by marvingay** [comment]
@niyorich No worries. You shouldn't have any further issues in later projects, however, a recommendation would be to start familiarizing yourself with using the command line interface to make these changes.

Our Contributing Guide in the root of the repository has a video on it!

Thanks again!

**Pull request closed without merging**
