### PR TITLE
Reworded the exercise hint in Foundations/DOM manipulation and events

### PR DESCRIPTION
**Pull request by DigitalKnight0**
- [✅ ] You have read [The Odin Projects Contributing Guide](https://github.com/TheOdinProject/curriculum/blob/main/CONTRIBUTING.md).
 - [ ✅] The title summarizes the change and where it happened, for example: "Fixes punctuation in Clean Code lesson".
 - [✅ ] If the PR is related to an open issue, use a [relevant keyword](https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests) and reference it with the `#` sign and the issue number.
 - [ ✅] You have previewed your markdown (if any) in the [Odin Markdown Preview Tool](https://www.theodinproject.com/lessons/preview)
 - [ ✅] If changes are requested, please make the changes in a timely manner. After you submit the changes, request another review from the maintainer (top right).

#### 1. Describe the changes made and include why they are necessary or important:

The previous hint caused a lot of confusion as to whether it makes any difference if you append the div
before appending the h1 and p.  

#### 2. Related Issue

Closes #XXXXX

### CODE REVIEW

**Comment by Maheshkumar-novice** [comment]
@DigitalKnight0 Hey buddy, I think this will be useful for you.

help

https://github.com/tchapi/markdown-cheatsheet

**Review by wise-king-sullyman — CHANGES_REQUESTED** [review]
I think that the existing verbiage here is adequate, but your changing of "div" to `<div>` is something I like.

Would you be open to editing this PR to just update the div styling in the existing sentence?

**Comment by wise-king-sullyman** [comment]
Also, @DigitalKnight0 just to note for the future, PR titles that more precisely describe what was changed and where it was changed help us to more efficiently work through things. I've already updated this title so you don't need to do anything here🙂

**Comment by DigitalKnight0** [comment]
@wise-king-sullyman Done and will keep that in mind

**Review by wise-king-sullyman — APPROVED** [review]
Thanks @DigitalKnight0!

**Pull request merged**
