### PR TITLE
Replaced screenshots with outdated default branch name

### PR DESCRIPTION
**Pull request by wise-king-sullyman**
Per #21760 I updated all of the screenshots with reference to 'master' branch and replaced with 'main' branch.

### CODE REVIEW

**Comment by KevinMulhern** [comment]
Hi @wise-king-sullyman, thanks for doing this but I think we need to redo all the screenshots in this lesson. It's a jarring experience to have so many different types of terminal screenshots with different atheistics.

The screenshots you've added are also a bit hard to read, I think its caused by the font your terminal is using. It looks a bit antiquated compared to the other screenshots.

**Comment by wise-king-sullyman** [comment]
10 4, yes it would be a better experience to have just one consistent terminal shown. I just didn't want to chirp at others to fix the issue when I could do it myself.

Also I agree the screenshots don't look the best and can get hard to read at smaller window sizes than what I was using.

**Review by I3uckwheat — CHANGES_REQUESTED** [review]
What @KevinMulhern said

**Comment by ZachBaird** [comment]
Hey @wise-king-sullyman , I'm not sure how it happened but this pull request looks like it contains a load of extra stuff now. I think your forked master branch may need rebasing somehow.

**Comment by wise-king-sullyman** [comment]
@ZachBaird rebased. Sorry about that.

**Review by I3uckwheat — APPROVED** [review]

**Pull request merged**
