### PR TITLE
Rails Pathway: Provide descriptive link text

### PR DESCRIPTION
**Pull request by Peaches-xo**
## Because

Rails Pathway: Provide descriptive link text (multiple assignees) #28290
"Links in our lessons should be sufficiently descriptive to improve accessibility. As per the [layout style guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md#links), link text should both concisely describe its purpose (or where the link will redirect a user), and must not include the words this nor here."

## This PR

Updates links and text in the following lessons: 
- [Introduction to RSpec](https://www.theodinproject.com/lessons/ruby-introduction-to-rspec)
- [Conclusion](https://www.theodinproject.com/lessons/ruby-conclusion)

## Issue

Related to #28290

## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project curriculum contributing guide](https://github.com/TheOdinProject/curriculum/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [x] The `Because` section summarizes the reason for this PR
-   [x] The `This PR` section has a bullet point list describing the changes in this PR
-   [x] If this PR addresses an open issue, it is linked in the `Issue` section
-   [x] If any lesson files are included in this PR, they have been previewed with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure it is formatted correctly
-   [x] If any lesson files are included in this PR, they follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

### CODE REVIEW

**Review by MaoShizhong — COMMENTED** [review]
Thank you for sorting these links out @Peaches-xo.

Would you be happy to fix the remaining lint errors? You should be able to handle them via the following: 

1. In `introduction_to_rspec.md`, in the lesson overview list, combine the last item into one line: `` - Understand the basic RSpec syntax: `describe` and `it`. ``
2. Same file line 48, add `bash` to the code block so it opens with `` ```bash `` instead of just the backticks.
3. Follow our [local linting and fixing instructions](https://github.com/TheOdinProject/curriculum/blob/main/CONTRIBUTING.md#curriculum-linting) to run the `fix:lesson` script on both files. You may need to run the script more than once for `introduction_to_rspec.md` to fix all the remaining errors.

There will still be a "required heading structure" error left for `conclusion.md` - you can ignore this one.

Let me know if you run into any trouble with this.

**Comment by Peaches-xo** [comment]
I have made the changes in 1 and 2. 

Quick Q about running the fix:lesson script with markdownlint-cli2. I feel like Ive done something wrong because after I run the command **npm run lint:lesson -- "./introduction_to_rspec.md"** , it says Linting: 0 file(s). Would this mean that it didn't find the file? Im not sure what the output is supposed to look like.

Screenshot 2024-07-08 at 12 15 42 PM

**Comment by MaoShizhong** [comment]
@Peaches-xo You'll need to do this in the root of the curriculum repo, otherwise it won't pick up the config files.
If you `cd ../..` so you're back to the root of the curriculum repo, you can then run:

```bash
npm run lint:lesson -- "./ruby/testing_ruby_with_rspec/introduction_to_rspec.md"
```

You should get a much more reasonable output from that.

**Comment by Peaches-xo** [comment]
Thanks Mao - That did the trick! There is only the one error left as you mentioned above ("required heading structure" error left for conclusion.md)

**Review by MaoShizhong — APPROVED** [review]
:rocket:

**Pull request merged**
