### PR TITLE
Fix/replace student wording

### PR DESCRIPTION
**Pull request by shiroinegai**
- [✔] You have read [The Odin Projects Contributing Guide](https://github.com/TheOdinProject/curriculum/blob/main/CONTRIBUTING.md).

#### 1.Describe the changes made:

Added a small section "Ownership in Learning".

Said section can be found in:
foundations/introduction/motivation_and_mindset.md

Section is paraphrased from @bycdiaz 's message in announcements.

Relevant instances of "student" are replaced with "learner" or "peer" throughout the curriculum. I have replaced such instances in template files as well. Do tell if they should not be touched.

#### 2. If this PR is related to an open issue please reference it with the `#` operator and the issue number below:

#XXXXX

### CODE REVIEW

**Review by thatblindgeye — COMMENTED** [review]
Nice job! Really only had the one suggestion in regards to the subject of this PR. Also looks like there is a misspelling in the Ownership in Learning section.

**Comment by shiroinegai** [comment]
I have committed the suggested changes and fixed my typo! That word gets me occasionally. 😅

**Comment by shiroinegai** [comment]
Updated the wording as requested!

**Comment by twalton83** [comment]
We had a meeting amongst the maintainers and decided to not proceed with these changes with regards to curriculum references because colloquially, this distinction is not significant enough to warrant these changes. 

That said, the "Solutions" verbiage above the student submissions list could be updated to say "Project Submissions", and we have discussed and approved this internally. 

Thank you for your effort anyways.

**Pull request closed without merging**
