### PR TITLE
DOM Manipulation and Events: Altering #2 of Assignment's Wording

### PR DESCRIPTION
**Pull request by Monatric**
…oint

The way #2 is worded on Assignment section implies there are practices/challenges to work with in the given resource. However, there are no existing practices/challenges available.

## Because

The purpose of this PR is to avoid confusion that may arise due to the way it is worded. Since not all TOP learners are in the community like Discord, by slightly altering the words and structure, we can ensure that the TOP learners can avoid getting lost in the process.

## This PR

• The wording of #2 in Assignment section of DOM Manipulation and Events lesson

## Issue

Closes #XXXXX

## Additional Information

https://discord.com/channels/505093832157691914/505093832157691916/1203284647266484244

## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [x] The `Because` section summarizes the reason for this PR
-   [x] The `This PR` section has a bullet point list describing the changes in this PR
-   [x] If this PR addresses an open issue, it is linked in the `Issue` section
-   [x] If any lesson files are included in this PR, they have been previewed with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure it is formatted correctly
-   [x] If any lesson files are included in this PR, they follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

### CODE REVIEW

**Comment by CouchofTomato** [comment]
@Monatric There are some errors the linter is throwing up. Are you happy to fix them in this PR?

**Comment by Monatric** [comment]
> @Monatric There are some errors the linter is throwing up. Are you happy to fix them in this PR?

I'm sorry, I'm not sure I can do this. I don't even know what is linter.

**Comment by CouchofTomato** [comment]
You can review the issues here https://github.com/TheOdinProject/curriculum/pull/27267/files

You just need to make the fixes then commit them to your PR.

**Comment by Monatric** [comment]
Alright, I'll have a look on it and see what I can do when I have the time.

**Comment by CouchofTomato** [comment]
@Monatric 

If you don't have time it's fine. I can review this as is. Just let me know

**Comment by thatblindgeye** [comment]
Gonna merge this as-is just to get it in, I believe there's been some other updates made to this lesson that resolves some of the linting errors.

**Comment by Monatric** [comment]
> @Monatric
> 
> If you don't have time it's fine. I can review this as is. Just let me know

Sorry, I haven't replied for a while. There's just a lot going on and I can't insert the time to learn about this.

**Pull request merged**
