### PR TITLE
Copy-editing Changes to OOP Principles

### PR DESCRIPTION
**Pull request by NerdsAreIn**
- [x] You have read [The Odin Projects Contributing Guide](https://github.com/TheOdinProject/curriculum/blob/main/CONTRIBUTING.md).
 - [ ] The title summarizes the change and where it happened, for example: "Fixes punctuation in Clean Code lesson".
 - [ ] If the PR is related to an open issue, use a [relevant keyword](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) and reference it with the `#` sign and the issue number.
 - [ ] You have previewed your markdown (if any) in the [Odin Markdown Preview Tool](https://www.theodinproject.com/lessons/preview)
 - [ ] If changes are requested, please make the changes in a timely manner. After you submit the changes, request another review from the maintainer (top right).

#### 1. Describe the changes made and include why they are necessary or important:

This contains the copy-editing changes made in a previous pull request. It was requested that I split my changes into two requests.

It is not necessary to continue to quote or bold terms that have already been explained. It is also not necessary to put quote marks around capitalised proper nouns. All this creates inconsistency.

#### 2. Related Issue

Closes #XXXXX

### CODE REVIEW

**Comment by NerdsAreIn** [comment]
I'm not sure I've done everything right ...? 

This builds on PR #23057.

**Comment by zachmmeyer** [comment]
Could you please fix the title to match the guidelines in the [Contribution Guide](https://github.com/TheOdinProject/curriculum/blob/main/CONTRIBUTING.md)?

**Review by wise-king-sullyman — CHANGES_REQUESTED** [review]
Thanks for taking the time to submit this! I have a few changes I would like to see:

**Comment by zachmmeyer** [comment]
Closed due to being stale.

**Pull request closed without merging**
