### PR TITLE
add my solution

### PR DESCRIPTION
**Pull request by alexgh123**
add my solution

### CODE REVIEW

**Comment by craftykate** [comment]
@alexgh123 Can you give your second link a name? Like this: `[View in browser](your link)`

**Comment by alexgh123** [comment]
I think I just updated the second link name. Let me know if I didn't do it
right.

Thanks,
Alex

**Comment by craftykate** [comment]
@alexgh123 That worked! I changed it to say "View in browser" to be consistent across all project pages, but you did it right. Let me know if you need github help with anything.

**Comment by alexgh123** [comment]
Awesome, thanks!

**Pull request merged**
