### PR TITLE
Authentication Basics : change GET into POST on logout

### PR DESCRIPTION
**Pull request by Tribhuwan-Joshi**
According to RESTful API principles we should use POST method  to request that have side effects on the server side. We are already using method=POST in the form.

## Issue

Closes #XXXXX

## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
-   [] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [ ] The `Because` section summarizes the reason for this PR
-   [ ] The `This PR` section has a bullet point list describing the changes in this PR
-   [ ] If this PR addresses an open issue, it is linked in the `Issue` section
-   [ ] If any lesson files are included in this PR, they have been previewed with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure it is formatted correctly
-   [ ] If any lesson files are included in this PR, they follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

### CODE REVIEW

**Review by fortypercenttitanium — COMMENTED** [review]
@Tribhuwan-Joshi  Question - how would the user hit this end point?

**Comment by fortypercenttitanium** [comment]
Logout routes are usually gets since we're not submitting a form to logout.

**Comment by Tribhuwan-Joshi** [comment]
> Logout routes are usually gets since we're not submitting a form to logout.

Logout will make the changes for the user, so shouldn't be it POST? 
[Passport js](https://www.passportjs.org/concepts/authentication/logout/ )  is also using POST.

**Comment by Tribhuwan-Joshi** [comment]
> @Tribhuwan-Joshi Question - how would the user hit this end point?

We can wrap the logout link within a form element with post method

**Comment by fortypercenttitanium** [comment]
> > @Tribhuwan-Joshi Question - how would the user hit this end point?
> 
> We can wrap the logout link within a form element with post method

I suppose you could do that but it seems unnecessarily complex for this assignment. It requires a significant refactor of the logout link, and additionally it would require that we give an explanation as to why we are using a form for logout.

I wouldn't mind seeing a note added to this lesson saying that you can make logout a post route, and why you might want to do that, but you would also need to provide instructions on how to change the logout link appropriately. The way this PR was originally submitted would've broke the assignment completely.

Feel free to reopen and submit with those changes if you feel up for it.

**Pull request closed without merging**
