### PR TITLE
rails_programming: rename files & folders and move webpacker.md to archive

### PR DESCRIPTION
**Pull request by 01zulfi**
Complete the following REQUIRED checkboxes:

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`

Complete the following checkboxes ONLY IF they are applicable to your PR. You can complete them later if they are not currently applicable:
-   [ ] I have previewed all lesson files included in this PR with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure the Markdown content is formatted correctly
-   [ ] I have ensured all lesson files included in this PR follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

<hr>

**1. Because:**

Related to:
1. https://github.com/TheOdinProject/top-meta/issues/109

**2. This PR:**

1. Moves webpacker.md to archive.
2. Renames files and folders to match [course structure on the website](https://www.theodinproject.com/paths/full-stack-ruby-on-rails/courses/ruby-on-rails).

**3. Additional Information:**

n/a

### CODE REVIEW

**Review by KevinMulhern — COMMENTED** [review]
Can we put the webpacker lesson within a rails folder in the archive please @01zulfi? just so it will be easier to find when theres a lot of lessons in the archive.

Everything else looks great 👍

**Comment by KevinMulhern** [comment]
Nice work, thanks @01zulfi 🚀

**Comment by 01zulfi** [comment]
Renamed `rails_programming` to `ruby_on_rails`, @KevinMulhern

**Comment by KevinMulhern** [comment]
Looks good to me @01zulfi 👍

**Comment by 01zulfi** [comment]
Holding to merge until #23797 is merged.

**Comment by KevinMulhern** [comment]
Hey @01zulfi,  I think we should merge this as soon as we can since we don't have an eta on the turbo forms PR and this PR changes more files, increasing the likely hood of conflicts.

**Review by KevinMulhern — APPROVED** [review]

**Pull request merged**
