### PR TITLE
Positioning lesson: Add article link for CSS position to additional resources

### PR DESCRIPTION
**Pull request by DevVivan**
## Because

I added an article link to the additional resources section as there were none before. This article provides some additional insights into CSS positioning and it utilises many examples to help students understand with more ease.

## This PR

- Added an article link for CSS positioning.

## Issue

Closes #XXXXX

## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [x] The `Because` section summarizes the reason for this PR
-   [x] The `This PR` section has a bullet point list describing the changes in this PR
-   [x]  If this PR addresses an open issue, it is linked in the `Issue` section
-   [x] If any lesson files are included in this PR, they have been previewed with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure it is formatted correctly
-   [x] If any lesson files are included in this PR, they follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

### CODE REVIEW

**Review by wise-king-sullyman — CHANGES_REQUESTED** [review]
Thanks for making this PR! The article looks good, but can you update [the link text itself to be more descriptive](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md#use-informative-markdown-link-titles)?

**Comment by DevVivan** [comment]
Alright, thanks for the feedback. I'm just a little unsure, how should I make it more descriptive? By providing details about the article itself or stating the source?

**Comment by wise-king-sullyman** [comment]
Yeah just something a bit more descriptive so that anyone that's (for instance) navigating the site using a screen reader can know what the link pertains to using just the link text.

Since the article title pretty much matches your description I think you could just have the link text be the article title itself.

**Comment by DevVivan** [comment]
I commited the fixed link text now, you can take a look and I guess merge if all is well.

**Review by wise-king-sullyman — APPROVED** [review]
Looks great, thanks!

**Pull request merged**
