### PR TITLE
Update project_mailers.md

### PR DESCRIPTION
**Pull request by Rodic**

### CODE REVIEW

**Comment by craftykate** [comment]
@Rodic - I think this link is for the wrong project. The link you included on this pull request on `rails/project_mailers.md` is for the private events project, but this page is for the flight booker project. Can you go to `rails/project_mailers.md` and change your link to go to the correct project? Let me know if I wasn't clear on that. Thanks!

**Comment by Rodic** [comment]
Hi Kate,

It says: "You'll be dusting off your Flight Booker project (or one of the other projects that has users registering)". I picked the other project. If it's a problem please feel free to remove my solution. 

I thought it would be nice to have mailer implemented in a project other than FlightBooker, so that future students can have more than one example of how to do it.

**Comment by craftykate** [comment]
You're right @Rodic! Sorry! I missed that line. I just noticed your project was different than the other ones and thought it was a different page. Thanks for setting me straight! =)

**Comment by Rodic** [comment]
No problem :)

**Pull request merged**
