### PR TITLE
Update link in ### Practice

### PR DESCRIPTION
**Pull request by MicoPham**
The url (https://repl.it/community/classrooms/34425) in section ### Practice keeps redirecting to https://repl.it/talk/all. Need to find an updated link to classroom or delete this section? Admins, please advise.

-Michael

### CODE REVIEW

**Comment by I3uckwheat** [comment]
@MicoPham I am working on this, I will have it fixed today:

Here's the first three exercises if you could test them and let me know if you run into any issues

https://repl.it/@I3uckwheat/troubleshooting#test.js
https://repl.it/@I3uckwheat/enter-a-number#script.js
https://repl.it/@I3uckwheat/lets-do-some-math#index.js

**Comment by MicoPham** [comment]
Yes sir. Will start on them now.

**Comment by MicoPham** [comment]
First link on "troubleshooting" checks out.
Third link on "lets-do-some-math" checks out.

Second link on "enter-a-number", should edit this part in scripts.js, 

"then if that number is `6`, it returns **`false`** otherwise it returns **`true`**" 

to

 "then if that number is `6`, it returns `true` otherwise it returns `false`". 




-Michael

**Comment by I3uckwheat** [comment]
> First link on "troubleshooting" checks out.
> Third link on "lets-do-some-math" checks out.
> 
> Second link on "enter-a-number", should edit this part in scripts.js,
> 
> "then if that number is `6`, it returns **`false`** otherwise it returns **`true`**"
> 
> to
> 
> "then if that number is `6`, it returns `true` otherwise it returns `false`".
> 
> -Michael

I have fixed these, thank you for checking it out! I will have the 4th one done soon today. It needs some more work to make beginner friendly.

**Comment by MicoPham** [comment]
As a beginner, I will try my best to contribute. lol. lmk

**Comment by I3uckwheat** [comment]
Fixed in #21743

**Pull request closed without merging**
