### PR TITLE
Ruby - Advanced topic: Updated links to become more descriptive

### PR DESCRIPTION
**Pull request by ItsTosh**
## Because
- Links should be sufficiently descriptive for accessibility

## This PR
- Updated the links in the [Advanced Topics](https://www.theodinproject.com/lessons/ruby-on-rails-advanced-topics) section of the Rails Pathway.
- Change the link text in line 265 by removing "this" outside of the link text
- Change the link text in line 320-324 by removing the asterisk which emboldens the first letter 
- Change the link text in line 328 by improving the conciseness of the sentence
- Change the link text in line 235 by removing "this" outside of the link text
- Change the link text in line 346 by improving clarity of the sentence
- Change the link text in line 347 by removing "this" outside of the link text 
- Change the link text in line 371& 374 by improving clarity of the sentence 

## Issue
Related to [#28290](https://github.com/TheOdinProject/curriculum/issues/28290)

## Additional Information

N/A

## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project curriculum contributing guide](https://github.com/TheOdinProject/curriculum/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [x] The `Because` section summarizes the reason for this PR
-   [x] The `This PR` section has a bullet point list describing the changes in this PR
-   [x] If this PR addresses an open issue, it is linked in the `Issue` section
-   [x] If any lesson files are included in this PR, they have been previewed with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure it is formatted correctly
-   [x] If any lesson files are included in this PR, they follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

### CODE REVIEW

**Review by JoshDevHub — COMMENTED** [review]
Looks good. Thank you for doing this @ItsTosh 

Would you be okay with fixing the remaining lint issues in this lesson? They weren't introduced by you, and you don't have to fix them if you don't want. But they all seem pretty straightforward to fix. Just have to change the code examples from using `~` to ```.

But if you don't want to do it just let me know and I'll go forward with approving and merging this as is.

**Comment by ItsTosh** [comment]
I'll give it a shot and see what I can do! I'll get back to you as soon as I can and let you know.

**Comment by MaoShizhong** [comment]
A heads up that the CONTRIBUTING.md file in this repo has instructions for local linting and fixing, where our scripts should be able to fix almost all of the issues flagged. There may be a TOP004 "Required headings structure" still present which can be left as is, but the code blocks, anchor links etc. should be fixable in one or two runs of the fix:lesson script.

**Comment by ItsTosh** [comment]
I think I did it! Do I need to create a new pull request or is that fine?

**Review by JoshDevHub — APPROVED** [review]
Keeping it in this PR is perfectly fine. Nice work, and thank you for contributing :raised_hands:

**Pull request merged**
