### PR TITLE
Node Routes: Restructure routers section with task

### PR DESCRIPTION
**Pull request by MaoShizhong**
## Because

One of #28665's aims is to improve the flow between our Express lessons and can achieve this by continuing from code from previous lessons. Therefore, the Routes lesson ought to adapt its language to also build off the basic Express app code introduced in the Intro to Express lesson.

That will allow the Controllers lesson to reference that code which learners should then have available if they were coding along.

## This PR

- Restructures "Routers" section to include a task to extend the basic Express app code with routers.
  - Changes order of code examples introduced.
  - Moves path extending info to main lesson text.
  - Links to Postman so learners can test non-GET routes.

## Issue

N/A

## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project curriculum contributing guide](https://github.com/TheOdinProject/curriculum/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [x] The `Because` section summarizes the reason for this PR
-   [x] The `This PR` section has a bullet point list describing the changes in this PR
-   [x] If this PR addresses an open issue, it is linked in the `Issue` section
-   [x] If any lesson files are included in this PR, they have been previewed with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure it is formatted correctly
-   [x] If any lesson files are included in this PR, they follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

### CODE REVIEW

**Comment by fcasibu** [comment]
Do you think it's better to name the files to like `authorRouter.js`, `bookRouter.js` instead of it being plural because it supposed to handle a "single" entity/model, if that makes sense

**Comment by MaoShizhong** [comment]
> Do you think it's better to name the files to like `authorRouter.js`, `bookRouter.js` instead of it being plural because it supposed to handle a "single" entity/model, if that makes sense, well to be fair the convention is not important but up to you and let me know what you think.

Good point

**Comment by fcasibu** [comment]
All good on this 👍 Will have to change my own PR as well.

**Review by 01zulfi — APPROVED** [review]
lgtm 🚀 

@fcasibu @MaoShizhong great work 🔥

**Pull request merged**
