### PR TITLE
hint about #deliver as prepare for rails5

### PR DESCRIPTION
**Pull request by dezerb**

### CODE REVIEW

**Comment by KevinMulhern** [comment]
Hey @dezerb, thanks for the pull request. I'm not sure about putting this in. Rails 5 hasn't released yet and the rest of the resources use rails 4. What do you guys think @eriktrautman, @muzfuz, @kriox26?

**Comment by muzfuz** [comment]
Don't know if it makes sense to anticipate an unreleased technology that is subject to change (however stable it might appear).

**Comment by eriktrautman** [comment]
Yes, I appreciate the hint but also lean away from inclusion just to reduce confusion.

**Comment by dezerb** [comment]
Ok you are probably right, it's to soon for that

**Comment by KevinMulhern** [comment]
It is an open issue https://github.com/TheOdinProject/curriculum/issues/2285 so we will keep on top of it. Thank you for taking the time to make this pull request though, and please don't let it discourage you from making any more.

**Pull request closed without merging**
