### PR TITLE
Int HTML & CSS : Added "which can be whatever name we want"

### PR DESCRIPTION
**Pull request by devnchill**
## Because

When i was studying this lesson i got confused if the names of these variables are already predifned like css functions ? And i was thinking i'll have to learn the names of those variables . So I thought informing about the naming custom properties would help me as i won't be stressed thinking i'll have to learn it and instead have my own names variables if the follow the correct syntax.

## This PR

+ Added "which can be whatever name we wan't" on line 33.

## Issue

Closes #XXXXX

## Pull Request Requirements

-   [X] I have thoroughly read and understand [The Odin Project curriculum contributing guide](https://github.com/TheOdinProject/curriculum/blob/main/CONTRIBUTING.md)
-   [X] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [X] The `Because` section summarizes the reason for this PR
-   [X] The `This PR` section has a bullet point list describing the changes in this PR
-   [ ] If this PR addresses an open issue, it is linked in the `Issue` section
-   [ ] If any lesson files are included in this PR, they have been previewed with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure it is formatted correctly
-   [ ] If any lesson files are included in this PR, they follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

### CODE REVIEW

**Review by MaoShizhong — CHANGES_REQUESTED** [review]
Original: #28800

You don't need to close a PR to make a change - you just need to commit and push any changes to that branch and it'll update the PR.

In this case, it seems an auto-formatter in your IDE has changed all of the `*` to `\*`, which *must* be changed back to `*`, i.e. get rid of the backslashes. When working on other public projects, make sure to disable any auto-formatters in your IDE in case it uses a different set of rules to what the project needs, like this one.

So you can just remove the backslashes, then commit and push to your `namingcustomproperties` branch then this PR will be updated with those changes.

**Comment by devnchill** [comment]
Okay !

**Comment by devnchill** [comment]
woah it worked like i just made changes to that branch and pr got updated as well ...

**Review by MaoShizhong — APPROVED** [review]

**Comment by MaoShizhong** [comment]
Yep, that's all a PR is. It's a request to pull code from a branch (in this case, your `namingcustomproperties` branch from your fork) to another branch (`main` in the upstream repo). So it just tracks that branch as you make changes to it.

**Pull request merged**
