### PR TITLE
Write frameworks and preprocessors lesson

### PR DESCRIPTION
**Pull request by msespos**
- [x] You have read [The Odin Projects Contributing Guide](https://github.com/TheOdinProject/curriculum/blob/main/CONTRIBUTING.md).
 - [x] The title summarizes the change and where it happened, for example: "Fixes punctuation in Clean Code lesson".
 - [ ] If the PR is related to an open issue, use a [relevant keyword](https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests) and reference it with the `#` sign and the issue number.
- [ ] If changes are requested, please make the changes in a timely manner. After you submit the changes, request another review from the maintainer (top right).

#### 1.Describe the changes made and include why they are necessary or important:

Latest version of the Frameworks and Preprocessors lesson

#### 2. Related Issue

None

### CODE REVIEW

**Comment by msespos** [comment]
This is the latest version, which has been edited for clarity but with no content changes.

**Comment by CouchofTomato** [comment]
@msespos Thanks

Discussed this and we're pretty sure the credit card thing has always been required. A warning should be sufficient to make clear that is needed and they should review the terms for themselves anyway

**Comment by msespos** [comment]
@CouchofTomato 

> @msespos Thanks
> 
> Discussed this and we're pretty sure the credit card thing has always been required. A warning should be sufficient to make clear that is needed and they should review the terms for themselves anyway

I think you meant to put this comment on my other PR (the Rails lesson)? There's nothing about credit cards in this lesson. I'll add the warning there if that's OK.

This is the PR I mean:
https://github.com/TheOdinProject/curriculum/pull/23149

Thanks!

**Comment by CouchofTomato** [comment]
lol yeah sorry mate. Got caught juggling too many different things 😆

**Comment by codyloyd** [comment]
your git history has gotten messed up here... which makes this PR weird.

To fix: pull a fresh copy of the main branch, create a NEW branch off of main and then copy/paste this updated text into the existing lesson file... THEN PR the new branch.

**Comment by codyloyd** [comment]
going to close this PR ... ping me when the new one is ready.

**Pull request closed without merging**
