### PR TITLE
Added knowledge checks and links for Objects and Object constructors

### PR DESCRIPTION
**Pull request by jtcaovan**
- [x] You have read [The Odin Projects Contributing Guide](https://github.com/TheOdinProject/curriculum/blob/main/CONTRIBUTING.md).

#### 1.Describe the changes made:

 Added knowledge checks and links to 'Objects and Object constructors'

#### 2. If this PR is related to an open issue please reference it with the `#` operator and the issue number below:

#22472

### CODE REVIEW

**Comment by ZachBaird** [comment]
Hey @jtcaovan , looks awesome. Can you just run through the knowledge-check links and add `class="knowledge-check-link"`? That style was added into the site for us to use.

**Comment by Maheshkumar-novice** [comment]
Hey, Just to Know, Don't we need to close the <a> tag?

**Comment by jtcaovan** [comment]
Hi @Maheshkumar-novice, yes the <a> tag does need to be closed. I noticed my error when I was adding the classes. Thanks for pointing it out!

**Comment by jtcaovan** [comment]
Hi @ZachBaird, I know you mentioned a creating a new PR as each section is completed. Sorry still learning the workflow, I just pushed two changes to one PR. For future reference, should I be creating a new branch for each new change?

**Review by ZachBaird — APPROVED** [review]
LGTM, gonna test this at some point and merge once I do, unless someone else on the team beats me to it.

**Comment by ZachBaird** [comment]
@jtcaovan It's up to you really. I'd suggest doing new branches only so that you can work on different sections as you go, and they aren't reliant on each other. That way you don't have to wait for say this PR to be approved, and later PRs can be approved or worked on independently of each other.

**Review by wise-king-sullyman — APPROVED** [review]
Looks great, thanks for your contribution!

**Pull request merged**
