### PR TITLE
 Foundation - Flexbox - Axes: fix shows code before code - Fix issue #27901

### LINKED ISSUE #27901: Foundation - Axes: shows code before code
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [x] Would you like to work on this issue?

### Describe your suggestion

There is some code showing before the 
".flex-container {
  flex-direction: column;
}"
part, it shows:
`</span>`
Screenshot_2024-04-30_14-58-31

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-axes

### (Optional) Discord Name

_No response_

### (Optional) Additional Comments

_No response_

### PR DESCRIPTION
**Pull request by NexusHiveMind**
## Because
There was a small issue of some code showing as '</span>', that is reflected in Issue #27901 I created a fix.

## This PR
-Remove the <span id='flex-vertical'> and </span> on lines 15 and 17 of foundations/html_css/flexbox/flexbox-axes.md entirely.
-Change the link fragment on line 54 from #flex-vertical to #axes, as recomended by MaoShizhong.

## Issue

Closes #27901

## Pull Request Requirements

-   [x ] I have thoroughly read and understand [The Odin Project curriculum contributing guide](https://github.com/TheOdinProject/curriculum/blob/main/CONTRIBUTING.md)
-   [x ] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [ x] The `Because` section summarizes the reason for this PR
-   [ x] The `This PR` section has a bullet point list describing the changes in this PR
-   [x ] If this PR addresses an open issue, it is linked in the `Issue` section
-   [x ] If any lesson files are included in this PR, they have been previewed with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure it is formatted correctly
-   [x ] If any lesson files are included in this PR, they follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

### CODE REVIEW

**Review by MaoShizhong — CHANGES_REQUESTED** [review]
Thanks @NexusHiveMind. Could you also remove the blank lines 17-18 as well please? There should only be a single blank line between "segments", and the removal of the closing span tag has left us with 3.

A note for future PRs, you will want to keep your fork's `main` branch untouched other than updating to keep it in sync with upstream (TOP's repo).
If you make changes to your main branch, you will have a lot of trouble if you needed to work on different things, as you'll now have unrelated changes getting in the way which can become a serious nightmare to resolve.

For future PRs, you will want to follow the [branch workflow](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md#working-on-an-issue) from our contributing guide, and have all work for a single PR in a new branch coming off main. If you then need to work on a different thing, you checkout back to main, update main if yuo need to, then make a new branch off main to keep it separate from the other branch.

**Review by NexusHiveMind — COMMENTED** [review]
Ok, perfect, I understand your comments and I had re-read the Branch workflow. Thank you.

**Review by MaoShizhong — APPROVED** [review]
:rocket:

**Comment by NexusHiveMind** [comment]
I pushed the correction to the main branch again, as I understand that the pull request will be updated from it. But I'll keep in mind to make my own branch for next time. Thank you for the patience.

**Pull request merged**
