### PR TITLE
Added rock-paper-scissors solution

### PR DESCRIPTION
**Pull request by tim87henry**
This is a PR template. If you are adding a solution link to the curriculum, leave this as is. If not, delete it and write the message you wish.

Thank you,

The Odin Project team.

### CODE REVIEW

**Comment by marvingay** [comment]
@tim87henry Hello.

Your solution on github pages doesn't work. If you refer to the console, the code itself contains a bug. 

This pull request will be closed for your convenience, you may re-submit once everything is functioning right. (Don't forget to make sure your fork is up to date!)

Thank you!

**Comment by tim87henry** [comment]
Hi,

Sorry for asking this. But, I didn't really find any bug with my solution(https://tim87henry.github.io/rock_paper_scissors/). I tried it on 3 different browsers. The only Warning I got was on Chrome. But that was a "DevTools failed to load SourceMap: Could not load content for chrome-extension.." error, not in my code.
Can you please let me know if you meant another bug in the code/logic?

Thanks!!

**Comment by marvingay** [comment]
@tim87henry Strange. I think it's due to the lack of input validation. I'll merge it. Apologies!

**Comment by tim87henry** [comment]
@marvingay Ah, I get it. Yeah, probably because the console wasn't open at first and you had to cancel the input. I should see if there is a way around that, as I learn more.

Thanks for your response mate!!

**Pull request merged**
