### PR TITLE
Google-Homepage Project

### PR DESCRIPTION
**Pull request by jlampe1985**
Sorry about the excess commits. Still getting used to git. :)

### CODE REVIEW

**Comment by craftykate** [comment]
No worries. =) If you want an easy way to add your solution that doesn't involve too much fuss you can look here: http://bit.ly/odin-solutions

**Comment by jlampe1985** [comment]
Just wondering how long does it take before the addition becomes live?


On Wed, Mar 25, 2015 at 8:49 AM, Kate McFaul <notifications@github.com>
wrote:

> No worries. =) If you want an easy way to add your solution that doesn't
> involve too much fuss you can look here: http://bit.ly/odin-solutions
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/TheOdinProject/curriculum/pull/1292#issuecomment-86091293>
> .
>



-- 

John Lampe, Digital Marketing Associate

Office: 559.737.6400

Lampe Chrysler Dodge Jeep Ram

**Comment by craftykate** [comment]
The website should update overnight, so it should be up tomorrow.

**Comment by jlampe1985** [comment]
Thanks! Good to know!

**Pull request merged**
