### PR TITLE
Javascript Conclusion: Update link text 

### PR DESCRIPTION
**Pull request by SeanAverS**
## Because
Update the link text to be more descriptive. 

## This PR
- Replace link text on line 9 

## Issue
Related to #27819 

## Pull Request Requirements
-   [x] I have thoroughly read and understand [The Odin Project curriculum contributing guide](https://github.com/TheOdinProject/curriculum/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [x] The `Because` section summarizes the reason for this PR
-   [x] The `This PR` section has a bullet point list describing the changes in this PR
-   [x] If this PR addresses an open issue, it is linked in the `Issue` section
-   [x] If any lesson files are included in this PR, they have been previewed with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure it is formatted correctly
-   [x] If any lesson files are included in this PR, they follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

### CODE REVIEW

**Review by MaoShizhong — CHANGES_REQUESTED** [review]
Thanks for these changes @SeanAverS.

A couple of small extra things needing done:

1. It looks like both for #28071 and this PR, you created your branch off *the previous branch*, as opposed to checking out to `main` then making a new branch off `main`. Because you branched off the previous branch, this branch includes the commits from the previous branches - as you can see, `more_testing.md` and `testing_basics.md` from previous PRs made their way into this diff.
   - To make this instance easier to fix, I've closed the `more_testing.md` PR, since it's already here. In the future, when you make a new branch for a different PR, you'll want to `git checkout main` *before* you create a new branch (so the branch comes off `main` instead, and is unrelated to your other branch).
2. Would you mind fixing the remaining linting errors for `more_testing.md` only? You should be able to address these by doing the following:
   - Follow the [local linting instructions](https://github.com/TheOdinProject/curriculum/blob/main/CONTRIBUTING.md) to set up then run `npm run fix:lesson -- javascript/testing_javascript/more_testing.md` **twice**. Twice, because some of the issues won't be fixable until a first run fixes another error first.
   - After running that twice, change the assignment ordered list prefixes all to use just `1.` (so no `2.` or `3.` - all just use `1.` instead) - we don't (yet) have an auto-fixer for that so you'll have to manually change them. That *should* be the end of all linting errors in `more_testing.md`.
   - Don't worry about linting errors in other files.

Let me know if you have any issues.

**Comment by SeanAverS** [comment]
Thank you for your feedback and closing the `more_testing.md` PR @MaoShizhong 

My mistake not switching to `main` before creating a new branch. Will be sure to not do that in the future. 

Regarding the remaining `more_testing.md` linting errors, I will be happy to work on them. Will let you know if I have any issues. :v:

**Comment by SeanAverS** [comment]
Hi @MaoShizhong 

After creating a new branch from `main` and running `npm run fix:lesson -- javascript/testing_javascript/more_testing.md` twice, my changes to the text links were gone. I then changed the text links and there were no more linting errors. 

Would it be okay to include the text link changes in this PR? I will make a note of it in the description. Please let me know if any adjustments are needed. Thanks.

**Comment by MaoShizhong** [comment]
Oh, you didn't need to create a new branch this time, I was just saying that for future PRs (else those PRs' branches will have old commits like these ones contaminating them).

You just need to do the steps in step 2 of my message above to this PR's branch, and that'll solve the issues present here. No need to make a new branch and new PR.

**Review by MaoShizhong — APPROVED** [review]
:fire:
Many thanks for getting these all sorted!
Now you can delete this branch (remote and local).
For future PRs, you'll want to make a new branch **off `main`**, so the process would be
1. Checkout to `main`
2. Update your local fork's `main`
   1. `git fetch upstream main`
   2. `git merge upstream/main`
3. Create and checkout to a new branch (which will now be off `main` and also with the latest updates)

**Pull request merged**
