### PR TITLE
Surround html tags with lines to follow lint

### PR DESCRIPTION
**Pull request by asdacosta**
## Because

Multiline HTML tags should be surrounded by blank lines or code block delimiters

## Issue

Closes #XXXXX

## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project curriculum contributing guide](https://github.com/TheOdinProject/curriculum/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [x] The `Because` section summarizes the reason for this PR
-   [x] The `This PR` section has a bullet point list describing the changes in this PR
-   [x] If this PR addresses an open issue, it is linked in the `Issue` section
-   [x] If any lesson files are included in this PR, they have been previewed with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure it is formatted correctly
-   [x] If any lesson files are included in this PR, they follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

### CODE REVIEW

**Review by wise-king-sullyman — CHANGES_REQUESTED** [review]
Thanks for putting this PR together!

Looks like there are another couple of lint errors being thrown, can you fix those? After that this should be good to go.

**Comment by asdacosta** [comment]
> Thanks for putting this PR together!
> 
> Looks like there are another couple of lint errors being thrown, can you fix those? After that this should be good to go.

I dont understand those two lint errors. Kindly fix those.

**Comment by Asartea** [comment]
@wise-king-sullyman I think those are known lint errors, resulting from the unorthodox structure of the installation lessons, which don't neatly fit the normal structure of a lesson. I think there was discussion about changing them to the "proper" lesson style at some point, but I'm not sure where/what the conclusion ended up being

**Comment by asdacosta** [comment]
> @wise-king-sullyman I think those are known lint errors, resulting from the unorthodox structure of the installation lessons, which don't neatly fit the normal structure of a lesson. I think there was discussion about changing them to the "proper" lesson style at some point, but I'm not sure where/what the conclusion ended up being

Oh Ok. But I still don't get the defined structure it is supposed to follow. You're the boss, so please do what you think has to be done or you can proceed to merge if there is not a precise conclusion for that like you said.

**Review by MaoShizhong — COMMENTED** [review]
In regards to the "Required heading structure" error, that comes from most of the headings after the assignment being the wrong level. The top of the file has a markdownlint-disable comment, but it mistakenly disables MD043, which we don't actually use. Instead, it should disable TOP004.

As per [#27960](https://github.com/TheOdinProject/curriculum/pull/27960#discussion_r1598394832), this whole thing is something we need to revisit later on and restructure these installation steps, but that's currently low priority given other stuff we need to focus on. So for now, the beste would be to change the MD043 disabling to TOP004, then also add a TODO comment at the top. Let's use the ones that are in the existing PSQL installation lessons. @asdacosta please replace the markdownlint-disable comment and the top with the following:

```md
<!-- TODO: Revisit lesson/heading structure to remove need to disable rules -->
<!-- markdownlint-disable MD024 TOP004 -->
```

As for the note box, we could probably remove the heading then return the note box to where it was in the introduction section (the level 4 heading is what's triggering the error). Technically we could just move it somewhere like just below the Assignment section (and leave the heading in), but I feel it's more visible at the top of the lesson.

**Comment by asdacosta** [comment]
> In regards to the "Required heading structure" error, that comes from most of the headings after the assignment being the wrong level. The top of the file has a markdownlint-disable comment, but it mistakenly disables MD043, which we don't actually use. Instead, it should disable TOP004.
> 
> As per [#27960](https://github.com/TheOdinProject/curriculum/pull/27960#discussion_r1598394832), this whole thing is something we need to revisit later on and restructure these installation steps, but that's currently low priority given other stuff we need to focus on. So for now, the beste would be to change the MD043 disabling to TOP004, then also add a TODO comment at the top. Let's use the ones that are in the existing PSQL installation lessons. @asdacosta please replace the markdownlint-disable comment and the top with the following:
> 
> ```
> 
> 
> ```
> 
> As for the note box, we could probably remove the heading then return the note box to where it was in the introduction section (the level 4 heading is what's triggering the error). Technically we could just move it somewhere like just below the Assignment section (and leave the heading in), but I feel it's more visible at the top of the lesson.

I’m very confused. Can you please do it…

**Comment by MaoShizhong** [comment]
@asdacosta You know how you moved the lesson-note box from the introduction section to the lesson overview section?
Move it back to where it was in the introduction section, then get rid of the level 4 heading inside the lesson-note.

**Comment by asdacosta** [comment]
> @asdacosta You know how you moved the lesson-note box from the introduction section to the lesson overview section?
> Move it back to where it was in the introduction section, then get rid of the level 4 heading inside the lesson-note.

Alright. I think I did so in the last commit, so will deleting the last file revert the last commit changes or I need to manually change and commit?

**Comment by MaoShizhong** [comment]
However you do it is up to you, whether that's a revert commit or just manually changing.

**Comment by asdacosta** [comment]
> However you do it is up to you, whether that's a revert commit or just manually changing.

I just wanted to be sure as I’ve not used the delete method before.

**Comment by MaoShizhong** [comment]
@asdacosta I'm not sure why the lesson file was deleted? All that needed to be done was moving the lesson-note back to the introduction section and just removing its level 4 heading. We don't want to delete the entire lesson file.

**Comment by asdacosta** [comment]
> @asdacosta I'm not sure why the lesson file was deleted? All that needed to be done was moving the lesson-note back to the introduction section and just removing its level 4 heading. We don't want to delete the entire lesson file.

This is why I wanted to confirm before deleting. I thought that’d revert the last commit changes. So will making changes on the last but one commit being back the file?

**Comment by MaoShizhong** [comment]
I thought you were intending to just revert the previous commit, I didn't realise you thought you needed to actually delete the file to do so. You don't delete anything, you'd just use `git revert HEAD~1` to make a new revert commit that undoes the changes from the previous.

While we could try to walk through another revert, it would probably be easiest in your case to do a fresh PR. Up to you

**Comment by asdacosta** [comment]
> I thought you were intending to just revert the previous commit, I didn't realise you thought you needed to actually delete the file to do so. Deleting the file won't "undo commits", it'll just do exactly that - delete the file. You don't delete anything, you'd just use `git revert HEAD~1` to make a new revert commit that undoes the changes from the previous.
> 
> While we could try to walk through another revert, it would probably be easiest in your case to do a fresh PR. Up to you

I prefer we do a revert instead of a new PR, so kindly show me how or if you could initiate the revert yourself that’d great as I’m new to this.

**Comment by MaoShizhong** [comment]
@asdacosta Personally, I would just do a new PR. It looks like you've been making these changes all via the GitHub interface as opposed to on your local machine using the Git CLI?

**Comment by asdacosta** [comment]
> @asdacosta Personally, I would just do a new PR. It looks like you've been making these changes all via the GitHub interface as opposed to on your local machine using the Git CLI?

Yes

**Comment by MaoShizhong** [comment]
> > @asdacosta Personally, I would just do a new PR. It looks like you've been making these changes all via the GitHub interface as opposed to on your local machine using the Git CLI?
> 
> Yes

It would be much easier to fix this by just opening a fresh PR, unless you're already comfortable with cloning this branch to your local machine and reverting last two commits locally before pushing back. A fresh PR would be by far the simplest otherwise.

**Comment by asdacosta** [comment]
> > > @asdacosta Personally, I would just do a new PR. It looks like you've been making these changes all via the GitHub interface as opposed to on your local machine using the Git CLI?
> > 
> > 
> > Yes
> 
> It would be much easier to fix this by just opening a fresh PR, unless you're already comfortable with cloning this branch to your local machine and reverting last two commits locally before pushing back. A fresh PR would be by far the simplest otherwise.

It already has conflicting files. I’m sure changes have been made to the original file so I might need to do a new PR.

**Pull request closed without merging**
