### PR TITLE
Remove broken link in Additional Resources

### PR DESCRIPTION
**Pull request by khopsickle**
The playlist "A Developer Tools Playlist" doesn't seem to exist anymore.

### CODE REVIEW

**Comment by khopsickle** [comment]
After reading through more of the on-boarding process, I'm not sure if this is the best way to point out a broken link.  Sorry if there's a better way!

**Comment by KevinMulhern** [comment]
Thanks for pointing out the broken link @khopsickle

**Comment by nhquiroz** [comment]
@khopsickle Maybe it's better using issues to report broken links :)

**Comment by khopsickle** [comment]
@nhquiroz probably a good idea, I didn't think about it much until after I did the pull request!

**Pull request merged**
