### PR TITLE
Rock paper scissors solution added

### PR DESCRIPTION
**Pull request by jamjamsnugglepuff**
This is a PR template. If you are adding a solution link to the curriculum, leave this as is. If not, delete it and write the message you wish.

Thank you,

The Odin Project team.

### CODE REVIEW

**Comment by ZachBaird** [comment]
Hey @jamjamsnugglepuff , it looks like your PR has some additional stuff. Ideally, there should be only 1 file changed with your student submission added to that file.

**Comment by jamjamsnugglepuff** [comment]
Hi Zach,

Thankyou was worried I think it had to do with me pulling from the upstream
branch
ill take a look at it and get back to you :)

Kind regards

Jayden

**Comment by marvingay** [comment]
Closing.

Lack of changes (3 days).

You're welcome to create another pull request, if you still need this solution displayed. Thank you!

**Comment by jamjamsnugglepuff** [comment]
Hi marvin,
I have been trying to figure out with this pull request i want to add in
two submissions
I have also attached a pdf to this email showing whats on my end
Kind regards
Jayden

*The two submissions i want to get pulled*

 *web_development_101/javascript_basics/project_etch_a_sketch.md
<https://github.com/TheOdinProject/curriculum/compare/master...jamjamsnugglepuff:master#diff-f6588fb38936c35a5a6a2140a807462d>

  * web_development_101/javascript_basics/project_rock_paper_scissors.md

*but for some reason it is showing up with a third submission *
*^C *<the name
[32mmaster [m
[31mremotes/origin/105ron-update-contributing [m
[31mremotes/origin/FCC-HTML [m
[31mremotes/origin/HEAD [m -> origin/master
[31mremotes/origin/I3uckwheat-patch-2 [m
[31mremotes/origin/chore/archive-introduction-to-rails-section [m
[31mremotes/origin/chore/archive-sinatra-lessons [m
[31mremotes/origin/chore/create-introduction-section-for-ruby [m
[31mremotes/origin/chore/fix-formatting-issues-with-new-ruby-lessons [m
[31mremotes/origin/chore/follow-up-to-new-ruby-lessons-being-released [m
[31mremotes/origin/chore/tweak-second-section-of-rails-course [m
[31mremotes/origin/chore/update-api-mailers-and-advanced-section-content [m
[31mremotes/origin/chore/update-content-in-active-record-basics-section [m
[31mremotes/origin/chore/update-content-in-forms-section [m

**Pull request closed without merging**
