### PR TITLE
Note about using login shell on Bash on Windows

### PR DESCRIPTION
**Pull request by waglebr**
```
This is a PR template, If you are adding a solution link to the curriculum leave this as is. If you are not, then delete it and write the message you wish.
Thank you,
The Odin Project team.

```

Note about using the login shell on Bash on Windows in order to get RVM running.

### CODE REVIEW

**Comment by waglebr** [comment]
Oh, it's important to highlight that configuration is done on the Bash **bold** shortcut **bold** properties.

**Comment by KevinMulhern** [comment]
Thanks @waglebr 😄 

This section is becoming very messy (not your fault) it reveals an interesting perspective on why windows and rails is a bad idea lol.

**Comment by waglebr** [comment]
Well, Bash on Windows is still beta, so I'm sure they still have a long way to go before making it fully functional, but honestly I'm loving it. About the section becoming messy, maybe you should consider putting all the info Windows related on separated page and leave just a link on the main page to those few (like me) that insist in using Windows. :D

**Comment by KevinMulhern** [comment]
Yeah I think we are going to separate out all the installation stuff in the near future. For example have one lesson about the different os choices in one lesson. Install ruby and the related stuff in a lesson at the start of the ruby course, all the rails related stuff at the beginning of the rails course etc. 

Thanks again for doing this 👍

**Pull request merged**
