### PR TITLE
Remove broken student solutions links, add mine

### PR DESCRIPTION
**Pull request by littlemighty**

### CODE REVIEW

**Comment by KevinMulhern** [comment]
Hey @littlemighty, I am going to hold off merging this until I see what the other Mod's think about deleting broken student submission links. I should have an answer for you by tomorrow hopefully :)

**Comment by kriox26** [comment]
Just checked, all removed links are broken. What do you say @KevinMulhern ? Until I have the script ready we could accept this type of PRs :+1:

**Comment by KevinMulhern** [comment]
Yeah sounds good to me :+1:  @kriox26

**Comment by littlemighty** [comment]
No worries, thanks guy's.

**Pull request merged**
