### PR TITLE
NodeJS Getting Started Lesson: Add Descriptive Link Text

### PR DESCRIPTION
**Pull request by ca-de-so**
## Because

Some of the link texts weren't descriptive enough and they also included the words `this` and `here` . These changes remedy these issues.

## This PR

1. Replaced link text to be more descriptive in the following lines in the markdown file : 
    - 33
    - 34
    - 37 
    - 40
    - 41
    - 43
    - 50
    - 73
    - 74
2. Line 45 in the markdown file had already been removed in a previous commit, so nothing more had to be done for that.
3. Removed the following lines from the markdown file entirely :
    - 46
    - 47
4. Because of the changes mentioned in points 2 and 3, I had to remove the NPM part from the  Assignment section since it was empty after making all the suggested changes.

## Issue

Related to #27819

## Additional Information

N/A

## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project curriculum contributing guide](https://github.com/TheOdinProject/curriculum/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [x] The `Because` section summarizes the reason for this PR
-   [x] The `This PR` section has a bullet point list describing the changes in this PR
-   [x] If this PR addresses an open issue, it is linked in the `Issue` section
-   [x] If any lesson files are included in this PR, they have been previewed with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure it is formatted correctly
-   [x] If any lesson files are included in this PR, they follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

### CODE REVIEW

**Review by MaoShizhong — CHANGES_REQUESTED** [review]
Thanks @ca-de-so for fixing up the links and dealing with the removed parts too! :rocket:

Would you be happy to fix up the remaining lint errors?
First thing would be that the lesson-note div containing `### Important notice` should be moved to be inside and at the top of the `### Assignment` div, and the heading changed to level 4. i.e. as follows:

```md
### Assignment

<div class="lesson-content__panel" markdown="1">

<div class="lesson-note" markdown="1">

#### Important notice

Recently the NodeJS.dev team removed a large amount of content from their website. Several of those removed pages were linked to in this lesson. Until we find a replacement for that content we will be linking directly to the markdown files on their GitHub repository. The formatting may look a bit odd, but the content should still be just as good.

</div>

- Let's dive in and start looking at Node server-side code! We will be hopping around lessons in the [NodeJS.org](https://nodejs.org/en/learn) docs which you should follow along.
```

The rest of the lint errors should be somewhat self explanatory and you can follow the [curriculum repo contributing guide](https://github.com/TheOdinProject/curriculum/blob/main/CONTRIBUTING.md) for instructions on how to lint check locally, and auto-fix some errors. Not all errors will be fixed automatically so will just need to read the lint errors and manually fix them (note that sometimes blank lines aren't actually blank lines because they contain only spaces!)

Let me know if you run into any issues with this, or need further clarification!

**Comment by ca-de-so** [comment]
Yes, sorry about that. I'll make the necessary changes and submit for review again.

**Comment by ca-de-so** [comment]
Hey, I have fixed the lint errors.

**Review by MaoShizhong — APPROVED** [review]
Thank you again for getting these fixed up! :rocket:

**Comment by ca-de-so** [comment]
Hey, no problem, happy to be helping out.

**Pull request merged**
