### PR TITLE
Update project_html_css.md with my solution

### PR DESCRIPTION
**Pull request by SawyerMerchant**

### CODE REVIEW

**Comment by muzfuz** [comment]
Nice work.  Do you want to include this solution?

**Comment by SawyerMerchant** [comment]
Yes I do. Thank you.

**Comment by muzfuz** [comment]
Ok awesome, I'll add your solution just gotta do a bit of fiddling to make it happen now :+1: I will sort it out no probs - and in future just keep your issue open and we will get it sorted!

**Comment by SawyerMerchant** [comment]
Thank you!

**Pull request merged**
