### PR TITLE
JS Recursive Methods: Replace the medium article with better resources

### PR DESCRIPTION
**Pull request by silenceinspace**
## Because
The previous information about what users can read the article is irrelevant. Now one needs to pay for a subscription to access the article instead of just having a free account on Medium. If one doesn't have or want to subscribe to Medium, then it is better for them to be immediately aware if they are entitled to read the article or not. 

## This PR
Changes: 
<-- (Note: A free Medium account is required to read this article)
--> (Note: It is a member-only story so you need to have a medium subscription)

## Issue
Closes #XXXXX

## Pull Request Requirements
-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [x] The `Because` section summarizes the reason for this PR
-   [x] The `This PR` section has a bullet point list describing the changes in this PR
-   [ ] If this PR addresses an open issue, it is linked in the `Issue` section
-   [ ] If any lesson files are included in this PR, they have been previewed with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure it is formatted correctly
-   [ ] If any lesson files are included in this PR, they follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

### CODE REVIEW

**Comment by wise-king-sullyman** [comment]
I'm not against this PR, but I wonder if we might want to just remove this additional resource instead. I'm not a huge fan of us pointing to an article which requires learners sign up with Medium.

WDYT @TheOdinProject/javascript ?

**Comment by silenceinspace** [comment]
Thank you for looking into it, Austin. I think completely removing it makes sense. And to naturally bring in another issue I opened recently #26497, do you think it would be possible to replace the medium article with the video I proposed? 
If you do decide to remove the article, there might be a gap to fill in. The additional section in that lesson now features two other articles. Including another type of content such as a video might help to make it slightly better.

**Comment by wise-king-sullyman** [comment]
I was actually just looking at that issue!

Yeah unless another maintainer jumps in to object in the next day or two I would say lets just remove this resource. Even if we don't replace it with one you've put forward already (I'll leave my comments about those resources in that issue) I'm sure we can find something more accessible.

**Comment by KevinMulhern** [comment]
Looks like nobody objects 🎉  @silenceinspace are you still happy to remove or replace this resource?

**Comment by silenceinspace** [comment]
@KevinMulhern Glad to hear from someone inside this PR. I certainly am! It would be amazing if we could replace the article resource with my/another better option.

**Comment by KevinMulhern** [comment]
> It would be amazing if we could replace the article resource with my/another better option.

The resources you found look good to me - lets do it 🚀

**Pull request closed without merging**
