### PR TITLE
Common Data Structures And Algorithms lesson: Added an Item in Additional Resource Section

### PR DESCRIPTION
**Pull request by szmazhr**
Complete the following REQUIRED checkboxes:

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`

Complete the following checkboxes ONLY IF they are applicable to your PR. You can complete them later if they are not currently applicable:
-   [x] I have previewed all lesson files included in this PR with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure the Markdown content is formatted correctly
-   [x] I have ensured all lesson files included in this PR follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

<hr>

**1. Because:**

This seems great and latest addition in Additional Resources section of the lesson. 

**2. This PR:**

* Added a playlist of JavaScript Algorithms and Data Structures from Codevolution on YouTube, this seems great and latest addition in Additional Resources section of the Common Data Structures And Algorithms lesson.

**3. Additional Information:**

### CODE REVIEW

**Comment by wise-king-sullyman** [comment]
This resource looks interesting, thank you for PRing it and fixing the order of knowledge checks and additional resources!

We'll need some more time to be able to review this as there's quite a lot of material here, do you have any particular recommendations from the series? If so it might be better to call those out or link directly to them rather than linking to the whole playlist.

**Comment by szmazhr** [comment]
I found the whole playlist useful, and I personally watched all videos there in, It is little longer but great resource.

**Comment by zachmmeyer** [comment]
OK. I don't think this playlist is bad. What's stopping me from immediately approving this PR is two things:

1. There are a total of seven additional resources for this project
2. Three of them are courses

Just under half of the addition resource content for this lesson are full length courses. What you are suggesting is adding a fourth course on top of the three, in addition to the seven total resources.

The ideal amount of additional resources has historically been a number between four and six, and typically not so many full length courses.

If I were to ask you to not only put your course at the bottom of the list, I would have to ask you to substitute out another resource and tell us why.

I brought up a brief idea on how to help this in future, and it's a rather large undertaking, but until then it's going to have to be something that you, the contributor, has to figure out.

It's up to you if you want to make those changes.

**Review by wise-king-sullyman — CHANGES_REQUESTED** [review]
@szmazhr after reviewing the playlist I actually would suggest that we place it at the end of the knights travails project since several of the data structures it explains are projects in the CS section.

It should be done in a manner similar to what we see at the end of [the todo list project](https://www.theodinproject.com/lessons/node-path-javascript-todo-list#want-more-practice).

**Comment by szmazhr** [comment]
> @szmazhr after reviewing the playlist I actually would suggest that we place it at the end of the knights travails project since several of the data structures it explains are projects in the CS section.
> 
> It should be done in a manner similar to what we see at the end of [the todo list project](https://www.theodinproject.com/lessons/node-path-javascript-todo-list#want-more-practice).

oh yes, that will be better. I will try to make required changes soon.

**Comment by zachmmeyer** [comment]
Closing due to staleness. If you'd like to work more on this PR, we'd be more than happy to reopen it.

**Pull request closed without merging**
