### PR TITLE
Computer basics: Update sections as per layout style guide

### PR DESCRIPTION
**Pull request by scottwright-dev**
## Because

Update the page as per the Odin Project style guide to improve consistency.

## This PR

Fixes the following: 

Lesson overview section
- Replaced * with a hyphen - for each list item.
- Added punctuation to list item containing a verb.

Assignment section
- Applied lazy numbering for list items.
- Added punctuation to list items containing a verb.

Additional resources section
- Changed "Checkout" to "Check out" for consistency in language.
- Added missing punctuation to the last line.

## Issue

Related to #26437

## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [x] The `Because` section summarizes the reason for this PR
-   [x] The `This PR` section has a bullet point list describing the changes in this PR
-   [x] If this PR addresses an open issue, it is linked in the `Issue` section
-   [x] If any lesson files are included in this PR, they have been previewed with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure it is formatted correctly
-   [x] If any lesson files are included in this PR, they follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

### CODE REVIEW

**Comment by ManonLef** [comment]
Thank you! Could you link to the related issue please? Thank for doing this.
Screenshot 2023-10-09 at 09 20 06

**Review by thatblindgeye — APPROVED** [review]
This looks good to me. The only thing for me personally is that having some list items end with punctuation and others not within the same list looks kind of *off*, but that could just be me. @ManonLef what do you think?

**Comment by scottwright-dev** [comment]
@thatblindgeye @ManonLef. I agree with the comment that it does look a little off. 

Please advise if you'd prefer me to rephrase the sentences to match the style guide or instead just add/remove the punctuation accordingly from that specific list and I can amend it.

**Comment by ManonLef** [comment]
I agree. We have rules on punctuation in lists in our style guide. But since this is the assignment section, and we also want descriptive links, perhaps we could change this to the regular assignment format like: 

> read [this article about what a computer is](link).

That makes them all entire sentences that need to include punctuation as well.

**Comment by scottwright-dev** [comment]
Hi, @ManonLef & @thatblindgeye. I've made the necessary changes and updated the commit as per the discussion. Please let me know if any further adjustments are needed! Many Thanks.

**Comment by ManonLef** [comment]
Thank you @scottwright-dev 

It's not what I had in mind entirely but maybe I should have given a better example. I'd prefer to then wait and see what @thatblindgeye has to say about my proposal since it would involve changing the sentences. 

Current:

1. [What is an operating system?](https://edu.gcfglobal.org/en/computerbasics/understanding-operating-systems/1/)
1. [What is an application?](https://edu.gcfglobal.org/en/computerbasics/understanding-applications/1/)
1. [Open source vs closed source software.](https://edu.gcfglobal.org/en/basic-computer-skills/open-source-vs-closed-source-software/1/)


My proposed change:

1. Read [this article about what an operating system is](https://edu.gcfglobal.org/en/computerbasics/understanding-operating-systems/1/).
1. Next, read [this article about applications](https://edu.gcfglobal.org/en/computerbasics/understanding-applications/1/).
etc.

**Comment by thatblindgeye** [comment]
Yeah this is tough... I almost feel like if every list item is literally just a link (like in the Assignment here), then mixing punctuation and no punctuation doesn't look as bad to me since in this case we're providing the article title as the link text. Otherwise if it's just text and one or more list items wouldn't receive end punctuation, don't add end punctuation to any list items in that list.

I don't think that helps with making it any less confusing 😆

**Comment by scottwright-dev** [comment]
Hi @ManonLef  / @thatblindgeye ,

I just wanted to follow up on this pull request. If there's anything else needed from my side or if you have additional feedback on the changes, please let me know. Thanks for taking the time to review and for your guidance throughout this process.

Best,

Scott

**Comment by thatblindgeye** [comment]
@scottwright-dev I'm going to merge this as is for now. We can iterate if needed, but I don't think its worth holding this PR up any longer for. Thank you for making these updates!

**Comment by scottwright-dev** [comment]
No problem. Enjoy your weekend @thatblindgeye!

**Pull request merged**
