### PR TITLE
Add helpful additional resource link regarding for loops in JS

### PR DESCRIPTION
**Pull request by JohnKeysCloud**
## Because
I was having issues understanding how for loops work. This article breaks down how they work while solving a problem that can be found in the tasks section of https://javascript.info/while-for

## This PR
- add [https://medium.com/@cyclonestudios/loop-ception-breaking-down-nested-for-loops-in-javascript-e3387ca1d6fc](url) link to additional resources section 

## Issue

Closes #XXXXX

## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [x] The `Because` section summarizes the reason for this PR
-   [x] The `This PR` section has a bullet point list describing the changes in this PR
-   [x] If this PR addresses an open issue, it is linked in the `Issue` section
-   [x] If any lesson files are included in this PR, they have been previewed with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure it is formatted correctly
-   [x] If any lesson files are included in this PR, they follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

### CODE REVIEW

**Review by fortypercenttitanium — APPROVED** [review]
Thanks!

**Review by fortypercenttitanium — CHANGES_REQUESTED** [review]
Actually, I think this resource would be better in the previous lesson where we teach about loops! https://github.com/TheOdinProject/curriculum/blob/main/foundations/javascript_basics/fundamentals-4.md

**Comment by JohnKeysCloud** [comment]
I agree. I think it should help a lot for those having trouble understanding them :)

**Comment by JohnKeysCloud** [comment]
I believe the pull request was made in the requested lesson :) (Fundamentals 4)

**Comment by Iswanna** [comment]
This link really helped when I was trying to understand for... Loop

**Comment by fortypercenttitanium** [comment]
> I believe the pull request was made in the requested lesson :) (Fundamentals 4)

I'm having a hard time finding it, can you link?

**Comment by fortypercenttitanium** [comment]
> I believe the pull request was made in the requested lesson :) (Fundamentals 4)

@JohnKeysCloud I'm having a hard time finding it, can you link?

**Pull request closed without merging**
