### PR TITLE
Add my solution to the HTML/CSS exercise

### PR DESCRIPTION
**Pull request by chenghw**

### CODE REVIEW

**Comment by KevinMulhern** [comment]
Hi, can you remove the blank line above your solution please.

**Comment by chenghw** [comment]
Hi Kevin,

Sorry this is my first time using GitHub and contributing. I tried editing and deleting any spacing in-between my line of 338 and the line above mine (337). Please let me know if this fixed the problem.

Thanks,
Ho Won

**Comment by KevinMulhern** [comment]
Hi,
That didn't do it, but don't worry about it I will fix it :)

**Comment by KevinMulhern** [comment]
Just had another look at it, You did fix it :)

**Comment by chenghw** [comment]
Awesome, thanks!

On Wed, Jun 10, 2015 at 3:10 PM, Kevin Mulhern <notifications@github.com>
wrote:

> Just had another look at it, You did fix it :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/TheOdinProject/curriculum/pull/1706#issuecomment-110881627>
> .
>



-- 
Ho Won Cheng
Carnegie Mellon University 2010
B.S. Decision Science

**Comment by chenghw** [comment]
Awesome, thanks!

**Pull request merged**
