### PR TITLE
Addin solution link to the project_etch_a_sketch.md file

### PR DESCRIPTION
**Pull request by Cesar-rdgz**
This is a PR template. If you are adding a solution link to the curriculum, leave this as is. If not, delete it and write the message you wish.

Thank you,

The Odin Project team.

### CODE REVIEW

**Comment by ZachBaird** [comment]
Hey @Cesar-rdgz ! It looks like some additional mark down files are in this pull request. Could you remove those so we're only getting the project_etch_a_sketch.md with your solution in it?

**Comment by Cesar-rdgz** [comment]
> Hey @Cesar-rdgz ! It looks like some additional mark down files are in this pull request. Could you remove those so we're only getting the project_etch_a_sketch.md with your solution in it?

It looks like it's already.

**Comment by I3uckwheat** [comment]
@Cesar-rdgz I have removed the extra files this time. Make sure you're being very careful with what you are committing. Extra files could possibly contain information you do not want to share.

**Comment by Cesar-rdgz** [comment]
> @Cesar-rdgz I have removed the extra files this time. Make sure you're being very careful with what you are committing. Extra files could possibly contain information you do not want to share.

Thanks, sure I will do.

**Pull request merged**
