### PR TITLE
Update transforms.md

### PR DESCRIPTION
**Pull request by sapienfrom2000s**
Makes false claim about chain transformation

## Because
It makes a false claim about chain transformations.

## This PR
Removes a stanza from the lesson.

## Issue

Closes #XXXXX

## Additional Information
The following sentence is taken from codepen article which makes the false claim._The end result relatively to the original element is exactly the same for both of these interpretations and this is true for any list of transforms, even with more than 2 transforms_.

## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [x] The `Because` section summarizes the reason for this PR
-   [x] The `This PR` section has a bullet point list describing the changes in this PR
-   [x] If this PR addresses an open issue, it is linked in the `Issue` section
-   [x] If any lesson files are included in this PR, they have been previewed with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure it is formatted correctly
-   [x] If any lesson files are included in this PR, they follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

### CODE REVIEW

**Comment by fabulousgk** [comment]
So your solution is to completely remove the article?  THis make no sense to me.

**Comment by fabulousgk** [comment]
I also dont see that line as being false.

**Comment by sapienfrom2000s** [comment]
Order of transformation matters in the lesson wheras the article contradicts it by saying it doesn't matter.

**Comment by fabulousgk** [comment]
The lesson also says there is some disagreement on that and provides the article to clarify

**Pull request closed without merging**
