### PR TITLE
Add HTML Attributes Section: HTML-Foundations

### PR DESCRIPTION
**Pull request by Fiattarone**
Added a small section on HTML attributes to smooth the lesson's transition into HTML.

Complete the following REQUIRED checkboxes:

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`

Complete the following checkboxes ONLY IF they are applicable to your PR. You can complete them later if they are not currently applicable:
-   [ ] I have previewed all lesson files included in this PR with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure the Markdown content is formatted correctly
-   [ ] I have ensured all lesson files included in this PR follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

<hr>

**1. Because:**

Closes #XXXXX
Just wanted to add some deeper insight into the functionality of HTML and help smooth the transition of the lesson. 

**2. This PR:**

- Add Knowledge Check section
- Add HTML Attributes lesson topic/section 

**3. Additional Information:**

### CODE REVIEW

**Comment by Fiattarone** [comment]
Hey, is there supposed to be a <span id=""> that I can link my anchor's href to for my edited knowledge check?

**Comment by KevinMulhern** [comment]
Thanks for putting this together @Fiattarone, However, I think we should leave the explanation of html attributes until the later [images lesson](https://www.theodinproject.com/lessons/foundations-links-and-images) where leaners will absolutely need to know what attributes are. 

There is already quite a bit for learners to take in with this boilerplate lesson, and I think attributes is out of scope of what this lesson is teaching. Happy to discuss further if you wish.

**Comment by Fiattarone** [comment]
I agree, some of these PRs were made without knowledge of the subsequent lessons. Should I move this to the images lesson?

**Comment by Fiattarone** [comment]
> Thanks for putting this together @Fiattarone, However, I think we should leave the explanation of html attributes until the later [images lesson](https://www.theodinproject.com/lessons/foundations-links-and-images) where leaners will absolutely need to know what attributes are.
> 
> There is already quite a bit for learners to take in with this boilerplate lesson, and I think attributes is out of scope of what this lesson is teaching. Happy to discuss further if you wish.

Hey @KevinMulhern , let me know if I should move this or if it's best to just close this PR. Thanks again!

**Comment by KevinMulhern** [comment]
Sorry for not getting back to you sooner @Fiattarone.

We have an explanation about attributes in the links and images lesson under this section: https://www.theodinproject.com/lessons/foundations-links-and-images#anchor-elements

But it could maybe be improved or made more visible?

**Comment by thatblindgeye** [comment]
@Fiattarone Just wanted to checkin to see if you had wanted to look into making the above update, or if you feel it'd be better to close this out?

**Comment by KevinMulhern** [comment]
Closing due to inactivity...

**Pull request closed without merging**
