### PR TITLE
[Ruby] Basic Data Types: Update link from web archive to the new one

### PR DESCRIPTION
**Pull request by kapustindev**
## Because

This PR is a minor fix for a link that currently points to web.archive.org. It appears that the original link did not provide a 301 redirect to the new page, which uses hyphens instead of underscores in the URL. This fix ensures that the link directs to the correct location without relying on web.archive.org.

## This PR

- The link has been replaced from the web archive to the original source.

## Issue

A simple change that is not part of an existing issue

## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [x] The `Because` section summarizes the reason for this PR
-   [x] The `This PR` section has a bullet point list describing the changes in this PR
-   [ ] If this PR addresses an open issue, it is linked in the `Issue` section
-   [x] If any lesson files are included in this PR, they have been previewed with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure it is formatted correctly
-   [x] If any lesson files are included in this PR, they follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

### CODE REVIEW

**Review by JoshDevHub — COMMENTED** [review]
Looks good @kapustindev :raised_hands: 

Before I merge, there are a number of lint errors in this file. They weren't introduced by you, and you shouldn't feel obligated to fix them if you don't want to. But if you do want to, you can find them by clicking the 'Files changed' tab and looking through the right column of the diff. You can also read [the section on linting](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md#curriculum-linting) in our style guide if you want to learn how to view these errors in your local environment.

Anyways, if you want to fix them, just make additional commits to this branch to clean them up. If not, I can just merge your change. Let me know.

**Comment by kapustindev** [comment]
@JoshDevHub fixed most of the linter errors, leaving only those that could affect the site's styles (`no-emphasis-as-heading`) or are not quite relevant (`lesson-headings`):

- First one will replace strong tag with h5
- Learning outcomes seems more suitable for this page given its current structure

But if needed, I can also fix those.

Also, I didn't fix one error (`default-section-content`): Value of 'lineNumber' passed to onError by 'TOP003' is incorrect for './curriculum/ruby/basic_ruby/basic_data_types.md'. 

I couldn't find a solution for it. If you can explain the problem to me, I can address it as well.

**Comment by thatblindgeye** [comment]
@kapustindev that error regarding `value of lineNumber...` is due to how the rule is creating errors and how this particular lesson is structured, so nothing for you to update here. Can you just open a followup issue for this lesson to remove the nested lists in both the Knowledge check and Additional Resources sections?

**Review by JoshDevHub — APPROVED** [review]
Looks good to me. We'll use the issue you made to get the other problems with this lesson cleaned up.

Thank you for contributing.

**Pull request merged**
