### PR TITLE
Setting up Git: 3 improvements

### PR DESCRIPTION
**Pull request by nikitarevenco**
## Because

So I recently had to re-install my system, and needed to go through the installing git again. I was confused by a few points and wanted to improve the lesson.

## This PR

- Clarified that the learner needs to use a private email address if that's what they gave Github. I personally got confused with this so this is why I'm adding it.
- An example of a name that needs to be given. 
- Clarified that the fingerprint output in the terminal needs to match one of the 4 github's provided fingerprints. I was confused by this and thought that it needs to match the SSH key from previous steps (excluding the email)

## Issue

Closes #XXXXX

## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [x] The `Because` section summarizes the reason for this PR
-   [x] The `This PR` section has a bullet point list describing the changes in this PR
-   [x] If this PR addresses an open issue, it is linked in the `Issue` section
-   [x] If any lesson files are included in this PR, they have been previewed with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure it is formatted correctly
-   [x] If any lesson files are included in this PR, they follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

### CODE REVIEW

**Comment by fabulousgk** [comment]
>  Replace with your actual email, or a private one if that's what you used for `GitHub.

It does not matter what email address you use here, as this is just a comment on the key and has not functional bearing.  TBH I am not sure why we even include that in the instructions.  It creates so much confusion, I think we should completely drop it.

> Next, on the left-hand side, click `SSH and GPG keys`. Then, click the green button in the top right corner that says `New SSH Key`. Name your key something that is descriptive enough for you to remember where it came from, for example `linux-ubuntu`. Leave this window open while you do the next steps.

I actually think we should slightly tweak to..."enough for you to remember what device this SSH key came from"

This would clarify why you are using a name I think.

> You should see this response in your terminal: **Hi username! You've successfully authenticated, but GitHub does not provide shell access.** Don't let GitHub's lack of providing shell access trouble you. If you see this message, you've successfully added your SSH key and you can move on. If the output doesn't correctly match up, then try going through these steps again or come to [the Discord chat](https://discord.gg/fbFCkYabZB) to ask for help.

Should we include something about the fingerprint message the first time you ssh to github (or any server for that matter)?

**Comment by nikitarevenco** [comment]
> > Replace with your actual email, or a private one if that's what you used for `GitHub.
> 
> It does not matter what email address you use here, as this is just a comment on the key and has not functional bearing. TBH I am not sure why we even include that in the instructions. It creates so much confusion, I think we should completely drop it.
> 
> > Next, on the left-hand side, click `SSH and GPG keys`. Then, click the green button in the top right corner that says `New SSH Key`. Name your key something that is descriptive enough for you to remember where it came from, for example `linux-ubuntu`. Leave this window open while you do the next steps.
> 
> I actually think we should slightly tweak to..."enough for you to remember what device this SSH key came from"
> 
> This would clarify why you are using a name I think.
> 
> > You should see this response in your terminal: **Hi username! You've successfully authenticated, but GitHub does not provide shell access.** Don't let GitHub's lack of providing shell access trouble you. If you see this message, you've successfully added your SSH key and you can move on. If the output doesn't correctly match up, then try going through these steps again or come to [the Discord chat](https://discord.gg/fbFCkYabZB) to ask for help.
> 
> Should we include something about the fingerprint message the first time you ssh to github (or any server for that matter)?

1. If that is actually just a comment, then yeah, I don't see the point in keeping it here. It creates unnecessary confusion like you said. I had no idea about this and thought the email is mandatory and needs to be the one that GitHub uses 

2. Oh yeah good point, specifying **device** specifically would be nice, adding that

**Review by xandora — CHANGES_REQUESTED** [review]
Overall, I think this is fine. Just need to either remove the `-C` or put the email back, but make a note about why it's there.

**Comment by nikitarevenco** [comment]
> Overall, I think this is fine. Just need to either remove the `-C` or put the email back, but make a note about why it's there.

Alright, I've removed `-C`

**Comment by nikitarevenco** [comment]
Also fixed the merge conflicts

**Pull request merged**
