### PR TITLE
Extra question mark removed

### PR DESCRIPTION
**Pull request by 91Flavio91**
Removed the extra question mark at the end of the first sentence in the Knowledge Check list (Foundations/JavaScript Basics/Fundamentals Part 1)

Complete the following REQUIRED checkboxes:

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`

Complete the following checkboxes ONLY IF they are applicable to your PR. You can complete them later if they are not currently applicable:
-   [ ] I have previewed all lesson files included in this PR with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure the Markdown content is formatted correctly
-   [ ] I have ensured all lesson files included in this PR follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

<hr>

**1. Because:**

Closes #XXXXX

**2. This PR:**

**3. Additional Information:**

### CODE REVIEW

**Review by fortypercenttitanium — CHANGES_REQUESTED** [review]
Hey @91Flavio91 do you see the merge conflicts on this PR? I'm guessing the spacing was changed before all the anchor tags. Fix those and I'll get this merged.

**Comment by 91Flavio91** [comment]
Hi @fortypercenttitanium ! Sorry, but I still have to get used to the entire process! Could you explain me how the merge conflicts with the PR? Because I don’t understand what I have to do! Thank you!

**Comment by fortypercenttitanium** [comment]
> Hi @fortypercenttitanium ! Sorry, but I still have to get used to the entire process! Could you explain me how the merge conflicts with the PR? Because I don’t understand what I have to do! Thank you!

At the bottom of this PR page, do you see the message that says "This branch has conflicts that must be resolved" ?

When I click that, this is what the conflict shows:

image

It looks like there are more spaces before the <a> tags than what the repo currently has. Your code editor might have added some without you knowing. Do you use a linter or formatter like Prettier?

**Comment by 91Flavio91** [comment]
@fortypercenttitanium Oh ok I understand now even though I still can't see the message ""This branch has conflicts that must be resolved". But, is it in the PR copy that you sent me at the beginning of this conversation? Anyhow, I use VScode but I don't remember to have installed the extension prettier. Maybe the option "format at saving" is on. Let me check it out.

**Comment by fortypercenttitanium** [comment]
> @fortypercenttitanium Oh ok I understand now even though I still can't see the message ""This branch has conflicts that must be resolved". But, is it in the PR copy that you sent me at the beginning of this conversation? Anyhow, I use VScode but I don't remember to have installed the extension prettier. Maybe the option "format on save" is on. Let me check it out.
> 
> **EDIT**: Ok, the option "format on save" is off. I don't know how this happened. Anyhow, how should I fix those spaces? Should I follow the same procedure that I followed the first time when I removed the question mark (that one that is written in the Odin Contribution Guide)?

Yes, that would be best.

**Comment by 91Flavio91** [comment]
@fortypercenttitanium Hi! Look, I'm trying to open a new issue, like is written on the guide, to fix those extra spaces. The problem is that I don't find the button "issues" next to the button "code" on my forked curriculum repo. Do you have any clue what is going on?

**Comment by fortypercenttitanium** [comment]
> @fortypercenttitanium Hi! Look, I'm trying to open a new issue, like is written on the guide, to fix those extra spaces. The problem is that I don't find the button "issues" next to the button "code" on my forked curriculum repo. Do you have any clue what is going on?

You shouldn't need to open a new issue, just either a) revert your fork to be up to date with main, make the fix again, and merge it with this branch, b) go into your current fork, remove the extra spaces, and push again, or c) close this pr, revert your fork, make the change, and push a new PR.

**Comment by 91Flavio91** [comment]
@fortypercenttitanium Hi! I've just opened the file to fix the extra spaces but they look correct, like in the picture that you sent me. There is just 1 space between "*" and the anchor element. I leave you a screenshot!
Screenshot (10)

**Comment by fortypercenttitanium** [comment]
> @fortypercenttitanium Hi! I've just opened the file to fix the extra spaces but they look correct, like in the picture that you sent me. There is just 1 space between "*" and the anchor element. I leave you a screenshot! Screenshot (10)

Sorry, I misspoke. I believe your editor removed the extra spaces. It looks to me like there are 3.

Are you by chance making these changes on a windows machine?

**Comment by fortypercenttitanium** [comment]
> @fortypercenttitanium Hi! I've just opened the file to fix the extra spaces but they look correct, like in the picture that you sent me. There is just 1 space between "*" and the anchor element. I leave you a screenshot! Screenshot (10)

Sorry, I misspoke. I believe your editor removed the extra spaces. It looks to me like there are 3.

Are you by chance making these changes on a windows machine?

**Comment by 91Flavio91** [comment]
@fortypercenttitanium ahahaha ok! Indeed, while I was writing the last message, I had hunch that you wanted me to ADD some spaces because they were deleted! Yes, I'm working on windows because I'm waiting to buy a new laptop for the VM. 

Ok, so I need to add more spaces. According to the picture that you sent me there should be 3, am I correct?

**Comment by fortypercenttitanium** [comment]
> @fortypercenttitanium ahahaha ok! Indeed, while I was writing the last message, I had hunch that you wanted me to ADD some spaces because they were deleted! Yes, I'm working on windows because I'm waiting to buy a new laptop for the VM. 
> 
> Ok, so I need to add more spaces. According to the picture that you sent me there should be 3, am I correct?

Gotcha, yeah try that. This could also be a CRLF/LF issue that windows likes to be annoying with. Check out this article and make this change in Vscode (or whichever editor you use):

https://dev.to/wagslane/how-to-get-consistent-line-breaks-in-vs-code-lf-vs-crlf-2c3p

**Comment by 91Flavio91** [comment]
@fortypercenttitanium allright, thank you for the guide! Ok, I've just fixed the spaces and I pushed. I don't know if I have to open a pull request.

**Pull request merged**
