### PR TITLE
Thanks for adding my solution.

### PR DESCRIPTION
**Pull request by jripka79**
```
This is a PR template, If you are adding a solution link to the curriculum leave this as is. If you are not, then delete it and write the message you wish.
Thank you,
The Odin Project team.
```

### CODE REVIEW

**Comment by KevinMulhern** [comment]
Hey @jripka79 it seems you are a little out of date with master. There should be a few more student solutions before yours. You need to update your fork with the latest changes and then submit again.

**Comment by jripka79** [comment]
Oh, I think I know what happened.  Thank you, I'll make the changes.  Learning the git ropes.  Appreciate it.

Joel

**Comment by KevinMulhern** [comment]
No problem :)

**Comment by KevinMulhern** [comment]
closed due to inactivity

**Pull request closed without merging**
