### PR TITLE
add word to fix typo

### PR DESCRIPTION
**Pull request by hoangtommy**
"that's because it uses the MiniTest testing framework instead of RSpec, which you have **been so** far." --> 
"that's because it uses the MiniTest testing framework instead of RSpec, which you have **been using** so far."

### CODE REVIEW

**Comment by 105ron** [comment]
If we are going to correct this, let's use `MiniTest` or `minitest`, not both. One must be correct, but I'm not sure which.

**Comment by hoangtommy** [comment]
Rhys, I did a quick search. Seems like both are used. The original repo uses `minitest` so it might make sense for us to follow that.

**Comment by 105ron** [comment]
Let's change `MiniTest` to `minitest` then in the paragraph, then I'll merge it. :tada:

**Comment by hoangtommy** [comment]
Done!

**Comment by 105ron** [comment]
Thank you :100:

**Pull request merged**
