### PR TITLE
fixes checkbox input type and creates spacing for section title in form-basics.md

### LINKED ISSUE #23377: Incorrect Formatting and Code Snippet in the Checkboxes section of Form Basics
I found two potential issues with the Checkboxes section of [form-basics.md](https://github.com/TheOdinProject/curriculum/blob/main/html_css/intermediate_html/form-basics.md) in the intermediate HTML and CSS course.

the section title is inside of the paragraph for the section.

The code snippet showing the creation of a checkbox option for pizza toppings uses `type="radio"` instead of `type="checkbox"`

### PR DESCRIPTION
**Pull request by rcamach7**
- [x] You have read [The Odin Projects Contributing Guide](https://github.com/TheOdinProject/curriculum/blob/main/CONTRIBUTING.md).
 - [x] The title summarizes the change and where it happened, for example: "Fixes punctuation in Clean Code lesson".
 - [x] If the PR is related to an open issue, use a [relevant keyword](https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests) and reference it with the `#` sign and the issue number.
 - [x] You have previewed your markdown (if any) in the [Odin Markdown Preview Tool](https://www.theodinproject.com/lessons/preview)
 - [x] If changes are requested, please make the changes in a timely manner. After you submit the changes, request another review from the maintainer (top right).

#### 1. Describe the changes made and include why they are necessary or important:

The header for the Checkboxes section is spaced away from the contents below to follow the format in the lesson. The code snippet input type for this section has been changed to "checkbox" instead of "radio"

Lesson in question is [form-basics.md](https://www.theodinproject.com/paths/full-stack-javascript/courses/intermediate-html-and-css/lessons/form-basics)

#### 2. Related Issue

Closes #23377

### CODE REVIEW

**Comment by thatblindgeye** [comment]
Can you please update the title of the PR to include the lesson that this fix is for?

**Comment by rcamach7** [comment]
> Thank you for the first time contribution! Can you please update the title of the PR to include the lesson that this fix is for?

Gotcha, title updated! Thank you

**Review by thatblindgeye — APPROVED** [review]
Thank you for fixing this. In the future please comment on an issue you see instead of just starting to work on it. If several users do this, we can end up with duplicate PRs for the same issue.

This does solve the issue of the incorrect input type being used. The other issue regarding the section title I am going to say is a whole other issue that should be unrelated to this.

**Review by thatblindgeye — CHANGES_REQUESTED** [review]
Actually just noticed, can you please bring your branch up to date with our main branch?

**Comment by thatblindgeye** [comment]
Apologies for the multiple comments. This PR is no longer relevant as another user has already fixed the issue. Thank you for wanting to help improve our lessons, and again please keep in mind to comment on issues you find and wait to be assigned before starting any work.

**Pull request closed without merging**
