### PR TITLE
Remove Question

### PR DESCRIPTION
**Pull request by sarif-agent**
## Because

The 3rd question (which i have deleted) given in this lesson's "Knowledge Section" has not answered in the curriculum properly. The question is quoted below: 

> What HTML element is used to create list items within both unordered and ordered lists?

The correct answer for this question is to nest them. 
But neither in previous lessons or in this lesson, curriculum doesn't teach the student on this specific question. 
Should be removed or needs to add a new lesson section about nesting lists.

## This PR

- Just deleted a question paragraph  sectioning at line 60 which is _"What HTML element is used to create list items within both unordered and ordered lists?"._

## Issue

Closes #XXXXX

Not closes any issue and not related.

## Additional Information

No related information.

## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [x] The `Because` section summarizes the reason for this PR
-   [x] The `This PR` section has a bullet point list describing the changes in this PR
-   [x] If this PR addresses an open issue, it is linked in the `Issue` section
-   [x] If any lesson files are included in this PR, they have been previewed with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure it is formatted correctly
-   [x] If any lesson files are included in this PR, they follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

### CODE REVIEW

**Comment by ManonLef** [comment]
The question asks what **HTLM element** is used. The answer is `li`

I don't believe this question is wrong. Please doet me know if you think I'm missing something.

**Comment by sarif-agent** [comment]
Hello, Ms. Manon. I also don't see any issue related to the question. The
problem is not how the curriculum presents the question. The problem lies
in the fact that the question is asked here.

When I click on the question, the paragraph it takes me to doesn't provide
any answer. I found the answer to this question not within the curriculum
itself but through additional resources provided at the bottom of the page
(in the "Additional Resources" section) regarding OL and UL (Ordered Lists
and Unordered Lists) (I even learned it by chance).

My English is not perfect, but I am certain about what I have read. When I
read the paragraph that the reference link in the question leads us to, I
still cannot see a clear answer regarding the specific question asked.

The paragraph only tells the student how to create an unordered list.
Nothing more than that.

Manon ***@***.***>, 28 Haz 2023 Çar, 20:21 tarihinde şunu
yazdı:

**Comment by sarif-agent** [comment]
Oh. I'm so sorry. Now i understand what it means. 

>What HTML element is used to create both an ordered and an unordered list?

>The question asks what HTLM element is used. The answer is <li>

I'm really sorry, i was thinking much more complicated. Sorry, i took your time.

**Comment by CouchofTomato** [comment]
@sarif-agent 

Can we close this PR then?

**Comment by sarif-agent** [comment]
Yes, go ahead.

28 Haz 2023 Çar 21:16 tarihinde Austin ***@***.***> şunu
yazdı:

**Comment by CouchofTomato** [comment]
Thanks @sarif-agent

**Pull request closed without merging**
