### PR TITLE
Change forum introduction to discourage introduction posts

### PR DESCRIPTION
**Pull request by CouchofTomato**
The forum intro used to encourage student introductions but it meant a lot of help posts were buried. Now with the chatroom hook it will also flood the forum posts room with a lot of introduction posts.

This change encourages introductions in the chatrooms and the forum be used when seeking help.

### CODE REVIEW

**Comment by I3uckwheat** [comment]
@CouchofTomato Do we want to mention the introductions room in the chat?

**Comment by CouchofTomato** [comment]
@I3uckwheat 

Do we? It would still flood the forum room on discord. Personally I think a chatroom is a great place to introduce yourself. The forums can still be used for those seeking study partners etc.

**Comment by I3uckwheat** [comment]
> @I3uckwheat
> 
> Do we? It would still flood the forum room on discord. Personally I think a chatroom is a great place to introduce yourself. The forums can still be used for those seeking study partners etc.

I think we're in agreement, keep introductions on discord. 

I mean, mention the introduction room in discord, in your edits above, to help keep general more clear.
image

**Comment by codyloyd** [comment]
beautiful

happy to merge.. but i'll give it a minute to make sure no one else has any objections

**Comment by CouchofTomato** [comment]
> 
> 
> @CouchofTomato
> 
> > @I3uckwheat
> > Do we? It would still flood the forum room on discord. Personally I think a chatroom is a great place to introduce yourself. The forums can still be used for those seeking study partners etc.
> 
> I think we're in agreement, keep introductions on discord.
> 
> I mean, mention the introduction room in discord, in your edits above, to help keep general more clear.
> image

@I3uckwheat Ahh yes perfect. Check out the updated text.

**Pull request merged**
