### PR TITLE
Added link to my projects for Web Development 101

### PR DESCRIPTION
**Pull request by Koullaras**
Added links to my project sites on the project_html_css.md file.

Thank you,

The Odin Project team.

### CODE REVIEW

**Comment by Javier-Machin** [comment]
Hi @Koullaras, please remove the changes to the README.

**Comment by Koullaras** [comment]
Will do so immediately.

**Comment by Koullaras** [comment]
I deleted what I added to the README.md file. I hope it's correct now.

**Comment by Koullaras** [comment]
Thank you very much!

**Pull request merged**
