### PR TITLE
Rename webpack-2.md to webpack-part-2.md

### PR DESCRIPTION
**Pull request by DoviMaj**
could be confused to mean webpack version 2. maybe change to Webpack part 2?

### CODE REVIEW

**Comment by KevinMulhern** [comment]
Hey @DoviMaj, just one question, if this is part 2 there must be a part 1. So where is the webpack part 1 lesson in the curriculum?

**Comment by DoviMaj** [comment]
inside this lesson https://www.theodinproject.com/courses/javascript/lessons/es6-modules#webpack
is where webpack is introduced

**Comment by KevinMulhern** [comment]
ahh ok, that isn't really enough content to call this lesson part 2 though imo.

Besides the 2 was referring to the webpack version. Webpack was on version 2 when we originally wrote this lesson. So just renaming this lesson to Webpack would be enough.

You'll also need to make the appropriate change to update the title on the site as well: https://github.com/TheOdinProject/theodinproject/blob/master/db/seeds/06_javascript_course_seeds.rb

**Comment by DoviMaj** [comment]
did it
https://github.com/TheOdinProject/theodinproject/pull/1416

**Comment by KevinMulhern** [comment]
Brilliant, thanks @DoviMaj

**Pull request merged**
