### PR TITLE
Etch-a-Sketch lesson: Add a link to event.preventDefault();

### PR DESCRIPTION
**Pull request by kellondavid**
Complete the following REQUIRED checkboxes:

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`

Complete the following checkboxes ONLY IF they are applicable to your PR. You can complete them later if they are not currently applicable:
-   [x] I have previewed all lesson files included in this PR with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure the Markdown content is formatted correctly
-   [x] I have ensured all lesson files included in this PR follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

<hr>

**1. Because:**

Closes #XXXXX
I've seen quite a few people running into an issue where their cursor would disable when they retrace blocks on their Etch-a-Sketch assignment on Discord. I always end up linking them to the mdn documentation for event.preventDefault();, and they seem to fix the issue on their own afterwards. I believe that adding this line into the assignment will help a lot of people figure this issue out on their own.

**2. This PR:**

- Add a link to event.preventDefault(); to help fix disabled cursor issue in Etch-a-Sketch assignment.

**3. Additional Information:**

### CODE REVIEW

**Comment by wise-king-sullyman** [comment]
Thanks for taking the time to put up this PR!

I'm not sure if we want to be introducing everyone to `event.preventDefault` at this point in the curriculum. Can you link a couple of the instances you mentioned where people needed to use it for this project?

**Comment by kellondavid** [comment]
> Thanks for taking the time to put up this PR!
> 
> I'm not sure if we want to be introducing everyone to `event.preventDefault` at this point in the curriculum. Can you link a couple of the instances you mentioned where people needed to use it for this project?

Hey there! Here's one instance, but two other instances were through voice chat with my friends (one time was when I was helped with this particular issue, another was when I helped a different friend).

https://discord.com/channels/505093832157691914/690590001486102589/1022770792154542160

I thought it would be nice to introduce the concept at Etch-a-Sketch and maybe revisit it right before Library assignment (a good amount of people also ask for help regarding the `Submit` event, and people usually direct them to `event.preventDefault`). 

There's also instances where `event.preventDefault()` might be of use in assignments shortly after Etch-a-Sketch, which is why I think it's not a bad place to briefly touch on it. For example Calculator: 
https://discord.com/channels/505093832157691914/690590001486102589/1001183390378242119
https://discord.com/channels/505093832157691914/690590001486102589/966665748653170699
(also used it myself for the calculator project)

and a LOT when it comes to forms in Library section:
https://discord.com/channels/505093832157691914/690590001486102589/1017838974548586636
https://discord.com/channels/505093832157691914/690590001486102589/992434296990224434
https://discord.com/channels/505093832157691914/690590001486102589/990719883123781682
https://discord.com/channels/505093832157691914/690590001486102589/990299702643789894
https://discord.com/channels/505093832157691914/690590001486102589/980931159728980078
https://discord.com/channels/505093832157691914/690590001486102589/1009250896296816690

Would love to here your feedback/opinion on this. Happy to help!

**Comment by wise-king-sullyman** [comment]
@kellondavid I'm not able to reproduce the issue that the linked etch a sketch mentions, could you put together a quick codesandbox or something to demonstrate it?

I could definitely see something being mentioned about `preventDefault` in the library project, and potentially the calculator project as well, but I'm still not sure about adding it for etch a sketch.

**Comment by kellondavid** [comment]
@wise-king-sullyman Of course, https://codepen.io/nollek/pen/vYRwWyv

I should have clarified that it's only an issue when you have the sketchpad to draw on mousedown. If you click on an area that's already been colored in, you'll see the disabled cursor and the rest of the grid will be filled on hover instead of mousedown.

If you believe that preventDefault shouldn't be introduced in etch, then I could go ahead and introduce it in library project with a little more detail added in. For me personally, it was nice to know about it early on.

**Comment by wise-king-sullyman** [comment]
Ahhh ok I see now, thanks for putting that codepen together!

Since the project spec for etch a sketch actually says to just have the color apply on hover rather than mousedown (likely because it avoids this sort of issue and simplifies things a decent bit) I lean towards not adding this here.

I think adding a note to use it in calculator specifically for things like `/` where people often encounter an issue that needs it would make sense, and mentioning it in more detail in the library project also probably wouldn't be a bad idea if you'd like to do that as well! At that point in the curriculum I think getting a little into the nitty gritty details of events and default behavior would be appropriate.

**Comment by kellondavid** [comment]
@wise-king-sullyman Thanks for the reply, and sounds good! Would I have to create and fill out a new pull request, or can I just edit this one?

**Comment by wise-king-sullyman** [comment]
Up to you honestly, a new PR is probably what I would do though. If you do that I would suggest mentioning this issue in the PR body when you make the new one.

**Comment by kellondavid** [comment]
@wise-king-sullyman Created a new PR here https://github.com/TheOdinProject/curriculum/pull/24818
Thanks again!

**Pull request closed without merging**
