### PR TITLE
Copy foundations Git content to top level directory

### PR DESCRIPTION
**Pull request by wise-king-sullyman**
Complete the following REQUIRED checkboxes:

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`

Complete the following checkboxes ONLY IF they are applicable to your PR. You can complete them later if they are not currently applicable:
-   [ ] I have previewed all lesson files included in this PR with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure the Markdown content is formatted correctly
-   [ ] I have ensured all lesson files included in this PR follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

<hr>

**1. Because:**

This idea was brought up while doing [this site PR](https://github.com/TheOdinProject/theodinproject/pull/2709/files#r823127052) and I agreed with it

**2. This PR:**

Copies the foundations Git content to the new top level Git directory before I move its location in the site fixture file. After the site is updated I will remove these lessons from their current location.

**3. Additional Information:**

### CODE REVIEW

**Review by KevinMulhern — COMMENTED** [review]
I forgot how many images we have in the basics lesson 😆 

Do we want these two lessons further nested within a "git_basics" folder based on the section naming on the site? I _think_ thats how @01zulfi has been doing it with their initiative to standardise naming and folder conventions.

**Comment by wise-king-sullyman** [comment]
@KevinMulhern I'm not against nesting these further, if we do though do you think the non-basics should be nested in an intermediate_git folder as well?

**Comment by 01zulfi** [comment]
Since I'm working on the folder structure of the curriculum repository, here's what I have to say.

The two Foundations git lessons will go in a `git_basics` folder. As for the the non-basics, it depends. If it's decided to have a dedicated section for them on the website, then the non-basics will be nested in a `intermediate_git` folder. If it's decided to not have a dedicated section, then _I_ don't feel a need for a `intermediate_git` folder.

**Comment by wise-king-sullyman** [comment]
Thanks for the input @01zulfi, I agree with that stance. Since it looks like we're going to have them in a dedicated section I'll nest all of them.

**Review by 01zulfi — CHANGES_REQUESTED** [review]
Few changes to bring this up to speed with the desired folder structure of the repository:

1. `lesson_a_deeper_look_at_git.md` needs to be renamed to `a_deeper_look_at_git.md`
2. `lesson_using_git_in_the_real_world.md` needs to be renamed to `using_git_in_the_real_world.md`
3. `project_practicing_git_basics` folder needs to be renamed to `git_basics`. This folder needs to have an `imgs` folder and all the image files need to be placed here.

**Comment by wise-king-sullyman** [comment]
@01zulfi great callouts!

One thing I did differently than you suggested was to name the folder for all of the git content in foundations `foundations_git`, since the content isn't all in the git_basics section.

Additionally/related I moved the commit messages lesson to the new `foundations_git` directory, since I figured it made more sense there than staying in the html/css section.

If you disagree with these calls please let me know, happy to talk through more of my decision process and figure out a better path.

**Comment by wise-king-sullyman** [comment]
@01zulfi I personally don't love having the html_foundations directory just for that commit lesson. Like you said since we're doing something unique with git vs everything else I'm more than alright with having things *slightly* different in this instance if you are.

I'll leave the decision up to you though since you're the one running the structure cleanup.

**Comment by 01zulfi** [comment]
Cool, let's embrace the uniqueness and go with `foundations_git`.

**Review by 01zulfi — APPROVED** [review]
Looks great 🔥

**Pull request merged**
