### PR TITLE
Add Josh Archer's solution to Student Solutions

### PR DESCRIPTION
**Pull request by PuffinBlue**
Hopefully I have entered this in the correct location!

### CODE REVIEW

**Comment by muzfuz** [comment]
Hey thanks! Could you please move your link to the bottom of the list?

**Comment by PuffinBlue** [comment]
Ah, sorry! Will do...

**Comment by muzfuz** [comment]
Thanks a lot.

BTW, in future you can just submit a new commit to the same request :+1:

**Comment by PuffinBlue** [comment]
I did attempt that, then screwed it up and thought I'd just start over :-) Now I know how to do it for next time!

**Pull request closed without merging**
