### PR TITLE
Add knowledge-check Preamble in missing lessons.

### LINKED ISSUE #23000: Knowledge Check preamble missing on some lessons
The:

"This section contains questions for you to check your understanding of this lesson. If you’re having trouble answering the questions below on your own, review the material above to find the answer."

preamble that should come after the Knowledge Check heading is missing on some lessons.

### PR DESCRIPTION
**Pull request by asadrjhk**
- [x] You have read [The Odin Projects Contributing Guide](https://github.com/TheOdinProject/curriculum/blob/main/CONTRIBUTING.md).
 - [x] The PR title summarizes the change and where it happened, for example: "Fixes punctuation in Clean Code lesson".
 
#### 1.Describe the changes made and include why they are necessary or important:

Add knowledge-check Preamble in missing lessons.

#### 2. If this PR is related to an open issue please reference it with the `#` operator and the issue number (and any [relevant keywords](https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests)) below:

closes #23000

### CODE REVIEW

**Comment by wise-king-sullyman** [comment]
@asadrjhk sorry but it looks like you've got some merge conflicts, can you resolve those?

**Comment by asadrjhk** [comment]
@wise-king-sullyman sorry but i didn't able to see any conflict in my local repo, can u point me to how to see that, i already pull the changes from the repo using command *git pull upstream main* and it merges in the feature branch. i had try that 
sorry, but i can't able to figure it out.

**Comment by wise-king-sullyman** [comment]
@asadrjhk you're right it seems to merge without causing conflicts.

See if you can do another pull of `upstream main` to merge main into your branch once more, then try pushing that merge commit to your branch here, and let's see if it irons itself out.

**Comment by wise-king-sullyman** [comment]
@asadrjhk looks like that worked! GitHub might just be having an off day :laughing:

**Review by wise-king-sullyman — APPROVED** [review]
This looks great, thank you for doing it!

**Pull request merged**
