### PR TITLE
Update the Rails Basics project to use the Rails Guides getting started project

### PR DESCRIPTION
**Pull request by CouchofTomato**
Because the existing blogger 2 project uses Rails 4 which is now
outdated

This commit changes the project to use the Rails getting started blog
project

### CODE REVIEW

**Review by rlmoser99 — COMMENTED** [review]
Do you think we should indicate that they can skip the installation information? Another option would be to say that they can start at section 3.2 or to just link them to that location. 

Also, do you think we should remind them to set it up on github, since the tutorial does not?

Otherwise, it looks good to me.

**Review by rlmoser99 — COMMENTED** [review]
Also, this Getting Started tutorial is currently an additional resource on this project/lesson, so we should probably delete it from that section.

**Comment by CouchofTomato** [comment]
@rlmoser99 

Thanks Mosby. Changes made. I think they'd benefit from at least reviewing the install section so I just made it clear they shouldn't need to install Rails.

**Review by rlmoser99 — APPROVED** [review]
Looks great!! ⭐

**Pull request merged**
