### PR TITLE
Add article about Rails sessions by Justin Weiss

### PR DESCRIPTION
**Pull request by lujanfernaud**
Another good resource for learning a bit more about sessions and cookies in Rails.

### CODE REVIEW

**Comment by KevinMulhern** [comment]
IMO this would be worth adding to the assignments to ensure a student goes through it, its a great resource.

What do you think @lujanfernaud ?

**Comment by lujanfernaud** [comment]
Sounds good to me. Maybe before the Rails Guides links?

**Comment by KevinMulhern** [comment]
That would be perfect 👍 😄

**Comment by lujanfernaud** [comment]
I just watched [this video](https://www.youtube.com/watch?v=mqUbnZIY3OQ) from RailsConf 2017 where he explains it in more depth. Being this a security topic, maybe the video could also be added to the assignments.

The resulting assignments could be:

1. Read [this article about how Rails sessions work](https://www.justinweiss.com/articles/how-rails-sessions-work/).
2. Watch [this video to dive deep into sessions](https://www.youtube.com/watch?v=mqUbnZIY3OQ).
3. Read [Rails Guides on Controllers](#) chapters 5-6. [...]
4. Read [Rails Guides on Controllers](#) chapter 8 [...].
5. Read [Rails guides on Controllers](#) chapter 11 [...].
6. Glance over the [Devise Documentation](#). [...]

What do you think @KevinMulhern ?

**Comment by KevinMulhern** [comment]
Brilliant @lujanfernaud, I think that would be perfect.

**Pull request closed without merging**
