### PR TITLE
Introduction to Express: Updated brad traversy express crash course.md

### PR DESCRIPTION
**Pull request by ReyHaider**
updated the link to the upto date express crash course by brad traversy(traversy media).

## Because

Traversy media has uploaded a new express crash course which is upto date. odin project linked to the older and outdated one. By updating this to the latest course, it can help people learn the newest stuff in express and avoid deprecated components.

## This PR

- Updated link to brad traversy express crash course.

## Issue

Closes #XXXXX

## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project curriculum contributing guide](https://github.com/TheOdinProject/curriculum/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [x] The `Because` section summarizes the reason for this PR
-   [x] The `This PR` section has a bullet point list describing the changes in this PR
-   [x] If this PR addresses an open issue, it is linked in the `Issue` section
-   [x] If any lesson files are included in this PR, they have been previewed with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure it is formatted correctly
-   [x] If any lesson files are included in this PR, they follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

### CODE REVIEW

**Comment by MaoShizhong** [comment]
Thanks for opening this PR @ReyHaider. We already have an open issue on this #27865 which someone has already requested to be assigned to, and we request that [PRs not be opened to fix something that's covered in an open issue](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md#check-before-doing-anything). We're leaning towards not updating the link for that video for reasons detailed in that issue.

For now, I'll close this PR since if we do decide to update the link, we will be assigning the person who requested it in that issue.

**Comment by ReyHaider** [comment]
Hi, Thank you for responding, I just wanted to clarify that the referred issue in your response is about updating nodeJs crash course while my PR was about updating the express crash course offered by traversy media, I did see that opened issue before sending a PR, and it did not contain any suggested changes related to intro to express section. Regards.

**Review by MaoShizhong — APPROVED** [review]
> Hi, Thank you for responding, I just wanted to clarify that the referred issue in your response is about updating nodeJs crash course while my PR was about updating the express crash course offered by traversy media, I did see that opened issue before sending a PR, and it did not contain any suggested changes related to intro to express section. Regards.

You are absolutely right and that is my mistake, so you have my sincere apologies!

We are actually in the process of updating our Node course, with [the Express section being the current milestone](https://github.com/orgs/TheOdinProject/projects/38/views/4), but we don't have a timeline set for when that will be released.

Just did a run through of the updated Express crash course and it still serves the curriculum purpose perfectly fine, where the Node crash course wasn't as justified in replacing the previous one in our context, so it won't hurt to update it while we still have this version of the lesson.

Thank you for making the suggestion, and sorry again for the mixup!

**Comment by ReyHaider** [comment]
Thank you for considering my suggestion, it's a pleasure to contribute in anyway :).

**Pull request merged**
