### PR TITLE
NodeJS Deployment Lesson: Update Render free plan informations

### PR DESCRIPTION
**Pull request by NestorNebula**
## Because

The Lessons says that Render's Free Plan requires a credit card but it not this is not the case currently.

## This PR

This PR:
* Updates informations about the Render Free Plan in the NodeJS Course, Express Section, Deployment Lesson.

## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project curriculum contributing guide](https://github.com/TheOdinProject/curriculum/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [x] The `Because` section summarizes the reason for this PR
-   [x] The `This PR` section has a bullet point list describing the changes in this PR
-   [ ] If this PR addresses an open issue, it is linked in the `Issue` section
-   [x] If any lesson files are included in this PR, they have been previewed with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure it is formatted correctly
-   [x] If any lesson files are included in this PR, they follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

### CODE REVIEW

**Review by MaoShizhong — CHANGES_REQUESTED** [review]
Thanks - can confirm the free plan doesn't seem to need a credit card currently to deploy. Could you also make the same change to the Ruby on Rails deployment lesson please? You can just push the change to this branch to add it to this PR.

**Comment by NestorNebula** [comment]
After reading the Render paragraph in the Ruby on Rails course, it doesn't refer to the need of a credit so I don't think that there is a change to do. Tell me if I am wrong.

**Review by MaoShizhong — APPROVED** [review]
You're right, I must have misread. Thanks for fixing this!

**Comment by NestorNebula** [comment]
Thanks, this was my first PR, a little change of course but I am happy to have contributed!

**Pull request merged**
