### PR TITLE
Style Guide - Foundations/HTML Foundations: Knowledge Checks and Learning Outcomes Fix

### LINKED ISSUE #23931: Style Guide - Foundations/HTML Foundations: Learning Outcomes and Knowledge Checks
# Foundations/HTML Foundations Section

This issue is part of the Style Guide Community Project, a way of offering members of The Odin Project community a chance to contribute to our curriculum. Users who wish to take part and contribute to any Style Guide issues should have thoroughly read the [layout style guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md) and [The Odin Project contributing guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md).
  
## Description of Issue

This issue ensures the Learning Outcomes and Knowledge Check sections have the correct verbiage and formatting. If one of these sections does not exist in a lesson, it should not be added.

Each applicable lesson for this issue should meet the following requirements:

- The Learning Outcomes section is renamed to "Lesson Overview".
- The Lesson Overview section follows the below format:
	```
	### Lesson Overview

	This section contains a general overview of topics that you will learn in this lesson.

	*   LESSON OVERVIEW ITEMS...
	```
- The Knowledge Check section follows the below format:
	```
	### Knowledge Check

	This section contains questions for you to check your understanding of this lesson on your own. If you’re having trouble answering a question, click it and review the material it links to.

	*   KNOWLEDGE CHECKS...
	```
- Each Knowledge Check item follows the below format:
	```
	*   <a class="knowledge-check-link" href="A KNOWLEDGE CHECK URL">A KNOWLEDGE CHECK QUESTION.</a>
	```
- Each Knowledge Check item redirects to a resource mentioned in the lesson, or to a section within the lesson, where the answer can be found. 
	- If it doesn't, note this in your PR, but don't remove the item.
  
## Acceptance Criteria

- [ ] The following lessons are updated according to the issue description above:
	- [ ] [Introduction to HTML and CSS](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/introduction-to-html-and-css)
	- [ ] [Elements and Tags](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/elements-and-tags)
	- [ ] [HTML Boilerplate](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/html-boilerplate)
	- [ ] [Working with Text](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/working-with-text)
	- [ ] [Lists](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/lists)
	- [ ] [Links and Images](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/links-and-images)
	- [ ] [Commit Messages](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/commit-messages)

### PR DESCRIPTION
**Pull request by ItsKatato**
Complete the following REQUIRED checkboxes:

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`

Complete the following checkboxes ONLY IF they are applicable to your PR. You can complete them later if they are not currently applicable:
-   [x] I have previewed all lesson files included in this PR with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure the Markdown content is formatted correctly
-   [x] I have ensured all lesson files included in this PR follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

<hr>

**1. Because:**

Closes #23931

**2. This PR:**

- [x] The following lessons are updated according to the issue description above:

  - [x]  [Introduction to HTML and CSS](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/introduction-to-html-and-css)
  - [x]  [Elements and Tags](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/elements-and-tags)
  - [x]  [HTML Boilerplate](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/html-boilerplate)
  - [x]  [Working with Text](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/working-with-text)
  - [x]  [Lists](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/lists)
  - [x]  [Links and Images](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/links-and-images)
  - [x]  [Commit Messages](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/commit-messages)

### CODE REVIEW

**Comment by ItsKatato** [comment]
I do have a question. Should I squash Style Guide commits into one or should they be separate?

**Review by thatblindgeye — APPROVED** [review]
Thanks for making the updates! Feel free to ask for another issue, otherwise more will be posted at some point 🙂

**Comment by 01zulfi** [comment]
@thatblindgeye The corresponding file for the Commit Messages lesson should be the one [`git/foundations_git` folder](https://github.com/TheOdinProject/curriculum/tree/main/git/foundations_git). This pull request updates the duplicate file for this lesson.

I'll deal with these duplicate files soon. For now, let me know if I should update the correct file for Commit Messages, or you'd want to handle it yourself via a issue/PR.

**Comment by thatblindgeye** [comment]
@ItsKatato Would you mind making a new PR to update the Commit Messages lesson in the directory noted in the message above?

**Comment by ItsKatato** [comment]
@thatblindgeye I don't mind! I'll get to work on that 👍🏽

**Pull request merged**
