### PR TITLE
Edit the JavaScript Memory game

### PR DESCRIPTION
**Pull request by leila-alderman**
Replaced the dead link to an example Memory game
with an updated example link.

Additionally, edited some of the surrounding text for improved
readability and flow.

### CODE REVIEW

**Review by marvingay — APPROVED** [review]
lgtm

**Comment by DoviMaj** [comment]
Not the same game tough

**Comment by marvingay** [comment]
The implementation of the game is more or less, similar..
Do you feel the CSS aspect of it would be too tricky?

**Comment by DoviMaj** [comment]
The css seems alright. but the game doesn't match the project description. 

> There should be a function that displays the cards in a random order anytime a user clicks one. Be sure to invoke that function when the component mounts.

**Pull request merged**
