### PR TITLE
Fund5 - Object Basis - Update the verbiage in Assignment part

### LINKED ISSUE #26931: Fundamentals Part 5: <Exercise JS.info extendable calculator>
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

Hello, I've been currently working on Foundations part 5 and was doing exercises from Javascript.info and I've been stuck at  " Extendable calculator " exercise. Don't know if it's supposed to be easy or it's just me, but I've been struggling for 2 days on it. Maybe you can check it to atleast tell me if it was totally planned from you. :)
https://javascript.info/array-methods#tasks
EDIT : I've been working on exercise " create keyed object from array " with the reduce() function. Took me some hours to understand how it was working. This vid helped me a lot :https://youtu.be/5nzBDkH9lWI
Maybe it can be useful ?

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-fundamentals-part-5

### (Optional) Discord Name

Hachounet

### (Optional) Additional Comments

_No response_

### PR DESCRIPTION
**Pull request by Hachounet**
## Because
As requested in the #26931 ticket, I'm requested by @thatblindgeye  to update the verbiage of the sentence line 162.  I've updated the sentence to encourage learners to do the exercices but make them aware of the potentially blocking issues they could encounter.

## This PR

- Updated the verbiage line 162 to encourage learners to do the exercices of javascript.info.

## Issue

Closes #26931

## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [x] The `Because` section summarizes the reason for this PR
-   [x] The `This PR` section has a bullet point list describing the changes in this PR
-   [x] If this PR addresses an open issue, it is linked in the `Issue` section
-   [x] If any lesson files are included in this PR, they have been previewed with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure it is formatted correctly
-   [x] If any lesson files are included in this PR, they follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

### CODE REVIEW

**Comment by MaoShizhong** [comment]
I'm actually of the opinion that we should not be advising learners at this point to do the extendable calculator task. While a learner might briefly encounter constructors in a linked MDN resource, I do not feel it appropriate for a learner at this point to be doing a task that instructs them to create one with methods etc. I think without actually teaching about constructors properly, it's too advanced for relatively little gain at this point.

@TheOdinProject/foundations thoughts?
I personally think we should state to do the exercises in the article *except* for the "Create an extendable calculator" task.

@Hachounet no need to make any changes yet - would like to hear from other team members first as to what they feel is most appropriate.

**Comment by thatblindgeye** [comment]
I'd agree with the above.

**Comment by MaoShizhong** [comment]
@thatblindgeye How would you feel about having that assignment step reworded entirely to (using your original suggestion from the issue as a base):
> Read through the [array method guide](https://javascript.info/array-methods) for a more comprehensive and in-depth guide to array methods in JavaScript. Complete the exercises at the end except for "Create an extendable calculator", as that involves more advanced concepts we have not yet covered.

I personally think the "keyed object from array" task, while tricky, should still be just about within scope. Just the calculator one that involves constructors doesn't feel appropriate to me.

**Comment by thatblindgeye** [comment]
@MaoShizhong yeah something like that sounds good

**Comment by MaoShizhong** [comment]
@Hachounet Could you reword that entire assignment step to the following please?
> Read through the [array method guide](https://javascript.info/array-methods) for a more comprehensive and in-depth guide to array methods in JavaScript. Complete the exercises at the end except for "Create an extendable calculator", as that involves more advanced concepts we have not yet covered.

Let me know if you run into issues doing this.

**Comment by Hachounet** [comment]
@MaoShizhong Yep, for sure. Will do it during evening,

**Comment by Hachounet** [comment]
@MaoShizhong Should be ok now.

**Review by MaoShizhong — APPROVED** [review]
:rocket:

**Pull request merged**
