### PR TITLE
Added Link to bcrypt implementation for Secure Password

### PR DESCRIPTION
**Pull request by don-hue**
- [x] You have read [The Odin Projects Contributing Guide](https://github.com/TheOdinProject/curriculum/blob/main/CONTRIBUTING.md).
 - [x] The title summarizes the change and where it happened, for example: "Fixes punctuation in Clean Code lesson".
 - [x] If the PR is related to an open issue, use a [relevant keyword](https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests) and reference it with the `#` sign and the issue number.
 - [x] You have previewed your markdown (if any) in the [Odin Markdown Preview Tool](https://www.theodinproject.com/lessons/preview)
 - [x] If changes are requested, please make the changes in a timely manner. After you submit the changes, request another review from the maintainer (top right).

#### 1. Describe the changes made and include why they are necessary or important:

...your text here

#### 2. Related Issue

Closes #XXXXX

### CODE REVIEW

**Comment by don-hue** [comment]
Following the NodeJS curriculum, I noticed a missing link during the authentication lesson (Securing passwords with bcrypt).
The description/instructions were unclear, so I found an article on how to implement bcrypt hashing/comparing. I added said article in the text as a hyperlink.

**Review by fortypercenttitanium — COMMENTED** [review]
It seems to me like the description of how to use bcrypt is already sufficient. I skimmed through the article and it goes through a lot of procedure that the learner should have done already. Can you explain what exactly was unclear about the lesson instructions that would necessitate reading this rather lengthy article to perform this step?

**Comment by don-hue** [comment]
Hey man, 
you are right. there is some overlap in the article and the curriculum. however, there is one major step which was pretty unclear to me: 

the part were I had to edit my ('/sign-up) route to use bcrypt.hash. 
-> in the article, you have to define a so called pre-middleware for mongoose: 

UserScheme.pre("save", function.......)
-> this is basically a function which will be called BEFORE we save our user and password to our MongoDB. In this step we take the user password, hash it and than we proceed to save the hashed password in our MongoDB.

**Comment by fortypercenttitanium** [comment]
> Hey man, you are right. there is some overlap in the article and the curriculum. however, there is one major step which was pretty unclear to me:
> 
> the part were I had to edit my ('/sign-up) route to use bcrypt.hash. -> in the article, you have to define a so called pre-middleware for mongoose:
> 
> UserScheme.pre("save", function.......) -> this is basically a function which will be called BEFORE we save our user and password to our MongoDB. In this step we take the user password, hash it and than we proceed to save the hashed password in our MongoDB.

That is certainly one way to do it, but it is not the only way. Alternatively, you could handle the hashing in the route handler before you call `User.save()`. I think that is what we are expecting the learner to do here since it is basically the path of least resistance. The `.pre` is a handy function but it's not absolutely necessary to complete this step.

My concern is that by adding this article, we are lengthening the time it will take for someone to complete this lesson for little benefit in the end. If you feel like this part of the lesson is unclear or could be better without this article, we'd be open to that.

Before I close, I'll let you respond in case I'm missing something that you'd like to point out.

**Comment by zachmmeyer** [comment]
Closed due to staleness.

**Pull request closed without merging**
