### PR TITLE
Update project_html_css.md

### PR DESCRIPTION
**Pull request by ennjoi**
```
This is a PR template, If you are adding a solution link to the curriculum leave this as is. If you are not, then delete it and write the message you wish.
Thank you,
The Odin Project team.
```

### CODE REVIEW

**Comment by ennjoi** [comment]
Just want to add my solutions to the curriculum page. Added commits to my master branch (ennjoi/curriculum). Would it be possible to let me know what other conflicts need to be resolved before my branch can be merged because I'm not sure anymore. Thank you!

**Comment by KevinMulhern** [comment]
Hey @ennjoi, it seems your html and css project file is out of date with the curriculum. There should be more solutions above yours. You need to sync your fork with the curriculum.

**Comment by ennjoi** [comment]
Thanks @KevinMulhern. Synced my fork just now.

**Comment by KevinMulhern** [comment]
Thanks @ennjoi

**Pull request merged**
