### PR TITLE
Added a note on Line 39

### PR DESCRIPTION
**Pull request by lerenah**
Line 39, references alternatives to using GitHub

This is a PR template. If you are adding a solution link to the curriculum, leave this as is. If not, delete it and write the message you wish.

Thank you,

The Odin Project team.

### CODE REVIEW

**Comment by KevinMulhern** [comment]
Wow I wasn't aware Github had lost that amount of users so far 😮 

Do you have a source for that I could read? (not disputing its accuracy, just want to learn more 🙂)

I think this might fit better in the [Introduction to Git Lesson](https://www.theodinproject.com/courses/web-development-101/lessons/introduction-to-git)

Its the first time we expose users to Git properly and just seems like the more appropriate place for something like this to me.

Whats your thoughts?

**Comment by lerenah** [comment]
I’ve been trying to hunt down the original link for it, maybe I should have included it in the note. But basically it has something to do with Microsoft buying github and a solid of number of users lost trust in the stability of github afterwards. It’s just a suggestion. 

I think the Introduction to Github link is quite effective! Thank you for the help!

Fate be changed 
Look inside 
Mend the bond
Broken by pride

**Comment by KevinMulhern** [comment]
Thanks @lerenah, I think mentioning that there are alternatives for Github would be great 👍
 
But we would like to remain impartial to the Github situation. We'd prefer to wait and see what MS does with Github before taking any stances. I personally don't think MS now owning Github needs to be highlighted in any of our lessons.

But I'm open to hearing your thoughts on why we should highlight it 🙂

**Comment by lerenah** [comment]
That is  a very sound stance!  Thank you for sharing :) !!

**Pull request closed without merging**
