### PR TITLE
Project Sending Confirmations: Add WSL instructions for Letter Opener

### LINKED ISSUE #28386: Sending Confirmation Emails: Add WSL instructions to setup letter_opener gem
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

In the project "Sending Confirmation Emails" of the Ruby on Rails course, it asks us to use the `letter_opener` gem. I had trouble trying to use it with WSL. After some time, I found the solution was to add the following to `config/environments/development.rb`:

```ruby
LetterOpener.configure do |config|
  config.file_uri_scheme = 'file://wsl.localhost/Ubuntu'
end
```

Additionally, I added the following to `~/.bashrc` to set the browser path so Launchy can detect it and open the email:

```bash
export BROWSER=/mnt/c/Program\ Files/Google/Chrome/Application/chrome.exe
```

The first snippet of code defines the `file_uri_scheme` for WSL, and the second one sets the browser path so Launchy can detect it and `letter_opener` can open the email.

I suggest that this fix for the issue be added to the project "Sending Confirmation Emails".

### Path

Ruby / Rails

### Lesson Url

https://www.theodinproject.com/lessons/ruby-on-rails-sending-confirmation-emails

### (Optional) Discord Name

tornado_77

### (Optional) Additional Comments

_No response_

### PR DESCRIPTION
**Pull request by AhmedTheGreatest**
## Because

 I had issues using letter opener on WSL. I felt like the solution to the problem I encountered will benefit many other learners.

## This PR

- Added instructions to setup and use the Letter Opener gem on WSL

## Issue

Closes #28386

## Additional Information

If you think anything should be changed, let me know. This is the very first iteration of the change.

## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project curriculum contributing guide](https://github.com/TheOdinProject/curriculum/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [x] The `Because` section summarizes the reason for this PR
-   [x] The `This PR` section has a bullet point list describing the changes in this PR
-   [x] If this PR addresses an open issue, it is linked in the `Issue` section
-   [x] If any lesson files are included in this PR, they have been previewed with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure it is formatted correctly
-   [x] If any lesson files are included in this PR, they follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

### CODE REVIEW

**Comment by AhmedTheGreatest** [comment]
Oh there are Markdown Lint errors, maybe I will try to fix those aswell.

**Comment by MaoShizhong** [comment]
If you can fix those, that'd be awesome. One of two passes of the project fix script should handle most, and you can manually change the first heading to Introduction.

**Comment by AhmedTheGreatest** [comment]
Okay! But, I created this pull request directly from the "Improve this lesson" button, so its not on my machine, how can I clone this, so I can run the project fix scripts?

**Comment by MaoShizhong** [comment]
> Okay! But, I created this pull request directly from the "Improve this lesson" button, so its not on my machine, how can I clone this, so I can run the project fix scripts?

```bash
git fetch origin
```
To update your clone's knowledge of what your remote fork has, including this new branch
```bash
git checkout --track origin/patch-5
```
To create a new local branch that's connected to your remote's `patch-5` branch.

Now you can commit and push to your patch-5 branch as if you created it locally in the first place, and it'll update here as normal.

**Comment by AhmedTheGreatest** [comment]
Okay, thanks alot @MaoShizhong. I will try my best to fix the issues today.

**Comment by AhmedTheGreatest** [comment]
Hello, I have fixed the markdown linting errors. I am so sorry that it took that much time. I was a bit busy with the summer vacation work. There was also a merge conflict, but I fixed it.

**Comment by AhmedTheGreatest** [comment]
I now also now fixed the remaining `MD036` markdown lint error.

**Review by JoshDevHub — APPROVED** [review]
Awesome work! Thank you for adding this.

**Pull request merged**
