### PR TITLE
Links and Images lesson: change relative & absolute links metaphor

### PR DESCRIPTION
**Pull request by tejasnishad**
## Because

This pull request proposes changes to the metaphor used to describe relative and absolute links in order to make it easier to understand.

## This PR

- The metaphor used to describe relative & absolute links in the links and images lesson of the HTML basics section in the foundations course has been changed.
- The use of link paths to explain links in the lesson felt confusing, so the new explanation has been written without link paths.
- I used the metaphor of addresses to explain relative and absolute links, with relative links being addresses as used in conversation (just the name of the street) and absolute links being addresses in correspondence (full address).

## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [x] The `Because` section summarizes the reason for this PR
-   [x] The `This PR` section has a bullet point list describing the changes in this PR
-   [x] If this PR addresses an open issue, it is linked in the `Issue` section
-   [x] If any lesson files are included in this PR, they have been previewed with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure it is formatted correctly
-   [x] If any lesson files are included in this PR, they follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

### CODE REVIEW

**Comment by KevinMulhern** [comment]
The amount of times this metaphor has changed is getting  crazy 😆 

I do think you're version is easier to understand @tejasnishad. But I think it needs to relate back to what the actual relative and absolute urls with examples like the older version does to be effective.

**Comment by tejasnishad** [comment]
Hey! I've added a paragraph with examples, please let me know if there's any other changes to be made.

**Comment by KevinMulhern** [comment]
After having a second look, I'm not sure if this is better than what we already have. @TheOdinProject/maintainers can I get some second opinions please?

Some extra context, there is a [discussion](https://github.com/TheOdinProject/curriculum/discussions/25424) about this content, and I'm positive this metaphor has been completely rewritten at least twice before. When you add up all the time it's taken to review all that, It might be good for us to draw a line under the churn this content has had.

**Comment by tejasnishad** [comment]
Thanks for mentioning the discussion! I wasn't aware of it before, I'll send a message there suggesting this metaphor, and see how it goes.

**Pull request closed without merging**
