### PR TITLE
A Paragaraph explaining box model in simple words

### PR DESCRIPTION
**Pull request by randyortonrko83**
Extended description, can be edited or revised for clarity

Complete the following REQUIRED checkboxes:

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`

Complete the following checkboxes ONLY IF they are applicable to your PR. You can complete them later if they are not currently applicable:
-   [ ] I have previewed all lesson files included in this PR with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure the Markdown content is formatted correctly
-   [ ] I have ensured all lesson files included in this PR follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

<hr>

**1. Because:**

Closes #XXXXX

**2. This PR:**

**3. Additional Information:**

### CODE REVIEW

**Comment by Overlandcoder** [comment]
There's a few typos/missing words in there that I'd love to fix.

**Comment by randyortonrko83** [comment]
> There's a few typos/missing words in there that I'd love to fix.

you are welcome to do that

**Comment by Overlandcoder** [comment]
> > There's a few typos/missing words in there that I'd love to fix.
> 
> you are welcome to do that

I think I'm unable to, since I'm not a Reviewer. Or I'm just not sure how to do it.

**Comment by zachmmeyer** [comment]
Thanks for wanting to contribute! Unfortunately, the content explaining the difference between padding, margin, and border is more along the lines of what we're looking for.

**Pull request closed without merging**
