### PR TITLE
Intermediate HTML and CSS: Provide descriptive link text

### PR DESCRIPTION
**Pull request by T0nci**
## Because

Links need enhanced accessibility and they need to follow the layout style guide.

## This PR

- Changes and improves the links and the sentences they are in
- Fixes style errors

## Issue

Related to #27819

## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project curriculum contributing guide](https://github.com/TheOdinProject/curriculum/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [x] The `Because` section summarizes the reason for this PR
-   [x] The `This PR` section has a bullet point list describing the changes in this PR
-   [x] If this PR addresses an open issue, it is linked in the `Issue` section
-   [ ] If any lesson files are included in this PR, they have been previewed with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure it is formatted correctly
-   [ ] If any lesson files are included in this PR, they follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

### CODE REVIEW

**Comment by T0nci** [comment]
Additional notes: I found that in CSS Functions lesson, on line 129 the text for replacing doesn't fully match the "Original text" cell in the spreadsheet, but I replaced it anyway since it looked exactly the same but without a few words.
image

**Review by MaoShizhong — CHANGES_REQUESTED** [review]
Thank you for getting the links sorted, @T0nci! The spreadsheet error was my mistake, probably an edit I made at some point to one cell but not properly to the "original text" cell. What you did was :ok_hand: 

Would you mind fixing up the remaining lint errors in both files? They should be pretty self explanatory.
Most should be fixable by following the curriculum repo's contributing guide to use the npm scripts for fixing. There will still be a few errors that can't be auto-fixed, e.g. the default section content, and ordered list prefixes. So if after running the fixer, you could manually fix the remaining ones, that'd be awesome!

Do let me know if you run into any issues!

**Comment by T0nci** [comment]
@MaoShizhong Will do that tommorow ASAP! Just reread the curriculum repo's contributing guide and it has everything I need to get the changes done.

I'm very sorry for not doing this sooner! I had done a few contributions to some lessons/projects a few weeks ago and never did the linting step then as they were simple rewording changes. But know I will know to do the linting step every time I contribute to this repo as it's a simple yet very important step to do.

**Comment by MaoShizhong** [comment]
> @MaoShizhong Will do that tommorow ASAP! Just reread the curriculum repo's contributing guide and it has everything I need to get the changes done.
> 
> I'm very sorry for not doing this sooner! I had done a few contributions to some lessons/projects a few weeks ago and never did the linting step then as they were simple rewording changes. But know I will know to do the linting step every time I contribute to this repo as it's a simple yet very important step to do.

No rush at all! If of course you end up swamped with stuff and things might take a while, let us know. We can always reassign things if we really need to. But generally speaking, there's no rush - we're all volunteers here!

At least running the lint checker is good by default; if you're not sure if you should or how you should fix any errors, you can always ask about it in your PR. Only recently did we implement the things that've made this process a lot simpler for people. Hopefully, as more PRs come in, there will be fewer and fewer existing lint errors which will make things easier to manage as a whole.

**Comment by T0nci** [comment]
@MaoShizhong A problem I ran into is having raw HTML(a lone <br> tag) in the css_functions lesson. I fixed it by adding a new line in it's place, but I don't know if this is an accepted fix and a desired outcome.

I see the Knowledge check default text now needs to be reworded in every lesson. The new sentence is more reassuring(to me at least as I had spent and am spending a lot of time worrying if I had been lazy by going through the lesson faster than other lessons and not figuring things out) and informative and I very much like it.

Also the Additional resources default text had me tripping. The text was the same as the expected default text, but it was still flagging as an error. It took me a few minutes to figure out that "isn't" isn't the same as "isn`t" lol.

**Review by MaoShizhong — APPROVED** [review]
All looks good to me, @T0nci, thank you very much!

About the `<br>` tag, your change was the right move :+1: Some parts of some lessons have been untouched for quite a while and there are some inconsistencies or practices we know no longer enforce as per the current style guide and linter, e.g. `<br>` tags are disallowed by the linter.
If you want a line break, it probably should be in a new paragraph anyway so a blank line is the best and actually looks a heck of a lot better as below:
image

**Comment by T0nci** [comment]
What about the commit that mentions "merged main into branch"? I don't know if that's normal because when I merged it yesterday it didn't show any commits, but today it did.

**Comment by MaoShizhong** [comment]
That commit is made when the merge happens, and normally shows - not an issue at all, since we (the team) typically squash before merging PRs into main. I'm not 100% sure why it didn't show up the first time - possibly there were no changes to merge when that was done so there was nothing for it to create a merge commit for.

**Pull request merged**
