### PR TITLE
Added the html tag for button with id=btn to the html file for method 2&3 explanation

### PR DESCRIPTION
**Pull request by caleb-munyasya**
- [X] You have read [The Odin Projects Contributing Guide](https://github.com/TheOdinProject/curriculum/blob/main/CONTRIBUTING.md).
 - [X] The title summarizes the change and where it happened, for example: "Fixes punctuation in Clean Code lesson".
 - [x] If the PR is related to an open issue, use a [relevant keyword](https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests) and reference it with the `#` sign and the issue number.
- [x] If changes are requested, please make the changes in a timely manner. After you submit the changes, request another review from the maintainer (top right).

#### 1.Describe the changes made and include why they are necessary or important:

I added the button tag with id = btn  to the html file example for clarification 

#### 2. Related Issue

keyword #XXXXX

### CODE REVIEW

**Comment by wise-king-sullyman** [comment]
@caleb-munyasya in any future PRs please reference the lesson name in the PR title, it makes things a bit easier to manage on our end :slightly_smiling_face:

**Review by wise-king-sullyman — CHANGES_REQUESTED** [review]
Since the redeclaration of the `btn` constant is also omitted from the JS in this example, I think that we should add it as well if we're adding in the related HTML for clarity.

Alternatively, I'm debating if adding these details back in is substantial, was this something that caused you a fair amount of confusion?

**Comment by twalton83** [comment]
@caleb-munyasya Do you mind addressing the above?

**Comment by caleb-munyasya** [comment]
Hey, I remember getting stuck for about 5-10 mins. Not sure if that is considered substantial!?

**Comment by wise-king-sullyman** [comment]
@caleb-munyasya if it had you stuck for 5-10 minutes I think that a change could be worthwhile.

If you add the item I requested in my previous comment I think this should then be good to go. If you have any questions about how to do so please ask them.

**Comment by wise-king-sullyman** [comment]
@caleb-munyasya are you interested in addressing the changes I requested?

If not (or we don't hear from you within the next week) I will close this pull request.

**Comment by wise-king-sullyman** [comment]
I am closing this PR as previously stated. If you think this is something that still needs to be addressed please file an issue or open another PR to do so.

**Pull request closed without merging**
