### PR TITLE
Add my solutions

### PR DESCRIPTION
**Pull request by brannj**

### CODE REVIEW

**Comment by craftykate** [comment]
@brannj Slight issue (sorry!) but your two links are the same. Please change your second link to the enumerables one instead of bubble sort and I'll merge them.

**Comment by brannj** [comment]
@craftykate Sorry. Thanks again for your help.

**Comment by craftykate** [comment]
@brannj Sure! We can't be _totally_ perfect or we'll make everyone else jealous. =)

**Comment by brannj** [comment]
@craftykate hahaha :)

**Pull request merged**
