### PR TITLE
Update from legacy doc

### PR DESCRIPTION
**Pull request by asdacosta**
## Because
Replace legacy documentation link which is no longer updated to the current one.

## This PR

- Change legacy documentation to the current one.

## Issue

Closes #XXXXX

## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project curriculum contributing guide](https://github.com/TheOdinProject/curriculum/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [x] The `Because` section summarizes the reason for this PR
-   [x] The `This PR` section has a bullet point list describing the changes in this PR
-   [x] If this PR addresses an open issue, it is linked in the `Issue` section
-   [x] If any lesson files are included in this PR, they have been previewed with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure it is formatted correctly
-   [x] If any lesson files are included in this PR, they follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

### CODE REVIEW

**Comment by CouchofTomato** [comment]
There seems to be a linting failure. Would you mind addressing that in this PR?

**Comment by asdacosta** [comment]
> There seems to be a linting failure. Would you mind addressing that in this PR?

I can't change the js to javascript since it's a link and doing that will distort it.

**Comment by CouchofTomato** [comment]
> > There seems to be a linting failure. Would you mind addressing that in this PR?
> 
> I can't change the js to javascript since it's a link and doing that will distort it.

A link?

**Comment by asdacosta** [comment]
> > > There seems to be a linting failure. Would you mind addressing that in this PR?
> > 
> > 
> > I can't change the js to javascript since it's a link and doing that will distort it.
> 
> A link?

Yes. I think it's from this 'https://reactjs'

**Comment by CouchofTomato** [comment]
This doesn't look like a link to me in the markdown. It might be a github thing you're seeing.

**Comment by asdacosta** [comment]
> This doesn't look like a link to me in the markdown. It might be a github thing you're seeing.

I did not copy the full link, I was trying to highlight where I think the problem is from. The link does contain 'js' which from the error, it says it is supposed to be 'javascript' rather.

**Comment by CouchofTomato** [comment]
The markdown itself doesn't look like a link. You just need to change `js` to `javascript`

image

**Comment by asdacosta** [comment]
> The markdown itself doesn't look like a link. You just need to change `js` to `javascript`
> 
> image

Ok
Should I close the PR and create another one with the update?

**Comment by CouchofTomato** [comment]
You should just be able to make the change and push up.

**Comment by asdacosta** [comment]
> You should just be able to make the change and push up.

Done.

**Review by CouchofTomato — APPROVED** [review]

**Pull request merged**
