### PR TITLE
Add my Javascript/Jquery File

### PR DESCRIPTION
**Pull request by NikhilSurana**

### CODE REVIEW

**Comment by craftykate** [comment]
@NikhilSurana  Same issue as your last pull request. We need a link to your code. See my other comments for info on how to do that. I'm closing all these, but please open new ones and let me know if I can help.

**Comment by craftykate** [comment]
@NikhilSurana And please don't be discouraged! Github can be tricky to understand at first. Everyone here is learning.

**Comment by NikhilSurana** [comment]
I can't merge my pull request. What should I do please help me on this

**Comment by muzfuz** [comment]
Hi Nikhil, you have submitted your pull request - one of the admins will review it, and either we will merge it or send back comments in case there are changes to be made.

**Comment by NikhilSurana** [comment]
Ok, Thanks

**Pull request closed without merging**
