### PR TITLE
docs: Added comments for custom markdown rules in .markdowndlint-cli2…

### PR DESCRIPTION
**Pull request by akhilmohnn**
**## Because**
This PR aims to improve clarity within the `.markdowndlint-cli2.jsonc` file by adding comments that explain the purpose of each custom markdown rule used in the project. This helps contributors and maintainers understand the specific rules being enforced.

**## This PR**
- Added detailed comments for each custom rule listed in the `customRules` section.
- Improved documentation within the configuration file to make it more user-friendly.

**## Issue**
This PR does not close any specific issue but contributes to the overall quality and maintainability of the project.

**## Additional Information**
No additional changes were made beyond adding comments.

**## Pull Request Requirements**
- [x] I have thoroughly read and understand [The Odin Project curriculum contributing guide](https://github.com/TheOdinProject/curriculum/blob/main/CONTRIBUTING.md).
- [x] The title of this PR follows the `location of change: brief description of change` format.
- [x] The `Because` section summarizes the reason for this PR.
- [x] The `This PR` section has a bullet point list describing the changes in this PR.
- [x] No specific issue is addressed by this PR.
- [x] Changes were previewed to ensure proper formatting.
- [x] Changes follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md).

Allow edits by maintainers.

### CODE REVIEW

**Review by MaoShizhong — CHANGES_REQUESTED** [review]
Thanks for this PR. For the sake of potential changes to our own rules, I'd prefer that instead of per-rule comments, we instead just have the comment for the array itself amended to something like:

```jsonc
// Custom rules specific to the project
// Docs for each rule can be found in `./markdownlint/docs`
```

With the built-in rules, we can't make changes to the rules themselves, only what setting, and the names of the rules aren't attached to their codes, hence the more descriptive comments. Our rules array has more descriptive rule names anyway which the comments essentially just repeat.

**Comment by akhilmohnn** [comment]
Thank you for the feedback! I’ve updated the .markdowndlint-cli2.jsonc file to include a single general comment for the custom rules array, as suggested. Let me know if there’s anything else I can adjust.

**Comment by MaoShizhong** [comment]
> Thank you for the feedback! I’ve updated the .markdowndlint-cli2.jsonc file to include a single general comment for the custom rules array, as suggested. Let me know if there’s anything else I can adjust.

Looks like you forgot to push the commits? This branch hasn't been updated with any changes.

**Comment by MaoShizhong** [comment]
Superceded by #29018

**Pull request closed without merging**
