### PR TITLE
foundation/CSSfoundation

### LINKED ISSUE #24330: Style Guide - Foundations/CSS Foundations: Lists and Code Blocks
# Foundations/CSS Foundations Section

This issue is part of the Style Guide Community Project, a way of offering members of The Odin Project community a chance to contribute to our curriculum. Users who wish to take part and contribute to any Style Guide issues should have thoroughly read the [layout style guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md) and [The Odin Project contributing guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md).
  
## Description of Issue

This issue ensures that any lists (numbered or bulleted) and codeblocks are properly formatted.

Each applicable lesson for this issue should meet the following bulleted requirements:

- All numbered lists are numbered properly per the style guide, including:
    - Lesson Overview, Knowledge Check, and Additional Resources sections all use bulleted lists
    - The Assignment section in lessons or projects uses numbered lists for their main content, and bulleted lists for sub-items.
    - The Extra Credit sub-section in project Assignments use only bulleted lists
- All lists have the proper whitespace between the list marker (e.g. `*` or `1.`) and the item text (see Nested List Spacing section of style guide)
- All lists are properly indented.
- All codeblocks have an explicit language declared.
	- If a codeblock combines multiple languages, each language is given its own codeblock with the correct language declared.
- Codeblocks that are a part of a list are properly indented.
 
## Acceptance Criteria

- [ ] The following lessons are updated according to the issue description above:
	- [ ] [CSS Foundations](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/css-foundations)
	- [ ] [Inspecting HTML and CSS](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/inspecting-html-and-css)
	- [ ] [The Box Model](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/the-box-model)
	- [ ] [Block and Inline](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/block-and-inline)

### PR DESCRIPTION
**Pull request by ritikaaaa177**
Complete the following REQUIRED checkboxes:

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`

Complete the following checkboxes ONLY IF they are applicable to your PR. You can complete them later if they are not currently applicable:
-   [ ] I have previewed all lesson files included in this PR with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure the Markdown content is formatted correctly
-   [x] I have ensured all lesson files included in this PR follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

<hr>

* This pr is related to  issue  https://github.com/TheOdinProject/curriculum/issues/24330

closes #24330

### CODE REVIEW

**Comment by ritikaaaa177** [comment]
@thatblindgeye please have a look

**Review by thatblindgeye — CHANGES_REQUESTED** [review]
Thank you for wanting to contribute! It looks like there are a few issues with the PR:

- Per the style guide, there should be multiple whitespaces between list markers (`*`  or `-` for bullets, `1.` for numbers), but the changes made remove them. For example, The block and inline file's first list item should be `*   You'll learn about "Normal flow."` (3 white spaces after the asterisk) rather than `* You'll learn about "Normal flow."` (1 whitespace after the asterisk).
- There are files changed not part of the original issue that need to be reverted and removed from this PR, as another contributor is working on those files.
- We want to preserve the original PR template, and when linking an issue to a PR we want to keep the `Closes` keyword before the issue number, so that merging the PR automatically closes the issue.

**Comment by ritikaaaa177** [comment]
have a look @thatblindgeye i have made the required changes

**Review by zachmmeyer — APPROVED** [review]
Thank you for contributing.

**Pull request merged**
