### PR TITLE
Update setting_up_git to configure default editor

### PR DESCRIPTION
**Pull request by crespire**
- [x] You have read [The Odin Projects Contributing Guide](https://github.com/TheOdinProject/curriculum/blob/main/CONTRIBUTING.md).
 - [x] The title summarizes the change and where it happened, for example: "Fixes punctuation in Clean Code lesson".
 - [x] If the PR is related to an open issue, use a [relevant keyword](https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests) and reference it with the `#` sign and the issue number.
- [x] If changes are requested, please make the changes in a timely manner. After you submit the changes, request another review from the maintainer (top right).

#### 1.Describe the changes made and include why they are necessary or important:

Adds a small section on configuring VSCode as the default editor for git.

#### 2. Related Issue
none

### CODE REVIEW

**Comment by marvingay** [comment]
Why is this change necessary or important?

I question if we should enforce an editor for `git`. The "advanced commands" that are being mentioned are unknown / ambiguous at the time and the utility of imposing this upon the user is highly subjective.

Additionally, there's a minor argument to be made about how using not-VSCode (and consequently not enforcing this settings change) is beneficial long-term as it provides exposure and usage of an editor that you may have to use in the real world anyway (e.g. SSH'ing into some server and only having nano or vi at your disposal).

**Comment by twalton83** [comment]
@marvingay i think we get a non insignificant amount of users stuck in vim and nano when they forget the -m flag in a commit who get confused and I think just using VSC here is beneficial.

**Comment by crespire** [comment]
I think @marvingay makes a lot of good points, but I do feel that, given the _target_ audience of the course in general, setting up VSCode as the default editor would be a somewhat prudent choice.

At this point in the course, folks may not even be comfortable in command line, so this change may help to ease people into "doing the dev thing." As people grow in their depth of knowledge, folks will figure out they can change the setting to whatever their preference is.

That being said, I think Marvin's point is valid, and perhaps changing the language so that it's clear this setting is a user preference might be a good change. That way, it isn't so much as enforcing VSCode as a default editor, but rather setting up users for success in a new endeavour.

**Comment by crespire** [comment]
I'm going to close this pull request, as I think there are changes in the git lessons that have made this obsolete, or at least misplaced.

Thanks for your input @marvingay and @twalton83!

**Pull request closed without merging**
