### PR TITLE
Please add my solution to HTML / CSS exercise

### PR DESCRIPTION
**Pull request by shrobbins**

### CODE REVIEW

**Comment by hgducharme** [comment]
You put your solution at the end of an already existing line. Please put your solution on it's own line, right above the "Put your solution above this line!" sentence. Once you fix that i'll be able to merge it in.

**Comment by shrobbins** [comment]
Thanks that makes sense.  I have just changed it.

Sue

**Comment by hgducharme** [comment]
Make sure you commit the change to your branch. It still shows that it's not properly formatted

**Comment by shrobbins** [comment]
Okay I think I have done it.

**Comment by hgducharme** [comment]
There you go, nice work

**Comment by shrobbins** [comment]
I just viewed the page online.  Mine does not show and the two people’s at the end of the list do not look right.
I will not touch anything as this is the first time I have tried to pull something up to Github.

**Comment by hgducharme** [comment]
It works for me, not sure why it's not showing up on your end

**Comment by shrobbins** [comment]
Yes I see mine on the github page it just does not show online.  The entry above though…one persons files do not show and the other one’s show twice.  Not sure if that was me.

**Pull request merged**
