### PR TITLE
Add my solution!

### PR DESCRIPTION
**Pull request by corneal64**
```
This is a PR template, If you are adding a solution link to the curriculum leave this as is. If you are not, then delete it and write the message you wish.
Thank you,
The Odin Project team.
```

### CODE REVIEW

**Comment by KevinMulhern** [comment]
Hey @corneal64, it seems your fork is very out of date with the curriculum, there should be a lot more student solutions than what are on the file you are submitting. You need to pull in changes from the curriculum upstream, add your solution and then make a pull request.

**Comment by corneal64** [comment]
Hi @KevinMulhern, how do I pull the new changes and update my fork of the repo?

**Comment by KevinMulhern** [comment]
It's too much to explain over this, can you please google your queries or go into our slack chat and ask for help.

**Comment by KevinMulhern** [comment]
Closed due to inactivity

**Pull request closed without merging**
