### PR TITLE
Javascript/Rails Final Projects: update links to more current resources

### LINKED ISSUE #25164: Full Stack Javascript, Final Project: LInks in the lesson should be updated.
### Describe your suggestion

The links here are very old, referencing Rails 5. We should find updated articles that provide similar content.

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-javascript-javascript-final-project

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### (Optional) Discord Name

crespire#8269

### (Optional) Additional Comments

_No response_

### PR DESCRIPTION
**Pull request by crespire**
## Because
Links in the lesson referenced older versions of Rails and were out of date.

## This PR
Updates a few links as well as adds a couple more.

## Issue
Closes #25164 

## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [x] The `Because` section summarizes the reason for this PR
-   [x] The `This PR` section has a bullet point list describing the changes in this PR
-   [x] If this PR addresses an open issue, it is linked in the `Issue` section
-   [x] If any lesson files are included in this PR, they have been previewed with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure it is formatted correctly
-   [x] If any lesson files are included in this PR, they follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

### CODE REVIEW

**Review by wise-king-sullyman — CHANGES_REQUESTED** [review]
Thanks for taking the time to put these forwards.

After looking at it we're actually leaning towards removing all of the additional resources here. You're definitely right that those ones you're looking to remove are outdated, but we feel that the new resources you've suggested aren't a great fit and that the firebase and typescript resources actually aren't great fits either.

Regarding the rails 7 + react article from DO that we would actually like to see moved to the [rails course version of the "Using Rails for your Backend" lesson](https://www.mongodb.com/languages/mern-stack-tutorial).

Would you like to update this PR to move that resource and just remove all of the others here?

**Comment by crespire** [comment]
> Thanks for taking the time to put these forwards.
> 
> After looking at it we're actually leaning towards removing all of the additional resources here. You're definitely right that those ones you're looking to remove are outdated, but we feel that the new resources you've suggested aren't a great fit and that the firebase and typescript resources actually aren't great fits either.
> 
> Regarding the rails 7 + react article from DO that we would actually like to see moved to the [rails course version of the "Using Rails for your Backend" lesson](https://www.mongodb.com/languages/mern-stack-tutorial).
> 
> Would you like to update this PR to move that resource and just remove all of the others here?

I am happy to move the Rails link to the appropriate lesson.

As for the TypeScript link, I do feel it is worthwhile to keep and I am curious as to why the link is slated for removal.

I'm the contributor that originally added the Typescript link. My reasoning for including it here was that at this point folks would have enough JS and React context it to be useful, rather than a distraction.

**Comment by crespire** [comment]
I've updated the link re: Rails 7 to the "Rails as a Backend" lesson in the Rails/React section. I removed the MERN stack tutorial link, as I know in the JS path Node is after and full MERN at this point might be too much.

Based on the request for the Rails link move, I have actually moved the Typescript resource to the conclusion of the Node section after Odinbook. I neglected to consider that there was a whole Node.JS section coming up in the JS course, and maybe Typescript at this time (after React, but before Node.js) might not be appropriate after all. The node section conclusion feels like a more appropriate for that link.

I did remove the Firebase link as well, as requested. I hope that my changes are acceptable.

**Review by wise-king-sullyman — APPROVED** [review]
You make a good point, having it after odin book makes sense! Thanks for making these changes!

**Pull request merged**
