### PR TITLE
Command Line Basics lesson: Fix sub-sub-subheading rendering error

### PR DESCRIPTION
**Pull request by Objectivitix**
Complete the following REQUIRED checkboxes:

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`

Complete the following checkboxes ONLY IF they are applicable to your PR. You can complete them later if they are not currently applicable:
-   [x] I have previewed all lesson files included in this PR with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure the Markdown content is formatted correctly
-   [x] I have ensured all lesson files included in this PR follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

<hr>

**1. Because:**

Currently, the "Opening files in VSCode from the Command Line" section in `foundations/installations/command_line_basics.md` has a sub-sub-subheading ("MacOS Users:") that doesn't render correctly on the site.
image

**2. This PR:**

- Uses bold text instead to head the two paragraphs, making this section easier to read
- Rephrases slightly to improve flow

**3. Additional Information:**
N/A

### CODE REVIEW

**Comment by 01zulfi** [comment]
@Objectivitix Are you still willing to commit the requested changes?

**Comment by zachmmeyer** [comment]
image
Looks good to me, closing.

**Comment by Objectivitix** [comment]
Hey everyone! First of all, I apologise for the late response. This PR is so buried in the obscure corners of the repository that I forgot it exists 😄

My bad. I'm currently on a trip, I'll be back and have access to my computer tomorrow, so I'll be sure to implement the requested changes. Thank you for your patience.

**Comment by zachmmeyer** [comment]
@Objectivitix Take your time. We'll check again when this ticket achieves a stale label.

**Comment by Objectivitix** [comment]
@01zulfi @zachmmeyer All requested changes committed.

**Review by zachmmeyer — APPROVED** [review]
This looks great! Thank you!

**Pull request merged**
