### PR TITLE
fix typo in factory function

### PR DESCRIPTION
**Pull request by osamamammar**
- [x] You have read [The Odin Projects Contributing Guide](https://github.com/TheOdinProject/curriculum/blob/main/CONTRIBUTING.md).
 - [x] The title summarizes the change and where it happened, for example: "Fixes punctuation in Clean Code lesson".
 - [x] If the PR is related to an open issue, use a [relevant keyword](https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests) and reference it with the `#` sign and the issue number.
- [x] If changes are requested, please make the changes in a timely manner. After you submit the changes, request another review from the maintainer (top right).

#### 1.Describe the changes made and include why they are necessary or important:

I found the letter "s" here is unimportant and unnecessary, especially since it has a strange shape during reading.

#### 2. Related Issue

fix typo in factory function #23070

### CODE REVIEW

**Review by DevlinRocha — CHANGES_REQUESTED** [review]
Instead of removing the "S" I think it would be better to use an apostrophe to make it appear like this:

`console.log`'s

**Comment by osamamammar** [comment]
It's okay. thank you. @DevlinRocha

**Comment by fortypercenttitanium** [comment]
> Instead of removing the "S" I think it would be better to use an apostrophe to make it appear like this:
> 
> `console.log`'s

As I mentioned earlier, this is actually not technically correct grammar. Thanks for the suggestions everyone, but I'm closing this.

**Comment by DevlinRocha** [comment]
> As I mentioned earlier, this is actually not technically correct grammar. Thanks for the suggestions everyone, but I'm closing this.

I'm sorry, I never saw another mention of this issue anywhere. I must have missed it.

**Pull request closed without merging**
