### PR TITLE
Added files via upload

### PR DESCRIPTION
**Pull request by alessandraz**
```
This is a PR template, If you are adding a solution link to the curriculum leave this as is. If you are not, then delete it and write the message you wish.
Thank you,
The Odin Project team.
```

google page project

### CODE REVIEW

**Comment by alessandraz** [comment]
google page project

**Comment by KevinMulhern** [comment]
Hey @alessandraz, you are requesting to add the files for your google home page project. This is not what you should have done. You should instead add a link to your project repo on github to the google home page project page on odin.

**Comment by alessandraz** [comment]
Oh, I din't understand. Sorry about that.

**Comment by KevinMulhern** [comment]
No Worries, if you need help jump on the Odin slack chat :smile:

**Pull request closed without merging**
