### PR TITLE
Foundations, Introduction to HTML & CSS: Fix broken link in assignment

### PR DESCRIPTION
**Pull request by scheals**
Complete the following REQUIRED checkboxes:

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`

Complete the following checkboxes ONLY IF they are applicable to your PR. You can complete them later if they are not currently applicable:
-   [ ] I have previewed all lesson files included in this PR with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure the Markdown content is formatted correctly
-   [ ] I have ensured all lesson files included in this PR follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

<hr>

**1. Because:**
The site currently is experiencing some issues.
Related bug reports:
https://discord.com/channels/505093832157691914/1029374285929795585/1029374285929795585
https://discord.com/channels/505093832157691914/505093832157691916/1030422258344267876

**2. This PR:**
Changes the link to a wayback machine one so the site is accessible.

**3. Additional Information:**

### CODE REVIEW

**Review by 01zulfi — COMMENTED** [review]
The link seems to work for me. Can you confirm if this is the case?

**Comment by scheals** [comment]
> The link seems to work for me. Can you confirm if this is the case?

I guess I shouldn't have said "so the site is accessible" because it *is* accessible, it just is unreadable. It is possible to circumvent this by turning on Reader Mode in the browser and refreshing a few times buuuut yeah.

errors everywhere

**Review by 01zulfi — APPROVED** [review]
Unfortunately, I'm unable to reproduce the issue. But looking at the discord chats you linked, I'm merging this to be on the safe side.

**Comment by scheals** [comment]
> Unfortunately, I'm unable to reproduce the issue. But looking at the discord chats you linked, I'm merging this to be on the safe side.

I think there's an eventListener that triggers on hover that makes the page fold like on the screenshot, it doesn't happen on page load. Once again, I should've been more precise with my description of what's happening, apologies!

I managed to reproduce the issue on:
Firefox, both Xubuntu and Windows,
Edge, Windows,
Chrome, Xubuntu.

**Pull request merged**
