### PR TITLE
added more description about screen sizes to wheres-waldo project des…

### PR DESCRIPTION
**Pull request by ForkEyeee**
…cription

## Because

The wheres waldo project is a photo tagging app, where clicking on an area of the image produces coordinates. However, the project description doesn't mention the fact that the game could be broken for those on mobile if it was designed solely with desktop in mind. Different desktop sizes are also similar in this regard, they will generate different coordinates onclick. 

This is one of the last few projects of the nodejs section and can be considered a portfolio project, so it should work fine on all screen sizes. Nodejs is a backend course, but the app could potentially be unusable depending on the screen that is accessing it. This is not the same as a web app simply not being responsive, because atleast it is still functional.

## This PR

* Added an extra line to the project description to discuss the issue with designing wheres waldo for one screen size.

## Issue

Closes #XXXXX

## Pull Request Requirements

-   [ ] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
-   [ ] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [ ] The `Because` section summarizes the reason for this PR
-   [ ] The `This PR` section has a bullet point list describing the changes in this PR
-   [ ] If this PR addresses an open issue, it is linked in the `Issue` section
-   [ ] If any lesson files are included in this PR, they have been previewed with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure it is formatted correctly
-   [ ] If any lesson files are included in this PR, they follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

### CODE REVIEW

**Comment by ManonLef** [comment]
Thank you for making this suggestion! 

I would like some input from the more experienced NodeJS @TheOdinProject/javascript maintainers please. I am worried about this possibly being too instructive at that point in the curriculum. Responsiveness is covered well by that point, and I could see changing window/screen size might be part of something everyone should check. But I could be wrong of course. 

Thanks for your patience!

**Comment by ForkEyeee** [comment]
> Thank you for making this suggestion!
> 
> I would like some input from the more experienced NodeJS @TheOdinProject/javascript maintainers please. I am worried about this possibly being too instructive at that point in the curriculum. Responsiveness is covered well by that point, and I could see changing window/screen size might be part of something everyone should check, including functionality attached to it (even though you mentioned it not simply being a responsiveness issue this is still a concern of mine). But I could be wrong of course for not understanding the full scope of said project.
> 
> Thanks for your patience!

Sure no problem. Additional input would be great

**Comment by codyloyd** [comment]
@ForkEyeee how this works depends exactly on how you've coded the coordinate-grabbing stuff...  WIll you please add a little disclaimer to your addition?

something like this:
> Depending on how you are getting the coordinates of a user's clicks, different screen sizes may produce different coordinates ........... so you may need to implement methods to normalize........


feel free to make the specific wording more natural.

**Comment by ForkEyeee** [comment]
@codyloyd 

Hi, I added a note under the line about validating coordinates with the database which talks about the screensize problem and how they may want to resolve it.

**Comment by codyloyd** [comment]
beautiful.  thanks 😄

**Comment by ForkEyeee** [comment]
and thanks to you two @codyloyd @ManonLef

**Pull request merged**
