### PR TITLE
Update project_rails.md

### PR DESCRIPTION
**Pull request by KelvinStone**

### CODE REVIEW

**Comment by KevinMulhern** [comment]
Hi Kelvin, are you deleting someone else's solution?

**Comment by KelvinStone** [comment]
That's a mistake. I must have clicked 'cut' instead of 'copy'. I only want to add my solution.

**Comment by KevinMulhern** [comment]
Could you update this PR by putting the other students solution back in? or make a new Pull request with just your solution added please :)

**Comment by KelvinStone** [comment]
I’ll make a new pull request.

**Pull request closed without merging**
