### PR TITLE
Corrected the link to my etch-a-sketch jquery project

### PR DESCRIPTION
**Pull request by Kr0ntar**
```
This is a PR template, If you are adding a solution link to the curriculum leave this as is. If you are not, then delete it and write the message you wish.
Thank you,
The Odin Project team.

```

### CODE REVIEW

**Comment by leosoaivan** [comment]
Break up the link to the repositories for the easy and difficult versions of the project, such as:
`Leonard's solution (Easy) | Leonard's solution (Difficult)`

**Comment by Kr0ntar** [comment]
My apologies.  My first time to contribute. Thanks for the advice. :)

**Comment by 105ron** [comment]
No problems @Kr0ntar . All fixed and added to the repository. Should be able to view it on the site tomorrow. 🎉

**Comment by Kr0ntar** [comment]
Thank you @Rhys.

**Pull request merged**
