### PR TITLE
Add Additional Resources to the page

### PR DESCRIPTION
**Pull request by marcusicaro**
An article from W3Schools regarding HTML text with some exercises in the end.

Complete the following REQUIRED checkboxes:

-   [x ] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x ] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`

Complete the following checkboxes ONLY IF they are applicable to your PR. You can complete them later if they are not currently applicable:
-   [x] I have previewed all lesson files included in this PR with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure the Markdown content is formatted correctly
-   [x] I have ensured all lesson files included in this PR follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

<hr>

**1. Because:**

Closes #XXXXX

**2. This PR:**

**3. Additional Information:**

### CODE REVIEW

**Review by wise-king-sullyman — CHANGES_REQUESTED** [review]
Thank you for making this PR!

One change I would like to see: the text you've used in the link isn't accessible to all users. Please take a look at this [resource about link text and accessibility from WebAIM](https://webaim.org/techniques/hypertext/#screen_readers) and adjust the link text you've used accordingly, then it should be good to merge 🙂

**Comment by marcusicaro** [comment]
All right! I'll it as soon as I get home from work.

Thanks!

**Comment by marcusicaro** [comment]
@wise-king-sullyman When I try to click "Mark as solved" inside the "Resolve conflicts" screen, "Mark as solved" is greyed out. I've created another pull request changing the "link" for better understanding of visual impaired people.

If I'm not doing it rightly, please guide me towards how I can better solve this. 

Thanks again!

**Review by marcusicaro — COMMENTED** [review]
@@ -185,5 +185,4 @@ This section contains questions for you to check your understanding of this less

This section contains helpful links to related content. It isn’t required, so consider it supplemental.

*   [HTML Text Formatting](https://www.w3schools.com/html/html_formatting.asp) article from W3Schools contains some great exercise to practice working with text in HTML.

**Comment by wise-king-sullyman** [comment]
@marcusicaro did you make a new PR? If so can you link it? I could very well be missing it, but I'm not seeing a new PR from you.

**Comment by marcusicaro** [comment]
Hey, @wise-king-sullyman , thanks for answering. Figured out I didn't create a PR before.

Here's the link for the pull request: https://github.com/TheOdinProject/curriculum/pull/24725

**Comment by wise-king-sullyman** [comment]
Closing this PR as a new PR with the same changes has been made.

**Pull request closed without merging**
