### PR TITLE
React States and Effects lessons: Convert triple tildes to triple backticks for codeblocks

### LINKED ISSUE #27459: React: Update codeblock delimiters
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

Codeblocks should be updated to align with new changes in our [layout style guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

In the sections named in this issue, codeblocks will be opened by a set of 3 tildes (the ~ character) and then closed by another set of 3 tildes. To align with the style guide, these tilde characters need to change to backticks (the ` character). Be sure to refer to [the codeblocks section](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md#codeblocks) of the style guide for an example of what this should look like.
## Guidance:
- Comment on this issue to get a section assigned to you. You can also ask for a specific one
- Please wait until you are assigned by a maintainer before starting to work on this issue to avoid multiple people working on the same sections
- Make sure to read the [contributing guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md) before starting your first contribution
- Please add the following to your PR in the Issues section: Related to #xxxxx, since this issue is divided into sections, individual PRs should NOT INCLUDE the closes keyword.
- **Please ensure that you update the delimiters in every listed lesson of the section you are assigned to.**

### [Getting Started With React (4 lessons)](https://www.theodinproject.com/paths/full-stack-javascript/courses/react#getting-started-with-react)
- [x] @Churtified  `React Components`, `What is JSX?`, `Rendering Techniques`, `Passing Data Between Components`

### [States and Effects(3 lessons)](https://www.theodinproject.com/paths/full-stack-javascript/courses/react#states-and-effects)
- [x] @marlatte  `Introduction to State`, `More on State`, `How to Deal with Side Effects`

### [Class Components (2 lessons)](https://www.theodinproject.com/paths/full-stack-javascript/courses/react#class-components)
- [x] @roopxx `Class Based Components`, `Component Lifecycle Methods`

### [React Testing (2 lessons)](https://www.theodinproject.com/paths/full-stack-javascript/courses/react#react-testing)
- [x] @kamranzafar4343 `Introduction to React Testing`, `Mocking Callbacks and Components`

### [The React Ecosystem (3 lessons)](https://www.theodinproject.com/paths/full-stack-javascript/courses/react#the-react-ecosystem)
- [x] @ParagPalkar `Project Shopping Cart`, `React Router`, `Type Checking with Proptypes`

### [More React Concepts (3 lessons)](https://www.theodinproject.com/paths/full-stack-javascript/courses/react#more-react-concepts)
- [x] @Ervin001 `Managing State with Context API`, `Reducing State`, `Refs and Memoization`

@JoshDevHub

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/paths/full-stack-javascript/courses/react

### PR DESCRIPTION
**Pull request by marlatte**
## Because

New changes in Odin's [layout style guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md#codeblocks) require updating the way codeblocks are written in lesson markdown. This PR addresses updates to the React course's section on States and Effects.

## This PR

- Replace triple tildes (~~~) with triple backticks (```) to delimit codeblocks in 3 files within `react/states_and_effects`

## Issue

Related to #27459 

## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [x] The `Because` section summarizes the reason for this PR
-   [x] The `This PR` section has a bullet point list describing the changes in this PR
-   [x] If this PR addresses an open issue, it is linked in the `Issue` section
-   [x] If any lesson files are included in this PR, they have been previewed with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure it is formatted correctly
-   [x] If any lesson files are included in this PR, they follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

### CODE REVIEW

**Comment by marlatte** [comment]
Is there a way to use the markdownlint extension for VSCode or corresponding eslint plugin with Odin's custom rules? I see the `.markdownlint-cli2.jsonc` file in the root `curriculum` folder, but I don't know how to run it.

**Review by JoshDevHub — COMMENTED** [review]
Looks great! @marlatte 

Would you be okay with fixing the other lint errors in these files? It seems that they're all related to list styles or blank lines, so should be pretty simple to fix.

**Comment by marlatte** [comment]
Yeah I'll happily take care of the rest! Should I update the PR to include that or just let the commits tell their own story?

Dunno how I missed that part of the guide, thanks! I probably didn't know what a linter was the first time I read it. I'll install those now. 

Also, has there ever been discussion of adding a `package.json` so that `npm lint-lesson ./path-to-file` would run the proper command?

**Comment by marlatte** [comment]
Okay, so far so good, but a few things before I update the PR:

- To comply with [MD024](https://github.com/DavidAnson/markdownlint/blob/v0.33.0/doc/md024.md), I had to add the hosting service name to the "Links" subheads.
- Even though lazy links are enforced in the config, they aren't automatically replaced by the linter extension the way other default ones are.
- The CLI linter is catching an error at `react/states_and_effects/project_memory_card.md:1`. The VSCode extension isn't picking it up, however, and even the `TOP004_test_invalid.md` isn't getting any yellow squiggles. Here's the error: `TOP004/lesson-headings Required heading structure [This rule threw an exception: wildcardRegex is not defined]`

**Comment by JoshDevHub** [comment]
You can just add some more commits to this PR to fix them.

> Also, has there ever been discussion of adding a package.json so that npm lint-lesson ./path-to-file would run the proper command?

We might explore doing something like this. Would have to talk to the team some more about it.

> To comply with [MD024](https://github.com/DavidAnson/markdownlint/blob/v0.33.0/doc/md024.md), I had to add the hosting service name to the "Links" subheads.

That seems fine to me.

> The CLI linter is catching an error at react/states_and_effects/project_memory_card.md:1. The VSCode extension isn't picking it up, however, and even the TOP004_test_invalid.md isn't getting any yellow squiggles. Here's the error: TOP004/lesson-headings Required heading structure [This rule threw an exception: wildcardRegex is not defined]

Yeah don't worry about this one. This is an error on the end of the configuration, and it's being worked on.

**Review by JoshDevHub — APPROVED** [review]
Looks great! Thank you for contributing.

**Pull request merged**
