### PR TITLE
Add my solution to javascript/jquery project

### PR DESCRIPTION
**Pull request by johnTheDudeMan**

### CODE REVIEW

**Comment by KevinMulhern** [comment]
You can update your pull request with the adjusted link @johnTheDudeMan :)

**Comment by johnTheDudeMan** [comment]
Okay, I'll try and figure out how to do that. I am still learning github, and I didn't do this one through command line.

**Comment by KevinMulhern** [comment]
If you go to the "files changes tab" beside the "conversation" and "commits" tabs at the top of this page you should be able to edit your changes by clicking on the pencil icon on the file.

**Comment by johnTheDudeMan** [comment]
Done, thanks for the help Kevin.

**Comment by KevinMulhern** [comment]
No problem :)

**Pull request merged**
