### PR TITLE
added my solution

### PR DESCRIPTION
**Pull request by henrythedj**
```
This is a PR template, If you are adding a solution link to the curriculum leave this as is. If you are not, then delete it and write the message you wish.
Thank you,
The Odin Project team.

```

### CODE REVIEW

**Comment by csrail** [comment]
Mr Roboto is cool @henrythedj !

What did you think of the project? If you've got thoughts on how to improve lessons to better prepare others for the project, drop me a direct message in slack.

Yay :D) onto mastermind!

**Comment by henrythedj** [comment]
Cornelius, who are you on slack?





On Thu, Aug 25, 2016 4:41 PM, Cornelius Soon notifications@github.com wrote:
Merged #4527 .

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub , or mute the thread .



Henry Harding McCall
hardingmccall@gmail.com
615.887.3624

**Comment by KevinMulhern** [comment]
@henrythedj he's cs-rails

**Comment by henrythedj** [comment]
ahh





On Fri, Aug 26, 2016 9:05 AM, Kevin Mulhern notifications@github.com wrote:
@henrythedj he's cs-rails

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub , or mute the thread .



Henry Harding McCall
hardingmccall@gmail.com
615.887.3624

**Pull request merged**
