### PR TITLE
Foundations/Git Basics and The Back End: Changed formatting for lesson overview and knowledge checks

### LINKED ISSUE #23930: Style Guide - Foundations/Git Basics and The Back End: Learning Outcomes and Knowledge Checks
# Foundations/Git Basics and The Back End Sections

This issue is part of the Style Guide Community Project, a way of offering members of The Odin Project community a chance to contribute to our curriculum. Users who wish to take part and contribute to any Style Guide issues should have thoroughly read the [layout style guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md) and [The Odin Project contributing guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md).
  
## Description of Issue

This issue ensures the Learning Outcomes and Knowledge Check sections have the correct verbiage and formatting. If one of these sections does not exist in a lesson, it should not be added.

Each applicable lesson for this issue should meet the following requirements:

- The Learning Outcomes section is renamed to "Lesson Overview".
- The Lesson Overview section follows the below format:
	```
	### Lesson Overview

	This section contains a general overview of topics that you will learn in this lesson.

	*   LESSON OVERVIEW ITEMS...
	```
- The Knowledge Check section follows the below format:
	```
	### Knowledge Check

	This section contains questions for you to check your understanding of this lesson on your own. If you’re having trouble answering a question, click it and review the material it links to.

	*   KNOWLEDGE CHECKS...
	```
- Each Knowledge Check item follows the below format:
	```
	*   <a class="knowledge-check-link" href="A KNOWLEDGE CHECK URL">A KNOWLEDGE CHECK QUESTION.</a>
	```
- Each Knowledge Check item redirects to a resource mentioned in the lesson, or to a section within the lesson, where the answer can be found. 
	- If it doesn't, note this in your PR, but don't remove the item.
  
## Acceptance Criteria

- [ ] The following lessons are updated according to the issue description above:
	- [ ] [Introduction to Git](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/introduction-to-git)
	- [ ] [Git Basics](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/git-basics)
	- [ ] [Introduction to the Back End](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/introduction-to-the-back-end)
	- [ ] [Introduction to Frameworks](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/introduction-to-frameworks-web-development-101)

### PR DESCRIPTION
**Pull request by iawong**
Complete the following REQUIRED checkboxes:

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`

Complete the following checkboxes ONLY IF they are applicable to your PR. You can complete them later if they are not currently applicable:
-   [x] I have previewed all lesson files included in this PR with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure the Markdown content is formatted correctly
-   [x] I have ensured all lesson files included in this PR follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

<hr>

**1. Because:**

Closes #23930

**2. This PR:**

 - Reformats the Lesson Overview and Knowledge Checks

**3. Additional Information:**

 - [x] [Introduction to Git](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/introduction-to-git)
 - [x] [Git Basics](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/git-basics)
 - [x] [Introduction to the Back End](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/introduction-to-the-back-end)
 - [x] [Introduction to Frameworks](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/introduction-to-frameworks-web-development-101)

### CODE REVIEW

**Review by thatblindgeye — CHANGES_REQUESTED** [review]
Looks good! Can you resolve the merge conflicts in the two files mentioned? Should just be due to another PR having moved the Additional Resources section to come after Knowledge Check.

**Comment by iawong** [comment]
Whoops

**Comment by iawong** [comment]
After some trouble, I think all the merge conflicts should be solved. Please let me know if I missed anything or I messed something up.

**Review by 01zulfi — COMMENTED** [review]
Hello @iawong, I see this PR is attempting to add two new git files to the `foundations` folder. This should not be the case. Can you remove these files, specifically `foundations/git_basics/git_basics.md` and `foundations/git_basics/introduction_to_git.md`?

We have recently moved all of our Git markdown files to the root level of this repository in a folder named `git`. You should find the files that need to be updated for the style guide in the [`git/foundations_git/`](https://github.com/TheOdinProject/curriculum/tree/main/git/foundations_git) folder. Please make all the relevant updates for Git Basics and Introduction to Git lessons there.

**Comment by iawong** [comment]
Alright, foundations/git_basics.md and foundations/introduction_to_git.md should be deleted and the style changes in git/foundations_git/git_basics.md and git/foundations_git/introduction_to_git.md should be applied.

**Review by thatblindgeye — CHANGES_REQUESTED** [review]
Looks like there's a few dup files included here. Can you remove the duplicate Intro to Frameworks files, the ones that include BACKUP, BASE, REMOTE, and LOCAL?

**Comment by iawong** [comment]
I think I've deleted them.

**Review by thatblindgeye — APPROVED** [review]
Yep, looks good! Thank you for fixing that up 🙂

**Pull request merged**
