### PR TITLE
CSS Functions lesson: Reword the linear-gradient example

### PR DESCRIPTION
**Pull request by themetar**
Complete the following REQUIRED checkboxes:

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`

Complete the following checkboxes ONLY IF they are applicable to your PR. You can complete them later if they are not currently applicable:
-   [ ] I have previewed all lesson files included in this PR with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure the Markdown content is formatted correctly
-   [ ] I have ensured all lesson files included in this PR follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

<hr>

**1. Because:**
Saying (for example) "the equation calculates the sides of the hypotenuse" sounds weird to me.

**2. This PR:**

* In css_math_functions.md, changed "calculates <arguments> of <result>" to  "use <arguments> to get <result>"

**3. Additional Information:**

### CODE REVIEW

**Review by wise-king-sullyman — CHANGES_REQUESTED** [review]
I think I understand what you're saying, and I agreed with it at first, but after some further consideration, I think we both initially read this differently than it's written.

Another way this could be written is that the `linear-gradient` function *uses* arguments (90deg, blue, red in this case) to calculate and draw a gradient. Does that way of writing it out make more sense to you?

I don't disagree that the current wording seems a tad confusing, so if you have an alternate suggestion I'd like to hear it. But I believe that your currently suggested change means something different, as it implies that angle, start color, and end color are the only arguments that can be passed.

**Comment by themetar** [comment]
My only objection was the grammatical wording of the sentence "..calculates the angle, starting color, and ending color of a gradient." It's like saying: The baker bakes the flower and yeast of the bread. What?! No, the baker _bakes bread_ (out of flower and yeast).

The paragraph is related to the css snippet, above it in the lesson, where linear-gradient is called with three parameters. It just restates the code, emphasizing that css functions are used. It might imply that that's the only way to use linear-gradient, but linear-gradient itself isn't the focus of the lesson. We can: add a clarification to that effect; add a link to docs (to nudge the student to see other uses of linear-gradient); or do nothing (as it was before). What should I do?

**Comment by wise-king-sullyman** [comment]
@themetar I think just a small clarification would be enough. We don't need to go in any great depth about it since, as you said, that function isn't the focus of the lesson. I just don't want us to replace potentially misleading information with other information that is potentially misleading in another way 🙂

**Comment by themetar** [comment]
@wise-king-sullyman I made some changes. Please review.

**Review by wise-king-sullyman — APPROVED** [review]
This looks great, thanks!

**Pull request merged**
