### PR TITLE
Update keys_in_react.md

### PR DESCRIPTION
**Pull request by asimn7**
feat: Added v4 to uuidv4 as uuid is not supported in the latest versions of Javascript.

## This PR

- changed from 'uuid' to 'uuidv4' and added import 

## Issue

Closes #XXXXX

## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project curriculum contributing guide](https://github.com/TheOdinProject/curriculum/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [x] The `Because` section summarizes the reason for this PR
-   [x] The `This PR` section has a bullet point list describing the changes in this PR
-   [x] If this PR addresses an open issue, it is linked in the `Issue` section
-   [x] If any lesson files are included in this PR, they have been previewed with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure it is formatted correctly
-   [x] If any lesson files are included in this PR, they follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

### CODE REVIEW

**Comment by asimn7** [comment]
Sorry, if this is a minor change, I got stuck here for quite a bit, so I thought of adding it.

**Comment by asimn7** [comment]
I don;t really know how the pull thing works, I think I have to reopen though.

**Comment by Asartea** [comment]
> I don;t really know how the pull thing works, I think I have to reopen though.

Yes; you've opened a pull request, and now need to wait for one of the maintainers to review it. If they approve it, they will merge it into the main branch, at which point your changes will be applied to the live version of the curriculum

**Comment by xandora** [comment]
We could do something clever and reduce it to just:
```jsx
import { v4 as uuid } from 'uuid';
```
It will update the code to use the v4 `uuid`s, but keep the rest of the function calls as they currently are.

**Comment by Asartea** [comment]
Actually, if all we're doing is creating UUID's, do we even need the library? I'm fairly the build in `crypto` library has a function for that

**Comment by xandora** [comment]
> Actually, if all we're doing is creating UUID's, do we even need the library? I'm fairly the build in `crypto` library has a function for that

You read that too? :D
I agree though, we could do it that way. Might need some of the other maintainers to check there's no actual reason why we're using `uuid` specifically first.

**Comment by Asartea** [comment]
> You read that too? :D

I plead the Fifth

> I agree though, we could do it that way. Might need some of the other maintainers to check there's no actual reason why we're using uuid specifically first.

I am not intimately familiar with this part of the curriculum, but the primary reason I could think of was that we might use it more later on, but a quick GitHub search seems to suggest this [is the only occurrence of it](https://github.com/search?q=repo:TheOdinProject/curriculum+uuid+language:Markdown+&type=code)

**Comment by MaoShizhong** [comment]
We don't need to import the `uuid` library for this example; we can use the built-in [`crypto.randomUUID()` function](https://developer.mozilla.org/en-US/docs/Web/API/Crypto/randomUUID) for each of those instead.

**Comment by xandora** [comment]
@MaoShizhong So there's no technical or lesson-based reason we're using the `uuid` package then? Sounds like we can drop a package, which is always nice. :)

**Review by MaoShizhong — CHANGES_REQUESTED** [review]
Thanks @asimn7 for this PR. As discussed above, we do not need the `uuid` package to be imported at all, an can instead use a built-in function to do the same thing.

The `todos` array in both examples on lines 49-53 and 86-90 can be changed to the following:

```js
const todos = [
  { task: "mow the yard", id: crypto.randomUUID() },
  { task: "Work on Odin Projects", id: crypto.randomUUID() },
  { task: "feed the cat", id: crypto.randomUUID() },
];
```

And the bad example on line 97 can be adjusted to have

```jsx
<li key={crypto.randomUUID()}>{todo.task}</li>
```

**Comment by cakegod** [comment]
An auto increment would also work fine.

**Comment by MaoShizhong** [comment]
@asimn7 is this something you still wish to work on?

**Pull request closed without merging**
