### PR TITLE
Add my solution to HTML/CSS project

### PR DESCRIPTION
**Pull request by JMurphyWeb**

### CODE REVIEW

**Comment by craftykate** [comment]
@JMurphyWeb You need to include the actual link to your code. A full explanation of exactly how to add your solution to the odin project can be seen here: http://bit.ly/odin-solutions. Just modify this pull request or close this one and start a new one. Let me know if you need help!

**Comment by JMurphyWeb** [comment]
Hi Kate,
Thanks for the email. I have now returned from holiday and i'm now trying
to re submit my solution to the first exercise.

I have one question with regards to the View in browser part of your video:
How can i view my solution in the browser using Github?
I have all my html and css files saved in the google-homepage repository
but i cannot work out how to actually view them in the browser and i
therefore cannot post a url to view my solution in browser.

Sorry but Git hub has caused me a lot of confusion so far, i hope you can
understand what my problem is.

I will go ahead and try to post my solution anyway without the view in
browser link.

Best,
Jack

**Comment by KevinMulhern** [comment]
Hi @JMurphyWeb, 
You can get a good idea of how to format your link to view it in the browser from the other students submissions. Also it seems your submission is just "+ add my solution here" and not a link to your project. Could you resubmit again with a link a to your repository on Github please.

**Comment by KevinMulhern** [comment]
Nevermind I am just seeing your most recent pull request.

**Comment by JMurphyWeb** [comment]
Hi Kevin,
thanks for the message.

I see that my solution is not on the Odin page - does that mean my pull
request wasn't successful/approved?

I am also confused as to how to view my solution in the browser.  The files
are saved in a repository in GitHub, but i dont know how to open/preview
them in webpage format.  Is there a button i can press when in github when
i am in my repository?

Thanks again for any assistance,
Jack

**Comment by JMurphyWeb** [comment]
I have just seen that this is all related to my old pull request.  I will copy and paste the above question into the new pull request so we can forget about this one.

**Pull request closed without merging**
