### PR TITLE
Add my solution to list

### PR DESCRIPTION
**Pull request by Vorelli**
This is a PR template. If you are adding a solution link to the curriculum, leave this as is. If not, delete it and write the message you wish.

Thank you,

The Odin Project team.

### CODE REVIEW

**Comment by mjosh51** [comment]
[google-homepage.zip](https://github.com/TheOdinProject/curriculum/files/4906152/google-homepage.zip)
Google Home Page by Mayor Josh, being a project assignment on TheOdin.

**Comment by mjosh51** [comment]
https://mjosh51.github.io/google-homepage/
Google Result Page by Mayor Josh, being a project assignment on TheOdin.

**Comment by mjosh51** [comment]
https://mjosh51.github.io/google-result-page/
Google Result Page by Mayor Josh, being a project assignment on TheOdin.

**Comment by YeisonQuiceno** [comment]
https://yeisonquiceno.github.io/google-homepage/
Google page project assignment-Yeison Quiceno

**Pull request merged**
