### PR TITLE
Jasons solutions

### PR DESCRIPTION
**Pull request by fo0man**
Add my solutions to a few of the rails projects

### CODE REVIEW

**Comment by craftykate** [comment]
Can you help me out and pull the current version of the curriculum and then add your solutions? A lot of solutions have been added since your version and we've changed (somewhat - mostly just streamlined) the format for adding a solution. They are all like this now: `[Your name's solution](link) | [View in browser](link)`. If you make your curriculum repository current it will be a lot easier to add your solutions.

**Comment by craftykate** [comment]
A super easy way to add solutions that doesn't involve making sure your curriculum repository is current can be seen here: bit.ly/odin-solutions. You can just edit on that page and it will always be up-to-date.

**Comment by fo0man** [comment]
Oh okay will do. I thought I pulled the current version first. Thanks.

**Comment by craftykate** [comment]
Thank you. Normally it isn't a big deal to have the latest version, but since I reformatted all the links it was going to take a while to clean them all up.

**Pull request closed without merging**
