### PR TITLE
Action Cable Assignment: Update 'Simple Messaging App' code-along 

### PR DESCRIPTION
**Pull request by thejwuscript**
Complete the following REQUIRED checkboxes:

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`

Complete the following checkboxes ONLY IF they are applicable to your PR. You can complete them later if they are not currently applicable:
-   [ ] I have previewed all lesson files included in this PR with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure the Markdown content is formatted correctly
-   [ ] I have ensured all lesson files included in this PR follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

<hr>

**1. Because:**

Turbolinks is no longer in active development, and Rails 7 comes with Hotwire which includes Turbo. It has essentially replaced turbolinks. Therefore "turbolinks:load" event listener no longer works in this lesson.

Another minor fix/typo involves clarifying the file path to connection.rb, so learners do not mistakenly create/duplicate the file at the wrong location.

**2. This PR:**

- Replace "turbolinks:load" with "turbo:load"
- Fix connection.rb file path to "app/channels/application_cable/connection.rb"

### CODE REVIEW

**Comment by ChargrilledChook** [comment]
Related issue: #24186

**Comment by zfz** [comment]
@thejwuscript  Thank you so much for your PR, I could make the event listener work after hours of troubleshooting the original js code.  Another thing I found is that we should assign `consumer.subscriptions.create` to a const object `messageChannel`, which will be called later to send the message.  The line 4 of `app/javascript/channels/message_channel.js` generate by Rails: 
```js
consumer.subscriptions.create("MessageChannel", {
```

So in Line 207 of the current tutorial, we should remind user to add this `const messageChannel` declaration, like:

```
Now when the form is submitted, we need to intercept and handle it. Open up our `app/javascript/channels/message_channel.js` and take a look at the code as it stands.
```
to
```
Now when the form is submitted, we need to intercept and handle it. Open up our `app/javascript/channels/message_channel.js` and take a look at the code as it stands. Assign the consumer.subscriptions to a const messageChannel, which will send the message later.
```

**Comment by CouchofTomato** [comment]
@ChargrilledChook Happy for this to be merged?

**Comment by ChargrilledChook** [comment]
@CouchofTomato I think these changes are good, but it's possible we may have to update it a bit more - bit of discussion from a few learners on the issue here https://github.com/TheOdinProject/curriculum/issues/24186

**Comment by ChargrilledChook** [comment]
Thanks for this contribution @thejwuscript 🚀

**Pull request merged**
