### PR TITLE
Rails basics : Change link texts

### PR DESCRIPTION
**Pull request by forge34**
## Because

Change link text in some lessons in rails basics

## This PR

- Routing lesson : change link text in line 212
- Blog app project : change link text in line 25
- Deployment lesson : change link text in lines 107 ,108 ,127 ,128 , 147 , 148 ,168 and 169

## Issue

Related to #28290

## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project curriculum contributing guide](https://github.com/TheOdinProject/curriculum/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [x] The `Because` section summarizes the reason for this PR
-   [x] The `This PR` section has a bullet point list describing the changes in this PR
-   [x] If this PR addresses an open issue, it is linked in the `Issue` section
-   [x] If any lesson files are included in this PR, they have been previewed with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure it is formatted correctly
-   [x] If any lesson files are included in this PR, they follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

### CODE REVIEW

**Review by MaoShizhong — COMMENTED** [review]
Thanks for getting these links sorted, @forge34.

Would you also be happy to fix the lint errors in `routing` and `project_blog_app`?
You should be able to sort most if not all of the errors in those files by following our [local linting and fixing](https://github.com/TheOdinProject/curriculum/blob/main/CONTRIBUTING.md#curriculum-linting) instructions, using the appropriate lesson/project scripts.

If you run into any issues with this, or there are any unfixable lint errors that need context-based manual fixing, let me know.

**Comment by forge34** [comment]
> Thanks for getting these links sorted, @forge34.
> 
> Would you also be happy to fix the lint errors in `routing` and `project_blog_app`? You should be able to sort most if not all of the errors in those files by following our [local linting and fixing](https://github.com/TheOdinProject/curriculum/blob/main/CONTRIBUTING.md#curriculum-linting) instructions, using the appropriate lesson/project scripts.
> 
> If you run into any issues with this, or there are any unfixable lint errors that need context-based manual fixing, let me know.

sure : )
just to make sure i can either use option 1 or 2 , or just option 2? from the link

**Review by MaoShizhong — APPROVED** [review]
:rocket:

Like with eslint/prettier, the VSCode extension just makes things more convenient by showing live error highlighting etc.
The best thing for actually seeing lint error details and fixing is to use the npm package and our scripts. So I handle large quantities of lint issues via the the npm scripts, but also have the extension because it makes things convenient when you're making changes, as you see squigglies in real-time.

**Comment by forge34** [comment]
> 🚀
> 
> Like with eslint/prettier, the VSCode extension just makes things more convenient by showing live error highlighting etc. The best thing for actually seeing lint error details and fixing is to use the npm package and our scripts. So I handle large quantities of lint issues via the the npm scripts, but also have the extension because it makes things convenient when you're making changes, as you see squigglies in real-time.

i see , from now on i have the extension and will continue using the npm scripts to fix and check if there is any errors

**Pull request merged**
