### PR TITLE
Update_project.md

### PR DESCRIPTION
**Pull request by Fully34**
I can't get my "view in browser" to connect to the stylesheet.  I'm just forwarding the solution until I figure that out.

Thanks!
-Fully

### CODE REVIEW

**Comment by craftykate** [comment]
@Fully34 I'm merging your link - but I took a look at your files. Your index file is `Homepage.html` and your stylesheet is `Stylesheet.css`. But in your index file you're linking to `stylesheet.css` - note the lowercase "s". So your index file is looking for a file that doesn't exist. I recommend making all your files have lowercase letters - just convention. If you change the name of your stylesheet it should work out just fine. Then you can come back and add your "View in browser" link.

**Comment by Fully34** [comment]
Duhhh!  Haha thank you!  That was so frustrating!  Funny how every problem
I've had so far has an extremely simple solution!

Thanks again!  And I'll make sure to keep it lowercase from now on.

Regards,
Chris

**Comment by craftykate** [comment]
@Fully34 You're welcome! Happy to help. Along with lowercase filenames I recommend naming your index file `index.html`. Another convention, it's not mandatory in most cases, but as you get further along you'll see that most people do that. It will help other people reading your code know what's going on and in some cases certain programs will automatically look for an index file called "index". Nothing wrong here with calling your file `Homepage`, but it's probably a good habit to pick up early on. Happy coding!

**Comment by Fully34** [comment]
10-4, will do!  I also had to fix one of the img references as well.  Same
problem with upper vs. lowercase.

Regards
Chris

**Comment by craftykate** [comment]
@Fully34 Lol - I loved your "What I learned" comment on your readme.

**Comment by Fully34** [comment]
Haha, I have to make notes like that to remember important stuff!

**Pull request merged**
