### PR TITLE
Rails/Routing - Fix syntax highlighting for Ruby code

### PR DESCRIPTION
**Pull request by onebree**
In response to issue #493

changed `language-ruby` to simply `ruby`, as suggested by Github-Flavored Markdown docs. In the document preview, it appears top work now. Prior to the commit, the code blocks were not highlighted correctly on the site, and not at all in Github.

### CODE REVIEW

**Comment by hgducharme** [comment]
@eriktrautman What do you think? I won't be able to run this on my server so I'm not sure.

**Comment by onebree** [comment]
@eriktrautman

**Comment by eriktrautman** [comment]
The issue is that we're not actually using pure Github Flavored Markdown on the project, we're using RedCarpet for it (see `md` in https://github.com/TheOdinProject/theodinproject/blob/master/app/helpers/application_helper.rb) and it needs `language-ruby` to work.  I updated Prism.js, our syntax highlighter, to account for comments better https://github.com/TheOdinProject/theodinproject/commit/32bfe58b4ec7d6d84685b6ba8ea8f9fda704e0ac

**Comment by onebree** [comment]
@eriktrautman Thank you for the clarification, and the fix as well. I did not look through the application itself for helpers. I now see that all `#` symbols are highlighted properly, and that your commit affects all pages.

**Pull request closed without merging**
