### PR TITLE
Ruby: Provide descriptive link text

### PR DESCRIPTION
**Pull request by TheSeagullDev**
## Because

Makes link text more descriptive

## This PR

Update link text in
- debugging.md
- basic_enumerable_methods.md
- predicate_enumerable_methods.md

## Issue

Related to #28290

## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project curriculum contributing guide](https://github.com/TheOdinProject/curriculum/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [x] The `Because` section summarizes the reason for this PR
-   [x] The `This PR` section has a bullet point list describing the changes in this PR
-   [x] If this PR addresses an open issue, it is linked in the `Issue` section
-   [x] If any lesson files are included in this PR, they have been previewed with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure it is formatted correctly
-   [x] If any lesson files are included in this PR, they follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

### CODE REVIEW

**Review by MaoShizhong — APPROVED** [review]
Many thanks for this @TheSeagullDev.

Would you be happy to fix the remaining linting errors across the three files? This should be doable by following our [instructions on linting and fixing locally](https://github.com/TheOdinProject/curriculum/blob/main/CONTRIBUTING.md) (it's possible that some lines with multiple auto-fixable errors might need more than one run of a fix script to capture everything).

If you're happy to do this, let me know once you've finished pushing those fixes. Likewise, let me know if you're not comfortable doing this, and I can merge this PR as is.

**Comment by TheSeagullDev** [comment]
@MaoShizhong Linting errors have been fixed (hopefully, I'm still in JS foundations). Let me know if I need to fix anything.

**Comment by TheSeagullDev** [comment]
@MaoShizhong The fix should be added now

**Review by MaoShizhong — APPROVED** [review]
:rocket:

**Pull request merged**
