### PR TITLE
Added Project Euler solutions and js/jquery project to pages

### PR DESCRIPTION
**Pull request by Flakari**
```
This is a PR template, If you are adding a solution link to the curriculum leave this as is. If you are not, then delete it and write the message you wish.
Thank you,
The Odin Project team.

```

### CODE REVIEW

**Comment by mindovermiles262** [comment]
Hi @Flakari 👋 
I really like the design of your sketchpad!  However, the reset and change pixel density buttons didn't work for me. I'm using the new Firefox. Oh no!

I'll merge this PR but it may be something you want to check out.  If you have any questions please let us know. We are always available in the [Odin Chatroom](https://gitter.im/TheOdinProject/theodinproject)

**Comment by Flakari** [comment]
Hey @mindovermiles262 ! Thanks a bunch! I downloaded the new Firefox and on my end everything seemed to work as intended. What about those buttons don't work for you if I may ask? Might help my debugging.

**Comment by mindovermiles262** [comment]
After I click on "clear canvas" or "pixel density" the grid no longer draws

**Comment by Flakari** [comment]
Oh, if you click on a color on the right side it should draw again. That was suggested by someone so you don't accidentally draw with a color you don't want before picking a color to start drawing on the new canvas with.

**Comment by mindovermiles262** [comment]
Ahh you're right 👍 It works okay after I choose a color

Great job!

**Pull request merged**
