### PR TITLE
Add another resource to find ruby gems

### PR DESCRIPTION
**Pull request by Pandenok**
- [ x] You have read [The Odin Projects Contributing Guide](https://github.com/TheOdinProject/curriculum/blob/master/CONTRIBUTING.md).

#### 1.Describe the changes made:

I humbly suggest to add in the lesson a direct link to the official Ruby community's gem hosting service https://rubygems.org/. It was never mentioned explicitly in the curriculum, only indirectly in other resources, so less attentive students could have missed that. And it seems to me the right place to mention it again.

#### 2. If this PR is related to an open issue please reference it with the `#` operator and the issue number below:

#XXXXX

### CODE REVIEW

**Comment by ZachBaird** [comment]
Hey @Pandenok , thanks for doing this!

Can we change the wording to be it's own sentence? I think it would read better if it was more like:
"Alternatively, you can browse through [RubyGems](https://rubygems.org/) to see what gem is the most popular one.

**Comment by Pandenok** [comment]
@ZachBaird, Hey! Thank you! I was trying only to integrate it in the existing text frame. Surely you can freely change it! :) Thank YOU!

**Comment by Pandenok** [comment]
@ZachBaird, I added another commit, I don't understand how to make a description of that one. It goes together with this pull request...

**Comment by ZachBaird** [comment]
Hey @Pandenok , it looks like you actually modified that line in the lesson with the description you were trying to type.
I read your thoughts, and I don't want to see us cut out an additional resource without replacing one. If you can find one you feel is more descriptive or in-depth, you can most certainly bring it up.

That being said, we want pull requests to be pretty focused on one thing, and this one's focus is adding the RubyGems resource on the one lesson, so I'd like you to revert the new change. Once that's done, I'll modify your initial stuff and get this pull request merged 💪🏼

**Comment by Pandenok** [comment]
Hi @ZachBaird! Thank you for explanation! I reverted the change. Thank you again!

**Pull request merged**
