### PR TITLE
Added my solution

### PR DESCRIPTION
**Pull request by edgar-**

### CODE REVIEW

**Comment by KevinMulhern** [comment]
Hi @edgar-  could you remove the blank line?

**Comment by edgar-** [comment]
@KevinMulhern I Just removed the blank line. Thank you

**Comment by KevinMulhern** [comment]
hmm its not allowing me to automatically merge to master for some reason, @craftykate, @eriktrautman  any ideas?

**Comment by eriktrautman** [comment]
Probably just a merge conflict, which will happen any time you try to merge two solutions from the same project.  You'll need to use the command line to disentangle.

**Comment by KevinMulhern** [comment]
Got it, thanks Erik!

**Pull request merged**
