### PR TITLE
Update understanding_errors.md

### PR DESCRIPTION
**Pull request by NerdsAreIn**
- [x] You have read [The Odin Projects Contributing Guide](https://github.com/TheOdinProject/curriculum/blob/main/CONTRIBUTING.md).

#### 1.Describe the changes made:

Edited for tautologous/repetitive content, glossed "throw", made the sentence order more logical.

#### 2. If this PR is related to an open issue please reference it with the `#` operator and the issue number below:

#XXXXX

### CODE REVIEW

**Comment by twalton83** [comment]
Out of curiosity, are you active in our Discord server? I notice you make a lot of contributions, we have a channel in the server dedicated to discussing larger changes.

**Review by twalton83 — APPROVED** [review]

**Comment by NerdsAreIn** [comment]
Hi. :) 

How come I can't see any of my changes on the live page?

I did check out the Discord chat room, but I find the layout a little off-putting, with all the open-ended scrolling to read previous messages. I also keep being bombarded with alerts telling me to "claim" my account, even though I already have. And then, when I try to go through the process, I'm told that my email is already registered....

**Comment by twalton83** [comment]
Sure, I was just asking because it's usually the best way to communicate large changes. 

Curriculum changes are not always instantaneous, but I suggest clearing your cache in case.

**Comment by NerdsAreIn** [comment]
Ok, I will endeavour to give it another shot, once I've resolved the "claiming" issue.

What counts as a large change?

How do you become a maintainer? Likewise, how do you gain write access on here?  

I'm a proofreader in my day job, and also a grammar nerd, so am very motivated to clean up the English. Though I have to be mindful to not "correct" any American spellings!

I also love this whole project. I really want to be able to help explain things to other learners.

**Comment by twalton83** [comment]
Maintainers are determined by the core team- you gotta get active on Discord to be seen :) You cannot have write access without earning the maintainer or core position. 

I’d consider your backend lesson changes to be larger. Once we’re removing and adding more than a few sentences of content, we want to discuss it.

**Comment by NerdsAreIn** [comment]
Thanks. :)  I can see my changes on the live page now.

 Are you a maintainer?

**Comment by twalton83** [comment]
Yes, I am!

**Comment by NerdsAreIn** [comment]
So, should I make turn the pull requests I've made on here into contribution suggestions on Discord?

How long will it take for my pull requests to be reviewed on here?

Thanks for your help, btw.

**Comment by twalton83** [comment]
It would be nice to discuss major changes first to ensure they’re something we want.

Since it’s a volunteer effort, PRs are reviewed and merged when a member of the team gets to them. It’s variable, but we try to get to them whenever we have time.

**Pull request merged**
