### PR TITLE
Update Javascript OdinBook instructions to use the correct faker library

### PR DESCRIPTION
**Pull request by ayoubmissaoui**
- [x] You have read [The Odin Projects Contributing Guide](https://github.com/TheOdinProject/curriculum/blob/main/CONTRIBUTING.md).
 - [x] The title summarizes the change and where it happened, for example: "Fixes punctuation in Clean Code lesson".
 - [x] If the PR is related to an open issue, use a [relevant keyword](https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests) and reference it with the `#` sign and the issue number.
 - [x] You have previewed your markdown (if any) in the [Odin Markdown Preview Tool](https://www.theodinproject.com/lessons/preview)
 - [x ] If changes are requested, please make the changes in a timely manner. After you submit the changes, request another review from the maintainer (top right).

#### 1. Describe the changes made and include why they are necessary or important:

Changed the link to point to (https://github.com/faker-js/faker)
#### 2. Related Issue

Closes #23340

### CODE REVIEW

**Review by CouchofTomato — APPROVED** [review]
Thank you for taking this on so quickly @ayoubmissaoui

**Comment by zachmmeyer** [comment]
@ayoubmissaoui For next time, when you use the `Closes` keyword and the number, it should be the issue number and not the number of the PR.

**Comment by ayoubmissaoui** [comment]
@zachmmeyer OHH thank you didn't know there was a difference ! So here I was supposed to put #23399, right ?

**Comment by zachmmeyer** [comment]
@ayoubmissaoui Correct!

**Pull request merged**
