### PR TITLE
Add comma to ES6 Features Lesson

### PR DESCRIPTION
**Pull request by zelf0**
This is my first pull request, just wanted to try it out on something small.

 - [x] You have read [The Odin Projects Contributing Guide](https://github.com/TheOdinProject/curriculum/blob/main/CONTRIBUTING.md).
 - [x] The title summarizes the change and where it happened, for example: "Fixes punctuation in Clean Code lesson".
 - [x] If the PR is related to an open issue, use a [relevant keyword](https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests) and reference it with the `#` sign and the issue number.
 - [x] You have previewed your markdown (if any) in the [Odin Markdown Preview Tool](https://www.theodinproject.com/lessons/preview)
 - [x] If changes are requested, please make the changes in a timely manner. After you submit the changes, request another review from the maintainer (top right).

#### 1. Describe the changes made and include why they are necessary or important:

Small punctuation fix in ES

#### 2. Related Issue

Closes #XXXXX

### CODE REVIEW

**Comment by zelf0** [comment]
Small punctuation fix in ES

**Comment by zachmmeyer** [comment]
> Small punctuation fix in ES

This should be in the PR template under the first step as the description of changes made.
I fixed the title of this PR to be more descriptive.

**Review by zachmmeyer — APPROVED** [review]
Thanks for adding the punctuation here. I will hold you to filling out the PR template correctly next time!

**Comment by zelf0** [comment]
> Thanks for adding the punctuation here. I will hold you to filling out the PR template correctly next time!

Thank you! Noted about the PR title, I'll get it right next time; really appreciate the feedback.

**Pull request merged**
