### PR TITLE
contributing  HTML/CSS google-homepage solution

### PR DESCRIPTION
**Pull request by codeNameJKB**
Hello, I am submitting my HTML/CSS google-homepage solution.

### CODE REVIEW

**Comment by kriox26** [comment]
Hi @codeNameJKB , the link for the online solution is wrong. It's pointing to a file that it's suppose to be in: `google-homepage/index.html` but your index is instead in `google-homepage/google-homepage/index.html`.
This is the link that you should use to generate the online solution: https://github.com/codeNameJKB/google-homepage/blob/master/google-homepage/index.html
Please fix that and resubmit

**Comment by codeNameJKB** [comment]
Hi @kriox26, Thank you for your help. I have corrected and push the URL. GIT is providing me with the status "Everything up-to-date" but I don't see another pull request when I click the open button above. Please let me know if you've receive the updated URL. Thanks

**Comment by kriox26** [comment]
@codeNameJKB no changes over here, it's simpler if you go to `Files changed` tab at the top of the screen, hit the edit button there and change the url, replacing it with this one: http://htmlpreview.github.io/?https://github.com/codeNameJKB/google-homepage/blob/master/google-homepage/index.html

**Comment by kriox26** [comment]
Also a recommendation, add this to your .css and your microphone icon will be better lined up with the form(the rest is really good, congrats :+1: ):
```css
.fa-microphone {
    left: 75px;
}
```

**Comment by codeNameJKB** [comment]
Hi @kriox26, It looks like the commit / pull request were submitted. Please let me know if everything is okay. Thanks.

**Comment by codeNameJKB** [comment]
Thanks Matias.

**Comment by kriox26** [comment]
@codeNameJKB There seems to be a `merge conflict`. To save you the trouble, I'm gonna close this Pull request, and you open a new one a submit your solution :+1:

**Comment by codeNameJKB** [comment]
hi Matias, 

I have submitted my solution. Question, if I wanted to resolve the merge conflict on my end, I would have had to use  git fetch and then select which branch to merge the solution in, or are there additional steps I would have need to take in order to successful resolved the merge conflict?

**Comment by kriox26** [comment]
Kevin has merged it :+1: . To resolve the conflict on your own you would need to do a `git checkout` to a local branch, then do a `git pull` to our `master` branch, resolve all the conflicts there, commit them, `git checkout master` to go to the master branch and finally do: `git merge --no-ff name_of_your_branch` to merge the changes. Then you do a `git push origin master` to push to your repo, and lastly, in your repo github page, hit the `compare` button and send a pull request. Something like this:
```
# This is in your command line, inside your repo
git checkout -b do_changes
git pull https://github.com/TheOdinProject/curriculum.git master
# Do all the changes you want, git add and then git commit
git checkout master
git merge --no-ff do_changes
git push origin master
# Now you have your changes on your remote repo. Compare -> Pull request
```

PD: It all depends on the branch name that has been created for the PR

**Comment by codeNameJKB** [comment]
Wow! That’s a lot of steps. I’m going to copy and paste to my evernote for future use. Thanks Matias & Kevin.

**Comment by Oli77777** [comment]
[Archive.zip](https://github.com/TheOdinProject/curriculum/files/3194124/Archive.zip)
Hopefully I am right here sharing my odin's google-homepage trial...

**Pull request closed without merging**
