### PR TITLE
Web Development 101, RPS console game

### PR DESCRIPTION
**Pull request by CPMSP**
This is a PR template. If you are adding a solution link to the curriculum, leave this as is. If not, delete it and write the message you wish.

Thank you,

The Odin Project team.

### CODE REVIEW

**Comment by marvingay** [comment]
@CPMSP  Hello. It appears there may or may not be a sizeable merge conflict with your pull request. Are you able to pull the most recent changes from the repository, resolve the merge conflicts (by removing the markers in your editor), and pushing them to your fork? Once that's done we can display your solution!

If you have questions do not hesitate to ask.

**Comment by CPMSP** [comment]
Apologies for that, it's been a while since I was on the Project.  What would be the best course of action to correct this?  Thank you so much for your time.

**Comment by marvingay** [comment]
@CPMSP You can either pull the changes locally from the main repository and fix the conflicts OR edit in your solution in a new pull request via the GUI on the website here OR re-fork the main repository, make the change with the same process as before.

**Comment by CPMSP** [comment]
I think I'll close this commit, delete the old fork, re-fork, and re-submit.  Does that seem to be a proper path forward with 17k conflicts to review?  Thanks @marvingay

**Comment by marvingay** [comment]
@CPMSP It seems to be the most convenient! Thanks again for the response. I'll close this for you, but you're still welcome to comment if you have questions!

**Pull request closed without merging**
