### PR TITLE
Added Javascript/jQuery solution

### PR DESCRIPTION
**Pull request by fcarrara**
```
This is a PR template, If you are adding a solution link to the curriculum leave this as is. If you are not, then delete it and write the message you wish.
Thank you,
The Odin Project team.
```

### CODE REVIEW

**Comment by KevinMulhern** [comment]
@kriox26 Looks like to bot didn't get this one? the link looks fine to me.

@fcarrara we are running a test with a bot that automatically adds students solutions when they are submitted.

**Comment by kriox26** [comment]
The bot is actually not running right now @kevinmulhern, I had to turn off my laptop, it had been on for a couple of days, it needed some rest lol

**Comment by KevinMulhern** [comment]
ah, ok :+1:

**Comment by fcarrara** [comment]
Hi guys, has it been merged? I still don't see my link on the website. Thanks! 
+1:

**Comment by KevinMulhern** [comment]
Sorry about that @fcarrara, there was a merge conflict.

**Comment by fcarrara** [comment]
Cool cheers!

**Pull request merged**
