### PR TITLE
heading statements were not previously 'selectable'

### PR DESCRIPTION
**Pull request by bappyasif**
now, this way or with those changes all those 'heading' statement can be easily selected using a mouse or trackpad, just a feedback, if i may, thanks

Complete the following REQUIRED checkboxes:

-   [ ] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [ ] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`

Complete the following checkboxes ONLY IF they are applicable to your PR. You can complete them later if they are not currently applicable:
-   [ ] I have previewed all lesson files included in this PR with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure the Markdown content is formatted correctly
-   [ ] I have ensured all lesson files included in this PR follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

<hr>

**1. Because:**

Closes #XXXXX

**2. This PR:**

**3. Additional Information:**

### CODE REVIEW

**Review by 01zulfi — COMMENTED** [review]
Thank you for submitting this pull request.

Unfortunately, using `##` will not render the headings correctly. You can check it out yourself in the [Lesson Preview Tool](https://www.theodinproject.com/lessons/preview):
image


We need to start our lesson headings from `###` so that it can render correctly on the website: 
image


Yes, heading statements are not easily selectable because they get converted into internal links and causes them to have the hover effect throughout the entire width. Before I close this pull request, do you think selectable headings is a feature we should have on the website?

**Comment by bappyasif** [comment]
thanks @01zulfi for you feedback, much appreciated.

and, to answer this question that you left earlier 'do you think selectable headings is a feature we should have on the website?', i would say why not, other documents saavy sites uses it!! just a thought, should be beneficial if you look at it from a perspective where people likes to highlight 'heading statement', like me!! 😁

and on top of it, im willing to work on those fixes / changes, if or when they are needed to be!! please let me know, if i can help in that regard or any other for that matter.

thanks again and happy coding :)

**Comment by 01zulfi** [comment]
Thanks for the feedback!

As for helping out, we always have new [issues](https://github.com/TheOdinProject/curriculum/issues) created with "Status: Help Wanted" label that could use some helping out. Additionally, you can create new issues with feature requests and bug reports and/or submit pull requests which can improve the curriculum.

**Comment by bappyasif** [comment]
@01zulfi thanks for creating a new issue with this, and sure i'll look into those 'help wanted' labelled tasks and see if i can be any help to those!! happy coding :)

**Pull request closed without merging**
