### PR TITLE
Style Guide - Foundations/HTML Foundations: Fixed lesson overview format

### PR DESCRIPTION
**Pull request by ItsKatato**
Complete the following REQUIRED checkboxes:

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`

Complete the following checkboxes ONLY IF they are applicable to your PR. You can complete them later if they are not currently applicable:
-   [x] I have previewed all lesson files included in this PR with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure the Markdown content is formatted correctly
-   [x] I have ensured all lesson files included in this PR follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

<hr>

**1. Because:**

Related to #23931 
There was a duplicate file and that one was updated instead of the correct file. I was asked to update this in #23949 

**2. This PR:**

- [x] The following lessons are updated according to the issue description above:

  - [x]  [Commit Messages](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/commit-messages)

### CODE REVIEW

**Review by thatblindgeye — APPROVED** [review]
Thank you for linking the other PR in your initial comment!

Seeing updates being made, I'm thinking that perhaps the actual Style Guide file could be updated to mention that unordered lists can either use the `-` hyphen format or the `*` asterisk format, since both are valid Markdown for unordered lists (and on here the default is the hyphen format). As a newer (?) contributor, do you feel that might be confusing at all?

**Comment by ItsKatato** [comment]
Hi @thatblindgeye 
I was wondering if there was actually a difference and I looked into it and there wasn't, but I just changed it cause that's what was shown in the guide. Having a statement saying that either one works would be perfect and help get rid of any confusion!

**Review by thatblindgeye — APPROVED** [review]
Would you want to make an issue for adding that verbiage to the style guide? You can of course also request to take the issue on as well.

If not no worries! Either way this has approval and will be merged!

**Comment by ItsKatato** [comment]
@thatblindgeye Sure, I would love to make an issue! The more contribution opportunities the better 👍🏽

**Pull request merged**
