### PR TITLE
What Is Node.js lesson: Update link

### PR DESCRIPTION
**Pull request by CutlerSheridan**
## Because

Currently, assignment #4 instructs the user to read the "Quick Start" section on the Node.js site, but it then has a note saying a lot of content has been removed recently and unhelpfully states the assignment "may no longer be as useful as it was."  In fact, the referenced section no longer exists on the Node.js site at all, leaving the user uncertain of whether they should read _anything_ on the site and rendering the existence of assignment #4 useless.

## This PR

- Updates the link in assignment #4 to navigate to an archived version of the Node.js site that still contains the "Quick Start" section using the Wayback Machine
- Amends the "NOTE" to reflect this change

## Issue

Closes (N/A)

## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [x] The `Because` section summarizes the reason for this PR
-   [x] The `This PR` section has a bullet point list describing the changes in this PR
-   [x] If this PR addresses an open issue, it is linked in the `Issue` section
-   [x] If any lesson files are included in this PR, they have been previewed with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure it is formatted correctly
-   [x] If any lesson files are included in this PR, they follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

### CODE REVIEW

**Comment by LeoKirasic** [comment]
Hey @CutlerSheridan thank you for creating the PR. I think we should link to the current node getting started tutorial instead of the archived one, we can omit the note about it not being useful as well. 

Would you be down to do another commit that:
- links to https://nodejs.dev/en/learn/introduction-to-nodejs/
- instructs learners to read the getting started section up to the TypeScript module
- omits the Note about the content not being useful anymore

It would be greatly appreciated. Thank you!

**Comment by CutlerSheridan** [comment]
@LeoKirasic done!  I haven't contributed much before—is there anything else I need to do to merge it or do you handle that?

**Review by LeoKirasic — APPROVED** [review]
Looks good. Thank you!

**Comment by LeoKirasic** [comment]
@CutlerSheridan Yeah, we're the one merging it. Thanks again!

**Pull request merged**
