### PR TITLE
Update deployment.md

### PR DESCRIPTION
**Pull request by kamranzafar4343**
## Because
Codeblocks should be updated to align with new changes in the [layout style guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md#codeblocks)

## This PR
 Remove aforementioned link from the Node path's deployment lesson

## Issue
Related to https://github.com/TheOdinProject/curriculum/issues/26939

## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [x] The `Because` section summarizes the reason for this PR
-   [x] The `This PR` section has a bullet point list describing the changes in this PR
-   [x] If this PR addresses an open issue, it is linked in the `Issue` section
-   [x] If any lesson files are included in this PR, they have been previewed with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure it is formatted correctly
-   [x] If any lesson files are included in this PR, they follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

### CODE REVIEW

**Review by kamranzafar4343 — COMMENTED** [review]
It looks fine. passed

**Review by fortypercenttitanium — CHANGES_REQUESTED** [review]
You removed the link for the video.

**Review by kamranzafar4343 — COMMENTED** [review]
"Thank you for your contribution! I appreciate the effort you've put into this commit. The code looks clean and well-organized. Keep up the good work!"

**Comment by kamranzafar4343** [comment]
Why to put link back in?

**Comment by fortypercenttitanium** [comment]
> Why to put link back in?

You remove a link in the lesson for "GoNodeJS video guide for deploying NodeJS applications to Fly.io". Why did you do that?

**Comment by kamranzafar4343** [comment]
"Remove aforementioned link from the Node path's deployment lesson"
Can you tell me what this means?

**Comment by fortypercenttitanium** [comment]
> "Remove aforementioned link from the Node path's deployment lesson" I understood that it says to remove the link from Node path's deployment lesson, can you tell me what this PR says? & I will put in back if this PR saying something else.

**You** wrote that in the PR description. Why is it being removed? The issue you linked has to do with markdown styling. I'm very confused why this link is being removed from the lesson. Is there a different issue I should be looking at?

**Comment by kamranzafar4343** [comment]
@01zulfi please have a look there!

**Comment by kamranzafar4343** [comment]
> > "Remove aforementioned link from the Node path's deployment lesson" I understood that it says to remove the link from Node path's deployment lesson, can you tell me what this PR says? & I will put in back if this PR saying something else.
> 
> **You** wrote that in the PR description. Why is it being removed? The issue you linked has to do with markdown styling. I'm very confused why this link is being removed from the lesson. Is there a different issue I should be looking at?

I think the probelm is caused by linking a different issue with PR.

**Comment by kamranzafar4343** [comment]
@fortypercenttitanium the issue was solved by linking the relevant issue with this PR.

**Comment by fortypercenttitanium** [comment]
> @fortypercenttitanium the issue was solved by linking the relevant issue with this PR. 

Okay I see now. That wasn't the issue that was linked originally!

You need to remove the words inside the square brackets on line 112 as well.

**Review by fortypercenttitanium — APPROVED** [review]

**Comment by kamranzafar4343** [comment]
Checks that has not passed: https://github.com/TheOdinProject/curriculum/actions/runs/7585891383/job/20662765502

**Comment by fortypercenttitanium** [comment]
It's fine - it's a new action we implemented and fixing those is out of scope for your issue.

**Comment by kamranzafar4343** [comment]
Thank you.

**Pull request merged**
