### PR TITLE
Update fundamentals-2.md

### PR DESCRIPTION
**Pull request by NerdsAreIn**
Proposed punctuation change to Conditionals bullet point 5.

 - [x] You have read [The Odin Projects Contributing Guide](https://github.com/TheOdinProject/curriculum/blob/master/CONTRIBUTING.md).

#### 1.Describe the changes made:

I punctuated the fifth bullet point under Conditionals for grammar and readability. It previously consisted of two sentences without a full stop between them.

#### 2. If this PR is related to an open issue please reference it with the `#` operator and the issue number below:

#XXXXX

### CODE REVIEW

**Comment by NerdsAreIn** [comment]
I'm new, so I didn't realise that "#" had a reserved use when I used it in my commit message. Sorry! Finding this a bit confusing...

**Comment by CatQueenCodes** [comment]
The original version seems a bit better. Thank you!

**Comment by NerdsAreIn** [comment]
But surely there should at least be a full stop/period before the "And"? That's the start of a new sentence.

**Comment by CatQueenCodes** [comment]
I would say the only change that needs to be made is making the "And" lower case. I don't think the extra commas are necessary. The ! inside the () is not ending the sentence

**Comment by ZachBaird** [comment]
@NerdsAreIn 
Sometimes a sentence sort of "works out" that way in spoken English, but in written English that wouldn't be correct.

With written English, a sentence doesn't start with an 'and' because a conjunction is actually meant to "splice" two _idea fragments_ together. The combined fragments then represent one cohesive idea which is what the sentence presents. 

Conjunctions aren't the only things used to combine sentence fragments either. Sometimes folks combine a conjunction with a comma (,) or use a semi-colon(;). When a semi-colon is used, it should **not** be followed with a conjunction. 

Either way, I think the original definitely needs revisited but that you had added a little too much punctuation around `and`. I think something like the following would be best since the 'more importantly' is a sort of conversational interjection in the text:

5. [This article](http://javascript.info/ifelse) covers the same basic concept \(read through it as a review!\) and - more importantly - offers the usual 'tasks' at the bottom of the page!

**Comment by I3uckwheat** [comment]
Lets go with what @ZachBaird said.

**Comment by CatQueenCodes** [comment]
@NerdsAreIn Please let us know if you plan to make this change!

**Comment by NerdsAreIn** [comment]
Hi. Sorry! I have been sick! 

I do find GitHub and its lingo rather confusing. I'll admit that I don't know how to actually make a change. Do I need "write access"? Can someone help me?

Concerning the grammar, I think @ZachBaird's suggestion of using dashes instead of commas to enclose "more importantly" is fine; this just creates a stronger break in the flow of the sentence. The point is that "more importantly" is a _supplementary_ adverbial, an adjunct, which could be removed from the sentence without affecting its meaning at all. The punctuation both reflects the natural pauses in speech that occur on either side of "more importantly" when reading the sentence aloud and its secondary grammatical role.

**Comment by marvingay** [comment]
@NerdsAreIn 
re: "Do I need write access?" 
No., it shouldn't be necessary to make any further changes.

Someone will get back to you regarding the change itself.

**Comment by NerdsAreIn** [comment]
Hi. I can see that no one has changed this yet and there is still a capital initial letter in the middle of what is currently a single sentence. Could somebody please change this, at least? Thanks in advance. Major grammar errors stress me... Haha.

**Comment by CatQueenCodes** [comment]
@NerdsAreIn you can update this pull request with the changes!

**Comment by CatQueenCodes** [comment]
Pushed it! Thanks for the change.

**Pull request merged**
