### PR TITLE
added solution

### PR DESCRIPTION
**Pull request by tcholmes3**
This is a PR template. If you are adding a solution link to the curriculum, leave this as is. If not, delete it and write the message you wish.

Thank you,

The Odin Project team.

### CODE REVIEW

**Comment by marvingay** [comment]
@tcholmes3 Solution submissions require you to edit at most 1 or 2 lines of markdown for the Project lesson you are submitting for. It appears you may have passed this file through a code formatter, resulting in expected changes.

If you can revert the extra changes, we can get your solution displayed!

**Comment by tcholmes3** [comment]
Marvin,

Based on what you've said, I'm thinking one of my VSCode extensions
formatted the entire markdown file. Is that correct?

I followed the instructions here
<https://blog.scottlowe.org/2015/01/27/using-fork-branch-git-workflow/>,
used GitBash, and used VSCode to edit. I guess I could delete both my local
and remote clone of the repo and just start the process over again. My
knowledge of Git is limited so, if this is ill-advised, please let me know.

Also, if there is a simpler way, please let me know. This is, after all, my
first pull request.

Thanks,
tcholmes3

**Comment by marvingay** [comment]
@tcholmes3 If you use "prettier" or any other code format extension, you will want to disable it in your VSCode **workspace** for the curriculum (so it's only disabled when you have that folder open).

I'll ensure that your solution is added this time :)

Stop by our discord chat or ask questions here if you have any more!

**Comment by tcholmes3** [comment]
Woah. That was fast.

Uhmm, thanks.

I guess I should create separate workspaces in VSCode and disable Prettier
within them when working on open-source projects, huh?

**Comment by marvingay** [comment]
When you open a "folder" in VSCode, it will cache a workspace by default. I encourage you to open folders in VSCode and not individual files.

I cannot comment on other open-source projects, but in this case, our **markdown parser** requires the code blocks to use tildes and not back ticks to properly show the code blocks properly. For some reason prettier defaults to using back ticks for markdown files.

**Comment by tcholmes3** [comment]
Yes, I do.
I will do my best to learn how to adjust settings by folder.

**Pull request closed without merging**
