### PR TITLE
Change 'echo' to 'nano' in command_line_basics.md

### PR DESCRIPTION
**Pull request by Zennoon**
## Issue

Closes #XXXXX

## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
-   [ ] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [x] The `Because` section summarizes the reason for this PR
-   [ ] The `This PR` section has a bullet point list describing the changes in this PR
-   [ ] If this PR addresses an open issue, it is linked in the `Issue` section
-   [ ] If any lesson files are included in this PR, they have been previewed with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure it is formatted correctly
-   [ ] If any lesson files are included in this PR, they follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

### CODE REVIEW

**Comment by ManonLef** [comment]
Could you explain why “nano” would be preferred over “echo”? I don’t believe “nano” to be available to every OS by default.

**Comment by Zennoon** [comment]
Hey, so in my understanding, the task in question asks us to create a new
file in a folder. To do so, the unix shell tutorial by swcarpentry has
given options including using nano, which opens the text editor and creates
the file if it doesn't exist already, or using touch which creates a new
empty file. Later on in the tutorial, it says that the echo command is used
to display / print a given input to the terminal. Therefore, I had assumed
that it can't be used to create a new file.
Thank You for reaching out, and inform me if I am mistaken.

**Comment by ManonLef** [comment]
Ah I see @Zennoon 
You can in fact create a new file with `echo`. A quick glance makes me think that is discussed in the "pipes and filters" chapter of the article. 

```bash
echo > test.md
```

The above would create the file `test.md` if not already present :)

**Comment by ManonLef** [comment]
Since a google search tells me that nano is not always installed by default on every OS and might have to be manually installed through the package manager, I think it is best to leave the instructions as is.

**Comment by Zennoon** [comment]
Awesome, thanks for the update!

**Pull request closed without merging**
