### PR TITLE
Move Learning Outcomes to the top

### PR DESCRIPTION
**Pull request by linh15**
- [x] You have read [The Odin Projects Contributing Guide](https://github.com/TheOdinProject/curriculum/blob/main/CONTRIBUTING.md).
 - [x] The title summarizes the change and where it happened, for example: "Fixes punctuation in Clean Code lesson".

#### 1.Describe the changes made and include why they are necessary or important:

- Move Learning Outcomes to the top
- Delete "Assignments" heading to avoid repetition with "Practice"
- Change the information about Solutions to become notes, because it is not an exercise and should not be a bullet point.

### CODE REVIEW

**Comment by wise-king-sullyman** [comment]
@linh15 in any future PRs please mention the lesson name in the PR title, doing so makes things easier for us to manage :slightly_smiling_face:

**Review by wise-king-sullyman — CHANGES_REQUESTED** [review]
Good catch on the Learning Outcomes being out of place!

I just have one suggestion/request I want to see.

**Comment by linh15** [comment]
> @linh15 in any future PRs please mention the lesson name in the PR title, doing so makes things easier for us to manage 🙂

Sorry about that, I will do it next time. Thanks for the reminder :)

**Comment by linh15** [comment]
> Good catch on the Learning Outcomes being out of place!
> 
> I just have one suggestion/request I want to see.

I have committed the change as you suggested.

**Review by wise-king-sullyman — APPROVED** [review]
Looks good! Thanks!

**Pull request merged**
