### PR TITLE
Css cheat sheet link shows "access denied", location: Intermediate HTML/CSS

### PR DESCRIPTION
**Pull request by Indiana-S-coder**
Location: Intermediate HTML/CSS
Fix : link in the assignment section "css cheat sheet"
The CSS CHEAT SHEET link given in the assignment section is not working and showing this -  "Access denied
Error code 1020
You do not have access to websitesetup.org.

The site owner may have set restrictions that prevent you from accessing the site."

## Issue

Closes #XXXXX

## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [ ] The `Because` section summarizes the reason for this PR
-   [ ] The `This PR` section has a bullet point list describing the changes in this PR
-   [ ] If this PR addresses an open issue, it is linked in the `Issue` section
-   [ ] If any lesson files are included in this PR, they have been previewed with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure it is formatted correctly
-   [ ] If any lesson files are included in this PR, they follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

### CODE REVIEW

**Comment by linkonsat** [comment]
This seems more of an issue. Were you interested in replacing the link @Indiana-S-coder? If not I'll go ahead and make an issue for it.

**Comment by Indiana-S-coder** [comment]
Sure, I would like to.
But do I have to use the link from same website or I can use other css
cheat sheet link from somewhere else?

**Comment by wise-king-sullyman** [comment]
One thought, do we want to potentially just change the link to something like https://devdocs.io/css/ or https://developer.mozilla.org/en-US/docs/Web/CSS?

**Comment by codyloyd** [comment]
this link works for me 🤔 .... but in the end the only real purpose of this document is for learners to get a glance at _allll_ of the possible CSS properties, just so they have a good frame of reference as they go through the subsequent lessons.... so anything will do.

I'm a big fan of the "devdocs" one @wise-king-sullyman posted

**Comment by linkonsat** [comment]
@Indiana-S-coder Are you still interested in adding the "devdocs" reference instead?

**Comment by Indiana-S-coder** [comment]
@linkonsat yes, I am still interested.

**Comment by Indiana-S-coder** [comment]
I have checked the link again:  https://htmlcheatsheet.com/css/ and it works fine now.
There is no need to change it.

**Comment by linkonsat** [comment]
@Indiana-S-coder. Perfect in this case i'll go ahead and close the PR.

**Pull request closed without merging**
