### PR TITLE
Fix spelling error and switch order of two steps

### PR DESCRIPTION
**Pull request by msespos**
- [x] You have read [The Odin Projects Contributing Guide](https://github.com/TheOdinProject/curriculum/blob/master/CONTRIBUTING.md).

#### 1.Describe the changes made:

a) Fixed one spelling error
b) Switched order of two steps in form_for section of project

#### 2. If this PR is related to an open issue please reference it with the `#` operator and the issue number below:

#XXXXX

### CODE REVIEW

**Comment by CatQueenCodes** [comment]
Can always count on you to catch spelling and grammar errors 😸 Thanks!

**Comment by msespos** [comment]
I switched steps 4 and 5 because I think the user needs the info that was in step 5 before they can start playing around with the suggestions that were in step 4.

**Comment by msespos** [comment]
Apologies for adding the second commit to this one; that was an error on my part - I meant them to be separate PRs.

**Comment by CouchofTomato** [comment]
Hey @msespos 

Thanks for the PR. None of the options in step 4 require a working create method. However I can see your point about having to change the create method to accept the params that will come from the form. The only thing I don't like is moving "test it out". That feels like it should be the last step to test out the form and make sure everything is working. How would you feel about leaving step 4 where it is currently, and instead just moving the line "You'll need to switch your controller's `#create` method again to accept the nested `:user` hash from `params`." to the end of point 3? Then we can just leave point 5 as "test it out".

I'm open to other suggestions if you think something else looks better.

**Comment by msespos** [comment]
@CouchofTomato So I think you are absolutely right and I was actually not sure about moving "test it out." So I think your suggested change sounds like the best one. Do I make this change and resubmit, or is it better if you make it at this point? Just let me know. Thanks!

**Comment by CouchofTomato** [comment]
@msespos 

All yours mate.

**Comment by CouchofTomato** [comment]
Thanks @msespos

**Review by CouchofTomato — APPROVED** [review]

**Pull request merged**
