### PR TITLE
Add my solution to HTML/CSS exercise

### PR DESCRIPTION
**Pull request by gaksedesu**
This is a PR template. If you are adding a solution link to the curriculum, leave this as is. If not, delete it and write the message you wish.

Thank you,

The Odin Project team.

### CODE REVIEW

**Comment by ZachBaird** [comment]
@gaksedesu It looks like you've added your solution in a manner inconsistent with the other student submissions. Can you modify your markdown so it looks like the other student submissions?

**Comment by ZachBaird** [comment]
@gaksedesu It doesn't look like the changes you made occurred in this pull request :(  I think you can directly edit the file here on the pull request via the `Files changed` tab.

**Comment by gaksedesu** [comment]
I think this time worked. (hopefully) @ZachBaird

**Comment by ZachBaird** [comment]
@gaksedesu It did! Looks great, awesome job!

**Pull request merged**
