### PR TITLE
Fix the id of the first input in checkboxes examples from lesson "Form Basics"

### PR DESCRIPTION
**Pull request by gerijeb**
- [x] You have read [The Odin Projects Contributing Guide](https://github.com/TheOdinProject/curriculum/blob/main/CONTRIBUTING.md).
 - [x] The title summarizes the change and where it happened, for example: "Fixes punctuation in Clean Code lesson".
 - [x] If the PR is related to an open issue, use a [relevant keyword](https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests) and reference it with the `#` sign and the issue number.
 - [x] You have previewed your markdown (if any) in the [Odin Markdown Preview Tool](https://www.theodinproject.com/lessons/preview)
 - [x] If changes are requested, please make the changes in a timely manner. After you submit the changes, request another review from the maintainer (top right).

#### 1. Describe the changes made and include why they are necessary or important:

Lesson: [Form Basics](https://www.theodinproject.com/paths/full-stack-javascript/courses/intermediate-html-and-css/lessons/form-basics).

In the section Checkboxes, the first input:checkbox has "child" as id, where it should've been "sausage" to match its corresponding label

#### 2. Related Issue

NA

### CODE REVIEW

**Comment by thatblindgeye** [comment]
Thank you for the first time contribution and for making this update! Can you please just edit your first post and follow the instructions of the template?

**Comment by gerijeb** [comment]
> Thank you for the first time contribution and for making this update! Can you please just edit your first post and follow the instructions of the template?

Thank you, I followed the steps and updated the post. I didn't find an open issue to put on number 2, so I wrote "Not Applicable".

**Review by thatblindgeye — COMMENTED** [review]
Yep no worries about that, that isn't always a required field, just something that should be filled out if there is an open issue related.

If you can just update the title of this PR as well to include the lesson, then just re-request a review from me and I'll get this merged for ya! :)

**Comment by gerijeb** [comment]
> Yep no worries about that, that isn't always a required field, just something that should be filled out if there is an open issue related.
> 
> If you can just update the title of this PR as well to include the lesson, then just re-request a review from me and I'll get this merged for ya! :)

Thanks for the explanation! Is the tittle better now?

**Comment by thatblindgeye** [comment]
Perfection, thanks so much!

**Review by thatblindgeye — APPROVED** [review]

**Pull request merged**
