### PR TITLE
Solution Link for Rock Paper Scissors Project - Web Dev 101

### PR DESCRIPTION
**Pull request by totalconsciousness**
This is a PR template. If you are adding a solution link to the curriculum, leave this as is. If not, delete it and write the message you wish.

Thank you,

The Odin Project team.

### CODE REVIEW

**Comment by marvingay** [comment]
@totalconsciousness Hello. It appears you may have deleted student solutions when attempting to resolve the merge conflicts. You may need to pull the current changes to your fork so we can have your solution displayed.

If you have questions do not hesitate to ask! Thank you!

**Comment by marvingay** [comment]
Resolved it on our end.

**Comment by marvingay** [comment]
If Github allows you to fix it via Github, it's often simpler that way.
In this case, on our side of things, that was not possible, so I used the Command Line Interface and VSCode to correct the problem.

**Comment by totalconsciousness** [comment]
Got it, thanks again.

**Pull request merged**
