### PR TITLE
Easy Fix:  Clarify instructions in fundamentals-2.md Ex.2

### PR DESCRIPTION
**Pull request by kdevay**
Complete the following REQUIRED checkboxes:

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`

Complete the following checkboxes ONLY IF they are applicable to your PR. You can complete them later if they are not currently applicable:
-   [x] I have previewed all lesson files included in this PR with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure the Markdown content is formatted correctly
-   [x] I have ensured all lesson files included in this PR follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

<hr>

**1. Because:**
- There are no instructions for locating Replit's console.
- Users report having to use their browser's dev tools to solve this exercise.
- Three within the top 5 comments (on the unforked Repl) mention this problem, so it is a fairly common issue. 

**2. This PR:**
- Proposed edit to line 52 would add language directing the user to the console toggle icon.

### CODE REVIEW

**Review by SauravJalui — COMMENTED** [review]
Hey @kdevay,

Thank you for suggesting to add these additional instructions.

You'll have to create a free replit account and fork the file to access the console. You can only run the unforked file, you can't access it's console.

The original instructions do ask to create an account and fork the file before the exercises start. You can  maybe update your instructions to say "you won't be able to access the replit console if you don't fork the file. Kindly create a free account and fork the file to access the console"

Best,
Saurav

**Comment by kdevay** [comment]
> You'll have to create a free replit account and fork the file to access the console. You can only run the unforked file, you can't access it's console.

Hi Saurav, thanks for your response. 

I already had an account, and I forked the file; then I realized none of the results were logging in the shell. I didn't realize the shell = the console.

I will revise my PR to reflect this more accurate wording of the issue: the shell is unresponsive, and users must view console logs via their browser dev tools.

I've attached a short screen recording illustrating the problem, and I also uploaded it to youtube (in case anyone is uncomfortable downloading videos from strangers):

Youtube: 
https://youtu.be/94T-20b4BMI (HD is still processing)

Download:
[shell-unresponsive.mov.zip](https://github.com/TheOdinProject/curriculum/files/9463392/shell-unresponsive.mov.zip)

**Comment by wise-king-sullyman** [comment]
@kdevay while opening the actual browser devtools does work, the experience is a bit better when you open the developer tools within replit, which you can do using the button in the below screenshot:
image

I agree that this isn't clear at the moment though, could you update your suggestion here to point users to that button? Once you've done that I think this will be good to go in.

**Comment by kdevay** [comment]
> could you update your suggestion here to point users to that button?

@wise-king-sullyman thanks for the clarification! I updated my PR following your suggestion. Hopefully my language is clear enough.

**Review by wise-king-sullyman — APPROVED** [review]
This looks great, thanks!

**Pull request merged**
