### PR TITLE
Javascript Computer Science Curriculum: Add a brief technical interview roadmap for studying algorithms

### LINKED ISSUE #26147: Javascript Computer Science: Add a brief roadmap/summary on how students can start drilling/studying algorithms for interviews
### Describe your suggestion

After reading the section on data structures/algorithms I felt like there was a huge gap to fill in terms of how to get started on studying for interviews. While doing my own research on what to do, I actually ended up creating my own PR to help improve on this. I realize the contributing guide says to create an issue before submitting a PR unless it's a simple issue, but I felt this was a pretty simple enhancement that I came up with from my own research and reading people's recommendations.

PR opened: https://github.com/TheOdinProject/curriculum/pull/26146 

### Path

Node / JS

### Lesson Url

https://github.com/joyceawt/curriculum/tree/main/javascript/computer_science

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### (Optional) Discord Name

_No response_

### (Optional) Additional Comments

_No response_

### PR DESCRIPTION
**Pull request by joyceawt**
## Because
After reading the section on Computer Science, I felt that there were a lot of gaps to fill. While there are other platforms like Leetcode which provide more information on how to drill data structures/algorithms, I felt like it would only make the entire curriculum more complete by offering some information for the student on how to start studying. 

I realized that I didn't open an issues for this but I was already sort of creating this list on my own for my own reference and that this is a simply simple addition, so I thought to just open the PR and see what you guys think.
EDIT: I've created an issue as well for better tracking :) 

## This PR
Adds a lesson on a brief roadmap/summary for how to study algorithms/data structures. I've covered the following:
1. How should I study - I've summarized the 2 main approaches I've seen mentioned online which include the topical and pattern approach.
2. Top problems asked - I added a piechart and ROI table from Algomonster (cited)
3. Provided a list of topics by priority based on what I saw online
4. Tips on studying - taking notes/developing a tracker, jotting down complexity analysis, mock interviews 
5. Additional resources - I've linked the most common resources mentioned for studying/grinding on algorithms/data structures

## Issue

Closes #26147 

## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
-   [X] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [X] The `Because` section summarizes the reason for this PR
-   [X] The `This PR` section has a bullet point list describing the changes in this PR
-   [X] If this PR addresses an open issue, it is linked in the `Issue` section
-   [X] If any lesson files are included in this PR, they have been previewed with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure it is formatted correctly
-   [X] If any lesson files are included in this PR, they follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

### CODE REVIEW

**Comment by ManonLef** [comment]
I am of the opinion that this might come across as encouragement to spend time on extra practice for technical interviews at a point that is too soon. I am not sure that's the general idea of TOP in this section. We generally recommend people to continue the curriculum and start the added practice when it's mentioned in the curriculum, which from the top of my head is in the `getting hired` section at the end. In the Node path, learners barely have portfolio worthy projects when they finish the CS section and I think that should be top priority. Just my two cents and I'll let @fortypercenttitanium to it.

**Review by fortypercenttitanium — CHANGES_REQUESTED** [review]
I agree with @ManonLef in that this is really valuable, but doesn't quite belong in this section. Can you commit to the Getting Hired section? At that point we can review where it should go in the order of the course.

**Comment by joyceawt** [comment]
@fortypercenttitanium  sure i'll modify my commit and move it to the get hired section!

**Comment by ManonLef** [comment]
@joyceawt just checking in to see if this is still on your radar :)

**Pull request closed without merging**
