### PR TITLE
replaces a dead link with another relevant link

### PR DESCRIPTION
**Pull request by ebukaume**
The former link "http://terenceponce.github.io/blog/2012/03/02/polymorphic-associations-in-rails-32/" responds with 404. So I looked for another resource on the topic "Polymorphic Association" and replaced it.

### CODE REVIEW

**Comment by leila-alderman** [comment]
Thanks for finding and reporting this broken link! I'm not crazy about the suggested replacement, though, as it doesn't seem to do a great job of explaining what's happening.

Here are three alternatives I found, ordered from simplest to more complex/in-depth:
 - [Semaphore](https://semaphoreci.com/blog/2017/08/16/polymorphic-associations-in-rails.html)
 - [Dev.to](https://dev.to/adjoa/rails-polymorphic-associations-511n)
 - [LaunchSchool](https://launchschool.com/blog/understanding-polymorphic-associations-in-rails)

**Comment by ebukaume** [comment]
Thanks for the follow-up.

Your recommended alternatives are pretty superior. Is it possible to add 2 links? 
[Dev.to](https://dev.to/adjoa/rails-polymorphic-associations-511n) can be used to whet the students' appetite while [LaunchSchool](https://launchschool.com/blog/understanding-polymorphic-associations-in-rails) builds on it; both did a nice job.

**Comment by leila-alderman** [comment]
Definitely! More additional resources is always better. Are you comfortable updating this pull request with those changes?

**Comment by ebukaume** [comment]
Sure, done!

**Comment by 105ron** [comment]
Thanks @ebukaume for the contribution.

**Pull request merged**
