### PR TITLE
Restructure lesson layout to fit layout style guide

### PR DESCRIPTION
**Pull request by adriananin**
## Because
The structure of this lesson does not follow the structure of the [layout guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md#lesson-layout) for lessons. The Additional resources section comes before the Knowledge check section which is inconsistent with the usual layout.

## This PR
- Move Additional resources section below Knowledge check section.

## Issue

Closes [#26422](https://github.com/TheOdinProject/curriculum/issues/26422)

## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [x] The `Because` section summarizes the reason for this PR
-   [x] The `This PR` section has a bullet point list describing the changes in this PR
-   [x] If this PR addresses an open issue, it is linked in the `Issue` section
-   [x] If any lesson files are included in this PR, they have been previewed with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure it is formatted correctly
-   [x] If any lesson files are included in this PR, they follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

### CODE REVIEW

**Comment by ManonLef** [comment]
Thank you for PRing this so quickly. It seems the codeblock was also edited, possibly by your formatter or linter. Could you revert that change?

**Comment by ManonLef** [comment]
I see you've made some changes but the codeblock is still formatted differently in this commit. You can see them side by side [in this changes overview](https://github.com/TheOdinProject/curriculum/pull/26426/files)

**Comment by adriananin** [comment]
Thanks

**Review by ManonLef — APPROVED** [review]

**Comment by ManonLef** [comment]
Thank you for making this change!

**Pull request merged**
