### PR TITLE
Update project_practicing_git_basics.md

### PR DESCRIPTION
**Pull request by mbeckdev**
Added a note to ignore something in the terminal that wasn't in the screenshot.

 - [ ] You have read [The Odin Projects Contributing Guide](https://github.com/TheOdinProject/curriculum/blob/master/CONTRIBUTING.md).

#### 1.Describe the changes made:

Added a note that says to ignore it if the terminal gives you "Your branch is based on 'origin/main', but the upstream is gone".

#### 2. If this PR is related to an open issue please reference it with the `#` operator and the issue number below:

#21930 -- Similar to this closed issue 
(#21939 says it fixed this on the Mac OS git instructions by checking for version 2.28 -- I am on git version 2.29.2 using the Xubuntu VM when I got this upstream note)

#### 3. Other notes: 
I got stuck on this for a bit and tried looking for answers online before ignoring it and going on - this note would have saved me the trouble.

Feel free to let me know if I'm doing this pull request wrong, I'm new to this.

### CODE REVIEW

**Comment by twalton83** [comment]
So, I happened to check this out because I had an inkling feeling this was due to a possible skipped instruction. Can I ask, if you clone the repo and open it on VS Code, does it show you master, or main in the bottom left corner when you open the folder in VSC?

**Comment by mbeckdev** [comment]
It's possible I could have missed a step somewhere.
After cloning my repo and opening it in VS Code it shows main in the bottom
left corner.

For fun I tried making another repo from scratch, and after the first
commit:
*I opened it in VS Code and it says main in the bottom left corner.
*after doing a `git status` I got the same message in the terminal at this
point `Your branch is based on 'origin/main', but the upstream is gone.
(use "git branch --unset-upstream" to fixup)`

**Comment by twalton83** [comment]
I deleted my comment but thanks for providing extra info! I’m happy to update but wanted to check first if it pops up as the result of a missed step somewhere or as a result of the main/master shift (which is when I receive the message). I’ll double check with someone else more familiar with Git before merging :)

**Comment by mbeckdev** [comment]
No worries,
I was wondering where comments showed up in github as I've never had one
before (I'm so new!). Today I learned a little more. Thanks for the info!

**Review by marvingay — APPROVED** [review]
The message displayed is a warning and normal.

I removed your change, solely because if somebody wants to investigate what that message means, that is their prerogative. However, I did expand the text instructions to match the message in the screenshot, such that the learner can be reasonably certain their output is fine regardless.

Thank you for bringing this up and for your contribution.

**Comment by mbeckdev** [comment]
Fair enough. Thanks for taking a look!

**Pull request merged**
