### PR TITLE
Ruby Course:  Installing Ruby - Update ruby version

### PR DESCRIPTION
**Pull request by karimdevelops**
## Because

The latest stable version is 3.3.5 and there are no major changes:
> Ruby 3.3.5 has been released.
This is a routine update that includes minor bug fixes. We recommend upgrading your Ruby version at your earliest convenience. For more details, please refer to the [GitHub release notes](https://github.com/ruby/ruby/releases/tag/v3_3_5).

Link: https://www.ruby-lang.org/en/news/2024/09/03/3-3-5-released/

## This PR

- Update 8 references of ruby version 3.3.4 to 3.3.5

## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project curriculum contributing guide](https://github.com/TheOdinProject/curriculum/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [x] The `Because` section summarizes the reason for this PR
-   [x] The `This PR` section has a bullet point list describing the changes in this PR
-   [x] If this PR addresses an open issue, it is linked in the `Issue` section
-   [x] If any lesson files are included in this PR, they have been previewed with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure it is formatted correctly
-   [x] If any lesson files are included in this PR, they follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

### CODE REVIEW

**Review by JoshDevHub — COMMENTED** [review]
Thank you for making this change!

We like to keep the Ruby version that's used in this installation lesson in sync with the Ruby version that is used for other repos in The Odin Project.

Would you be okay with bumping the Ruby versions in the [Main App repo](https://github.com/TheOdinProject/theodinproject) and the [Ruby testing repo](https://github.com/TheOdinProject/ruby_testing)? If you've never done that type of thing and don't feel comfortable doing so, I can handle it myself. Just wanted to offer to you if you're interested.

**Comment by karimdevelops** [comment]
> Thank you for making this change!
> 
> We like to keep the Ruby version that's used in this installation lesson in sync with the Ruby version that is used for other repos in The Odin Project.
> 
> Would you be okay with bumping the Ruby versions in the [Main App repo](https://github.com/TheOdinProject/theodinproject) and the [Ruby testing repo](https://github.com/TheOdinProject/ruby_testing)? If you've never done that type of thing and don't feel comfortable doing so, I can handle it myself. Just wanted to offer to you if you're interested.

I'd love it do it! But sadly I am not exactly sure how to do it... Should I just clone it, make changes in the markdown file and then make a pull request? I really want to do it, I'd appreciate your help.

**Comment by karimdevelops** [comment]
@JoshDevHub It successfully worked! I will make a PR soon.
I faced only one problem (which was fixed) `bundle install` returned one err in main repo but then after a quick search I install postgresql `sudo pacman -S postgresql`, then no errors were returned and it successfully worked.
Enough talking, I will make the PR now!

**Comment by JoshDevHub** [comment]
@karimdevelops I wouldn't worry about testing your changes locally. There are a lot of things that need to be set up, and I don't want you to have to jump through all that.

Instead just make a PR to the main [theodinproject](https://github.com/TheOdinProject/theodinproject). There will be tests that take your changes and run remotely in an environment that has everything configured and set up already. These tests are what I meant by "CI". If the PR passes CI, it should be fine to merge it.

**Comment by karimdevelops** [comment]
Sure mate

**Comment by karimdevelops** [comment]
@JoshDevHub I will create two seperate pull requests, I guess? Creating them now

**Review by JoshDevHub — APPROVED** [review]

**Pull request merged**
