### PR TITLE
html-foundations project-recipes: Add clarification about public/private repos and Github Pages

### PR DESCRIPTION
**Pull request by sykul**
I was confused for a minute when I attempted to follow this instruction about deploying my site on Github Pages because I had had my repo set to private. Adding this little instruction will help avoid that confusion or surprise if others also have their repos set to private.

## Because
Users unfamiliar with Github might not realise that changing their repo to public will fix this problem, and may feel compelled to purchase a paid Github subscription.

## This PR
Add a clarifying sentence to the instructions which states that a free Github account can use Github Pages but only if the repo is set to public. Link to instructions on how to set repos to public too.

## Issue
N/A

## Additional Information
N/A

## Pull Request Requirements
-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [x] The `Because` section summarizes the reason for this PR
-   [x] The `This PR` section has a bullet point list describing the changes in this PR
-   [x] If this PR addresses an open issue, it is linked in the `Issue` section
-   [x] If any lesson files are included in this PR, they have been previewed with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure it is formatted correctly
-   [x] If any lesson files are included in this PR, they follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

### CODE REVIEW

**Review by KevinMulhern — CHANGES_REQUESTED** [review]
Thanks for taking the time to do this @sykul. With the default being private for new repos, I can definitely see how this could be something many learners have trouble with. 

I reckon we should promote this to be included in the first step under [this heading](https://www.theodinproject.com/lessons/foundations-recipes#setting-up-your-projects-github-repository) , we could change it to something like this:

```
1.  Create a new repo for this project on GitHub.com. Name it `odin-recipes` and choose the `public` option instead of the default private.
```

**Comment by KevinMulhern** [comment]
Hey @sykul, just checking in. Do you still want to work on this PR?

**Comment by KevinMulhern** [comment]
No response

**Comment by sykul** [comment]
Hi. Sorry. Big life stuff. I'm happy to go ahead with the PR as you recommended. Would you mind reopening?

**Comment by KevinMulhern** [comment]
Sure thing @sykul

**Review by KevinMulhern — APPROVED** [review]
Looks great, thanks @sykul

**Pull request merged**
