### PR TITLE
Added solutions to tic-tac-toe and restaurant projects

### PR DESCRIPTION
**Pull request by carldoleolundgren**
Hello there - evidently my pull request didn't work correctly for my tic-tac-toe project. With this pul request, I'm adding solutions for both that project and the restaurant page. 

This is a PR template. If you are adding a solution link to the curriculum, leave this as is. If not, delete it and write the message you wish.

Thank you,

The Odin Project team.

### CODE REVIEW

**Comment by 105ron** [comment]
I only see merge conflict markers and no solution for tic-tac-toe?

**Comment by carldoleolundgren** [comment]
My apologies - I'm not sure why that is. Should I create whole new commits for each of the solutions and re-submit a pull request?

**Comment by 105ron** [comment]
You can just add another commit to this branch and it will update the pull request.

**Comment by marvingay** [comment]
Merge conflicts resolved.

**Pull request merged**
