### PR TITLE
Add my HTML/CSS solution to the list please.

### PR DESCRIPTION
**Pull request by paulca55**
This is a PR template. If you are adding a solution link to the curriculum, leave this as is. If not, delete it and write the message you wish.

Thank you,

The Odin Project team.

### CODE REVIEW

**Comment by leosoaivan** [comment]
:tada:

**Comment by leosoaivan** [comment]
Feel free to add your solutions to the top of the list next time!

**Comment by paulca55** [comment]
Yeeeyyy first ever pull request merged :)

Thanks!

**Comment by paulca55** [comment]
Sorry I felt a bit cheeky putting it at the top and it said add your solution below this list, but I know for next time.

**Pull request merged**
