### PR TITLE
Remove warm-up project

### PR DESCRIPTION
**Pull request by Demo318**
Event Manager project broken. Since Spotlight Labs closed its doors, its congress API has not been maintained correctly. As of 10/18/2017, it is no longer functioning. All API calls are timing out.

```
This is a PR template, If you are adding a solution link to the curriculum leave this as is. If you are not, then delete it and write the message you wish.
Thank you,
The Odin Project team.

```

### CODE REVIEW

**Comment by mindovermiles262** [comment]
I still think there is value in this project.  It looks like Code for America has made a ruby wrapper for [the API](https://github.com/codeforamerica/congress) that we could use instead, and ProPublica is [taking over the congress API](https://www.propublica.org/article/taking-cues-and-some-projects-from-sunlight-labs)

**Comment by KevinMulhern** [comment]
I think there is value in it too @mindovermiles262. But IMO unless jumpstart labs update their tutorial I don't think we have any choice but to remove it.

We could make a note in the project side on our side to instruct the user to use that new wrapper. But that could get messy quickly, have the potential to be very confusing and wouldn't be a good experience for the user. We would also have to maintain the instructions in the long term which could become a head ache if they change again.

Thankfully its just a warm up project though, this should hopefully have less of an impact on the quality of the course.

**Comment by mindovermiles262** [comment]
I'd be willing to rewrite the article for Jump Start Labs - looks like it's open sourced.

Let me look into this - I will aim to have an update by 01 Nov

**Comment by KevinMulhern** [comment]
Thanks @mindovermiles262 😄  I'm sure they'l be very grateful for that.

**Comment by mindovermiles262** [comment]
I'm going to close this PR. There is an open issue I will assign myself to.

Thanks for letting us know about this, @Demo318 👍 We really appreciate it!

**Pull request closed without merging**
