### PR TITLE
Clean Code lesson: missing semicolon in code example A #27724

### LINKED ISSUE #27724: Clean Code: <Missing semicolon in code example A>
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

In the **what is clean code** lesson content, the second paragraph says 

> In the first example, single-letter variables are used, there is a semicolon in the middle of lines, and the indentation is inconsistent. The result is a piece of code that is confusing and messy.

referring to this piece of code

```
const x = function (z) {
  const w = "Hello ";
return w + z
};

x("John");

```

but there is no semicolon in the middle of any line.

What can be done? Reintroduce the semi colon or remove the  reference to a semicolon?

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-clean-code

### (Optional) Discord Name

daniel.scrypt

### (Optional) Additional Comments

_No response_

### PR DESCRIPTION
**Pull request by danieletie**
- remove reference to semicolon in code example A

## Because

Remove wrong reference to semicolon in the Code Example A. Makes the content of the lesson more comprehensice as there is no more  reference to a semicolon that doesn't exist.

## This PR

- delete the line _there is a semicolon in the middle of lines_

## Issue

Closes #27724 

## Pull Request Requirements

-   [ x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
-   [ x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [ x] The `Because` section summarizes the reason for this PR
-   [ x] The `This PR` section has a bullet point list describing the changes in this PR
-   [ x] If this PR addresses an open issue, it is linked in the `Issue` section
-   [ x] If any lesson files are included in this PR, they have been previewed with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure it is formatted correctly
-   [ x] If any lesson files are included in this PR, they follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

### CODE REVIEW

**Comment by MaoShizhong** [comment]
@danieletie  For easier referencing: https://github.com/TheOdinProject/curriculum/issues/27724#issuecomment-2028894640

Sure, go ahead and fix up any other references to that semicolon thing that we no longer need.

And sure, make that verbiage change for the camelCase thing as well.

**Comment by danieletie** [comment]
Hello @MaoShizhong , I'm a little confused rn with the issue #s.

Do I make pull requests quoting this issue #27726 going forward, or do i stil refer to #27724.

I'm sorry, I'm not so conversant with how all this works.

Also do I get to delete the other issue raised?

**Comment by MaoShizhong** [comment]
> Hello @MaoShizhong , I'm a little confused rn with the issue #s.
> 
> Do I make pull requests quoting this issue #27726 going forward, or do i stil refer to #27724.
> 
> I'm sorry, I'm not so conversant with how all this works.
> 
> Also do I get to delete the other issue raised?

@danieletie No, I just referenced and answered the question here in this PR because the PR has already been opened, so it'd be better to continue any discussions regarding what changes need to be made in the PR itself.

You do not need to open any new PRs/issues or delete anything.

This PR is already linked with #27724 because you put "Closes #XXXXX" in the PR message, meaning if this PR gets merged, it'll automatically close that issue. So nothing you need to do on your end about that.

Any further changes you need to make in this PR, you just commit and push to your fork's `clean_code_missing_semicolon....` branch which will automatically update here (because a PR just tracks that branch).

I see you've opened a new PR, probably because you were confused as to what you needed to do.
To keep things all together, I will close that PR. You can then checkout back to the branch for this PR, make the changes there and push and commit to this branch.

**Review by MaoShizhong — APPROVED** [review]
We're all good to go! :rocket:
Thank you for raising the issue and making the changes.

**Pull request merged**
