### PR TITLE
Update link to Normalize.css

### PR DESCRIPTION
**Pull request by jcvargas1**
The current link for Normalize.css in the assignments section appears to be out of date and leads the user to a 404 link. I have updated the link which is https://necolas.github.io/normalize.css/

Complete the following REQUIRED checkboxes:

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`

Complete the following checkboxes ONLY IF they are applicable to your PR. You can complete them later if they are not currently applicable:
-   [x] I have previewed all lesson files included in this PR with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure the Markdown content is formatted correctly
-   [x] I have ensured all lesson files included in this PR follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

<hr>

**1. Because:**

Closes #XXXXX

**2. This PR:**

**3. Additional Information:**

### CODE REVIEW

**Comment by LeoKirasic** [comment]
Are you sure the link is broken? Seems to be working for me. Could possibly be an issue on your end.

Normalize

**Comment by jcvargas1** [comment]
How odd. It works for me now as well too, but when you click their project site link on the webpage now that gives a 404. Perhaps they were in the middle of doing something to the site at the moment I had checked. 

image

**Comment by LeoKirasic** [comment]
@jcvargas1 I don't think that a broken link on their page matters too much since there's another one that links directly to the github. It's best we keep it as it is.

**Comment by jcvargas1** [comment]
Yeah, my apologies. Like I said, the link might of just not worked in the moment I was attempting to view it. Thanks regardless!

@LeoKirasic

**Comment by LeoKirasic** [comment]
Thanks for taking your time to make a PR!

**Pull request closed without merging**
