### PR TITLE
HTML/CSS exercise

### PR DESCRIPTION
**Pull request by CodingGeekOdin**
This is a PR template. If you are adding a solution link to the curriculum, leave this as is. If not, delete it and write the message you wish.

Thank you,

The Odin Project team.

### CODE REVIEW

**Comment by ryanford-frontend** [comment]
Can you format your submission with markdown like the others in the file?

**Comment by CodingGeekOdin** [comment]
ok i will do it thanks!

**Comment by CodingGeekOdin** [comment]
sorry, i think i did something wrong...

**Comment by 105ron** [comment]
It looks like you deleted the content in the file. I'll close this and you can open a new pull request from scratch. If you need help ask on our forum or chat room and someone will be happy to assist.

**Pull request closed without merging**
