### PR TITLE
Javascript: Update Asynchronous JavaScript and APIs lessons to follow layout style guide

### PR DESCRIPTION
**Pull request by BLooDBRothER**
Complete the following REQUIRED checkboxes:

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`

Complete the following checkboxes ONLY IF they are applicable to your PR. You can complete them later if they are not currently applicable:
-   [x] I have previewed all lesson files included in this PR with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure the Markdown content is formatted correctly
-   [x] I have ensured all lesson files included in this PR follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

<hr>

**1. Because:**

Lessons under javascript (Asynchronous JavaScript and APIs) in NodeJS path doesn't follow Layout Style Guide

**2. This PR:**

Update these lesson as per the guide

**3. Additional Information:**

### CODE REVIEW

**Review by wise-king-sullyman — CHANGES_REQUESTED** [review]
The changes you've made so far look great, thanks for making them!

One request: it seems like a lot of the link text in these lessons is less than great, which can be a big negative for accessibility. Could you improve the link text [where needed as we outline in the style guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md#use-informative-markdown-link-titles)?

If you're unsure which links are problematic or what we're looking for with regards to improvement please let me know!

**Comment by BLooDBRothER** [comment]
Hi! Bit busy with my exams for past few days.
Are you referring this type fixes?
```
 Read [this article](https://javascript.info/async-await) for a solid introduction to async/await. [This article](https://codeburst.io/javascript-es-2017-learn-async-await-by-example-48acc58bad65) also has some good examples of its use.
```
### To
```
 Read this [Async and Await](https://javascript.info/async-await) article for a solid introduction to async/await. This [Async and Await examples](https://codeburst.io/javascript-es-2017-learn-async-await-by-example-48acc58bad65) article also has some good examples of its use.
```
## In MD way
 Read [this article](https://javascript.info/async-await) for a solid introduction to async/await. [This article](https://codeburst.io/javascript-es-2017-learn-async-await-by-example-48acc58bad65) also has some good examples of its use.
### To
 Read this [Async and Await](https://javascript.info/async-await) article for a solid introduction to async/await. This [Async and Await (examples)](https://codeburst.io/javascript-es-2017-learn-async-await-by-example-48acc58bad65) article also has some good examples of its use.

**Comment by BLooDBRothER** [comment]
@wise-king-sullyman Hi! any updates?

**Comment by wise-king-sullyman** [comment]
Hey! Sorry I've been slam busy as well, in your example I would actually do something like:

Read this [Async and Await article](https://javascript.info/async-await) for a solid introduction to async/await. This [Async and Await examples article](https://codeburst.io/javascript-es-2017-learn-async-await-by-example-48acc58bad65) also has some good examples of its use.

**Comment by BLooDBRothER** [comment]
Got it! I will rectify it and update you on it

**Comment by BLooDBRothER** [comment]
I made the requested changes.
Notify me if there is any correction.

**Comment by wise-king-sullyman** [comment]
@BLooDBRothER apologies for the confusion, I would still include the word "this" in those sentences, just outside of the link text.

**Comment by BLooDBRothER** [comment]
@wise-king-sullyman Sorry for that confusion!
I rectified it, Notify me if there is any correction. I'm happy to work :slightly_smiling_face:

**Review by wise-king-sullyman — APPROVED** [review]
Looks great, thanks!

**Pull request merged**
