### PR TITLE
Added my flight booker solution to the project file

### PR DESCRIPTION
**Pull request by learnsometing**
This is a PR template. If you are adding a solution link to the curriculum, leave this as is. If not, delete it and write the message you wish.

Thank you,

The Odin Project team.

### CODE REVIEW

**Comment by leila-alderman** [comment]
@learnsometing Your GitHub repo shows that you've already hosted this project on Heroku. Would you like to add a link to your live site to your solution here?

**Comment by learnsometing** [comment]
@leila-alderman I think I'll leave the heroku link out of the curriculum file. I may take the site off heroku in the future so I figured it would be easier to update that link through my github repo than to do it here.

**Comment by learnsometing** [comment]
@leila-alderman thanks for asking.

**Comment by leila-alderman** [comment]
@learnsometing Cool -- I'll go ahead and merge this then. Thanks!

**Pull request merged**
