### PR TITLE
Change 'empty div elements' to 'empty semantic HTML elements'

### PR DESCRIPTION
**Pull request by JonathanYiv**
The course introduced you to the semantic HTML elements like `<aside>, <header>, <footer>`, and stated that usage of them for semantic purposes is preferable to divs if possible.
This change seems to be appropriate for instilling best practices

### CODE REVIEW

**Comment by KevinMulhern** [comment]
Did the resources make it clear what semantic elements are? It's been an absolute age since I went though this lesson.

We can merge this though, and keep an eye on chat for any confusion in relation to this.

**Comment by ZASMan** [comment]
@JonathanYiv, on the word `semantic` you should make it a link to what semantic elements are. It's not exactly the most common adjective either.

**Comment by JonathanYiv** [comment]
In the sixth lesson ["What's New for HTML5,"](https://www.theodinproject.com/courses/html5-and-css3/lessons/what-s-new-in-html5) the course introduced semantic elements as the first Learning Outcome 'What are semantic tags and how are there more of them in HTML5?' and in the introductory sentence 'Another set of new features is the use of more semantic tags in your markup so you don’t need to put a div around everything (you can use the aside or footer etc).'

Is this best practice in the actual industry?
I can add a link referencing it if it seems unclear

**Comment by KevinMulhern** [comment]
It should be best practice, in reality the semantic tags like `aside` and `article` have narrow depending on the type of website you have. Divs are still the most used tags from my own experience. I know thats anecdotal though. 

I have no problem with this being merged though as its completely correct. We should keep an eye out to see if it causes any confusion though.

**Pull request merged**
