### PR TITLE
Fix Grammar: Problem Solving

### PR DESCRIPTION
**Pull request by Fiattarone**
Saw that we were using double quotes on double quotes for the beginning quote. Fixed by replacing inner double quotes with single quotes.

Complete the following REQUIRED checkboxes:

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`

Complete the following checkboxes ONLY IF they are applicable to your PR. You can complete them later if they are not currently applicable:
-   [ ] I have previewed all lesson files included in this PR with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure the Markdown content is formatted correctly
-   [ ] I have ensured all lesson files included in this PR follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

<hr>

**1. Because:**

Closes #XXXXX
Because ""Fiattarone's quote" -- Fiattarone" is incorrect, it should be:  "'Fiattarone's quote' -- Fiattarone"

It may not be obvious at first, but the " > " induces a quote line which includes the " "'s automatically. 

**2. This PR:**

- Replaced inner double quotes with a set of single quotes

**3. Additional Information:**

### CODE REVIEW

**Review by CouchofTomato — CHANGES_REQUESTED** [review]
The `>` should add the quote marks for us, which is why we see the double quotes so I think we can just get rid of the quote marks altogether otherwise we'd probably see `"'` instead.

**Comment by CouchofTomato** [comment]
> Actually on the fence about this one, shouldn't this be single quotes within double quotes because Anton Spraul is quoting Think Like a Programmer? I know he wrote the book, but I believe the single & double quote rules still apply because the book itself is still a separate entity. The rule also applies when quoting yourself.

Your proposed solution looks like this

image

This doesn't look right to me.

**Review by Fiattarone — COMMENTED** [review]
Took changes from @CouchofTomato into account and fixed outstanding errors.

**Review by zachmmeyer — APPROVED** [review]
I like the way this looks, except for the quotes, but that's an us problem and not a you problem.

Thank you!

**Pull request merged**
