### PR TITLE
Foundations/JS basics part 2: Updated list styles

### PR DESCRIPTION
**Pull request by damon314159**
## Because
List styles in lesson file don't match the new style guide

## This PR
Makes the required changes to bring the style in line

## Issue

Contributes to #27119

## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [x] The `Because` section summarizes the reason for this PR
-   [x] The `This PR` section has a bullet point list describing the changes in this PR
-   [x] If this PR addresses an open issue, it is linked in the `Issue` section
-   [x] If any lesson files are included in this PR, they have been previewed with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure it is formatted correctly
-   [x] If any lesson files are included in this PR, they follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

### CODE REVIEW

**Comment by damon314159** [comment]
@thatblindgeye slight roadbump on this one. The linter isnt happy about the heading used to give the Replit warning note it's title
When you check the linter configs:
```
"MD043": {
      "headings": [
        "### Introduction",
        "### Lesson overview",
        "*",
        "### Assignment",
        "### Knowledge check",
        "### Additional resources"
      ],
      "match_case": true
    }
    ```
    It allows * wildcards only between lesson and assignment, but since this note falls between assignment and knowledge, there's no way to make it pass.
    
   Either the note needs moving way up the page (where it will be nowhere near replit assignment), or the linter config needs an asterisk between assignment and knowledge check.
   
   Happy to PR the linter configs with a green light. Thoughts?

**Comment by thatblindgeye** [comment]
Yep, some of our lessons will trigger this error unfortunately. It may be worth us trying to customize our own rule for heading structures rather than using the default rule (which only allows this sort of limitation, either an exact structure or wildcard of anything). 

I'm sort of leaning towards removing that heading as I'm not sure it's totally needed... What do you think? Would be interested from the user's perspective in terms of what is helpful when going through these lessons.

**Comment by damon314159** [comment]
If you take out the h4 heading you don't get the warning triangle, so people might gloss over it.
Even if they don't it feels like a bandage over a larger issue, that sometimes you might need notes in places the template isnt expecting

**Comment by thatblindgeye** [comment]
The styling is set up so that any note boxes render with an icon whether there is a heading inside it or not, so that wouldn't be an issue. But agreed that the Assignment section at least may have level 4 headings. That's something that would be a follow up issue, though. For now I'll leave it up to you whether to remove that heading or not, as I don't feel super strong about it. I've opened https://github.com/TheOdinProject/curriculum/issues/27162 for now as a follow up

**Comment by damon314159** [comment]
As the config file was changed, this test would no longer fail if rerun - but I don't have the permissions to rerun it @thatblindgeye

**Comment by JoshDevHub** [comment]
@damon314159 reran and it still fails

Probably have to merge `main` into this branch to get the necessary config update

**Comment by damon314159** [comment]
That was a hard fought battle 😆 - bot is finally happy

**Review by thatblindgeye — APPROVED** [review]

**Pull request merged**
