### PR TITLE
Add knowledge checks to How Does the Web Work in foundations

### PR DESCRIPTION
**Pull request by dylan-workhub**
- [x] You have read [The Odin Projects Contributing Guide](https://github.com/TheOdinProject/curriculum/blob/master/CONTRIBUTING.md).

#### 1.Describe the changes made:

Added knowledge checks to `How Does the Web Work` in foundations.

#### 2. If this PR is related to an open issue please reference it with the `#` operator and the issue number below:

#22259

### CODE REVIEW

**Comment by dylan-workhub** [comment]
I was a little unsure of what exactly to do with the learning outcomes for this one, and I may have added too many knowledge checks, so if changes are needed just let me know!

**Review by rlmoser99 — CHANGES_REQUESTED** [review]
Great job updating this lesson! There are not too many Knowledge Checks, as this lesson covers a lot of terminology. 

I would combine the packet one into one question, something along the lines of 'What are packets and how are they used to transfer data?'

And either combine 'What is a client? What is a server?' into one question, or put them on two lines.

In addition, I think the last Learning Outcome should be moved to the Knowledge Check section.

**Comment by dylan-workhub** [comment]
Changes have been made! Let me know if there's anything else.

**Review by rlmoser99 — APPROVED** [review]
This looks great! Thank you so much for taking the time to update this lesson!

**Pull request merged**
