### PR TITLE
Project Express 105: Update assignment to mention Glitch

### PR DESCRIPTION
**Pull request by takinabradley**
## Because

The MDN tutorial currently seems to prefer learners to use Glitch over Railway. It was a bit confusing that only Railway was mentioned.

## This PR

- Edits references to Railway to also include Glitch to avoid confusion for learners

## Issue

Closes #XXXXX

## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [x] The `Because` section summarizes the reason for this PR
-   [x] The `This PR` section has a bullet point list describing the changes in this PR
-   [x] If this PR addresses an open issue, it is linked in the `Issue` section
-   [ ] If any lesson files are included in this PR, they have been previewed with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure it is formatted correctly
-   [ ] If any lesson files are included in this PR, they follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

### CODE REVIEW

**Comment by takinabradley** [comment]
I made this PR before deploying with Glitch, once I assumed it was a valid thing to do.

Something of note is that I had issues with the current Node LTS when using Glitch. I rolled back to an earlier version of node with `nvm` and installed an older `mongoose` package to get Glitch to play nice. Is this possibly why glitch wasn't mentioned?

**Comment by MaoShizhong** [comment]
Glitch wasn't mentioned because it was only added to the local library tutorial around December last year it seems: https://github.com/mdn/content/pull/30945

Apparently even though Glitch's docs say the max supported Node version is 16.14, apparently people have had success by following the instructions specified in an open PR to [provide fix for Glitch Node version compatibility](https://github.com/mdn/content/pull/32695).

Would you mind testing those instructions with the latest version of mongoose? Since I think you said that the latest Mongoose version requires Node v16.20 and if Glitch only supports up to v16.14, then that linked PR's fix may not be sufficient? But if it is, then there wouldn't be much else to do on our end if and when that MDN PR gets merged.

**Comment by takinabradley** [comment]
@MaoShizhong 

I tested on a local project real quick using `nvm use 16.14`, and immediately upon doing `npm install mongoose`, I'm met with EBADENGINE warnings just like I was getting originally trying to host with Glitch:
```
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'bson@6.5.0',
npm WARN EBADENGINE   required: { node: '>=16.20.1' },
npm WARN EBADENGINE   current: { node: 'v16.14.2', npm: '8.5.0' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'mongodb@6.3.0',
npm WARN EBADENGINE   required: { node: '>=16.20.1' },
npm WARN EBADENGINE   current: { node: 'v16.14.2', npm: '8.5.0' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'mongoose@8.2.2',
npm WARN EBADENGINE   required: { node: '>=16.20.1' },
npm WARN EBADENGINE   current: { node: 'v16.14.2', npm: '8.5.0' }
npm WARN EBADENGINE }
```

Normally, when I see this I see runtime behavior problems, but upon some light actual *using* of mongoose and ignoring these warnings, I haven't run into any (yet). 

When I was talking in the Discord, I had seen and proactively fixed this by rolling back to Mongoose 7 before figuring out I needed to allow IP access to MongoDB- so it (may) not actually be a problem.

I'll spin up a test project on Glitch here soon (maybe tomorrow) and see if it works. It's definitely possible that with more usage that there could be issues.

**Comment by takinabradley** [comment]
@MaoShizhong 

Faster update than I thought. Seems to be working fine on Glitch (with very little mongoose code reading and deleting to a DB), despite the errors.

**Review by MaoShizhong — APPROVED** [review]
Just tested things myself with a Glitch deploy using only latest package versions, and both with the `>=v16` engine part in `package.json` as per the above PR, and without.

Can confirm that without, it defaults to v10 and breaks due to Mongoose using optional chaining.
With, it will use v16.14 which while it brings up the EBADENGINE warnings, will not prevent any of the tutorial's features from working.

Since this PR is just about mentioning Glitch (because it was only a recent addition to MDN's tutorial), there isn't much of an issue and so I'll approve.

Hopefully on MDN's side, that PR gets merged fairly soon so people don't run into the Node v10/optional chaining issue.

According to that (or its linked issue), the latest Node version is something Glitch will hopefully be looking into as well.

Either way, since v16.14 won't actually break any features of the tutorial app, Glitch isn't one of the listed PaaS in the deployment lesson, *and* we're planning to move away from the MDN tutorial in the Node revamp, I don't think there's much else we need to do here unless things actually start breaking.

**Pull request merged**
