### PR TITLE
Copyedit/ruby conditional lesson

### PR DESCRIPTION
**Pull request by leosoaivan**
Should we have assignments in this lesson?

### CODE REVIEW

**Comment by leosoaivan** [comment]
@leila-alderman's edited the Conditional Lesson, so we can but that link in there.

**Comment by leila-alderman** [comment]
That link was already in the Additional Resources section for this lesson, but I moved it up to a new Assignment section in my PR.

**Comment by KevinMulhern** [comment]
@leosoaivan oh oh, looks like merging that other caused some conflicts 🙈

**Comment by leosoaivan** [comment]
Looks like I've mucked up the resolve lol

**Comment by leosoaivan** [comment]
No worries anyway, I saw @leila-alderman and those are great. Closing this PR.

**Pull request closed without merging**
