### PR TITLE
Javascript Final Project: add introductory React and Typescript additional resource

### PR DESCRIPTION
**Pull request by crespire**
## Because
Typescript is becoming more important in the JS/React ecosystem (not to mention other frontend frameworks like Angular are also TS based), it may be worthwhile including some resources on TypeScript.

Per discussion on Discord, this PR adds an additional resource, but can also serve as a discussion point for if/when/how the curriculum includes TypeScript.

[edit]
The resource being added: https://profy.dev/article/react-typescript

## This PR
* Adds an additional resource link to the Javascript Final on using React with Typescript

## Additional Information
https://discord.com/channels/505093832157691914/1048324977046339644

## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [x] The `Because` section summarizes the reason for this PR
-   [x] The `This PR` section has a bullet point list describing the changes in this PR
-   [x] If this PR addresses an open issue, it is linked in the `Issue` section
-   [x] If any lesson files are included in this PR, they have been previewed with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure it is formatted correctly
-   [x] If any lesson files are included in this PR, they follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

### CODE REVIEW

**Comment by Aureatus** [comment]
The concern that comes straight to mind for me, is how and when/if we handle the matter of telling typescript to ignore a line/expect errors. In some cases, it's useful/needed, but by telling people that we could end up causing them to ignore things that they don't understand, rather than trying to figure it out.

**Comment by crespire** [comment]
> The concern that comes straight to mind for me, is how and when/if we handle the matter of telling typescript to ignore a line/expect errors. In some cases, it's useful/needed, but by telling people that we could end up causing them to ignore things that they don't understand, rather than trying to figure it out.

Agreed. `// eslint-disable-next-line react-hooks/exhaustive-deps` comes to mind as a candidate, for example.

**Comment by Aureatus** [comment]
> Agreed. `// eslint-disable-next-line react-hooks/exhaustive-deps` comes to mind as a candidate, for example.
I think it's probably wise to have it as the last lesson in a typescript module, more an appendix than a fully fledged lesson perhaps.

**Comment by zachmmeyer** [comment]
@crespire I'm going to approve this and merge it. Does it need a follow up issue to add more content related to eslint or adding a module?

**Review by zachmmeyer — APPROVED** [review]

**Comment by crespire** [comment]
> @crespire I'm going to approve this and merge it. Does it need a follow up issue to add more content related to eslint or adding a module?

I think it's a good stand alone article. By this point, learners should have everything set up anyway. Thanks, Zach!

**Pull request merged**
