### PR TITLE
Project Testing Practice: added examples to caesar cipher test cases

### LINKED ISSUE #27968: Testing Practice: Clarification on caeser cipher.
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

In the caeser cipher function, it is not clear whether we have to test considering punctuations or not ? if yes then in which way ? for example, in alphabet and numbers we shift in order eg. for factor 2 'a' becomes 'c' but if we have do it for let's say the period ('.') which way does it go ?
image

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-javascript-testing-practice

### (Optional) Discord Name

DVS-CODES

### (Optional) Additional Comments

_No response_

### PR DESCRIPTION
**Pull request by catbree**
## Because

This came from issue #27968, a student found the instructions on `caesarCipher`  unclear and suggested to add examples and clarity to make it easier for others to understand.

## This PR

* Added example to test wrapping.
* Added clarification and example to test case preservation.
* Added clarification and example to test punctuation.

## Issue

Closes #27968

## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project curriculum contributing guide](https://github.com/TheOdinProject/curriculum/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [x] The `Because` section summarizes the reason for this PR
-   [x] The `This PR` section has a bullet point list describing the changes in this PR
-   [x] If this PR addresses an open issue, it is linked in the `Issue` section
-   [x] If any lesson files are included in this PR, they have been previewed with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure it is formatted correctly
-   [x] If any lesson files are included in this PR, they follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

### CODE REVIEW

**Comment by CouchofTomato** [comment]
Hey @catbree 

Thanks for making this PR.

There are some linting issues. Some aren't related to your PR so you can take them on if you want but some are. Can you take a look at the details for the failing lint check above and let me know if you need anything clarified.

**Comment by catbree** [comment]
@CouchofTomato I've fixed the linting issues. Question: Is it possible for me to run the markdown lint checks by myself? I was referencing the list of issues directly on Github and the lines didn't match once I started making edits on the file itself. So I thought I may have been missing something...

**Review by CouchofTomato — APPROVED** [review]

**Comment by CouchofTomato** [comment]
@catbree I haven't looked for a while but the last time I looked running github actions outside of their normal execution context was somewhat painful. I haven't heard it's got any easier but I haven't really gone looking.

Thanks for making those changes.

**Comment by MaoShizhong** [comment]
@catbree and @CouchofTomato Linting (and fixing) can be done locally very easily by following the instructions in our updated [curriculum repo contributing guide](https://github.com/TheOdinProject/curriculum/blob/main/CONTRIBUTING.md).

Make sure your branch is in sync with upstream main to so you've got the latest markdown lint configuration. Once that's done, the instructions there make running the checks and autofixing some of the errors fairly straightforward.

**Comment by catbree** [comment]
Awesome, thank you @CouchofTomato @MaoShizhong I've learnt alot. :-)

**Pull request merged**
