### PR TITLE
Advanced Grid Properties: Add Josh Comeau's article about grid as an extra resource 

### PR DESCRIPTION
**Pull request by nikitarevenco**
## Because

I found an awesome guide to Grid that really helped me solidify understanding about Grid when I first did those lessons, I feel that this resource would help people struggling with Grid.

## This PR

Adds an interactive article about Grid as an additional resource for the Advanced Grid Properties section, covering everything learnt up to that point and some more too.

## Issue

Closes #XXXXX

## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [x] The `Because` section summarizes the reason for this PR
-   [x] The `This PR` section has a bullet point list describing the changes in this PR
-   [x] If this PR addresses an open issue, it is linked in the `Issue` section
-   [x] If any lesson files are included in this PR, they have been previewed with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure it is formatted correctly
-   [x] If any lesson files are included in this PR, they follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

### CODE REVIEW

**Comment by JoshDevHub** [comment]
Did you intend to close this @nikitarevenco ?

**Comment by nikitarevenco** [comment]
> Did you intend to close this @nikitarevenco ?

No, new to git hub and didn't know this will get closed if I delete my fork of the repo. Is it possible for this to be opened please?

**Comment by JoshDevHub** [comment]
It is possible for me to reopen it, but then the actions we have set to run on Pull Request won't work properly because they can't checkout your nonexistent branch. And that's a problem.

You'll have to make a new PR with this change in it.

Also if you're going to be a frequent contributor to TOP (and it seems like you've made a few contributions lately), I would advise not deleting your fork.

**Comment by nikitarevenco** [comment]
Thank you! Yes, I am currently going through the curriculum myself and opening issue / pr when I have a suggestion. I'll re-create this PR.

**Pull request closed without merging**
