### PR TITLE
Update deployment.md

### PR DESCRIPTION
**Pull request by CouchofTomato**
```
Updated the link to the Heroku deployment guide from Rails 4 to Rails 5

```

### CODE REVIEW

**Comment by KevinMulhern** [comment]
👍 looks good

**Comment by CouchofTomato** [comment]
Thanks, but what about the code changes?

**Comment by KevinMulhern** [comment]
code changes?

**Comment by CouchofTomato** [comment]
Heh, no. The joke was missed. Let's all move on.

**Pull request merged**
