### PR TITLE
Fixed some typos, grammar, punctuation, and a link

### PR DESCRIPTION
**Pull request by TheDarkula**
The Pomodoro Technique "great article" link isn't working, so I updated it with a similar one from the same site.

### CODE REVIEW

**Comment by OlehSliusar** [comment]
Are you sure coordinating conjunctions should be capitalized? (and, but, or, for, nor, etc.)

**Comment by TheDarkula** [comment]
Yeah, it's part of a title, not "sentence case"

**Comment by 105ron** [comment]
I think that would depend on what style guide you are using for headings. I don't know if we need to be that particular with the curriculum. We would like to encourage more people to contribute to lessons like in the Ruby and JavaScript overhaul we are trying to complete at the moment. Picking on whether a conjunction in a title should be capitalized probably makes us look elitist and discourages new users from contributing. We have many users whose primary language isn't English, we would like to create an environment that welcomes content from them to improve the overall course. Just my 2 cents worth, Rhys.

**Comment by OlehSliusar** [comment]
@105ron you're right

**Comment by TheDarkula** [comment]
Fantastic. Thanks!

**Pull request merged**
