### PR TITLE
Using `$ rails routes`

### PR DESCRIPTION
**Pull request by fredo-**
To see all the routes and controllers#actions they map to.

 - [x] You have read [The Odin Projects Contributing Guide](https://github.com/TheOdinProject/curriculum/blob/master/CONTRIBUTING.md).

#### 1.Describe the changes made:

Small addition of `$ rails routes` command to bring concepts full circle

#### 2. If this PR is related to an open issue please reference it with the `#` operator and the issue number below:

#XXXXX

### CODE REVIEW

**Comment by CouchofTomato** [comment]
Thanks @fredo- 

We already mention this command in the introduction. Are you thinking it should also be referenced later on to make things more clear?

**Comment by rlmoser99** [comment]
I was just looking at the PR too and noticed that `rails routes` is mentioned twice in this lesson already. Once in introduction and once under the heading "Rails Routes and Route Helpers". 

I am unsure that it needs to be mentioned a third time, but maybe it should be included in the "Learning Outcomes".

**Comment by CouchofTomato** [comment]
I wonder if anyone tries to type the $ because we explicitly list it there...

**Comment by rlmoser99** [comment]
@CouchofTomato The `$` is explicitly listed several times throughout the lessons. However, I wouldn't be surprised if that does trip people up occasionally.

**Comment by fredo-** [comment]
@CouchofTomato, that's what I'm thinking. Bringing it up again here would remind us of that command at the perfect time to bring things full circle. 

And I think the $ is fine, I mostly read it as the prompt flag, which is pretty standard other docs I've seen in the past

**Comment by rlmoser99** [comment]
@CouchofTomato I'm not sure this addition is in the right place. 

In looking at the entire lesson, I would like to see a question on it added it to the "Learning Outcomes" and add section 6.1 of the Rails Guides to Assignment #1.
https://guides.rubyonrails.org/routing.html#listing-existing-routes

Let me know what you think, especially about the additional reading.

**Comment by CouchofTomato** [comment]
@rlmoser99 We should definitely have that link in there because it nicely covers the other commands you can use with rails routes.

That and a learning outcome would definitely cover it I feel.

**Review by rlmoser99 — CHANGES_REQUESTED** [review]
@fredo- Would you like to make these changes, or would you like for me to close this PR?

- Add it to the "Learning Outcomes"
- Add section 6.1 of the Rails Guides to Assignment #1.
https://guides.rubyonrails.org/routing.html#listing-existing-routes

**Comment by fredo-** [comment]
I'm on it @rlmoser99

**Comment by fredo-** [comment]
Hey @rlmoser99, I added your comments, let me know if there are any other updates you need

**Review by rlmoser99 — APPROVED** [review]
Thank you for taking the time to update the learning outcomes and the assignment. I updated the wording to be more of a reminder, since the way it was phrased seemed like it was new information to this lesson (it is mentioned twice).

**Pull request merged**
