### PR TITLE
Added my solution for the Project Euler problems

### PR DESCRIPTION
**Pull request by just-n**
```
This is a PR template, If you are adding a solution link to the curriculum leave this as is. If you are not, then delete it and write the message you wish.
Thank you,
The Odin Project team.
```

### CODE REVIEW

**Comment by KevinMulhern** [comment]
Hey @just-n are you submitting through a fork?

**Comment by just-n** [comment]
Yes, I'm submitting through a fork

**Comment by KevinMulhern** [comment]
It seems to be out of date with the original curriculum repo, you need to update it locally by doing the following `git pull upstream master`

**Comment by just-n** [comment]
Ok, I got it fixed. I was getting a few errors, but it seems to be up to date now.

**Comment by KevinMulhern** [comment]
Awesome, thanks @just-n

**Pull request merged**
