### PR TITLE
Tweek collapsible student solutions

### PR DESCRIPTION
**Pull request by morrowdavidson**
The `<span>` seems to not convert the markdown as I expected. After reading the [kramdown docs](https://kramdown.gettalong.org/documentation.html) more closely perhaps a `<div>` will.  Probably a better element here anyway.

### CODE REVIEW

**Comment by KevinMulhern** [comment]
Have you tested this on your local copy of the site @morrowdavidson?

**Comment by KevinMulhern** [comment]
It seems all you need to do to get it to work, is add this to the details element: 
`<details markdown="block">`

We do something similar in the installing_ruby.md file.

Please try to do a few local tests before submitting for review. We always assume contributors do and releasing untested code is always a bad idea 😞

**Comment by morrowdavidson** [comment]
Yeah sorry. I was having difficulty getting my local top app to pull from my repo of the curriculum. I was able to do it and the `<div>` fixed the issue.

**Comment by KevinMulhern** [comment]
Ahhh `markdown="block"` wasn't working with that list due to the indentation of the summary element. It needs to be indented exactly one tab when its within the details element.

Kramdown is very temperamental with indentation 😄

**Comment by morrowdavidson** [comment]
@KevinMulhern Okay fixed the indentation. And used `markdown="block"` and removed the unneeded `<div>`. Sorry again for a pull request without fully testing.

**Comment by KevinMulhern** [comment]
@morrowdavidson Thanks for updating it 😄 Its no problem, its just a great habit to get into.

**Pull request merged**
