### PR TITLE
Update project_calculator.md

### PR DESCRIPTION
**Pull request by Jding9**
This is a PR template. If you are adding a solution link to the curriculum, leave this as is. If not, delete it and write the message you wish.

Thank you,

The Odin Project team.

### CODE REVIEW

**Comment by Jding9** [comment]
I've changed my calculator.html to index.html like you suggested and it works now! Thank you!

**Comment by marvingay** [comment]
@Jding9 the calculator still doesn't function on github pages.

**Comment by Jding9** [comment]
Marvingay, thank you for your comment, but I'm really confused, when I go to the link https://jding9.github.io/Calculator/ 
it works perfectly fine?

**Comment by marvingay** [comment]
@Jding9  Small bit of feedback, it's not immediately obvious what the operands are as they aren't displayed on screen. Only the result.

Merged your solution! Thanks for the submission.

**Pull request merged**
