### PR TITLE
Factory Functions and the Module Pattern: Reword step 4 in the Assignment section

### LINKED ISSUE #27484: Factory Functions and the Module Pattern: Reword a step in the Assignment section
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

A suggestion to reword Step 4 in the Assignment section to make it more clear that this step is optional if you have read the above articles.

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-javascript-factory-functions-and-the-module-pattern

### (Optional) Discord Name

T0nci

### (Optional) Additional Comments

_No response_

### PR DESCRIPTION
**Pull request by T0nci**
## Because

Reworded step 4 for more clarity and added a notice for the step.

## This PR

- Adds a starting bit to clarify that step 4 is an optional alternative.
- Adds a notice at the end that this series uses jQuery syntax but the learner doesn't need to understand that syntax and should focus on the module pattern concept.

## Issue

Closes #27484

## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [x] The `Because` section summarizes the reason for this PR
-   [x] The `This PR` section has a bullet point list describing the changes in this PR
-   [x] If this PR addresses an open issue, it is linked in the `Issue` section
-   [ ] If any lesson files are included in this PR, they have been previewed with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure it is formatted correctly
-   [ ] If any lesson files are included in this PR, they follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

### CODE REVIEW

**Comment by T0nci** [comment]
A bit confused, why does this PR have the commits from the previous PR(issue and branch)? I worked on a completely different branch.

**Comment by T0nci** [comment]
@MaoShizhong 
Googled the problem, and it turns out that this is common. Atleast I think that's my case. Some did magic and trickery(that means I have no clue what they did 😅) but some said that trick didn't work.

So I figured I will wait for your response and help.

**Comment by MaoShizhong** [comment]
@T0nci I have a feeling this is caused by you branching off your previous PR's branch, as opposed to checking out to main again (and then pulling from upstream main to sync your main branch) then branching off the updated main.

The simplest thing I think in this case, is to close this PR and start fresh, since it's only a small change to make.

Make a note of what the change needs to be (you can still find it here, it won't disappear even when the PR closes.

1. `git checkout main`
2. `git pull upstream main` (this will update your `main` branch with the latest TOP version - this will only work if you added the upstream repo as a remote as per the [contributing guide](the console overview video and read through the page)
3. You can delete your `reword_step_four` branch via `git branch -D reword_step_four`
4. Create and checkout to a new branch via `git checkout -b reword_step_four`
5. Now you can make your changes and commit -> push as normal.

The key difference is you're branching off an updated `main` branch, not branching off your previous feature branch, if that makes sense?

Give that a go. If you run into any issues doing this, feel free to DM me on Discord but hopefully the above steps should suffice.
I'll close this PR for now and let you get on with that when you get the chance, no rush :+1:

**Comment by fabulousgk** [comment]
I have done this several times I am sad to admit.

**Comment by T0nci** [comment]
@MaoShizhong A very insightful lesson. I get it! Branching off of my branch for Calculator also branched the commits to the new branch.

I was following the commands for a fresh `main` branch, but the mistake I made was not deleting the not needed branch in the first place.

I should definetly practice branching for features. I have forgotten to do that from the Rock Paper Scissors project 😔

**Comment by T0nci** [comment]
I feel you faboulousgk.

Good thing a senior dev is here to guide and learn from! Although definitely not a guarantee for not repeating it again 🤣

**Comment by MaoShizhong** [comment]
Not a senior by any means :P

**Pull request closed without merging**
