### PR TITLE
Add my solution to curriculum

### PR DESCRIPTION
**Pull request by IDCrisis2**

### CODE REVIEW

**Comment by craftykate** [comment]
Please change misspelling of "from" and I can add it. Thanks!

**Comment by craftykate** [comment]
@IDCrisis2 Please update your pull request so we can merge it or it will be closed soon. Thanks!

**Comment by IDCrisis2** [comment]
I did update the request; and, I believe it was merged already...

**Comment by craftykate** [comment]
Thanks, I didn't realize there was a new pull request for it. I'll close this pull request now.

**Pull request closed without merging**
