### PR TITLE
Added solution to HTML/CSS project

### PR DESCRIPTION
**Pull request by gelubogdan**
```
This is a PR template, If you are adding a solution link to the curriculum leave this as is. If you are not, then delete it and write the message you wish.
Thank you,
The Odin Project team.
```

### CODE REVIEW

**Comment by KevinMulhern** [comment]
Hey @gelubogdan could you add your solution to the bottom of the page please

**Comment by sambasten** [comment]
https://github.com/sambasten/google-homepage





/google-homepage

**Comment by gelubogdan** [comment]
Hey,

Sorry for that. It's fixed now :)

Bogdan

**Comment by KevinMulhern** [comment]
Thanks @gelubogdan 
@sambasten you need to open a pull request to add your solution.

**Pull request closed without merging**
