### PR TITLE
Project: Micro-Reddit: Add tip for using rails c instead of rails console

### PR DESCRIPTION
**Pull request by Overlandcoder**
## Because

Provides readers with a helpful tip that the command `rails c` may be used instead of `rails console`

## This PR

Added a short phrase in which the tip is explained

## Issue

Closes #XXXXX

## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [x] The `Because` section summarizes the reason for this PR
-   [x] The `This PR` section has a bullet point list describing the changes in this PR
-   [ ] If this PR addresses an open issue, it is linked in the `Issue` section
-   [x] If any lesson files are included in this PR, they have been previewed with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure it is formatted correctly
-   [x] If any lesson files are included in this PR, they follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

### CODE REVIEW

**Comment by CouchofTomato** [comment]
I wonder if it would be better to add a little knowledge section somewhere instead letting users know that most rails commands have shorter versions. Will also be a handy reference area for them to refer back to. What do you think?

**Comment by Overlandcoder** [comment]
> I wonder if it would be better to add a little knowledge section somewhere instead letting users know that most rails commands have shorter versions. Will also be a handy reference area for them to refer back to. What do you think?

Yes that's a good idea, I was initially thinking that too but wasn't sure where a section like that should be placed.

**Comment by CouchofTomato** [comment]
I'll discuss with the team and get back to you.

**Comment by ChargrilledChook** [comment]
@Overlandcoder we agree that fleshing it out more would be a good addition, but we're also happy to merge this as a quick improvement. Your call how to approach it - would you like to do it as part of this PR or come back to it with a different issue?

**Comment by Overlandcoder** [comment]
> @Overlandcoder we agree that fleshing it out more would be a good addition, but we're also happy to merge this as a quick improvement. Your call how to approach it - would you like to do it as part of this PR or come back to it with a different issue?

It's probably easier for me to make a new PR.

Also, I did some searching, but couldn't find any other short-cut commands other than "g", "s" and "c", at least not ones that are useful for that point in the course. I'm thinking we could add a little paragraph right above this section (https://www.theodinproject.com/lessons/ruby-on-rails-micro-reddit#your-task). Or would it be better somewhere else?

**Comment by ChargrilledChook** [comment]
@Overlandcoder There's a few different ways we could go with it - could you make an issue for it and we can discuss more there? If you reference this PR in the issue it will give it some more context too

**Pull request merged**
