### PR TITLE
Add missing paragraph at: Intermediate HTML and CSS > Forms > Forms Basics > Additional Resources

### PR DESCRIPTION
**Pull request by 91Flavio91**
Add missing paragraph under Additional Resources section

## Because

I added the usual paragraph under the "Additional Resources" section given that it is always present and was missing in this lesson.

## Issue

Closes #XXXXX

## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [x] The `Because` section summarizes the reason for this PR
-   [ ] The `This PR` section has a bullet point list describing the changes in this PR
-   [ ] If this PR addresses an open issue, it is linked in the `Issue` section
-   [ ] If any lesson files are included in this PR, they have been previewed with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure it is formatted correctly
-   [ ] If any lesson files are included in this PR, they follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

### CODE REVIEW

**Comment by codyloyd** [comment]
@91Flavio91 you have merge conflicts that need to be resolved.
CleanShot 2023-06-12 at 09 07 14

Probably this is because your local version of this file was slightly out of date, and git doesn't know how to properly resolve the differences between your version and the most recent version.

clicking that 'resolve' button should show you what's up so you can fix it.  Alternatively, it _might_ be easier if you reset your local branch, make it up to date with the latest version of the curriculum and then re-add this paragraph.

**Comment by 91Flavio91** [comment]
@codyloyd Hi! ok, I try to click on the button but it tells me that it could be to complex to resolve the issue (I drop a picture to let you understand what I mean). How can I reset my branch? Using the `git pull` commands?
Schermata 2023-06-12 alle 16 41 03

**Comment by codyloyd** [comment]
on your branch running `git reset --hard origin/main` will wipe out _all_ changes on your branch and make it identical to our current origin/main branch... then you can re-add your paragraph and push your branch up.  that should fix the merge conflict.

**Comment by 91Flavio91** [comment]
@codyloyd ok I've redone everything but I think I have to update my local repository with some pulling because when I try to `git push origin <mybranch>` I get the message that you see in the picture
Schermata 2023-06-12 alle 19 39 06

**Comment by codyloyd** [comment]
`git push -f` to force the push 😄

**Comment by 91Flavio91** [comment]
@codyloyd aaaa right XD

Anyhow, I've just done it and I've seen in real time that it was updating the status here on the page and the conflict reappeared. Do I try another time? Maybe someone in the meantime updated the remote?

**Comment by CouchofTomato** [comment]
@91Flavio91 

You need to checkout main

`git checkout main`

then `git pull`

then you can switch back to the branch you made for this PR

then you can do the hard reset as Cody suggested and make the changes and then push them up. git reset to origin/main still only resets is to the state of main on your local machine, that is why you need to pull down the latest changes to main before doing the reset.

Hope that helps.

**Comment by 91Flavio91** [comment]
@CouchofTomato Hi! Yeah I pulled from `main` but it says `Already up to date`. Then I switched to my branch, I opened the file and my modifications were there. I don't get it. I make you a video to show you what's happening.

https://github.com/TheOdinProject/curriculum/assets/107210617/ff3bde9e-b04a-4123-9b72-a1104b67e2b7

**Comment by CouchofTomato** [comment]
You need to do a hard reset as cody suggested. This should ensure your branch matches main. Then you should be able to make the changes and push them up.

I can't view those videos as they are an unsupported type.

**Comment by 91Flavio91** [comment]
@CouchofTomato  Ok, I did it again and this is what happens when I try to `git push -f`:

fatal: 'add_missing_paragraph' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.


This is what I did: I `git reset --hard origin/main` in my branch > switched to main and `git pull` and it said 'Already up to date' > switched to my branch again and added the paragraph again > add, commit,`git push -f <mybranch>` and those messages appeared!

**Comment by CouchofTomato** [comment]
> fatal: 'add_missing_paragraph' does not appear to be a git repository

This is a weird error. Can you share a screenshot of your terminal when you get that error?

**Comment by 91Flavio91** [comment]
@CouchofTomato Sure! There you go
Schermata 2023-06-14 alle 13 47 27

**Comment by 91Flavio91** [comment]
@CouchofTomato Wait wait, check this out. I realised that the command I was doing was incorrect. Now it worked with `git push -f origin <mybranch>`
Schermata 2023-06-14 alle 13 53 38

**Comment by CouchofTomato** [comment]
Something is wrong with your branch. You will probably need to nuke it and start over.

**Comment by 91Flavio91** [comment]
@CouchofTomato that's weird though. Did you see the last screenshot? Do I delete my branch and restart over?

**Comment by CouchofTomato** [comment]
> @CouchofTomato that's weird though. Did you see the last screenshot? Do I delete my branch and restart over?

I think the issue is that you're pulling down from your fork but the fork is now out of sync with our main branch. https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork might offer an easy solution through githubs web ui to update your fork, then you can pull down from main and follow the steps again and everything should be ok.

**Comment by 91Flavio91** [comment]
@CouchofTomato gotcha! Thank you! I try this and I'll let you know!

**Comment by 91Flavio91** [comment]
@CouchofTomato Done! 

I tell you what happened. I forked the curriculum repository days ago. When I started to work on this issue I cloned the curriculum repo that I forked days ago, I didn't fork it again nor I updated it. 

At this point it is clear my lack of understanding regarding the forking operation. 
I thought that when you fork a repo it stays in your remote github and you don't need to fork it again. Every new work that happens on the original repo, you will find it in your forked repo. Instead it doesn't look this way. It's like that when you fork a repo you are making a "screenshot' of that repo at that specific moment in time. Everything that happens in the original repo won't be updated to the repository that you forked. Am I right?

**Comment by CouchofTomato** [comment]
> @CouchofTomato Done!
> 
> I tell you what happened. I forked the curriculum repository days ago. When I started to work on this issue I cloned the curriculum repo that I forked days ago, I didn't fork it again nor I updated it.
> 
> At this point it is clear my lack of understanding regarding the forking operation. I thought that when you fork a repo it stays in your remote github and you don't need to fork it again. Every new work that happens on the original repo, you will find it in your forked repo. Instead it doesn't look this way. It's like that when you fork a repo you are making a "screenshot' of that repo at that specific moment in time. Everything that happens in the original repo won't be updated to the repository that you forked. Am I right?

Yeah it forks at that moment in time because changes may be made to the original that you don't want in your copy. Not all forks are to make changes to the original. Some fork and then change the original repo to do something in a different way. You can add the original as an upstream to git so you can pull down changes but I thought it was probably easier in this instance to use the github UI.

**Review by CouchofTomato — APPROVED** [review]

**Comment by 91Flavio91** [comment]
@CouchofTomato gotcha! Thank you, I appreciated your clarifications!

**Pull request merged**
