### PR TITLE
add video to additional resources

### PR DESCRIPTION
**Pull request by hoangtommy**
Found this video that summarizes controllers and routes pretty well. It's from App Academy's free curriculum. Not sure if we're against linking to their stuff haha?

### CODE REVIEW

**Comment by CouchofTomato** [comment]
Is there a reason you removed a resource? Was it outdated or do you feel the one you added was better?

**Comment by hoangtommy** [comment]
@CouchofTomato the resource was outdated and the video within the resource was no longer available. This commit was addressing this [issue](https://github.com/TheOdinProject/curriculum/issues/8878).

**Comment by hoangtommy** [comment]
Austin, I made a text edit to another lesson on the curriculum and committed it. I just read that all commits on my branch will fall into this PR so I apologize for not pushing the new and different commit from another branch. Learnings for next time =)

**Comment by hoangtommy** [comment]
@CouchofTomato curious what next steps I can take to take this off your plate and move it along?

**Comment by KevinMulhern** [comment]
Hi @hoangtommy, looks like this PR got a bit messed up with other commits. I don't think its mergeable in its current state. 

I think this happens when you make a change locally and your master branch isn't up to date with the upstream master branch and then pull in the upstream changes after making a new commit locally.

I know its a pain, but would you mind making a new PR with your changes? I don't believe you can fix this PR without a lot of yak shaving on your local machine unfortunately 😞 

To fix your local copy I'd do something like this:

Reset your master branch to a commit before you made your commits: `git reset --hard 4ee0dda4f81d275a65573eb69210cb64eb559b64` - this will fix your master branch

I'd advice using a branch workflow as that gets around issues like these. This is the typical workflow we use with GIT:

1. From your master branch pull in the latest changes: `git pull upstream master`

2. Now create a new branch `git checkout -b feature/my-branch`

3. Make your changes, add and commit them.

4. Push your branch to github, go to your fork and open a new PR.


Let me know if you need any help with anything.

Thanks,
Kevin

**Comment by I3uckwheat** [comment]
@KevinMulhern We're fixing it now :)

**Pull request closed without merging**
