### PR TITLE
Updated OOP: links, resources, and minor errors

### PR DESCRIPTION
**Pull request by JonathanYiv**
I looked around a little bit for a replacement for the refactoring.
What do you think of codewars?
Once you solve a problem, it shows a page where you can look at other's solutions sorted by best practices, which are often the most refactored version.

```
This is a PR template, If you are adding a solution link to the curriculum leave this as is. If you are not, then delete it and write the message you wish.
Thank you,
The Odin Project team.

```

### CODE REVIEW

**Comment by JonathanYiv** [comment]
@KevinMulhern

**Comment by JonathanYiv** [comment]
Or maybe [exercism.io](http://exercism.io/languages/ruby/about). I haven't it tried it yet but I will today and see if conceptually meets the needs.

**Comment by KevinMulhern** [comment]
Thanks for this @JonathanYiv, Codewars and exercism are great resources. But I feel like they are potentially rabbit holes. It would be great to recommend them as resources to go through after doing the ruby course as a way to continue practicing Ruby.

I wouldn't be too worried about getting refactoring in here at the moment, After the current redesign project is done I'll be free to work on something else Odin related. Overhauling the Ruby course is the project I want to do the most. I've got a lot of ideas for separating out and expanding the OOP section in particular. There will probably be a lesson dedicated to just refactoring in the new course.

**Comment by JonathanYiv** [comment]
Ok!

**Pull request merged**
