### PR TITLE
Update tic-tac-toe-project.md

### PR DESCRIPTION
**Pull request by kitague**
add my solution to Students solution

This is a PR template. If you are adding a solution link to the curriculum, leave this as is. If not, delete it and write the message you wish.

Thank you,

The Odin Project team.

### CODE REVIEW

**Comment by 105ron** [comment]
Hi @kitague,
could you please check the formatting of the markdown of your solution please. It needs to follow the other students formatting to display correctly on the site. You can usually get a markdown previewer for most Ides that will alert you to the fact these won't render as hyperlinks. Thanks, Rhys.

**Comment by kitague** [comment]
Hi  Rhys,

I made some changes and resubmitted my solution. 

Thank you
Ousmane

**Comment by 105ron** [comment]
Thanks. I've merged it and I'll close this one.

**Comment by kitague** [comment]
Thanks Rhys!

**Pull request closed without merging**
