### PR TITLE
Add my solution to HTML/ CSS exersize

### PR DESCRIPTION
**Pull request by banet**
This is a PR template. If you are adding a solution link to the curriculum, leave this as is. If not, delete it and write the message you wish.

Thank you,

The Odin Project team.

### CODE REVIEW

**Comment by Javier-Machin** [comment]
Hi @banet 

You forgot adding the links to your solution.

**Comment by banet** [comment]
Sorry for that. I m doing this for the first time.

Here is my link: 

https://github.com/banet/google-homepage

**Comment by Javier-Machin** [comment]
I added your solution, it will show up tomorrow.

Remember to follow the instructions [here](https://github.com/TheOdinProject/curriculum/blob/master/contributing.md) for your next pull requests :)

**Comment by banet** [comment]
Hi

How to add link again?

I tried to edit file again but have got message "You’re editing a file in a
project you don’t have write access to. Submitting a change to this file
will write it to a new branch in your fork banet/curriculum, so you can
send a pull request."

What should I do?

My link to solution is here:
https://github.com/banet/google-homepage

Regards
Bane

**Comment by banet** [comment]
Thank man! :)

**Pull request merged**
