### PR TITLE
Added solution

### PR DESCRIPTION
**Pull request by iBinbar**
I added my own solution to the list

### CODE REVIEW

**Comment by muzfuz** [comment]
Hey thanks.  Your jQuery solution doesn't have a link!

**Comment by iBinbar** [comment]
Yea I was having trouble generating one, it wouldn't pull my is file, but I
didn't think I submitted a pull request on that one

**Comment by muzfuz** [comment]
Ok no worries.  I'll merge, but I'm going to have to delete your addition manually as it's a dead link right now.

**Comment by muzfuz** [comment]
Done.  Please resubmit your jQuery link in a new pull request when you get a chance!

**Comment by iBinbar** [comment]
Yea OK thanks

**Pull request merged**
