### PR TITLE
Added missing Knowledge Checks and Knowledge Check links to NodeJS/Testing Database Operations

### PR DESCRIPTION
**Pull request by MrButak**
- [X] You have read [The Odin Projects Contributing Guide](https://github.com/TheOdinProject/curriculum/blob/main/CONTRIBUTING.md).
 - [X] The PR title summarizes the change and where it happened, for example: "Fixes punctuation in Clean Code lesson".
 
#### 1.Describe the changes made and include why they are necessary or important:

I added missing Knowledge Checks and Knowledge Check links to the NodeJS/Testing Database Operations.

#### 2. If this PR is related to an open issue please reference it with the `#` operator and the issue number (and any [relevant keywords](https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests)) below:

#22965

### CODE REVIEW

**Comment by MrButak** [comment]
I should have asked this first as this is my first time submitting a pull request.
Am I the one that closes this?

**Comment by twalton83** [comment]
No, you are not. It needs to be merged.

**Comment by MrButak** [comment]
I see, hopefully me closing it did not cause any issues. If it did let me know and I'll fix it.

**Review by fortypercenttitanium — APPROVED** [review]

**Comment by fortypercenttitanium** [comment]
Thanks for your contribution!

**Pull request merged**
