### PR TITLE
Node forms lesson

### LINKED ISSUE #27642: New Lesson: Forms and Data Handling
## Lesson overview

Strategy on using forms for create/update and data sanitisation and validation

## Lesson outline

The following items define the scope of the lesson. The lesson outline is flexible; you can improve, expand, and omit items whilst writing lesson content (make sure the pull request description mentions that).

- Discuss forms and how to handle create and update entity forms in Express
- How to deal with error messages
- Discuss data sanitisation & validation via [Express validator](https://express-validator.github.io/docs/) 
- Code examples for above

https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/forms is a good guide for this lesson

## Acceptance criteria

If the requirements here are not met, the work effort is not complete.

- [ ] Lesson conforms to the outline above (unless outline has been modified).
- [ ] Lesson follows our [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md).

### Get the lesson template

Download the lesson template using the following command (replace `lesson_name` with the actual lesson name):

```bash
curl -o <lesson_name>.md https://raw.githubusercontent.com/TheOdinProject/curriculum/main/templates/lesson-template.md 
```

### PR DESCRIPTION
**Pull request by LexiphanicStroon**
## Because

This is a new lesson planned with the node revamp project discord channel to replace the old node forms validation and sanitization lesson

## This PR

This PR rewrites the old express forms lesson with a brand new one, that contains an in house assignment and additional resources.

## Issue

Closes #27642

## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project curriculum contributing guide](https://github.com/TheOdinProject/curriculum/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [x] The `Because` section summarizes the reason for this PR
-   [x] The `This PR` section has a bullet point list describing the changes in this PR
-   [x] If this PR addresses an open issue, it is linked in the `Issue` section
-   [x] If any lesson files are included in this PR, they have been previewed with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure it is formatted correctly
-   [x] If any lesson files are included in this PR, they follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

### CODE REVIEW

**Review by LexiphanicStroon — COMMENTED** [review]
Fixing typos, adding link to express-validator docs

**Comment by wise-king-sullyman** [comment]
Hello and thank you for your contribution!

Please fill out the PR template so that we can better triage this. Was this new lesson something discussed with the team or is it being done as part of an existing issue or initiative?

**Comment by LexiphanicStroon** [comment]
> Hello and thank you for your contribution!
> 
> Please fill out the PR template so that we can better triage this. Was this new lesson something discussed with the team or is it being done as part of an existing issue or initiative?

Hello @wise-king-sullyman ! My apologies. Yes this was discussed with the node revamp team in the Discord, I was assigned this as a new lesson. I've updated the comment accordingly :)

**Review by 01zulfi — CHANGES_REQUESTED** [review]
@LexiphanicStroon great work, can't wait to see the lesson live 🔥 

Can you please address the following issues before I give a full review:

- We need to add a section on how learners should display error messages returned from validation
- We didn't cover the case where we update/delete an item. The backend requires a identifier to successfully update/delete. This can be done by creating a hidden input "id" field. You can refer to the linked MDN article
- We can remove `nodemon`. Simple `node` or `node --watch` commands should suffice for our use case.

**Comment by LexiphanicStroon** [comment]
> @LexiphanicStroon great work, can't wait to see the lesson live 🔥
> 
> Can you please address the following issues before I give a full review:
> 
> * We need to add a section on how learners should display error messages returned from validation
Currently the server is sending it in json and it is displayed in the browser. I thought it might be a good assignment for them to figure out how to use the locals object to display errors, unless you think that's too difficult at this point. The old forms lesson felt far too much like a tutorial for my taste, and quite unlike all the other lessons, but if you think it should just be part of the lesson I'll change it. 
> * We didn't cover the case where we update/delete an item. The backend requires a identifier to successfully update/delete. 
This can be done by creating a hidden input "id" field. You can refer to the linked MDN article
Question for the overall structure based on this, should the lesson also go through setting up a database? I heard in the node channel that we are dropping mongo, and using Prisma, and SQL, is that right? Should we go through installing Prisma and setting up a DB, or will they know that on their own already?
> * We can remove `nodemon`. Simple `node` or `node --watch` commands should suffice for our use case.
Good copy

**Comment by 01zulfi** [comment]
closing in favor of #28390

**Pull request closed without merging**
