### PR TITLE
remove broken link from add resources

### PR DESCRIPTION
**Pull request by binarygit**
- [x] You have read [The Odin Projects Contributing Guide](https://github.com/TheOdinProject/curriculum/blob/main/CONTRIBUTING.md).
 - [x] The title summarizes the change and where it happened, for example: "Fixes punctuation in Clean Code lesson".
 - [ ] If the PR is related to an open issue, use a [relevant keyword](https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests) and reference it with the `#` sign and the issue number.
 - [x] You have previewed your markdown (if any) in the [Odin Markdown Preview Tool](https://www.theodinproject.com/lessons/preview)
 - [ ] If changes are requested, please make the changes in a timely manner. After you submit the changes, request another review from the maintainer (top right).

#### 1. Describe the changes made and include why they are necessary or important:

...your text here

#### 2. Related Issue

Closes #XXXXX

### CODE REVIEW

**Comment by zachmmeyer** [comment]
The link works for me. Could you please verify that it is not working?

Also, could you please fill out the pull request template as requested in the future?

**Comment by binarygit** [comment]
hey! 
it is strange. It is not working when I click the link from TOP site itself (I tried it from my laptop and mobile) but works when I copy the url in the file I just edited and post it in the browser.

**Comment by binarygit** [comment]
The url changes to: http://rubylearning.com/satishtalim/object_serialization.html
when I click on the link in TOP

**Comment by zachmmeyer** [comment]
Oh wow. Wait a minute.

OK. The site has a dead link on it.
Your commit shows removing a Wayback version of the link and you removing it. Your commit also has conflicts. Something is funky here.

If you could resolve your conflict and replace the link with https://web.archive.org/web/20160505174806/http://rubymonk.com/learning/books/4-ruby-primer-ascent/chapters/45-more-classes/lessons/104-serializing that should fix everything and we can get this PR merged.

**Comment by binarygit** [comment]
The link you just gave me is for ruby monk's serializing lesson, which is listed just above the link I removed

**Comment by zachmmeyer** [comment]
@binarygit You are not wrong there, sorry this is getting confusing.
https://web.archive.org/web/20200627063721/http://rubylearning.com/satishtalim/object_serialization.html

**Comment by zachmmeyer** [comment]
Thank you!

**Comment by binarygit** [comment]
This was fun @zachmmeyer and I will conscientiously fill out the pull req template in the future :D

**Comment by zachmmeyer** [comment]
Until next time.

**Pull request merged**
