### PR TITLE
Fix form example typos

### PR DESCRIPTION
**Pull request by lopezaxel**
Fix indentation, change lost 'f' to 'form' at line 173 and because in line 173 there is a form.submit then in the example should be a input submit. Also change 'Javascript' to 'JavaScript'.

### CODE REVIEW

**Comment by marvingay** [comment]
@Drew-Goddyn  Specifically, with the `f.submit` on line 173. `f.submit` seems valid to me, is there a difference here where it needs to be changed?

Good to merge, if so.

**Comment by lopezaxel** [comment]
In line 171 is used the parameter |form| and in line 172 is used form.text_field, so in line 173 there must be used the |form|  parameter instead of the |f| parameter.

```
  171  <%= form_with model: @article do |form| %>
  172    <%= form.text_field :title %>
  173    <%= f.submit "Create" %>
  174  <% end %>
```

**Comment by leosoaivan** [comment]
LGTM

**Comment by marvingay** [comment]
@lopezaxel  Thank you for your contribution, as always!

**Pull request merged**
