### PR TITLE
Revisiting Rock Paper Scissors lesson: Add two resources to Additional Resources

### PR DESCRIPTION
**Pull request by lloydlobo**
Complete the following REQUIRED checkboxes:

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`

Complete the following checkboxes ONLY IF they are applicable to your PR. You can complete them later if they are not currently applicable:
-   [x] I have previewed all lesson files included in this PR with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure the Markdown content is formatted correctly
-   [ ] I have ensured all lesson files included in this PR follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

<hr>

**1. Because:**

- This **particular** lesson was **missing resources** in the "_Additional Resources_" section.

Closes: Not that I am aware of.

**2. This PR:**

- Adds links to **two references** that **align** with the Git workflow **related** content.

**3. Additional Information:**

### CODE REVIEW

**Review by wise-king-sullyman — CHANGES_REQUESTED** [review]
These resources seem great, that first one is especially neat!

One change I would like to see: I think that we should somehow state that the first resource references a lot of commands that we talk about later in the curriculum, and to only "worry" about the commands they're familiar with so far. At least until students reach our "A Deeper Look at Git" lesson.

**Comment by lloydlobo** [comment]
> These resources seem great, that first one is especially neat!
> 
> One change I would like to see: I think that we should somehow state that the first resource references a lot of commands that we talk about later in the curriculum, and to only "worry" about the commands they're familiar with so far. At least until students reach our "A Deeper Look at Git" lesson.

Thanks for the feedback. 🙏🏽  It makes a lot of sense as I wasn't even aware of the upcoming lessons. 🔖 

## Proposed Changes

<details>
<summary>Toggle Markdown</summary>
<pre>
<code>
* Open source is great for collaborating. So mastering Git's basics is the minimum requirement.  
  Actively learn Git workflows discussed in this lesson with this [interactive **Visual Git Cheatsheet**]  
  (https://ndpsoftware.com/git-cheatsheet.html#loc=index;) by Andrew Peterson.   
  Only a few essential tools are necessary. Yet, it’s beneficial to know the intricacies.   
  **It's okay to be unfamiliar** with the variety of commands you'll interact with.   
  We'll discuss them later in the curriculum, especially in the **"A Deeper Look at Git"Lesson**. 
</code>
</pre>
<pre>
<code>
* Make pushing your local commits to remote branches **easier** with the command `git push -u origin <branch>`.   
  It automatically links the local branch you push with the remote one.  
  [Read this educative.io article](https://www.educative.io/edpresso/what-is-the-git-push--u-remote-branch-name-command) by Talha Ashar and 
  commit faster to a remote branch with a simple `git push` command. 
</code>
</pre>
</details>

image

## Additional Information

* It seems that it's a bit verbose now. 😄 
* Awaiting your or anyone else's ⚡ ideas/suggestions regarding this.

<sub>**Have a good one!**<sub>

**Comment by wise-king-sullyman** [comment]
@lloydlobo that looks really good! I agree that it's a bit verbose now though. For the first addition, what do you think of dropping a couple sentences like so:

  Actively learn Git workflows discussed in this lesson with this [interactive **Visual Git Cheatsheet**](https://ndpsoftware.com/git-cheatsheet.html#loc=index;) by Andrew Peterson. **It's okay to be unfamiliar** with the variety of commands you'll interact with. You'll learn about the ones you're unfamiliar with later in the curriculum.

**Comment by lloydlobo** [comment]
@wise-king-sullyman Thanks! And yes, the shorter version is easy on the eyes and the mind.

**Review by wise-king-sullyman — APPROVED** [review]
Looks perfect! Thanks for contributing this!

**Comment by lloydlobo** [comment]
> Looks perfect! Thanks for contributing this!

I appreciate it! Thanks for helping out with the ⚡ edits and suggestions.

<sub>Have a good one. 👍🏽</sub>

**Pull request merged**
