### PR TITLE
Add my solution

### PR DESCRIPTION
**Pull request by lujanfernaud**
```
This is a PR template, If you are adding a solution link to the curriculum leave this as is. If you are not, then delete it and write the message you wish.
Thank you,
The Odin Project team.

```

### CODE REVIEW

**Comment by arun1595** [comment]
@lujanfernaud What's with "I0-I6 (Plus Extras)"?

**Comment by lujanfernaud** [comment]
Completed from I0 to I6 (that's how they named the different sections in [the tutorial](http://tutorials.jumpstartlab.com/projects/blogger.html)).

It's not important, it can be deleted.

**Comment by arun1595** [comment]
@lujanfernaud Oh. It wasn't obvious(atleast to me). Btw, good work :+1: 

I am fine with removing it. If you're fine too, please update the PR :)

**Comment by lujanfernaud** [comment]
Thanks @arun1595 :)

**Pull request merged**
