### PR TITLE
CSS foundations: Fix typo in Additional Resources

### PR DESCRIPTION
**Pull request by eoinmoore**
Complete the following REQUIRED checkboxes:

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`

Complete the following checkboxes ONLY IF they are applicable to your PR. You can complete them later if they are not currently applicable:
-   [x] I have previewed all lesson files included in this PR with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure the Markdown content is formatted correctly
-   [x] I have ensured all lesson files included in this PR follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

<hr>

**1. Because:**

Closes #XXXXX

**2. This PR:**

**3. Additional Information:**

### CODE REVIEW

**Comment by LeoKirasic** [comment]
@eoinmoore Looks/Sounds fine to me the way it is.

**Comment by eoinmoore** [comment]
@LeoKirasic Thanks for adding the tags, will do that myself next time.

"ways on how to" doesn't make sense grammatically. An alternative, cleaner phrasing might be:

> Changing the Font Family describes a few different approaches to using custom fonts.

or

> Changing the Font Family describes a few different methods for using custom fonts.

or

> Changing the Font Family describes how to use custom fonts in a few different ways.

**Comment by LeoKirasic** [comment]
@eoinmoore can you re word it to be the first sentence you gave as an example please?

**Review by LeoKirasic — APPROVED** [review]
Thank you.

**Pull request merged**
