### PR TITLE
JavaScript / "Project: Binary Search Trees": Ensure nodes in Step 1 are smaller than 100

### PR DESCRIPTION
**Pull request by JamesGJ5**
## Because

In Step 1 of the "Tie it all together" section of the assignment at theodinproject.com/lessons/javascript-binary-search-trees#assignment, tell the student to ensure the nodes created have values smaller than 100.

Do this so that Step 4 will definitely unbalance the binary tree as intended, Step 4 reading:

"Unbalance the tree by adding several numbers > 100"

## This PR

- Change Line 60 from "1. Create a binary search tree from an array of random numbers. You can create a function that returns an array of random numbers every time you call it, if you wish." to "1. Create a binary search tree from an array of random numbers < 100. You can create a function that returns an array of random numbers every time you call it, if you wish."

## Pull Request Requirements
-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [x] The `Because` section summarizes the reason for this PR
-   [x] The `This PR` section has a bullet point list describing the changes in this PR
-   [ ] If this PR addresses an open issue, it is linked in the `Issue` section
-   [x] If any lesson files are included in this PR, they have been previewed with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure it is formatted correctly
-   [x] If any lesson files are included in this PR, they follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

### CODE REVIEW

**Comment by linkonsat** [comment]
I don't quite understand the benefit of this change. From my understanding of doing the binary search tree myself I was able to unbalance it with numbers above 100. So I don't quite get what having it specifically be less than one hundred would change. That said if this case I do think this is a great little easer egg folks could find by playing around with the numbers they are generating. 

That all said, I am curious why it's the case that having numbers above 100 wouldn't unbalance it.

**Comment by JamesGJ5** [comment]
Thanks for your comment, @linkonsat 

I'll double-check by reasoning soon and send a more detailed explanation if I continue to believe this is an issue 👍

**Comment by JamesGJ5** [comment]
Hey @linkonsat, hope you're well! Here's a more detailed explanation of why I think this is an issue. Hopefully the formatting comes across correctly...

ISSUE:

An example of an array that can be randomly generated if the student follows Step 1 under "Tie it all together": [125, 743, 289, 548, 295, 739, 419].

Here is the balanced binary search tree that results from the random array above:

│       ┌── 743
│   ┌── 739
│   │   └── 548
└── 419
    │   ┌── 295
    └── 289
        └── 125
It is true that the tree is balanced.

The following array contains numbers to be added that are an example of the student following Step 4 under "Tie it all together" correctly--this array consists only of "several numbers > 100": [744, 742, 549, 547, 296, 294, 126, 124].

However, while the step itself says this should unbalance the tree, this example results in the tree still being balanced after the additions:

│           ┌── 744
│       ┌── 743
│       │   └── 742
│   ┌── 739
│   │   │   ┌── 549
│   │   └── 548
│   │       └── 547
└── 419
    │       ┌── 296
    │   ┌── 295
    │   │   └── 294
    └── 289
        │   ┌── 126
        └── 125
            └── 124
It is true that the tree is balanced.

SOLUTION:

Step 1 should tell the student to ensure that the random numbers generated are less than 100. Example: [2, 5, 67, 32, 99, 76, 44].

Here is the balanced binary search tree that results from the random array above:

│       ┌── 99
│   ┌── 76
│   │   └── 67
└── 44
    │   ┌── 32
    └── 5
        └── 2
It is true that the tree is balanced.

Now, if the student adds "several numbers > 100" as Step 4 instructs, the result is that the tree is GUARANTEED to be unbalanced, since additions will only ever stem from the same node of the initial, balanced tree.

For example, if the student adds numbers from the array [101, 123, 678, 397], the following unbalanced tree is created:

│                   ┌── 678
│                   │   └── 397
│               ┌── 123
│           ┌── 101
│       ┌── 99
│   ┌── 76
│   │   └── 67
└── 44
    │   ┌── 32
    └── 5
        └── 2
It is false that the tree is balanced.


CONCLUSION:

While the steps as they are in the lesson will probably result in the correct thing most of the time, following them won't result in the correct thing 100% of the time; this solution aims to ensure 100% correctness of the steps with little added complexity. This also teaches the student what it takes to make sure a binary search tree is unbalanced, so that they can better understand binary search trees.

If this isn't followed, I have a question: any idea why a minimum of 100 mentioned in Step 4 in the first place, as opposed to any other number? Please let me know if I have missed anything 👍

**Comment by JamesGJ5** [comment]
Hey @linkonsat, hope you're well! Here's a more detailed explanation of why I think this is an issue. Hopefully the formatting comes across correctly, I had to put the full stops in to prevent the printed trees from collapsing here...

ISSUE:

An example of an array that can be randomly generated if the student follows Step 1 under "Tie it all together": [125, 743, 289, 548, 295, 739, 419].

Here is the balanced binary search tree that results from the random array above:

│.......┌── 743
│....┌── 739
│....│...└── 548
└── 419
....│...┌── 295
....└── 289
........└── 125
It is true that the tree is balanced.

The following array contains numbers to be added that are an example of the student following Step 4 under "Tie it all together" correctly--this array consists only of "several numbers > 100": [744, 742, 549, 547, 296, 294, 126, 124].

However, while the step itself says this should unbalance the tree, this example results in the tree still being balanced after the additions:

│...........┌── 744
│.......┌── 743
│.......│...└── 742
│...┌── 739
│...│...│...┌── 549
│...│...└── 548
│...│.......└── 547
└── 419
 ...│.......┌── 296
 ...│...┌── 295
 ...│...│...└── 294
 ...└── 289
 .......│...┌── 126
 .......└── 125
 ...........└── 124
It is true that the tree is balanced.

SOLUTION:

Step 1 should tell the student to ensure that the random numbers generated are less than 100. Example: [2, 5, 67, 32, 99, 76, 44].

Here is the balanced binary search tree that results from the random array above:

│.......┌── 99
│...┌── 76
│...│...└── 67
└── 44
 ...│...┌── 32
 ...└── 5
 .......└── 2
It is true that the tree is balanced.

Now, if the student adds "several numbers > 100" as Step 4 instructs, the result is that the tree is GUARANTEED to be unbalanced, since additions will only ever stem from the same node of the initial, balanced tree.

For example, if the student adds numbers from the array [101, 123, 678, 397], the following unbalanced tree is created:

│...................┌── 678
│...................│...└── 397
│...............┌── 123
│...........┌── 101
│.......┌── 99
│...┌── 76
│...│...└── 67
└── 44
 ...│...┌── 32
 ...└── 5
 .......└── 2
It is false that the tree is balanced.


CONCLUSION:

While the steps as they are in the lesson will probably result in the correct thing most of the time, following them won't result in the correct thing 100% of the time; this solution aims to ensure 100% correctness of the steps with little added complexity. This also teaches the student what it takes to make sure a binary search tree is unbalanced, so that they can better understand binary search trees.

If this isn't followed, I have a question: any idea why a minimum of 100 mentioned in Step 4 in the first place, as opposed to any other number? Please let me know if I have missed anything 👍

**Comment by linkonsat** [comment]
That makes sense. I'll go ahead and merge the changes. I was just a bit curious as to the reasoning based on when I did it. Appreciate you doing this.

**Pull request merged**
