### PR TITLE
My Jquery Solution

### PR DESCRIPTION
**Pull request by NikhilSurana**

### CODE REVIEW

**Comment by muzfuz** [comment]
Hey, do you need some help figuring out what to do?

**Comment by NikhilSurana** [comment]
Please help me to add solution in odin project

**Comment by muzfuz** [comment]
Hey Nikhil, it's up to the admins to add the solution.  Once you have submitted it, we review the submission, and then we either merge it or send back comments for changes.  I'll check it now and let you know in a second.

**Comment by NikhilSurana** [comment]
Hey When I run my code using htmlpreview it doesn't run my code properly but when i try to run my code on my PC it work perfectly. Can you help on that?

**Comment by muzfuz** [comment]
Are you trying to generate the HTML preview from your HTML page?  It should be done using this link.

https://github.com/NikhilSurana/Etch-A-Sketch/blob/master/Etch-A-Sketch.html

**Comment by NikhilSurana** [comment]
Yupe using this link

**Comment by muzfuz** [comment]
Hm... I'm not sure what's causing it then.  Perhaps best if you do a few searches on google - I know HTML Preview can cause issues.

**Comment by NikhilSurana** [comment]
ok thanks for your help

**Comment by NikhilSurana** [comment]
ok thanks for your help

**Comment by NikhilSurana** [comment]
ok thanks for your help

**Comment by NikhilSurana** [comment]
Ok thanks for your help

**Pull request closed without merging**
