### PR TITLE
Update conclusion.md

### PR DESCRIPTION
**Pull request by NerdsAreIn**
Made some grammar changes and also fleshed out some of the acronyms. This gives the reader a little more to go off. As a beginner and a learner, I don't like encountering specialist jargon or acronyms with zero context or explanation. I think that a course for beginners (or any course, really) should assume that the learner is not versed in computerese.

 - [x] You have read [The Odin Projects Contributing Guide](https://github.com/TheOdinProject/curriculum/blob/main/CONTRIBUTING.md).

#### 1.Describe the changes made:

...your text here

#### 2. If this PR is related to an open issue please reference it with the `#` operator and the issue number below:

#XXXXX

### CODE REVIEW

**Comment by twalton83** [comment]
Thanks for the changes, just a heads up that the PR templates should be filled out correctly. Thanks!

**Comment by NerdsAreIn** [comment]
Is "PR" proofreading?

**Comment by twalton83** [comment]
Screen Shot 2021-06-15 at 8 59 48 AM
"Pull Request"

**Comment by CatQueenCodes** [comment]
> Is "PR" proofreading?

Pull Request template

**Pull request merged**
