### PR TITLE
Edited project (finished now)

### PR DESCRIPTION
**Pull request by J-kaizen**
```
This is a PR template, If you are adding a solution link to the curriculum leave this as is. If you are not, then delete it and write the message you wish.
Thank you,
The Odin Project team.
```

### CODE REVIEW

**Comment by KevinMulhern** [comment]
Hey @J-kaizen, you seem to have just added a blank line?

**Comment by J-kaizen** [comment]
Not quite sure what's going on there. I linked my student solution to github but don't see it appearing on ToP.

**Comment by KevinMulhern** [comment]
ah ok, It usually takes a day for it to appear. If it isn't there by the end of today let me know on slack and I'll run the update manually 😄

**Comment by J-kaizen** [comment]
Thanks!

**Pull request closed without merging**
