### PR TITLE
binary search tree

### PR DESCRIPTION
**Pull request by hiendinhngoc**

### CODE REVIEW

**Comment by KevinMulhern** [comment]
Hi @hiendinhngoc, it seems that are trying to update a older version of the curriculum. There are newer submission that will have been removed in your pull request.

**Comment by hiendinhngoc** [comment]
Did you mean I have to update the repository before pull request?

**Comment by KevinMulhern** [comment]
If you look at your commit, there are only a few submissions before yours. Whereas on the actual page for that project there are many more submissions. I take it you have a version of the curriculum cloned on your computer? You need to do a 'git pull' every time you add a new link to your version. That will update it with all the latest submissions.

**Comment by KevinMulhern** [comment]
Closing due to being open for 14 days without being resolved.

**Pull request closed without merging**
