### PR TITLE
Computer Science: Recursion Project: Adjust headings, ordering and linked resources

### LINKED ISSUE #27238: Computer Science: Recursion Project: Use proper heading structure
### Problem

The recursion project content in both the JavaScript and Ruby paths should change to conform to the [project layout](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md#project-layout) specified in the LAYOUT_STYLE_GUIDE.

This will involve a bit of a refactor on the organization of the content, as currently there are two separate assignments on the page and no introduction.

### Lesson(s)
- https://www.theodinproject.com/lessons/ruby-recursion
- https://www.theodinproject.com/lessons/javascript-recursion

### Acceptance Criteria
- [ ] Add an introduction section to the project
- [ ] Move the Fibonacci exercise and the merge sort exercise into one assignment block
- [ ] Make sure you change the project content in both the Ruby and the JavaScript course material

### LINKED ISSUE #27392: Recursion: Merge sort solution in linked Wikipedia
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Problem
There is a version of merge sort in pseudocode on the linked Wikipedia page that makes solving the assignment trivial.

### Context
There was recently a closed issue #27224 about the C-like version of merge sort on the linked Wikipedia page. But this issue and the change appears to be unaware there is also a [highly verbose pseudocode example](https://en.wikipedia.org/wiki/Merge_sort#Top-down_implementation_using_lists) of merge sort  further down the page which can be almost directly translate to JS.

In my own case reading through the wikipedia article and this pseudocode made writing a JS version trivial. I did not have to wrestle with the problem and figure out how to tackle it.

I am not sure if that matches the learning intent of the assignment, or perhaps this was added to the wikipedia page subsequent to this course module, or perhaps it is not the goal to have learners dig in to solve this assignment.

### Action
There are two courses of action **_if_** this is worth addressing:
1. Remove the link to wikipedia if the pseudocode version is judged to undermine the learning goal; or
2. Refer learners to ignore the C versions in favour of the pseudocode if it is considered supporting the learning goal.

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/javascript-recursion

### (Optional) Discord Name

latch909

### (Optional) Additional Comments

_No response_

### PR DESCRIPTION
**Pull request by thomasmcinnis**
## Because

- The content was divided between two seperate assignments, did not have an introduction, and did not follow the style guide.

## This PR

- Add an introduction
- Merge the assignments
- Removes link to wikipedia article which contained full merge sort solution
- Seperate the informational content from the assignment content
- Reorganise linked resources between sections and additional resources section

## Issue

Closes #27238 
Closes #27392

## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [x] The `Because` section summarizes the reason for this PR
-   [x] The `This PR` section has a bullet point list describing the changes in this PR
-   [x] If this PR addresses an open issue, it is linked in the `Issue` section
-   [x] If any lesson files are included in this PR, they have been previewed with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure it is formatted correctly
-   [x] If any lesson files are included in this PR, they follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

### CODE REVIEW

**Comment by linkonsat** [comment]
@thomasmcinnis It looks good. It just looks like you have a merge conflict to resolve and then I would be more than happy to approve it.

**Comment by thomasmcinnis** [comment]
@linkonsat Thanks - sorry I missed that. Updated now.

**Review by JoshDevHub — CHANGES_REQUESTED** [review]
Just going to request fixing these lint/format errors and we should be good to merge. The Ruby file also has some errors, but due to a bug in our configuration (which is known about and people are working to fix it), they're not being picked up by the CI tool. This makes it annoying for me to highlight them for changing. You can look into these locally if you want using techniques outlined in our [contributing guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md#curriculum-linting), but you definitely don't have to if it's too much trouble.

Great work by the way :rocket:

**Comment by thomasmcinnis** [comment]
@JoshDevHub Thanks - I missed that linting cli tool from contributing guide my bad. Went through and fixed for both JS and Ruby now

**Review by JoshDevHub — APPROVED** [review]
Awesome work. Thank you for contributing :partying_face:

**Pull request merged**
