### PR TITLE
contribute google-webpage new solution

### PR DESCRIPTION
**Pull request by reploid3660**
```
This is a PR template, If you are adding a solution link to the curriculum leave this as is. If you are not, then delete it and write the message you wish.
Thank you,
The Odin Project team.
```

### CODE REVIEW

**Comment by j-campbell** [comment]
screen shot 2016-05-30 at 6 19 43 pm
small issue on the buttons on my laptop (screenshot attached)

**Comment by reploid3660** [comment]
Oh! Thanks a lot! I guess it's the proportion of the screen that causes the problem.. I will figure it out.

**Comment by j-campbell** [comment]
I should prob check mine against different screen sizes too now you mention it :) it was on safari if that helps :)

**Comment by KevinMulhern** [comment]
@j-campbell responsive design is a bit advanced for this particular part of the course. Learning how to make sites responsive to different screen sizes is taught much later on. It's perfectly okay for the google home page replica to not look great in smaller screens as it's not expected of the student to be able to do that at this point 😄

**Comment by j-campbell** [comment]
Sorry! I was making a pull request and it came up in my feed!

**Comment by KevinMulhern** [comment]
It's no problem, I just don't want you guys getting overwhelmed with adding responsive design if it's potentially your first html and css project. 👍

**Comment by reploid3660** [comment]
I see! Through your words, I have a clearer understanding of what skills should  I have at every stages.Really thanks for every comments and guides from both of you!

**Pull request merged**
