### PR TITLE
Advanced HTML and CSS Transforms lesson: Provide better explanation for transform order.

### LINKED ISSUE #28415: Advanced HTML and CSS course: Add another source that discusses how transforms are applied
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

Currently when discussing the chaining of transform operations the curriculum links to this link on [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/transform#values). It states "“The transform functions are multiplied in order from left to right, meaning that composite transforms are effectively applied in order from right to left.”

I struggled quite a bit with this concept since to me it was more intuitive to read them left to right and MDN doesn't really explain the difference too well.

I asked in the Discord yesterday for some clarification, and somebody provided [this](https://codepen.io/bali_balo/post/chaining-transforms) an an additional source which cleared things up for me a lot.

I think it might be beneficial to add it as an additional resource if others are struggling with something similar.

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-advanced-html-and-css-transforms

### (Optional) Discord Name

_No response_

### (Optional) Additional Comments

_No response_

### PR DESCRIPTION
**Pull request by Victor-M-Giraldo**
## Because
The wording regarding how CSS transforms are applied is a bit confusing.

## This PR
- Clarifies the order of how transforms can be interpreted. 

## Issue
Closes  #28415.

## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project curriculum contributing guide](https://github.com/TheOdinProject/curriculum/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [x] The `Because` section summarizes the reason for this PR
-   [x] The `This PR` section has a bullet point list describing the changes in this PR
-   [x] If this PR addresses an open issue, it is linked in the `Issue` section
-   [x] If any lesson files are included in this PR, they have been previewed with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure it is formatted correctly
-   [x] If any lesson files are included in this PR, they follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

### CODE REVIEW

**Review by MaoShizhong — CHANGES_REQUESTED** [review]
Not sure how some links suddenly have their hrefs wrapped with `< >`, perhaps an auto-formatter without you realising? I'd check this in your IDE to make sure that auto-formatters don't interfere with projects that follow different style rules.

If you could remove the `< >` from these various links, that'd be great :+1:

**Comment by Victor-M-Giraldo** [comment]
> Not sure how some links suddenly have their hrefs wrapped with `< >`, perhaps an auto-formatter without you realising? I'd check this in your IDE to make sure that auto-formatters don't interfere with projects that follow different style rules.
> 
> If you could remove the `< >` from these various links, that'd be great 👍

Sorry about that. It was Prettier. Should be good now I think.

**Review by MaoShizhong — APPROVED** [review]
:rocket:

"Save without formatting" (or binding formatting to its own keybind and not having it run on save) will be very useful, it that's what got in the way here.

**Comment by Victor-M-Giraldo** [comment]
> 🚀
> 
> "Save without formatting" (or binding formatting to its own keybind and not having it run on save) will be very useful, it that's what got in the way here.

Will do, thanks!

**Pull request merged**
