### PR TITLE
added links for my google home page project

### PR DESCRIPTION
**Pull request by nynd**

### CODE REVIEW

**Comment by craftykate** [comment]
@nynd There are too many files changed (5 total) for me to be able to merge your solution. I'm not sure what happened, but I can only merge your solution if just the curriculum readme has been changed. Here's a short video showing a very easy way to add your links to odin: http://bit.ly/odin-solutions. I'm going to close this pull request, but open a new one using the method in that video and I'll add your solution then. Let me know if you need help!

**Comment by nynd** [comment]
i'm new to git and github. i cloned the curriculum folder after i forked so
it sent me down a really long path where i got lost and did a bad pull and
push.
sorry about about that.
your tutorial is great though. thanks!
do you do code reviews and corrections ?

On Mon, Mar 30, 2015 at 11:51 AM, Kate McFaul <notifications@github.com>
wrote:

> Closed #1336 <https://github.com/TheOdinProject/curriculum/pull/1336>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/TheOdinProject/curriculum/pull/1336#event-268631669>.
>



-- 
ny.nd

**Comment by craftykate** [comment]
I totally understand - git/github can seem very weird at first. Everyone submitting links to odin is learning so there are certainly no judgements from me if there are errors! I don't usually review people's code, though. Do you have a specific question?

**Comment by nynd** [comment]
Not really.
But i might some day.
Is that ok?

**Comment by craftykate** [comment]
I can't guarantee I'll have all the answers, but I'd be happy to take a look and see if I can help. =)

**Comment by nynd** [comment]
Thank you.

**Pull request closed without merging**
