### PR TITLE
Updating URL for student submissions

### PR DESCRIPTION
**Pull request by Saul-Good-Homie**
For knights Travails - The student solution section was missing the URL and it references a partner. 

Updating paragraph to be consistent with the first section.

-Saul

### CODE REVIEW

**Comment by 105ron** [comment]
You took away your solution? 👀

**Comment by Saul-Good-Homie** [comment]
🙋‍♂️ Hi my name is Saul and I'm an idiot...

haha dangit! Obviously an accident. Can I fix it from here or do I have to wait for you to approve this pull and then resubmit?

**Comment by marvingay** [comment]
@Saul-Good-Homie  You can make another commit and it will automatically be involved with this pull request.

**Comment by marvingay** [comment]
Appropriate changes were made.

**Pull request merged**
