### PR TITLE
Add my solution to HTML/CSS exercise

### PR DESCRIPTION
**Pull request by ArthurTolen**
This is a PR template. If you are adding a solution link to the curriculum, leave this as is. If not, delete it and write the message you wish.

Thank you,

The Odin Project team.

### CODE REVIEW

**Comment by ZachBaird** [comment]
Hey @ArthurTolen , it looks like your pull request is removing some student submissions. Could you try updating your repository to the version ours is on and then push back up to yours so this pull request is updated?

When all is said and done, the only change in `Files changed` should be your added line :)

**Comment by ArthurTolen** [comment]
Hi Zach, I'm trying to fix the issue but I'm a little lost. How exactly can I update my repository to this version? I'm fairly new and any help will be greatly appreciated.

**Comment by ZachBaird** [comment]
@ArthurTolen No worries, this can seem confusing when contributing code to a project that a lot of hands touch.

Give the Video under the Hard way a watch here: https://github.com/TheOdinProject/curriculum/blob/master/contributing.md

But the TL;DR of it is that you have 3 repo's with 3 separate versions you need to keep in mind:

- Our Curriculum repo here
- Your forked Curriculum repo
- Your local Curriculum repo you edit on your machine. This should be cloned from your **forked** repo.

Generally, when it comes to big projects and version control with Git, you want to identify a repo or a branch (in this case it's a repo) that is considered "the source of truth". It's the one you want to be in-version with as much as possible so that you won't be working on backwards stuff or get merge conflicts.

In this case, the source of truth is our repo here.

What you want to do is check what `remote` repositories you have associated with your local one first. To do this, you would go to your local Curriculum repo and run `git remote -v` and see what it says. `origin` should point to your forked repo; you should be able to tell by the URI. I'm assuming origin will be the only remote that shows up. If that's the case, then what you want to do is add **this** repo, our **source of truth** as another remote repo for your local one. You can do this with `git remote add realOrigin git@github.com:TheOdinProject/curriculum.git` (assuming you're using SSH. I got this URL from the `clone` button on Github).

Once that's done the rest is simple. You want to use `git pull realOrigin master` to pull in the master branch of our source of truth, which will bring **your local repo** up to date with ours. You can then `git push origin master` to your forked repo, which will send those updates to your forked copy and bring it up to date as well. Once you do that, this pull request should update automatically.

You **might** get merge conflicts. If that's the case, watch a quick video on Youtube or something on resolving merge conflicts. It's daunting at first but really straightforward once it clicks. Let me know if you need anymore guidance!

**Comment by ArthurTolen** [comment]
Thank you so much for this Zach! It was greatly helpful

**Pull request closed without merging**
