### PR TITLE
My solution!

### PR DESCRIPTION
**Pull request by mdowell12**

### CODE REVIEW

**Comment by craftykate** [comment]
Please change the misspelling of "browser" and I can add. Thanks!

**Comment by craftykate** [comment]
@mdowell12 I was going to make the changes by hand but it turns out your "view in browser" link is just a link to the html code. Please change the typo and change the view link. Let me know if you need help.

**Comment by mdowell12** [comment]
Hi Kate,

Thanks for following up on this.  To be honest, I didn't fix it the first
time around because I couldn't figure out how to make an edit.  Could you
give me a little guidance?

Thanks,

Matt

**Comment by craftykate** [comment]
@mdowell12 Open the "files changed" section above, then click the little pencil icon to edit. If that doesn't work you can just close this request and open a new one.

**Comment by mdowell12** [comment]
Hey Kate,

I previewed the existing HTML file in my browser and my solution doesn't
seem to be working as it did before.  I'll have to make some changes before
putting it on The Odin project website.  I'll go ahead and close this
request until then.

Thanks for your help,

Matt

**Comment by craftykate** [comment]
@mdowell12 Here's a video showing exactly how to add a solution to the odin project in case it can help out in the future: http://bit.ly/odin-solutions

Good luck with your code, let me know if I can help with anything.

**Pull request closed without merging**
