### PR TITLE
Improve punctuation, and readability of the 'keys in react' lesson

### PR DESCRIPTION
**Pull request by cakegod**
## Because
Lessons has some punctuation, and readability issues.

## This PR

- Improves punctuation and readability

## Issue

Closes #XXXXX

## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [x] The `Because` section summarizes the reason for this PR
-   [x] The `This PR` section has a bullet point list describing the changes in this PR
-   [x] If this PR addresses an open issue, it is linked in the `Issue` section
-   [x] If any lesson files are included in this PR, they have been previewed with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure it is formatted correctly
-   [x] If any lesson files are included in this PR, they follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

### CODE REVIEW

**Review by ManonLef — COMMENTED** [review]
Thank you! I left a bit of feedback but would also like to state that this lesson is already being worked on here in an older PR: https://github.com/TheOdinProject/curriculum/pull/25826 which is near ready to merge. It might be good to wait for their final adjustment to see what's left to edit.

**Comment by cakegod** [comment]
> Thank you! I left a bit of feedback but would also like to state that this lesson is already being worked on here in an older PR: https://github.com/TheOdinProject/curriculum/pull/25826 which is near ready to merge. It might be good to wait for their final adjustment to see what's left to edit. 

It seems I missed the already-opened PR. I'll wait for its merge before making any further changes

**Comment by ManonLef** [comment]
That PR is merged now

**Comment by ManonLef** [comment]
@cakegod once you're ready for a re-review, please request it :) Looks like there are some conflicts that need resolving.

**Review by ManonLef — CHANGES_REQUESTED** [review]
merge conflicts need resolving first before I can review the changes

**Comment by cakegod** [comment]
> merge conflicts need resolving first before I can review the changes

I have new changes, but they are... abundant. I will fix the merge and commit the existing changes before opening an issue or new PR.

**Comment by cakegod** [comment]
I'll make a new PR.

**Pull request closed without merging**
