### PR TITLE
Added my Rock-paper-scissors solution.

### PR DESCRIPTION
**Pull request by RoyNyaga**
This is a PR template. If you are adding a solution link to the curriculum, leave this as is. If not, delete it and write the message you wish.

Thank you,

The Odin Project team.

### CODE REVIEW

**Comment by ryanford-frontend** [comment]
Did you make the github pages you're linking to? I'm getting 404s for both of them

**Comment by RoyNyaga** [comment]
Am just realizing it, i don't know what is happening because i followed the
same steps used in the google home page project

**Comment by RoyNyaga** [comment]
ooopppppps sorry i made a mistake in entering the link to where the project
is published. Since am submitting the updated version of the project with a
user interface i will just fix the mess. thanks

**Comment by RoyNyaga** [comment]
if you got time you could check again, i fixed it.

**Comment by 105ron** [comment]
It's fixed. Looks great. :+1: Should be on the website now.

**Pull request merged**
