### PR TITLE
Add student solution

### PR DESCRIPTION
**Pull request by NicolayD**
Add my solutions to the two tasks.

```
This is a PR template, If you are adding a solution link to the curriculum leave this as is. If you are not, then delete it and write the message you wish.
Thank you,
The Odin Project team.

```

### CODE REVIEW

**Comment by 105ron** [comment]
Hi @NicolayD ,
for future student submissions you need to `git pull origin master` to update your curriculum. As you branched this a week or so ago any new student submissions don't get included into you branched repository. As time goes on there will be more student solutions making the conflicts longer and harder to solve. If you can update your repository before including your solution it can be merged immediately. Thanks, Rhys.

**Comment by NicolayD** [comment]
I understand. I'm sorry about that, I still don't have that much experience with forked repositories. I cloned the curriculum and will regularly pull from master, I hope that will resolve this issue.

**Comment by 105ron** [comment]
Alright, that was bad information. You need to add `git remote add upstream https://github.com/theodinproject/curriculum.git` as a remote then `git pull upstream master` . That will fix the issue. :smile: Sorry for the confusion..

**Comment by NicolayD** [comment]
Did that. Worked beautifully. Sorry for your trouble again, I'll relearn the git details about forking and so on. Might even try to get a friend of mine and just experiment on github. I also saw the problem with my last comment and know why it doesn't make sense. :D

**Comment by 105ron** [comment]
No worries. We are currently working on lessons and student projects for more exposure to these processes in git and github. You can't be expected to know everything and they way you are submitting your projects is a good way to learn more about git. Most just submit them by the browser which is easier but when you want to contribute to larger OS projects it needs to be done through the command line. Thanks, Rhys.

**Pull request merged**
