### PR TITLE
My solution (Rock-Paper-Scissors, complex way) + Etch-a-Sketch

### PR DESCRIPTION
**Pull request by mortvicious**
This is a PR template. If you are adding a solution link to the curriculum, leave this as is. If not, delete it and write the message you wish.

Thank you,

The Odin Project team.

### CODE REVIEW

**Comment by mortvicious** [comment]
This is a PR template. If you are adding a solution link to the curriculum, leave this as is. If not, delete it and write the message you wish.

Thank you,

The Odin Project team.

**Comment by ZachBaird** [comment]
Hey @mortvicious ! It looks like your pull request includes adding Jcoen's solution - which is already in the file. If you look at your version, Jcoen is now in there twice. If you can revert/remove that change, your pull request should be set to go :)

**Comment by mortvicious** [comment]
> Hey @mortvicious ! It looks like your pull request includes adding Jcoen's solution - which is already in the file. If you look at your version, Jcoen is now in there twice. If you can revert/remove that change, your pull request should be set to go :)

It seems that everything should be OK now :)

**Comment by ZachBaird** [comment]
Great @mortvicious :)

**Pull request merged**
