### PR TITLE
Updated project RPS

### PR DESCRIPTION
**Pull request by JohnHerrera14**
This is a PR template. If you are adding a solution link to the curriculum, leave this as is. If not, delete it and write the message you wish.

Thank you,

The Odin Project team.

### CODE REVIEW

**Comment by bycdiaz** [comment]
@JohnHerrera14 Could you edit your submission so that all of the link text is between the square brackets? [All text in here] instead of [All text] in here.

thanks

**Comment by JohnHerrera14** [comment]
I beg your pardon, I'm very new, I have no idea where to make those
changes. If you could walk me through it would be greatly appreciated.

Thanks.
John

**Comment by bycdiaz** [comment]
On this page, you can go here: 
image

Then edit the file:
image

Then you can add a comment and click "Commit Changes"
image

Let me know if you still have additional questions.

**Comment by JohnHerrera14** [comment]
Done! Thanks for your help!

**Comment by JohnHerrera14** [comment]
Says it is merged

**Comment by bycdiaz** [comment]
@JohnHerrera14,

Right. I merged it.

**Pull request merged**
