### PR TITLE
My solution to Google Homepage

### PR DESCRIPTION
**Pull request by FTdadPTjedi**
This is a PR template. If you are adding a solution link to the curriculum, leave this as is. If not, delete it and write the message you wish.

Thank you,

The Odin Project team.

### CODE REVIEW

**Comment by ryanford-frontend** [comment]
You live demo link doesn't seem to be working. Can you confirm you made the github page?

**Comment by FTdadPTjedi** [comment]
image
This is what I am seeing in the repo settings. It says it has published, but I am unable to view the page. I have been through the directions several times and cannot find what I have done wrong. Do you have any suggestions for me?

**Comment by FTdadPTjedi** [comment]
Came back this morning and the preview link works. The markdown was correct but I missed a setting in Github that allowed it to be published.

**Comment by 105ron** [comment]
There seems to be a sub module added in the pull request? Might need to start again or remove it with another commit.

**Pull request closed without merging**
