### PR TITLE
Remote wsl information

### PR DESCRIPTION
**Pull request by longebane**
Using WSL isn't scary when you can access the file system directly with remote-wsl and WSL now allows you almost identical functionality for full stack development.

### CODE REVIEW

**Comment by 105ron** [comment]
The reason it is highly discouraged is because the amount of people who *think* they know what they are doing, then get stuck and have to ask for help. It was taking too much time to resolve the issues in chat. If you know how to use it, it's great.

**Comment by longebane** [comment]
I totally understand what you're saying, and was hesitant to append to this section.
However, I had a student of mine, who is *completely* new to development, find it easier to use WSL.
And by new, I mean, he has no idea what the terminal is, git, npm, html/css/js, etc.
When combined with Remote-WSL, he didn't need to worry about symlinks. He completed the course without needing to resort to googling or anything. The course worked just the same for him. In fact, he was completely overwhelmed by VM's and lost motivation until I pointed him to WSL.
I just feel WSL is at a point where it might help new dev's intimidated by VM's.
Kind of ironic too, since the course makes WSL feel more overwhelming/advanced than VM's.
Obviously this is just anecdotal evidence from 1 person, but it's worth a look into I think.

**Comment by longebane** [comment]
Additionally, I still left the *not recommend* warning and *not supported* text to make this a softer transition!

**Comment by 105ron** [comment]
Ok, I will leave it to @I3uckwheat what he wants to do. He's the one that does a lot of the troubleshooting.

**Comment by I3uckwheat** [comment]
@longbane just letting you know I'm getting to this asap!

**Pull request merged**
