### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by DoviMaj**
- [x] You have read [The Odin Projects Contributing Guide](https://github.com/TheOdinProject/curriculum/blob/master/CONTRIBUTING.md).

#### 1.Describe the changes made:

Changed HTML and CSS course description. since it doesnt make much sense for those not comming from the ruby path.

#### 2. If this PR is related to an open issue please reference it with the `#` operator and the issue number below:

#XXXXX

### CODE REVIEW

**Review by CatQueenCodes — CHANGES_REQUESTED** [review]
I think changing “HTML and CSS” to “This lesson” would sound a bit better.

**Comment by DoviMaj** [comment]
i didnt quite understand how would that make sense, since this is the whole course description @CatQueenCodes . Or did u mean "This course"?

**Comment by CatQueenCodes** [comment]
Oops! Yes, “This course” sounds good to me.

**Comment by CatQueenCodes** [comment]
@DoviMaj Actually, thinking about it, it may be best to say:

 “Learn how to make responsive designs that look great in a web browser!”

**Comment by CatQueenCodes** [comment]
Actually, thinking about it, it may be best to say “ Learn how to make responsive websites that look great in a web browser!”

**Comment by DoviMaj** [comment]
I took a look at the course and since responsivenes is only part of the course/module(how its described in JavaScript), imo it shouldnt be so emphasized in the description. And actually what is meant by design frameworks is responsive design frameworks so im rephrasing that also.

From:
Good web design doesn't happen by accident. HTML & CSS takes a deeper look at front-end design and development, expanding on what is covered in Foundation. You'll be equipped to deeply understand and create your own design frameworks!

To:
1 - Good web design doesn't happen by accident. This course takes a deeper look at front-end design and development, expanding on what is covered in Foundations. You'll learn how to design and develop websites that look great in any device and you'll be equipped to deeply understand and create your own responsive design framework!

2 - Good web design doesn't happen by accident. You'll learn how to design and develop websites that look great in any device and be equipped to deeply understand and create your own responsive design framework!

3 - Good web design doesn't happen by accident. This course takes a deeper look at front-end design and development, expanding on what is covered in Foundations. You'll be equipped to deeply understand and create your own responsive design framework!

what do u think @CatQueenCodes ?

**Comment by I3uckwheat** [comment]
@DoviMaj 1

**Comment by CatQueenCodes** [comment]
Thanks!

**Pull request merged**
