### PR TITLE
 Setting Up A React Environment: fix link for guide to React dev tools

### PR DESCRIPTION
**Pull request by SAL778**
last working snapshot of the react dev tools guide

## Because

Current link for "guide for React Developer Tools" is broken. Needed to be updated with the last working snapshot of the website.

## This PR

- replaced Pluralsight link with a web archive Pluralsight link

## Issue

Closes [#26948](https://github.com/TheOdinProject/curriculum/issues/26948)

## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [x] The `Because` section summarizes the reason for this PR
-   [x] The `This PR` section has a bullet point list describing the changes in this PR
-   [x] If this PR addresses an open issue, it is linked in the `Issue` section
-   [x] If any lesson files are included in this PR, they have been previewed with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure it is formatted correctly
-   [x] If any lesson files are included in this PR, they follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

### CODE REVIEW

**Comment by rlmoser99** [comment]
@codyloyd This broken link has had several duplicate issues and PRs created. When you have time to review this PR, this closed PR may have some alternatives to these changes:
https://github.com/TheOdinProject/curriculum/pull/27007

**Comment by KURELLANAVEEN** [comment]
> @codyloyd This broken link has had several duplicate issues and PRs created. When you have time to review this PR, this closed PR may have some alternatives to these changes: #27007

@rlmoser99 I wanted to express my interest in contributing to this issue. If possible, could you please assign the task to me? I'm eager to work on it and will ensure to follow the contribution guidelines closely.

**Comment by rlmoser99** [comment]
@KURELLANAVEEN Since the person that created the issue checked the box "Would you like to work on this issue?" it is implied that this issue is assigned to the them. They already have this PR created. So, I am going to leave it up to the reviewer and possibly what @SAL778 thinks.

**Comment by codyloyd** [comment]
I'm going to go ahead and merge this one.  I don't _love_ relying on web.archive for stuff like this BUT, I don't have the bandwidth to investigate other options at the moment.  this resource has already been vetted and approved by people with much more react experience than I.

**Pull request merged**
