### PR TITLE
Update project_calculator.md

### PR DESCRIPTION
**Pull request by JohnHerrera14**
This is a PR template. If you are adding a solution link to the curriculum, leave this as is. If not, delete it and write the message you wish.

Thank you,

The Odin Project team.

### CODE REVIEW

**Comment by bycdiaz** [comment]
@JohnHerrera14, you put an unnecessary space between the square brackets and parenthesis that produces the link. Can you correct that? Thanks

**Comment by JohnHerrera14** [comment]
Hi, I don't see it added to the list yet, where could I find it to update
this mistake?

**Comment by JohnHerrera14** [comment]
Nevermind, it's updated now.

Thanks!

**Comment by bycdiaz** [comment]
@JohnHerrera14 Unfortunately, it looks like the link isn't working. I believe it may be https://github.com/JohnHerrera14/Calculator. But please grab the correct link and add it to the file.

**Comment by JohnHerrera14** [comment]
updated

**Pull request merged**
