### PR TITLE
WAI-Aria: Correct grammer

### PR DESCRIPTION
**Pull request by OmarNaguib**
## Because

wrong use of both
could also be corrected to: "which would confuse users that use both a screen reader and a keyboard to navigate the page."

## This PR

fixes incorrect grammer

## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [x] The `Because` section summarizes the reason for this PR
-   [x] The `This PR` section has a bullet point list describing the changes in this PR
-   [x] If this PR addresses an open issue, it is linked in the `Issue` section
-   [x] If any lesson files are included in this PR, they have been previewed with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure it is formatted correctly
-   [x] If any lesson files are included in this PR, they follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

### CODE REVIEW

**Comment by ManonLef** [comment]
I don't think this is wrong usage of the word 'both' 🤔
It's used as a conjuction. I will attach a screenshot below from [the editor's manual website](https://editorsmanual.com/articles/both-how-to-use/)
Screenshot 2023-08-03 at 11 29 00

**Comment by OmarNaguib** [comment]
> I don't think this is wrong usage of the word 'both' 🤔 It's used as a conjuction. I will attach a screenshot below from [the editor's manual website](https://editorsmanual.com/articles/both-how-to-use/) Screenshot 2023-08-03 at 11 29 00

But in the original text the conjunction is between a screen reader and using a keyboard, That's different than the examples you provided
 
To my understanding,
You can say: i use both a fork and a knife
But you can't say: i use both a fork and cut with a knife
Because you can't add the fork, a noun, to the verbal sentence of cutting
Likewise, you can't add the screen reader to using a keyboard
Has to be between equal things

Screenshot_20230804-105612

**Comment by ManonLef** [comment]
Thank you and apologies for my confusion!

**Comment by OmarNaguib** [comment]
Alright, Thank you for your work!

**Pull request merged**
