### PR TITLE
[JavaScript - Project: Recursion] : Capitlization of Fibonacci corrected

### PR DESCRIPTION
**Pull request by aconstas**
## Because

This PR addresses grammar.

## This PR

- Capitalized "Fibonacci"

## Issue

Closes #XXXXX

## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [x] The `Because` section summarizes the reason for this PR
-   [x] The `This PR` section has a bullet point list describing the changes in this PR
-   [x] If this PR addresses an open issue, it is linked in the `Issue` section
-   [x] If any lesson files are included in this PR, they have been previewed with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure it is formatted correctly
-   [x] If any lesson files are included in this PR, they follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

### CODE REVIEW

**Comment by JoshDevHub** [comment]
Nice spot @aconstas 

Would you be comfortable making this same change in the ruby course's version of this exercise? You can see [here](https://github.com/TheOdinProject/curriculum/blob/main/ruby/computer_science/project_recursion.md?plain=1#L8) that it has the same error.

**Comment by aconstas** [comment]
Thanks Josh!

Absolutely! I'll get on it.

**Comment by aconstas** [comment]
@JoshDevHub 

Just submitted a PR for the Ruby course correction!

My apologies though, I am now realizing I could have edited this PR to include the Ruby change instead of creating another one.

**Review by JoshDevHub — APPROVED** [review]
Yeah adding onto this PR is what I had in mind, but that's okay. Glad to merge both of them.

Thank you for your contributions :raised_hands:

**Pull request merged**
