### PR TITLE
Binary Search Trees Project: Use lazy numbering

### PR DESCRIPTION
**Pull request by zachmmeyer**
Complete the following REQUIRED checkboxes:

-   [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [X] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`

Complete the following checkboxes ONLY IF they are applicable to your PR. You can complete them later if they are not currently applicable:
-   [X] I have previewed all lesson files included in this PR with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure the Markdown content is formatted correctly
-   [X] I have ensured all lesson files included in this PR follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

<hr>

**1. Because:** the numbered lists in this project are hard-coded

Closes #XXXXX

**2. This PR:** changes the numbered lists to use lazy numbering.

**3. Additional Information:**

### CODE REVIEW

**Review by 01zulfi — APPROVED** [review]
Looks good 🚀 

(Unfortunately, there's a merge conflict)

**Comment by zachmmeyer** [comment]
@01zulfi It's more than a single merge conflict. Looks like changing this modified a whole bunch of indexes in the ruby folder? Not sure what's up with that. I'll have to figure this out later.

I'll probably just make another branch and make these changes locally rather than trying to use GitHub.

**Comment by 01zulfi** [comment]
@zachmmeyer It's most likely because I recently merged this PR:
1. #23846

**Comment by zachmmeyer** [comment]
Well, that sucks.
I'll just make a new PR, because I couldn't get the conflicts sorted. It kept renaming everything regardless, and I don't want to mess anything up.

**Pull request closed without merging**
