### PR TITLE
Foundation>Links and Images > A Metaphor: Fix current room

### PR DESCRIPTION
**Pull request by simcity290596**
## Because

purpose: in Foundation>Links and Images > A Metaphor , the metaphor is wrong, current room is /museum. Current room is NOT /museum/movie_room.html 
benefit: Avoid confusion for people new to relative and absolute path concept

## This PR

- _current room (the museum movie room /museum/movie_room.html)_ changed to

> _current room (the museum  /museum/)_

## Pull Request Requirements

-   [ ] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [x] The `Because` section summarizes the reason for this PR
-   [x] The `This PR` section has a bullet point list describing the changes in this PR
-   [ ] If this PR addresses an open issue, it is linked in the `Issue` section
-   [x] If any lesson files are included in this PR, they have been previewed with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure it is formatted correctly
-   [x] If any lesson files are included in this PR, they follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

### CODE REVIEW

**Review by xandora — CHANGES_REQUESTED** [review]
Would it make even more sense to drop the `/shops/` directory from the equation all together? Then when you travel from `/museum/movie_room.html` to `/museum/coffee_shop.html` you're just going from one "room" in the museum to another.

**Comment by simcity290596** [comment]
The explanation given by "The Odin project" is correct and **my pull request is wrong**.
We are indeed in `/museum/movie_room.html`
Reading this metaphor after 2 weeks, I now understand what they are saying.

As for your suggestion I think _personally_ both the metaphors (one provided by The Odin Project and the other metaphor provided by you) are confusing.
Let me try to explain:

> Why The Odin Project metaphor is confusing
In the museum example, 

- `town` is like root directory
- `museum` is like a directory
- `movie-room` is like a file inside museum directory (but it should be a directory) 

So, why changing from one room(`/museum/movie_room.html`) to another(`/museum/shops/coffee_shop.html`) is given by `./shops/coffee_shop.html` statement. 
- "." represents `museum_ room`
- but `movie_room.html` is not mentioned here. There is no "getting out" of `movie-room`. No mention that we left `movie-room`

I think a better solution would be
- `town` is like root directory
- `museum` is like a directory
- `movie-room` is also like a directory inside `museum` directory
- `movie-room` contains old movie reels which are like files. Some files are `The Wizard of Oz.reel`, `Goldfinger.reel` etc.
- `shop` is a room containing all the shop related rooms (we can remove this `shop` directory if u want)
- `antique-shop` is a directory
- `antique-shop` contains _vintage.radio_ file

Now if we are `movie-room` and we want to go to locate `vintage.radio` we can go through this path `../shop/antique-shop/vintage.radio`
- `..` is saying go to parent directory of current room (`movie-room`) which is `museum` (notice here, that `movie room` is also mentioned here)
- `/shop` is saying go to shop
- `../shop/antique-shop/vintage.radio` is relative path to locate `vintage.radio` from `movie.room`
 
P.S.
- I am a little sleep deprived, let me come back to this with a fresh head. I know my example is probably more confusing that the Odin project one
- This is my first PR, I cant believe I am talking to a real person from the other side of the world. Lol, I am happy even if this PR gets denied

**Comment by xandora** [comment]
I think a visual aid in necessary to work this through! Here's a quick one, it might not be enough to figure this out I just made it and want people to see it :D
image

**Comment by xandora** [comment]
I think we should probably move this back to being an issue and have it as something that needs working on.

**Pull request closed without merging**
