### PR TITLE
Add dropdowns to separate ruby on rails & firebase content in rails_backend.md

### PR DESCRIPTION
**Pull request by 01zulfi**
- [x] You have read [The Odin Projects Contributing Guide](https://github.com/TheOdinProject/curriculum/blob/main/CONTRIBUTING.md).
 - [x] The title summarizes the change and where it happened, for example: "Fixes punctuation in Clean Code lesson".
 - [x] If the PR is related to an open issue, use a [relevant keyword](https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests) and reference it with the `#` sign and the issue number.
 - [x] You have previewed your markdown (if any) in the [Odin Markdown Preview Tool](https://www.theodinproject.com/lessons/preview)
 - [x] If changes are requested, please make the changes in a timely manner. After you submit the changes, request another review from the maintainer (top right).

#### 1. Describe the changes made and include why they are necessary or important:

[This lesson](https://www.theodinproject.com/paths/full-stack-javascript/courses/javascript/lessons/using-ruby-on-rails-or-baas-for-your-back-end) requires scrolling from the user to get to their respective content. Adding dropdowns will alleviate that

#### 2. Related Issue

Closes #XXXXX

### CODE REVIEW

**Comment by thatblindgeye** [comment]
Thanks for making this update! There is something I want to investigate accessibility wise with this update, so for now I'm just adding the blocked label to let other maintainers know not to merge it (just in case you got worried that your PR was blocked from merging at all).

**Review by thatblindgeye — COMMENTED** [review]
So I think my concern is whether we'd be overusing the `<details>` elements just for the sake of putting everything into one. I think it could definitely make sense for the Assignment section, but I'm not entirely sure about other sections.

I'm going to label this back to Needs Review to have another maintainer provide some input.

**Comment by wise-king-sullyman** [comment]
IMO having to expand dropdowns for each section of the lesson is bad UX, but I see where you're coming from with the suggestion because what currently exists isn't great either.

I believe that we should split these into two separate lessons entirely, and serve the JS version in the JS path and the RoR version in the RoR path.

**Comment by wise-king-sullyman** [comment]
The current decision is to have independent versions of this lesson in each path. In order to do that we will need to:

1. Rename js-rails folder to js-and-the-backend

2. Pull firebase content out of this lesson, place in a new lesson with an appropriate name

3. Make relevant site PRs to update the seed files for each path.

Are you interested in doing this @01zulfi?

**Comment by 01zulfi** [comment]
I'll take it on.

**Comment by 01zulfi** [comment]
Closing this since all the tasks in the above acceptance criteria have been completed in https://github.com/TheOdinProject/curriculum/pull/23607 and https://github.com/TheOdinProject/theodinproject/pull/2645

**Pull request closed without merging**
