### PR TITLE
Julia addition

### PR DESCRIPTION
**Pull request by juliataylor83**
Adding my google-homepage easy solution to the webpage.

### CODE REVIEW

**Comment by juliataylor83** [comment]
I left off the 'preview in browser' in the first pull request, so I've attempted to fix that with my second pull request.

**Comment by KevinMulhern** [comment]
Hey @juliataylor83, it looks like you added a tilde '~' to the end of the file name. That will stop it from displaying correctly. Could you remove that addition please :)

**Comment by juliataylor83** [comment]
Hi Kevin - sorry about that, looks like I just used the wrong file! I think I've fixed it - let me know if I need to do anything different. Thanks :)

**Comment by KevinMulhern** [comment]
Hi @juliataylor83, the other file is still in your pull request. But I will merge it and remove the extra file. Congratulations on the completion of your first project for the curriculum :)

**Pull request merged**
