### PR TITLE
React: Class Based Components: fix grammar #2

### PR DESCRIPTION
**Pull request by kol3x**
## Because
Follow up to my previous PR #26441, sorry for the confusion!

## This PR
+ Changed "now a days" to "nowadays"

## Issue

Closes #XXXXX

## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [x] The `Because` section summarizes the reason for this PR
-   [x] The `This PR` section has a bullet point list describing the changes in this PR
-   [ ] If this PR addresses an open issue, it is linked in the `Issue` section
-   [x] If any lesson files are included in this PR, they have been previewed with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure it is formatted correctly
-   [x] If any lesson files are included in this PR, they follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

### CODE REVIEW

**Comment by ManonLef** [comment]
there seems to be a spelling error on another line as well. I'd be thankful if you want to add a correction to it. 
Screenshot 2023-10-08 at 20 21 08

A bunch [of other files](https://github.com/TheOdinProject/curriculum/pull/26449/files) are showing similar spelling errors, unrelated to this PR, but please let me know if you'd like to correct those as well since they show up in each PR now :)

**Comment by kol3x** [comment]
> there seems to be a spelling error on another line as well. I'd be thankful if you want to add a correction to it. Screenshot 2023-10-08 at 20 21 08
> 
> A bunch [of other files](https://github.com/TheOdinProject/curriculum/pull/26449/files) are showing similar spelling errors, unrelated to this PR, but please let me know if you'd like to correct those as well since they show up in each PR now :)

Sure! I would love to fix those as well. I should only fix it in the same article first to complete this PR and then open another PR for all other files, correct?

**Comment by ManonLef** [comment]
@kol3x since they all involve typing errors, I'd be fine with you updating them across all files really. Thanks so much for picking this up! It's appreciated.

**Comment by kol3x** [comment]
> @kol3x since they all involve typing errors, I'd be fine with you updating them across all files in this PR really. Thanks so much for picking this up! It's appreciated.

I think I'm done... I did it with Github Desktop, but I used it for the first time. Everything seems fine, I just can't figure if the branch is still synced with main

**Review by ManonLef — APPROVED** [review]

**Comment by ManonLef** [comment]
Looking great! Thanks so much for fixing the additional typos as well!

**Pull request merged**
