### PR TITLE
Foundations/Revisiting Rock Paper Scissors: Fix lint errors

### PR DESCRIPTION
**Pull request by roopxx**
## Because
There was an error in the markdown config file which did not include the `"pre"` element in the "allowed_elements" array, causing inline code HTML error. Additionally, the link label was not descriptive enough, leading to another lint error.

## This PR
- Updated the link label text in the lesson to follow descriptive text standards.
- Updated the "allowed_elements" array in the markdown config file to include the `"pre"` element.

## Issue
Related to #27119  

## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [x] The `Because` section summarizes the reason for this PR
-   [x] The `This PR` section has a bullet point list describing the changes in this PR
-   [x] If this PR addresses an open issue, it is linked in the `Issue` section
-   [x] If any lesson files are included in this PR, they have been previewed with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure it is formatted correctly
-   [x] If any lesson files are included in this PR, they follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

### CODE REVIEW

**Review by JoshDevHub — CHANGES_REQUESTED** [review]
The changes to the Revisiting Rock Paper Scissors lesson and the markdownlint configuration look good. I'm guessing the heading issue is meant to be resolved with #27332 ?

I'm confused about the changes in  `advanced_html_css/accessibility`. They don't seem to fit in the context of this PR, and given you didn't write about them in the PR description,  you might not be aware that they're here @roopxx ? For this PR, the changes in these files should be reverted. Issues in those files should be addressed in a different PR.

**Comment by roopxx** [comment]
Thanks for the feedback, @JoshDevHub.

I apologize for the oversight with including all files in one PR. As a beginner, I'm still learning to manage commits effectively. Last night, I tried researching how to separate changes into different PRs, but couldn't find a clear solution.
Could you please offer guidance on the best approach? I want to address the issues correctly and follow the proper protocol.

Thanks again for your help.

**Comment by JoshDevHub** [comment]
It's no problem @roopxx 

Locally, you want to work from branches to keep work separate. So a workflow where you have multiple PRs open might look something like:
```sh
# from `main`
git checkout -b my_first_pr # create a branch to work on a PR

# make changes
git add .
git commit -m "commit message"
git push origin my_first_pr # push changes up and allow for PR

git checkout main # go back to main
git checkout -b my_second_pr # create a new branch from main to work on the next PR
```
I suspect you made the branch from this PR from the same branch you used for another PR. You want to always create your new branches from `main`.

For fixing this PR for the advanced html and css stuff got merged in. This means you should be able to fix it by doing another merge commit with `upstream/main`. You're okay to do that right? Looks like you have a few merge commits in this work already.

**Comment by roopxx** [comment]
Thanks for the tips, @JoshDevHub!

Got it, I'll start creating new branches from main hereafter to keep things organized.Also I'll sort out the advanced HTML and CSS section by doing another merge commit with upstream/main on this PR.

Appreciate your help! 🙂

**Review by JoshDevHub — CHANGES_REQUESTED** [review]
Great that fixed things.

One last change, and then I'll merge this. On line 80, there's a lint error you can quickly fix.
```
# current and incorrect
It isn’t required, so consider it supplemental.

# correct
It isn't required, so consider it supplemental.
```
Now those might look the exact same, but the apostrophe character in the word "isn't" is different.

**Comment by roopxx** [comment]
@JoshDevHub, Welcome 🤗. Looking forward to contributing more in the future.

**Pull request merged**
