### PR TITLE
Chore/upload curriculum images to repo

### PR DESCRIPTION
**Pull request by xiaozhong21**
- [x] You have read [The Odin Projects Contributing Guide](https://github.com/TheOdinProject/curriculum/blob/main/CONTRIBUTING.md).

#### 1.Describe the changes made:

Upload images/screenshots to repo for the curriculum to later replace the links with them using statically.

#### 2. If this PR is related to an open issue please reference it with the `#` operator and the issue number below:

Resolves [#22433](https://github.com/TheOdinProject/curriculum/issues/22433)

### CODE REVIEW

**Review by wise-king-sullyman — CHANGES_REQUESTED** [review]
This is looking really great so far, thank you for getting right on it!

Couple things:

The image linked in rails_programming/apis/project_kittens_api is actually demonstrating using an API to reach a photo so that one we want to leave actually.

There are also gifs that we will want to move into the curriculum repo along with these pngs, can you add those as well?

**Comment by xiaozhong21** [comment]
Thanks for the comment! 

I have done the following: (1) deleted the image for rails_programming/apis/project_kittens_api from repo; and (2) added GIF images to the repo (I found only one GIF, please let me know if I missed anything).

**Review by wise-king-sullyman — CHANGES_REQUESTED** [review]
It looks like there is another gif in the Knight's Travails project which we'll want to pick up. You only need to worry about the one within the ruby_programming directory, and not the ones outside of that directory.

Additionally, looks like last time I missed a couple of things. We also should probably get the Google logo in the Google homepage project and the other couple of images in the Ruby debugging lesson.

Not sure how you're going about finding the linked images but I used this search to try and track them all down to make sure they were here in this review, so if it's of any help: 
image

If you have any questions please feel free to message on this PR and @ me or ping me in the contribution-suggestions channel in the discord.

**Comment by wise-king-sullyman** [comment]
@xiaozhong21 are you needing any help with this?

If anything in my last change request was unclear or you're just short on time please let me know.

**Comment by xiaozhong21** [comment]
@wise-king-sullyman Thanks for checking in! I am just a little short on time but I will finish and ship it by the end of this week! :)

**Comment by wise-king-sullyman** [comment]
@xiaozhong21 need some help / don't have time to finish this up? If yes to either it's no biggie, but I would appreciate you letting me know.

**Comment by wise-king-sullyman** [comment]
I've added the final images in another PR which I branched off of your branch here to keep things in one PR, so I'm going to close this one.

Thanks again for everything that you did though!

**Pull request closed without merging**
