### PR TITLE
Submit student solution

### PR DESCRIPTION
**Pull request by waglebr**
```
This is a PR template, If you are adding a solution link to the curriculum leave this as is. If you are not, then delete it and write the message you wish.
Thank you,
The Odin Project team.

```

### CODE REVIEW

**Comment by waglebr** [comment]
Thanks Rhys! 👍

**Comment by 105ron** [comment]
No worries @waglebr . I can show you how to update your fork to be up to date with TOP's curriculum before you add your next solution if you would like so there's no merge conflicts. :) Otherwise more practice at resolving merge conflicts for me 👍

**Comment by waglebr** [comment]
Sorry for that, I actually tried to update my fork but couldn't figure out how... I'd appreciate if you could point me the right direction. 👍

**Comment by waglebr** [comment]
Hi Rhys, I just managed to update my fork. Thanks!

**Pull request merged**
