### PR TITLE
React: Complete README

### PR DESCRIPTION
**Pull request by scorpi4n**
## Because

The README in the react folder was mostly blank (only had "wip") whereas the other folders had complete READMEs.

## This PR

- Completes the react folder's README in the same way the other folders' READMEs are

## Issue

The contributing guide said small changes can have a PR submitted without opening an issue

## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [x] The `Because` section summarizes the reason for this PR
-   [x] The `This PR` section has a bullet point list describing the changes in this PR
-   [ ] If this PR addresses an open issue, it is linked in the `Issue` section
-   [ ] If any lesson files are included in this PR, they have been previewed with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure it is formatted correctly
-   [ ] If any lesson files are included in this PR, they follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

### CODE REVIEW

**Comment by ManonLef** [comment]
Thank you for doing this! I do wish to discuss this with @TheOdinProject/maintainers 

With the ever changing content, I wonder if these are a good idea to keep around to be honest. A bunch of new lessons were added recently and I'm sure the README's haven't been updated.  

Perhaps we can consider a better format for the README's which doesn't include the path layout and is less coupled. Instead we could consider a contributing guide, a contact method for professionals or content creators or something like that? I would love to hear opinions.

**Comment by scorpi4n** [comment]
I was kind of wondering the same while I put it together. I was doing the 'Using Git In The Real World' lesson and found the blank README, so I figured I might as well create a PR.

I do think it'd be a good idea to either entirely rewrite or just remove the README's. All of them have a disclaimer saying that they might be out of sync with the actual courses, and the README I put together hadn't been touched in about a year.

**Comment by thatblindgeye** [comment]
I feel like we could get away with just removing them. I can't think of anything that should live in individual directory README's that isn't better suited to the top level README/contribution guide, other than possibly a basic overview of what the course is/should ideally cover (though is that really necessary?).

**Comment by 01zulfi** [comment]
The current layout of course README's was part of the folder structure project I was working on last year. See https://github.com/TheOdinProject/top-meta/issues/109

+1 on removing the course READMEs. They are out -of-date and provide little to no value.

**Comment by scorpi4n** [comment]
Removing the READMEs is simple enough, I can do that if that's how we want to move forward.

**Comment by 01zulfi** [comment]
@scorpi4n Yes, please make a PR if you can

**Comment by scorpi4n** [comment]
Alright! I'll close those this one and work make a new PR

**Pull request closed without merging**
