### PR TITLE
Working with Text: Fixed Grammar

### PR DESCRIPTION
**Pull request by OscarMilde**
Corrected grammatical error: 'an H' to 'a H'

## Because

There was a grammatical error throughout the piece where 'An' was typically by 'H'. Either the 'H' in 'HTML' or for 'h1'. 

## This PR

- Foundations: Working with Text. Corrected one consistent typo throughout the piece found in lines 20, 60, 70 and 152 of the .md file. 

## Issue

Closes #XXXXX

## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [x] The `Because` section summarizes the reason for this PR
-   [ ] The `This PR` section has a bullet point list describing the changes in this PR
-   [ ] If this PR addresses an open issue, it is linked in the `Issue` section
-   [ ] If any lesson files are included in this PR, they have been previewed with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure it is formatted correctly
-   [ ] If any lesson files are included in this PR, they follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

### CODE REVIEW

**Review by zachmmeyer — CHANGES_REQUESTED** [review]
@OscarMilde Hello! Thanks for contributing!
While these changes look correct to me, it appears you selected the second checkbox of the PR requirements without fulfilling them. Please correct this error and we'll be able to move forward.

**Comment by OscarMilde** [comment]
Hey @zachmmeyer, my pleasure! Apologises for the error, I've unticked the PR BP.

**Comment by zachmmeyer** [comment]
@OscarMilde the second checkbox is a requirement around the title. You must put a better title. You checked it saying you put a title that fits those requirements, but you did not.

**Comment by OscarMilde** [comment]
My mistake! Hopefully corrected now, @zachmmeyer

**Comment by zachmmeyer** [comment]
@OscarMilde I have been referring to the title of the Pull Request.
You have it titled as `Update working-with-text.md`. The requirements we have set ask that you follow this format for your title: `location of change: brief description of change`.
I'm going to assist you here and suggest a suitable title for this work: `Working with Text: Fixed Grammar`.
Here is a screenshot of open PR's on this repository, most of them are following these guidelines:
image
Please let me know if you do not understand what I am asking and I will make the changes and move this work forward.

**Comment by OscarMilde** [comment]
Hey @zachmmeyer sorry for all the back-and-forth, I think I understand but to save time, would it be OK if you made the change? Better to learn from you see it in action!

**Comment by zachmmeyer** [comment]
Before:
image
After:
image
Do you understand what I am talking about now?

**Comment by OscarMilde** [comment]
Hey @zachmmeyer yes I understand now, I've since read the Commit Messages lesson and that, combined with what you've done here, make perfect sense. Thanks so much and sorry for all the back-and-forth. Have a good day!

**Review by zachmmeyer — APPROVED** [review]

**Pull request merged**
