### PR TITLE
Update caesar_cipher.md

### PR DESCRIPTION
**Pull request by bhenning83**
This is a PR template. If you are adding a solution link to the curriculum, leave this as is. If not, delete it and write the message you wish.

Thank you,

The Odin Project team.

### CODE REVIEW

**Comment by marvingay** [comment]
@bhenning83 It appears you may have accidentally deleted another solution in the process of adding your own. If you could add it back, we can get your solution displayed! Refer to the "Files changed" tab for clarity.

Thank you!

**Comment by bhenning83** [comment]
Whoops, sure did. I think I just created a separate pull request. I'm googling how to edit an existing pull request and it wasn't clear to me. Should I have just left a comment with the file I deleted?

**Comment by marvingay** [comment]
@bhenning83 I believe it depends on which outlet you are submitting the pull requests. If it's from a fork of the repository, simply pushing new commits on the same branch as the PR will automatically update the PR.

None the less, thank you for making the change so quickly!

**Comment by bhenning83** [comment]
Got it. Yeah thanks for the info.

**Pull request closed without merging**
