### PR TITLE
(temidayo's solution)   https://github.com/temideeone/google-homepage

### PR DESCRIPTION
**Pull request by temideeone**
This is a PR template. If you are adding a solution link to the curriculum, leave this as is. If not, delete it and write the message you wish.

Thank you,

The Odin Project team.

### CODE REVIEW

**Comment by Deetss** [comment]
You didnt actually add you solution to the commit, you might want to check this out

**Comment by leosoaivan** [comment]
Please add your name, and format the solution as a link. Look at the other solutions added for a hint.

**Comment by temideeone** [comment]
thank you sir i have try to do that but don't know if its correct or not
please let me know if there any correction ....thanks for your support.
temidayo.

On Feb 10, 2019 17:57, "L. P. Soai-Van" <notifications@github.com> wrote:

Please add your name, and format the solution as a link. Look at the other
solutions added for a hint.

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/TheOdinProject/curriculum/pull/9531#issuecomment-462150959>,
or mute the thread

**Comment by leosoaivan** [comment]
When you edit the markdown files to add your solution, it should look exactly like the solutions already written. It should basically look like:
`* [Your name](Link to your solution)`

I've made the edits this time. Please try it again next time.

**Pull request merged**
