### PR TITLE
Getting Hired - Removes sentence.

### PR DESCRIPTION
**Pull request by bycdiaz**
Removes point about following up after an application.

## Because

I know this is subjective. But it doesn't feel useful or productive to follow up after applying for a role. But if folks feel strongly about this, I suppose we can leave it in.

## Issue

Closes #XXXXX

## Pull Request Requirements

-   [ ] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
-   [ ] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [ ] The `Because` section summarizes the reason for this PR
-   [ ] The `This PR` section has a bullet point list describing the changes in this PR
-   [ ] If this PR addresses an open issue, it is linked in the `Issue` section
-   [ ] If any lesson files are included in this PR, they have been previewed with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure it is formatted correctly
-   [ ] If any lesson files are included in this PR, they follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

### CODE REVIEW

**Comment by MaoShizhong** [comment]
As per https://discord.com/channels/505093832157691914/891423158836547665/1226024581454626846, I think we can ignore this linter issue for this PR. Only one issue is flagged, but it requires creating and deciding on content for a `### Lesson overview` section, which will then end up flagging that we're missing the `### Assignment`, `### Knowledge check`, and `### Additional resources` sections respectively. All but the `### Additional resources` section would require some kind of thought that's out of the scope of this PR (and there are quite a few lessons (approx. 70), especially in the Getting Hired course that would flag the same issue).

**Comment by bycdiaz** [comment]
@thatblindgeye I agree with that. There's a ton of subjectivity and we should make that position clear.

**Comment by bycdiaz** [comment]
p.s. Just to confirm: this is cool to merge? @MaoShizhong @thatblindgeye

**Comment by MaoShizhong** [comment]
I can't speak for the content, so I'll pass that to another maintainer. But at least for linting, that's something we probably want to revisit separately, as it'll affect a fair few lessons (in this course and other ones). So the linting thing should be fine to ignore for this PR.

**Review by thatblindgeye — APPROVED** [review]

**Pull request merged**
