### PR TITLE
Adds article regarding CRUD in SQL context.

### PR DESCRIPTION
**Pull request by bycdiaz**
I noticed that the database resources don't explicitly mention CRUD (but it seems like it is implied). Please feel free to double check me. If context around CRUD is useful, let me know if the resource I've added adds value to this lesson.

### CODE REVIEW

**Comment by leila-alderman** [comment]
@bycdiaz Are you adding this resource to this lesson because of the learning objectives at the top of the page? If so, my inclination is to delete the CRUD learning objectives instead. 

CRUD and REST are introduced well in the Getting Your Feet Wet lesson (https://www.theodinproject.com/courses/ruby-on-rails/lessons/getting-your-feet-wet), which feels to me like a more appropriate place.

If you think this content is still valuable at this point in the curriculum, though, I would recommend selecting a different article. My suggestion: https://www.codecademy.com/articles/what-is-crud

**Comment by bycdiaz** [comment]
@leila-alderman I haven't gone beyond this lesson so I trust your judgement. I'll delete the CRUD learning objectives.

**Comment by leila-alderman** [comment]
LGTM :+1:

**Comment by KevinMulhern** [comment]
👍 nice addition, thanks @bycdiaz 
:shipit:

**Pull request merged**
