### PR TITLE
Fix #24665 and Minor grammatical changes 

### LINKED ISSUE #24665: Bug - Rails Basics - Controller:ln 166: Remove link to SnapChat - Help users avoid Wormhole
Complete the following REQUIRED checkboxes:
-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `Bug - location of bug: brief description of bug` format, e.g. `Bug - React section: Knowledge Checks don't link to resource`

The following checkbox is OPTIONAL:
-   [x] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Bug:**
Avoiding falling into wormholes is hard when starting out.

Linking to SnapChat is an invitation to an infinite, addictive wormhole.

I propose that the link be removed.

**2. How To Reproduce:**
Visit the [controllers section](https://www.theodinproject.com/lessons/ruby-on-rails-controllers) and search `SnapChat`.

**3. Expected Behavior:**
The link shows up... maybe this isn't really a bug... It works as expected.

**4. Desktop/Device:**
Not applicable.

**5. Additional Information:**
The screenshots below tell the story of where the bug is.

This is more of an editorial note... so I hope I'm not annoying you guys. I'd be happy to make a PR fixing this.

Thank you for TOP - It has been a great resource. I'm a big fan.

Screen Shot 2022-09-21 at 11 54 29

Screen Shot 2022-09-21 at 13 48 06

### PR DESCRIPTION
**Pull request by amnindersingh12**
While going through the controllers.md file, I noticed some grammatical errors, so I used Grammarly and LanguageTool to double-check the content. I made a few minor changes to the controllers.md file based on Grammarly's suggestions.

Complete the following REQUIRED checkboxes:

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`

Complete the following checkboxes ONLY IF they are applicable to your PR. You can complete them later if they are not currently applicable:
-   [ ] I have previewed all lesson files included in this PR with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure the Markdown content is formatted correctly
-   [ ] I have ensured all lesson files included in this PR follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

<hr>

**1. Because:**

Closes #XXXXX

**2. This PR:**

**3. Additional Information:**
1. I have addressed this #24665 issue. I have removed the Snapchat link from there to help users to avoid wormhole. 
2. Also, I have fixed some grammatical errors in the `controller.md`.

### CODE REVIEW

**Comment by zachmmeyer** [comment]
I like what Grammarly did here. Unfortunately it didn't seem to catch all the extra spaces.
Do you have any interest in finding and deleting the extra spaces in this lesson? There are quite a few.
Otherwise I'll create an issue for it and assign it to someone else.

**Comment by amnindersingh12** [comment]
> I like what Grammarly did here. Unfortunately it didn't seem to catch all the extra spaces. Do you have any interest in finding and deleting the extra spaces in this lesson? There are quite a few. Otherwise I'll create an issue for it and assign it to someone else.

Sure, I'm happy to fix contribute. I can fix all those extra spaces.

**Comment by zachmmeyer** [comment]
Did something happen with this PR?

**Comment by amnindersingh12** [comment]
Hi @zachmmeyer , I'm closing this PR and will raise another PR to address the issue. 
Thank you

**Pull request closed without merging**
