### PR TITLE
Typo error in for loop explanation. location of change: Problem solving: explanation of for loop.

### PR DESCRIPTION
**Pull request by shonebinu**
The loop is (i <= answer), so shouldn't it be "We want to loop until `i` is equal to `answer`"?

Complete the following REQUIRED checkboxes:

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`

Complete the following checkboxes ONLY IF they are applicable to your PR. You can complete them later if they are not currently applicable:
-   [ ] I have previewed all lesson files included in this PR with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure the Markdown content is formatted correctly
-   [ ] I have ensured all lesson files included in this PR follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

<hr>

**1. Because:**

Closes #XXXXX

**2. This PR:**

**3. Additional Information:**

### CODE REVIEW

**Comment by CouchofTomato** [comment]
Hey @shonebinu 

Thanks for creating a PR. In this case I think the existing terminology is correct. We want the loop to run up to and including until `i` is equal to the answer. For that to happen we need to increase the loop until `i` is greater than `answer` at which point to loop condition fails.

It's a difficult one because I know the point you're trying to make. We want to loop *while* `i` is less than or equal to `answer`, but since we state `until` rather than `while`, and since for loops check the condition first, we want the loop condition check to continue until `i` is higher than `answer` and then break.

It could be that we change the wording to better reflect the point trying to be made. Or that we add some further explanation that because the condition in the loop is evaluated first we need it to run until `i` is higher than `answer` and then break the loop so if you want to consider and take that on let me know. I'll leave this open for if you want to make that change.

**Comment by shonebinu** [comment]
Thank you for your detailed explanation on this topic. Really!

I'm sorry, i wanted to work on this as my first pr.

But I'm only a beginner and English isn't my primary language.

It would be best if it's done by someone else.

**Comment by CouchofTomato** [comment]
Thanks @shonebinu 

Appreciate you letting us know. I'll close this for now. If you want to create an issue for someone to pick up about this then let me know.

**Comment by shonebinu** [comment]
Hi @CouchofTomato 
I just noticed that there isn't any semicolon at the end of 'console.log()' in this chapter (for every console.log(), there isn't any semicolon) https://github.com/TheOdinProject/curriculum/blob/main/foundations/javascript_basics/fundamentals-1.md

Should I make a pr or an issue mentioning this? Should I work on it?
I got the same results without semicolons, but I saw in other resources that it's a good practice to reduce bugs and other insecurities.

I don't want to waste maintainers' time by creating a new pull req / issue. That's why asked. Sorry if it's a stupid thing to ask.

**Pull request closed without merging**
