### PR TITLE
Update project_js_jquery.md

### PR DESCRIPTION
**Pull request by rssatnam**
```
This is a PR template, If you are adding a solution link to the curriculum leave this as is. If you are not, then delete it and write the message you wish.
Thank you,
The Odin Project team.
```

### CODE REVIEW

**Comment by KevinMulhern** [comment]
Hey @raditotev, it looks like your fork is out of date with the curriculum, there should be many more solutions above yours.

**Comment by rssatnam** [comment]
Hello,

Are you talking to me ? Who's @raditotev ?

**Comment by raditotev** [comment]
Hey guys,

I would appreciate if you stop mentioning my name in this conversation ;) I keep getting emails every time. Clearly I've got nothing to do with this pull request.

**Comment by rssatnam** [comment]
OK, I'm updating my fork first, I'm new here, so checking how to update fork repo.

**Comment by KevinMulhern** [comment]
Whoops sorry, It usually goes to the creator of the PR when I type @

**Pull request closed without merging**
