### PR TITLE
Added Jacob Dallaire's solution for google clone

### PR DESCRIPTION
**Pull request by Dallaire**
```
This is a PR template, If you are adding a solution link to the curriculum leave this as is. If you are not, then delete it and write the message you wish.
Thank you,
The Odin Project team.

```

### CODE REVIEW

**Comment by Dallaire** [comment]
Added a commit for the JS project solution

**Comment by arun1595** [comment]
@Dallaire Looks like the stylesheet isn't being loaded in https://dallaire.github.io/google-search-page/

**Comment by Dallaire** [comment]
Took a look and the stylesheet loaded just fine for me on both Firefox and Chrome, as well as mobile.

**Comment by arun1595** [comment]
@Dallaire MY bad. It works fine. Good work :+1:

**Pull request merged**
