### PR TITLE
Solutions added

### PR DESCRIPTION
**Pull request by deedle42**
```
This is a PR template, If you are adding a solution link to the curriculum leave this as is. If you are not, then delete it and write the message you wish.
Thank you,
The Odin Project team.

```

### CODE REVIEW

**Comment by KevinMulhern** [comment]
Hey @deedle42 there seems to be a lot of merge conflict markers in your PR. You can see them here https://github.com/TheOdinProject/curriculum/pull/5122/files

Can you remove those please 😄

**Comment by deedle42** [comment]
I don't know what that means.

**Comment by KevinMulhern** [comment]
Which part?

**Comment by deedle42** [comment]
Merge conflict markers. This is the second time it's happened. I'm not sure
what I'm doing wrong. I've been following the video to get things pushed to
git.

**Comment by KevinMulhern** [comment]
by any chance are you adding your solutions to the files and then pulling in the latest changes from the original curriculum repo?

**Comment by KevinMulhern** [comment]
Closed due to no reply.

**Pull request closed without merging**
