### PR TITLE
Contributing to "installation_overview.md" file in Foundations curriculum

### PR DESCRIPTION
**Pull request by jagritisurabhi**
Added a line in the Additional resources section detailing steps for dual booting a windows system to install Linux

## Because
The installation overview lists three options to create a development environment with Linux OS. There is a link in the description to a video detailing steps to create a virtual box/VM which is option 1, A  suggestive new resource has been added in the Additional resources section talking about steps to cover option 2 as well i.e dual booting a computer which inherently has windows OS on it

## This PR
1. Added new resource in the additional resources section
2. Added a description and a hyperlink to a blog

## Issue
No issue, rather a contribution to the curriculum

## Pull Request Requirements
-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [x] The `Because` section summarizes the reason for this PR
-   [x] The `This PR` section has a bullet point list describing the changes in this PR
-   [x] If this PR addresses an open issue, it is linked in the `Issue` section
-   [x] If any lesson files are included in this PR, they have been previewed with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure it is formatted correctly
-   [x] If any lesson files are included in this PR, they follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

### CODE REVIEW

**Comment by xandora** [comment]
If we're going to add a new guide, I'd prefer that we take the time and replace the guide in the lesson instead. There are a couple issues with the article that I'm not super thrilled about (16GB root directory, really?!).

@jagritisurabhi Could you have a look at the lesson we have in the main lesson content, and see if what you're proposing here would be sufficiently replace the current one?

**Review by xandora — CHANGES_REQUESTED** [review]
See previous comment.

**Comment by thatblindgeye** [comment]
@jagritisurabhi just checking in to see if you've seen the above comment

**Comment by jagritisurabhi** [comment]
@thatblindgeye Apologies for my late reply. The content I have suggested will be an addendum in the Reference section without any change in the existing content. The suggestion has been a good guide in helping understand OS partitioning and it's set up. I think it is sufficient in providing that information to the learners.

**Comment by zachmmeyer** [comment]
Closing in 1 week.

**Pull request closed without merging**
