### PR TITLE
Added my project submission.

### PR DESCRIPTION
**Pull request by dudepare**
```
This is a PR template, If you are adding a solution link to the curriculum leave this as is. If you are not, then delete it and write the message you wish.
Thank you,
The Odin Project team.
```

I'm impressed.

### CODE REVIEW

**Comment by cdouglass** [comment]
@dudepare Could you fix the markdown so the preview link works correctly?

**Comment by dudepare** [comment]
@cdouglass removed the space in between.

**Comment by cdouglass** [comment]
@dudepare Looks good!

**Comment by dudepare** [comment]
Thanks!

**Pull request merged**
