### PR TITLE
adding all changes

### PR DESCRIPTION
**Pull request by kalebleeroy13**
This is a PR template. If you are adding a solution link to the curriculum, leave this as is. If not, delete it and write the message you wish.

Thank you,

The Odin Project team.

### CODE REVIEW

**Comment by 105ron** [comment]
Hi @kalebleeroy13, we don't need the files for your solution to be hosted on our repository, we only need a link to the solution in the correct file. I'll leave this open so you can correct it. If you have problems with how to do this, come and ask us in the general room on the Discord chat. Thanks, Rhys.

**Comment by kalebleeroy13** [comment]
I'm sorry I didn't know how do I submit a link

    On Tuesday, October 8, 2019, 06:00:45 AM EDT, Rhys <notifications@github.com> wrote:  
 
 
Reopened #12580.

**Comment by kalebleeroy13** [comment]
im sorry I don't know how to addd the link

**Comment by 105ron** [comment]
The link will be this https://github.com/kalebleeroy13/google-homepage and the file will be here https://github.com/TheOdinProject/curriculum/blob/master/web_development_101/the_front_end/project_html_css.md . If you are logged in you should be able to see an edit button and edit the file by adding the link in the same format as other student solutions.

**Pull request closed without merging**
