### PR TITLE
Update flexbox-growing-and-shrinking.md

### PR DESCRIPTION
**Pull request by sapienfrom2000s**
## Because
flex-shrink covers the point what happens if parent container is smaller than the sum of flex items. flex grow doesn't cover the complementary case of what happens if parent container is larger than the sum of flex items.

## This PR
Adds content to the lesson.

## Issue

Closes #XXXXX

## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [x] The `Because` section summarizes the reason for this PR
-   [x] The `This PR` section has a bullet point list describing the changes in this PR
-   [x] If this PR addresses an open issue, it is linked in the `Issue` section
-   [x] If any lesson files are included in this PR, they have been previewed with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure it is formatted correctly
-   [x] If any lesson files are included in this PR, they follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

### CODE REVIEW

**Comment by codyloyd** [comment]
I like this inclusion.. but the wording is awkward.  Specifically, this sentence:

> If after resizing parent container grows

can you clean it up?

**Comment by sapienfrom2000s** [comment]
@codyloyd I have made a new commit. Are you okay with it?

**Comment by codyloyd** [comment]
Unfortunately, I think what you've written now has ended up being more confusing.  Consider something like this:



> When the flex-container's main size is larger than the combined main sizes of the flex items, the extra space is distributed among the flex items, with each item growth being their growth factor value as a proportion of the sum total of all the container's items' flex grow factors.

> For example, if there are two items in a flex container, and they both have `flex-grow: 1`, then they will be the same size.  Likewise, if they both have `flex-grow: 2` or `flex-grow: 1000`, then they will be the same size because the proportions are the same.

If, however, one of the items has `flex-grow: 2` and the other has `flex-grow: 1`, then the sizes will be different.  The size of each element will be calculated as a fraction of the total of the various growth-factors among all children.  In this case, we have a `2` and a `1`, so the item with `flex-grow: 2` will be `2/3` the width of the total, and the item with `flex-grow: 1` will be `1/3` of the total.

> This can be difficult to calculate in more complex situations, and it is usually not something you will want to rely on to precisely size specific flex-children.  In real-world usage, the most common situation **by far** is simply using `flex-grow: 1` to make a specific child grow to fill a parent or using `flex-grow: 1` on all children to size them equally.

> For example, if you are using flexbox to position a sidebar on a webpage, you will likely have two main flex-children, the sidebar and the main-content area.  Do not try to use extreme flex-grow proportions to size your sidebar.  Rather, just make the sidebar a static width (200px-300px, or whatever seems logical in your use case) and then put `flex-grow: 1` on the main-content div to make it grow to fill the remaining area.

**Comment by sapienfrom2000s** [comment]
_The "grow factor" also applies when the combined size of all flex items is smaller than their parent container. In that case, the distribution of remaining space among flex items is proportional to the ratio of their flex-grow numbers._
@codyloyd , How about this?

**Pull request closed without merging**
