### PR TITLE
Reorder exercises according to increasing difficulty

### PR DESCRIPTION
**Pull request by MicoPham**
The exercises now goes by increasing difficulty accordingly to Fundamentals 1-4. 

tempConversion (Fundamentals 1 - Operators)
leapYears (Fun1&2 - Math Operators + Conditionals)
sumAll (Fun1&2&4 Math + Conditionals + Iteration)
repeatString (Fun2&4 Conditionals + Iteration)
reverseString (Fun4 ArrayMethods + Iteration)
removeFromArray (Fun3+4)

### CODE REVIEW

**Comment by twalton83** [comment]
Were the provided solutions taken into account for this ordering? And reordering these would also require editing the README for some of these exercises that assume their current order.

**Comment by MicoPham** [comment]
Provided solutions weren't taken into account. But I guess it's fine the way it is. Thank you for the input twalton83.

**Comment by twalton83** [comment]
I'm not unilaterally against the changes, just wanted to make sure it was all taken into account! We can totally discuss this more, I wasn't shooting you down :)

**Comment by MicoPham** [comment]
I mean, after having a good night's sleep, I realized that there are many ways to tackle a problem and some might find certain problems easier than others so maybe it was ordered in that way for a reason. I didn't notice the README's were labeled numerically. Hah

**Pull request closed without merging**
