### PR TITLE
Update project_html_css.md

### PR DESCRIPTION
**Pull request by RazzaFrazza**
Added my Student Solution

### CODE REVIEW

**Comment by craftykate** [comment]
Your second link is not in link form. Please fix your links so they are `[link name](link)` (and with no spaces in between the brackets and parentheses). Thanks!

**Comment by RazzaFrazza** [comment]
Okay. Fixed. Sry.

**Comment by craftykate** [comment]
@RazzaFrazza  I can't get the second link to work. Does it work for you? This is what you gave: http://htmlpreview.github.io/?https://github.com/RazzaFrazza/google-homepage/blob/index.html

**Comment by RazzaFrazza** [comment]
I don't know how I missed that. Fixed it as well.

**Pull request merged**
