### PR TITLE
Added Samantha's Solution to HTML/CSS project

### PR DESCRIPTION
**Pull request by SWFullPotential**
This is a PR template. If you are adding a solution link to the curriculum, leave this as is. If not, delete it and write the message you wish.

Thank you,

The Odin Project team.

### CODE REVIEW

**Comment by 105ron** [comment]
Hi @SWFullPotential,
the file where this project belongs is at https://github.com/TheOdinProject/curriculum/web_development_101/the_front_end/project_html_css.md . Could you please copy and paste the line with your solution to that file please.

**Comment by SWFullPotential** [comment]
Oops! Yes, I’ll do it right away!

**Comment by 105ron** [comment]
:+1:Looks good. It will take up to 24 hours to appear on the website.

**Comment by SWFullPotential** [comment]
Cool! Thanks! 😊

**Pull request merged**
