### PR TITLE
The Cascade: Remove additional resource

### PR DESCRIPTION
**Pull request by nikitarevenco**
## Because

This resource goes into how to install Google Fonts, which [TOP recommends against using in a later lesson](https://www.theodinproject.com/lessons/node-path-intermediate-html-and-css-more-text-styles#fonts). Installing fonts is covered in another lesson

## This PR

- Removes resource that goes into how to install custom fonts

## Issue

Closes #XXXXX

## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [x] The `Because` section summarizes the reason for this PR
-   [x] The `This PR` section has a bullet point list describing the changes in this PR
-   [x] If this PR addresses an open issue, it is linked in the `Issue` section
-   [x] If any lesson files are included in this PR, they have been previewed with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure it is formatted correctly
-   [x] If any lesson files are included in this PR, they follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

### CODE REVIEW

**Comment by ManonLef** [comment]
I’d prefer reconsidering the “strong advisory against using Google fonts” in the other lesson and instead educating people or directing them to an article on how to use them while also being privacy laws compliant. I’d like some team input on this @TheOdinProject/foundations

**Comment by nikitarevenco** [comment]
> I’d prefer reconsidering the “strong advisory against using Google fonts” in the other lesson and instead educating people or directing them to an article on how to use them while also being privacy laws compliant. I’d like some team input on this @TheOdinProject/foundations

Yeah, maybe the wording is a bit too much. Context image:

**Comment by fabulousgk** [comment]
This is something I working on as part of my refactoring of that lesson: https://github.com/TheOdinProject/curriculum/issues/27241#issuecomment-1963076652

**Comment by MaoShizhong** [comment]
Thanks @fabulousgk :rocket:
I'm with @ManonLef on being against the use of "We strongly advise against" and for the alternative suggested.

**Comment by zachmmeyer** [comment]
Is the linter complaining any cause for concern?

**Comment by MaoShizhong** [comment]
I'm personally in favour of removing the additional resource purely as an "it's not really that relevant for this particular lesson" (especially given that the assignment makes a point about doing things without custom fonts yet, and that custom fonts are taught later), and specifically *not* to do with the Google Fonts thing. That side seems to be covered by fabulousgk in their WIP.

If others agree with the additional resource removal, then it won't be an issue to knock out the 3 simple linting errors. I can update my spreadsheet for the accessible links thing too if that gets fixed.

The suggested fix I had noted for that one is to change the link text from
> [Here’s an example] for the CSS color property.

to
> Here’s an example of [the CSS color property].

**Comment by thatblindgeye** [comment]
@MaoShizhong I'm good with the resource removal and with the suggestion regarding the verbiage for the other lesson.

@zachmmeyer In general we want to have any linter errors resolved, but depending on the context of them popping up in PRs we've either been ignoring them or asking users if they want to resolve those errors. If a user is making an update not really related to our style guide I've ignored the errors, if a user is making an update related to the style guide I'll ask.

**Review by MaoShizhong — APPROVED** [review]

**Pull request merged**
