### PR TITLE
Add my solution to HTML/CSS exercise

### PR DESCRIPTION
**Pull request by abdulebens**
This is a PR template. If you are adding a solution link to the curriculum, leave this as is. If not, delete it and write the message you wish.

Thank you,

The Odin Project team.

### CODE REVIEW

**Comment by mindovermiles262** [comment]
Hey @abdulebens 👋

Please remove the space between the opening `*` and `[` . Once done I'll merge this PR. If you have any issues please reach out to us on the discord chat 😃

Thanks, and welcome to TOP

**Comment by mindovermiles262** [comment]
Hey @abdulebens 👋

There shouldn't be a space between the closing `]` and opening `(` in links.

The correct syntax for your link should be the following:

```
Abdu Ebens' solution (Easy)](https://github.com/abdulebens/google-homepage) - [View in Browser](https://abdulebens.github.io/google-homepage/)
```

Please make the necessary changes and I will merge this PR. If you have any questions please reach out to me by `@`ing me or stop by our discord chat.

Thanks and welcome to TOP 😃

**Comment by abdulebens** [comment]
I have made the changes. thanks

**Comment by 105ron** [comment]
It looks like this commit has been deleted. Please redo this PR if you would like your solution on the web site.

**Pull request closed without merging**
