### PR TITLE
Foundations/Setting up Git lesson: suggest adding note to install Guest Additions on VM

### PR DESCRIPTION
**Pull request by donntrenton**
Added note to 2.4 and item in "Additional resources" for guidance on installing Guest Additions for Linux to your VM.

## Because
In "Setting up Git" step 2.4 you need to copy a long SSH key from your VM to host computer, but this is very difficult without shared clipboard. It would be helpful to advise readers to enable the Shared Clipboard feature in their VM; this requires that the VM first have Guest Additions installed.

## This PR
* Added a note in step 2.4 advising that the reader enable the Shared Clipboard feature in the VM and note that Guest Additions must be installed.
* Added an item to "Additional resources" that with links to Oracle VirtualBox documentation and a video demo on YouTube.

## Issue
Not related to any existing open issue.

## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [x] The `Because` section summarizes the reason for this PR
-   [x] The `This PR` section has a bullet point list describing the changes in this PR
-   [ ] If this PR addresses an open issue, it is linked in the `Issue` section
-   [ ] If any lesson files are included in this PR, they have been previewed with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure it is formatted correctly
-   [ ] If any lesson files are included in this PR, they follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

### CODE REVIEW

**Comment by ManonLef** [comment]
I don't have much experience with VM's but shouldn't guest additions already be installed if users follow the [VM install instructions in our lesson](https://www.theodinproject.com/lessons/foundations-installations)?



@TheOdinProject/installations would you mind having a look?

**Comment by xandora** [comment]
@ManonLef Correct, we do mention installing the Guest Additions directly after your screenshot. 

image

Enabling the shared clipboard also goes beyond what we recommend. Users should not be trying to copy anything into or out of their VMs. The advice we give early in the curriculum is to work solely within the VM, maximising it to full screen and "pretending Windows doesn't exist". 

image

**Comment by ManonLef** [comment]
@donntrenton Thanks again for your suggestion/PR! This is however something that is not in line with our recommendations and therefore can't be implemented (see @xandora 's feedback) so I will close it for now.

**Comment by donntrenton** [comment]
Thanks for following up on this. I must have missed the Guest Additions option on installation. Also, I understand the policy of not using the shared clipboard and had intended to follow through with it, until I reached the SSH key. It is just very difficult to copy manually.

**Pull request closed without merging**
