### PR TITLE
add my solution

### PR DESCRIPTION
**Pull request by SamuelLangenfeld**
```
This is a PR template, If you are adding a solution link to the curriculum leave this as is. If you are not, then delete it and write the message you wish.
Thank you,
The Odin Project team.

```

### CODE REVIEW

**Comment by KevinMulhern** [comment]
Hey @SamuelLangenfeld it seems you are trying to add your solution to an outdated version of this file. Are you submitting your pull request through a fork? or editing the file directly on github?

**Comment by SamuelLangenfeld** [comment]
Hi @KevinMulhern, I just edited the file on github. Should I always be submitting pull requests to add solutions, or is editing the file acceptable too? In contributing.md it says that editing the file is the easiest way to go when you're just adding your link.

**Comment by KevinMulhern** [comment]
Yeah editing the file directly on github is fine. Someone must have submitted a solution to the same file at the same time as you. Can you please submit your solution again in another PR? Sorry for an inconvenience.

**Comment by SamuelLangenfeld** [comment]
@KevinMulhern No problem. I just want to say that I really appreciate all of the work you guys put into building and maintaining this program. It's been amazing to have such a great learning resource.

**Comment by KevinMulhern** [comment]
Thanks for the kind words @SamuelLangenfeld 😄

**Pull request closed without merging**
