### PR TITLE
Update project_html_css.md

### PR DESCRIPTION
**Pull request by nayar-ali**

### CODE REVIEW

**Comment by craftykate** [comment]
@nayar-ali You have a formatting issue in your browser link. You have to put the `(easy)` inside the bracket like this: 
`[View in browser(easy)](link)` or else the link won't work right. When you update that I can add your link.
Thanks! Let me know if you need more help.

**Comment by nayar-ali** [comment]
Hi 
sorted it, hope thats better.

**Comment by craftykate** [comment]
I can't get the second link to work. Does this work for you @nayar-ali? http://htmlpreview.github.io/?github.com/nayar-ali/google-homepage/blob/master/Google.html

**Comment by nayar-ali** [comment]
No it doesn't work for me either, i don't know how to get that link i just copied the format of the other submissions which is probably why its not working. how can i get a 'preview in browser link'?

**Comment by craftykate** [comment]
Ohhhh, I get it. Okay, navigate to where your html code is (not the folder or repository, but the actual html file you want to see a preview of, in your case https://github.com/nayar-ali/google-homepage/blob/master/html/index.html) and THEN add the github preview part BEFORE that link (http://htmlpreview.github.io/?). So, the full link will be the two parts together: http://htmlpreview.github.io/?https://github.com/nayar-ali/google-homepage/blob/master/html/index.html. Does that help? Let me know if you have any other questions.

**Comment by nayar-ali** [comment]
done, is that ok? sorry about this...

**Comment by craftykate** [comment]
Yes, perfect! Don't worry, github can seem magical and mystical at first. But you got it! You already got the pull request stuff down, but if you're still a little shaky you can check out this short video showing how to do it for the odin project step by step: bit.ly/odin-solutions

**Pull request merged**
