### PR TITLE
Update project_advanced_building_blocks.md

### PR DESCRIPTION
**Pull request by Sasikala-Ravichandran**

### CODE REVIEW

**Comment by hgducharme** [comment]
Please do not delete the `your solution here...` line, and add yours ABOVE that line. Also, please fix your solutions to match the proper formatting: `[text](link to project)`

**Comment by craftykate** [comment]
I fixed the issues and added by hand. Closing this.

**Comment by Sasikala-Ravichandran** [comment]
Thanks Kate for the extended support.

**Comment by craftykate** [comment]
You're welcome @Sasikala-Ravichandran! Feel free to contact me if you need any further help uploading solutions.

**Pull request closed without merging**
