### PR TITLE
add alternate version for sqlite3

### PR DESCRIPTION
**Pull request by svn1991**
This is a PR template. If you are adding a solution link to the curriculum, leave this as is. If not, delete it and write the message you wish.

Thank you,

The Odin Project team.

### CODE REVIEW

**Comment by I3uckwheat** [comment]
Can you explain why we need this change?

**Comment by svn1991** [comment]
The original sqlite3 version mentioned errored out when I was trying to set up the installation process on Windows. However, after googling and trial and error, the proposed sqlite3 worked. So I thought I should suggest it in case any other users faced this problem.

**Comment by leila-alderman** [comment]
The Odin Project doesn't officially support development on Windows, so I don't think that this an update we need to make. 

If you'd like to work on creating a more complete documentation for how to do all of the installations on Windows along with corrections to any of the Linux commands that may differ for Windows, we're open to that. We'd like to avoid making those additions piecemeal, though, as that could lead to confusion in which directions to follow and whether or not we're actually able to support Windows.

**Comment by codyloyd** [comment]
also.. why are we linking a fork that is less up-to-date than the original.

**Pull request closed without merging**
