### PR TITLE
Motivation and Mindset lesson: removed duplicate Monkeytype mention

### PR DESCRIPTION
**Pull request by MightyOakCoder**
removed duplicate mention of Monkeytype

## Because

Monkeytype is mentioned twice in the additional resources bullet point on typing speed. 

## This PR

- removed the last mention of Monkeytype and added the "and" between [typing.com](https://www.typing.com/), [TypingClub.com](https://www.typingclub.com/)

## Issue

Closes #XXXXX

## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [x] The `Because` section summarizes the reason for this PR
-   [x] The `This PR` section has a bullet point list describing the changes in this PR
-   [ ] If this PR addresses an open issue, it is linked in the `Issue` section
-   [ ] If any lesson files are included in this PR, they have been previewed with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure it is formatted correctly
-   [ ] If any lesson files are included in this PR, they follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

### CODE REVIEW

**Comment by cakegod** [comment]
That was actually supposed to be [Keybr.com](https://www.keybr.com/). A typo when we were inlining the list in this [commit](https://github.com/TheOdinProject/curriculum/commit/f0768c46fcfeb0208f5ce9230642be0238ba0aa9#diff-d0ad3ac4eed9eb119f261b048e5306ddbef0e92a71bad971218d2e5bf40eaf09R180).

**Comment by CouchofTomato** [comment]
@MightyOakCoder Do you want to update the resource as mentioned in the earlier comment?

**Comment by JoshDevHub** [comment]
@MightyOakCoder Just tagging again to check in.

Are you okay adding in the link to [Keybr.com](https://www.keybr.com/)? This was mistakenly removed in the same place that the Monkeytype duplication was added.

**Comment by MightyOakCoder** [comment]
I don't mind updating it, but not sure how to update a PR? I could drop this Pr and submit? Also, what is this "MarkdownLink / Lint lesson files (pull_request) fail? Should ###Motivate really be changed to ###Lesson overview?
Required heading structure
foundations/introduction/motivation_and_mindset.md:7 TOP004/lesson-headings Required heading structure [Expected: ### Lesson overview; Actual: ### Motivation]

**Comment by JoshDevHub** [comment]
> Also, what is this "MarkdownLink / Lint lesson files (pull_request) fail?

No need to worry about this.

> I don't mind updating it, but not sure how to update a PR?

At the top of this PR discussion, you'll see a "Files changed" tab. Click on that tab. In that tab, you should be able to access an "Edit file" button by clicking on the three dots at the top right of the diff view. Quick screenshot of that:
image

Then you can go to line 180 and add the Keybr.com link back in. There should be a green button at the top for committing your changes, which will automatically insert them into this PR.

Let me know if you have any other questions :thumbsup:

**Comment by MaoShizhong** [comment]
Looks like the first MonkeyType mention was removed in #27656 (so current order is `typing.com` -> `TypingClub.com` -> `MonkeyType`).

Is it necessary to include `keybr.com`? As much as I like the site, it doesn't feel all too necessary to have to add back in when we already have 3 good typing sites linked.

**Comment by JoshDevHub** [comment]
Ah dang. Sorry another PR got in ahead of this one :upside_down_face:

And yeah @MaoShizhong we can probably go without `keybr.com`. I'll close this down, but if anyone feels strongly about keeping `keybr.com` in, feel free to make an issue/PR for it.

**Pull request closed without merging**
