### PR TITLE
feat(foundations): add tip about pressing `.` key on GitHub

### PR DESCRIPTION
**Pull request by nikitarevenco**
I recently discovered this and I think it's awesome. I prefer this over using the web github interface. And I think it'll be useful to learners! 😃 

You can even use it on this PR

### CODE REVIEW

**Comment by XAJX179** [comment]
wow :100:

**Review by MaoShizhong — COMMENTED** [review]
I'll leave this open for other maintainers' thoughts.

Personally, I'm not convinced this would provide significant and relevant benefit to this particular lesson or the curriculum as a whole. It's neat, sure, but there are many neat features of GitHub or VSCode or other tools where if we added them to the curriculum just because they're nifty, we'd bloat everything and dilute the actual focus. I don't see this as being important enough to students that they need to know this as part of the curriculum.

**Comment by KevinMulhern** [comment]
I think I agree with @MaoShizhong, we need to be very intentional with anything we add to lessons.
 
How do you see this being useful for learners @nikitarevenco?

**Comment by nikitarevenco** [comment]
> I think I agree with @MaoShizhong, we need to be very intentional with anything we add to lessons.
> 
> How do you see this being useful for learners @nikitarevenco?

Since TOP also gives various other tips e.g. press tab to auto-complete in the command line, I figured that it wouldn't hurt to mention this, but this was just a suggestion I instantly made a PR without an issue since it's a very small change

since you and Mao aren't in favor of this idea though, i'll close it!

**Pull request closed without merging**
