### PR TITLE
Update project_html_css.md

### PR DESCRIPTION
**Pull request by RazzaFrazza**
Added my Solution.

### CODE REVIEW

**Comment by craftykate** [comment]
Your closing bracket on your first link is going in the wrong direction. It's like: `[link name[(link)`. Please fix and I can merge. Thanks!

**Comment by RazzaFrazza** [comment]
Okay no problem. I'll fix it asap. Thanks for the heads up.

**Comment by RazzaFrazza** [comment]
Should be fixed now.  I don't see that in my code. Everything validates.

**Comment by craftykate** [comment]
It's still showing up on my end with the bracket backwards.

**Comment by craftykate** [comment]
I was going to fix it by hand, but the first link (https://github.com/https://github.com/RazzaFrazza/google-homepage) throws a 404. Can you just open a new pull request with the correct link?

**Comment by RazzaFrazza** [comment]
Yeah sorry about that. I didn't understand what you meant at first.

**Pull request closed without merging**
