### PR TITLE
Updating text to something less opinionated

### PR DESCRIPTION
**Pull request by simonkrausgit**
I know many people that care a great deal about where materials for your products are sourced or which persons fabricated this product. But I still really like this metaphor, so I propose a change of this example to something that doesn't trigger as many emotions.
This proposal took me just a few minutes to type up, maybe you agree and help me to come up with a good example.

### CODE REVIEW

**Comment by KevinMulhern** [comment]
I see your point @simonkrausgit, in the same vain many people are opinionated on cars,  are they environmentally friendly, are the parts from the manufacturer reliable, do they meet the most stringent of safety regulations etc. I cant really think of an example that people wont have an opinion on. But really the point of the paragraph isn't to offend anyone, its just to explain what rails is in a metaphor that students can understand. I don't see any problems with leaving it as is but I want know what @eriktrautman and @muzfuz think before we make any decisions.

**Comment by simonkrausgit** [comment]
Thanks for your comment @KevinMulhern. I totally see your point regarding people being opinionated about cars. I tried to make it as neutral as possible and I think it's more neutral than the previous version.

**Comment by nhquiroz** [comment]
I think the metaphor often used on software about these topics is the "black box": you don't know (and you don't care) what happens inside, you only care about the "answers" it gives to your "questions".

**Comment by KevinMulhern** [comment]
I agree with you about it being more neutral @simonkrausgit. @nhquiroz black box could be used too, although I think the car one is more fitting due to the previous paragraph explaining that rails is more convention than configuration. The creators and maintainers of rails choose whats best for developers the same way that car manufacturers choose what they think is best for drivers.

**Comment by eriktrautman** [comment]
I'm fine with the proposed modification though in general in the future I'd prefer to avoid parsing individual paragraphs like this.

**Pull request merged**
