### PR TITLE
Project: Rock Paper Scissors: Change wording of JS link check step

### LINKED ISSUE #28083: Rock Paper Scissors: <Third bullet point in the "Setup the project structure" step should be formulated differently>
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

"Check if webpage includes JavaScript" can be confusing, especially to beginners, seeing it doesn't properly describe what the individual is doing (or supposed to be doing). My suggestion would be to change that into: "Check if JavaScript is linked correctly". 

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-rock-paper-scissors

### (Optional) Discord Name

BakedBeansOnToast

### (Optional) Additional Comments

_No response_

### PR DESCRIPTION
**Pull request by emmahare**
## Because
The third bullet point in the first step in the Assignment section of the [Project: Rock Paper Scissors](https://www.theodinproject.com/lessons/foundations-rock-paper-scissors) lesson, was worded in a way that could lead to confusion: "Check if the webpage includes JavaScript", whilst the user is actually supposed to check if they've linked their JavaScript correctly.

## This PR

- Remove the previous step description, and add new description

## Issue

Closes #28083 

## Pull Request Requirements
-   [x] I have thoroughly read and understand [The Odin Project curriculum contributing guide](https://github.com/TheOdinProject/curriculum/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [x] The `Because` section summarizes the reason for this PR
-   [x] The `This PR` section has a bullet point list describing the changes in this PR
-   [x] If this PR addresses an open issue, it is linked in the `Issue` section
-   [x] If any lesson files are included in this PR, they have been previewed with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure it is formatted correctly
-   [x] If any lesson files are included in this PR, they follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

### CODE REVIEW

**Comment by xandora** [comment]
Thanks for taking the time to raise this issue/PR. I might be totally missing the point here, but what are we actually checking with this step? That JavaScript is working in the browser? That you successfully added a `<script>` tag like earlier suggested? Or is it something else?

Would it be better to say something like, "Within the script tag, add some JavaScript:"?

**Comment by emmahare** [comment]
The step I changed the wording of is actually part of another step: "Setup project structure" which is the first step of the Assignment section in the "Project: Rock Paper Scissors" lesson. Basically, it's telling the user to check whether they've linked their JavaScript correctly, by taking the following steps: 1: write "console.log("Hello World");" in JavaScript, and 2: Check if "Hello World" is logged in the browser console. So the step (I changed) itself, needs to have a description of the fact that the user needs to be checking whether they've linked it correctly.

**Comment by emmahare** [comment]
> Thanks for taking the time to raise this issue/PR. I might be totally missing the point here, but what are we actually checking with this step? That JavaScript is working in the browser? That you successfully added a `<script>` tag like earlier suggested? Or is it something else?
> 
> 
> 
> Would it be better to say something like, "Within the script tag, add some JavaScript:"?

The step I changed the wording of is actually part of another step: "Setup project structure" which is the first step of the Assignment section in the "Project: Rock Paper Scissors" lesson. Basically, it's telling the user to check whether they've linked their JavaScript correctly, by taking the following steps: 1: write "console.log("Hello World");" in JavaScript, and 2: Check if "Hello World" is logged in the browser console. So the step (I changed) itself, needs to have a description of the fact that the user needs to be checking whether they've linked it correctly.

**Review by JoshDevHub — APPROVED** [review]
Seems like a good change to me :rocket:

**Pull request merged**
