### PR TITLE
Objects and Object Constructors: Add two video resources for prototypal inheritance and this

### PR DESCRIPTION
**Pull request by selfdivision**
Added two video resources under assignment for better understanding of Prototypal Inheritance and This. I found these helped me tremendously grasp the concepts even better.

## Because
While the resources under assignment are fine, I found these two videos to provide an excellent explanation of prototypal inheritance and `this`.

## This PR
- Added video under assignment for prototypal inheritance.
- Added video under assignement for `this`.

## Pull Request Requirements
-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [x] The `Because` section summarizes the reason for this PR
-   [x] The `This PR` section has a bullet point list describing the changes in this PR
-   [x] If this PR addresses an open issue, it is linked in the `Issue` section
-   [x] If any lesson files are included in this PR, they have been previewed with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure it is formatted correctly
-   [x] If any lesson files are included in this PR, they follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

### CODE REVIEW

**Comment by thatblindgeye** [comment]
@pappasdev thanks for opening this PR! Is there information in either of these videos you're submitting that aren't really covered in the already existing assignment tasks? Or is it more covering similar information in a different medium (video vs text)?

**Comment by pappasdev** [comment]
> @pappasdev thanks for opening this PR! Is there information in either of these videos you're submitting that aren't really covered in the already existing assignment tasks? Or is it more covering similar information in a different medium (video vs text)?

It is a different medium, but that wasn't the purpose for this PR. I just find that these videos do an excellent job explaining the concepts in this section with many examples of use cases. If not slightly better.

**Comment by thatblindgeye** [comment]
@selfdivision Gotcha. So I'm not sure if these should be added onto the assignment or not. Since they seem more like "nice to view if you need/like to", my gut is that they could be Additional Resources, though we already have a lot there as it is...

Cleaning up Additional Resources is something we'll need to do anyways, so if you'd want to move those videos to that section it's something we can revisit at that time.

**Comment by selfdivision** [comment]
Sounds like a good idea to me. Thanks for looking over my PR.

**Pull request closed without merging**
