### PR TITLE
Update oop-concepts.md

### PR DESCRIPTION
**Pull request by NerdsAreIn**
- [x] You have read [The Odin Projects Contributing Guide](https://github.com/TheOdinProject/curriculum/blob/main/CONTRIBUTING.md).
 - [x] The PR title summarizes the change and where it happened, for example: "Fixes punctuation in Clean Code lesson".
 
#### 1.Describe the changes made and include why they are necessary or important:

Numerous grammatical changes, for the sake of correctness and consistency.  

Deleted some resources that I found confusing, unoriginal and of little value, and substituted them with some new ones. Web Dev Simplified is an excellent YouTube channel and its SOLID videos did more for my understanding than all the other resources put together; I solidly (haha) grasped each principle after watching the corresponding video.

I found some of the language in this lesson confusing or insufficiently explanatory, so did some rephrasing and fleshing out.

In the code examples, I thought it was bad practice to have both the condition within the if clause and the resulting method called "gameOver", so I changed the latter.

#### 2. If this PR is related to an open issue please reference it with the `#` operator and the issue number (and any [relevant keywords](https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests)) below:

#XXXXX

### CODE REVIEW

**Comment by twalton83** [comment]
> Deleted some resources that I found confusing, unoriginal and of little value, and substituted them with some new ones.
I'm hesitant to approve based on personal confusion or subjective view of originality- it would be super helpful if you can expand upon this opinion.

**Comment by NerdsAreIn** [comment]
Hi. Sorry it's taken me so long to respond. 

I actually feel like the first article in the current list isn't great, either. This is not only because, as already noted, it contains a confusingly unfamiliar JQuery example, but also because I don't think that the section on Object Role Stereotypes provides a helpful approach to the Single Responsibility Principle; it makes things more complicated than they need to be. That leaves less than half of the article contributing much to the understanding of the topic, from my point of view. 

As for the third article: where to start... It lacks mastery of basic English spelling, punctuation and grammar. It doesn't even pass the test for basic readability. I mean, this is how the author introduces himself on his blog page: "Hello again, its been a Journey since I wrote my last article back in 2017, it has been a very busy years,..."

The code is a bit of a mess: inconsistent layout and weird spacing, missing semi-colons and other punctuation, Spanish (?) words mixed in, single-letter variables, excessive and unnecessarily complex examples and lots of "// code", which really isn't helpful ... It made me wonder if I was actually reading JavaScript, and I feel I have a decent grip on the language at this stage. Also, weird diversions into factory functions and TypeScript, which unnecessarily complicate matters. 

I know that pretty much anyone can publish to sites like Medium and there seems to be little-to-no quality-checking or proofreading involved, so I would be wary of content from sites like that.

**Comment by twalton83** [comment]
Thanks for the context!

**Comment by I3uckwheat** [comment]
@NerdsAreIn Hey, could you split this PR into two? There's two concepts happening here. Copyedits and link changes.

Having both of these in one PR makes it very difficult to get something merged and reviewed if there's disagreement on either of these concepts.

**Comment by I3uckwheat** [comment]
Closing because of above comment.

**Pull request closed without merging**
