### PR TITLE
Update project_recursion.md

### PR DESCRIPTION
**Pull request by dm-murphy**
This is a PR template. If you are adding a solution link to the curriculum, leave this as is. If not, delete it and write the message you wish.

Thank you,

The Odin Project team.

### CODE REVIEW

**Comment by KevinMulhern** [comment]
Hi @dm-murphy, we are no longer accepting submissions for this project through Github. We just rolled out a new feature which allows you to submit your solution through the website.

It will be at the bottom of the page for this project. Can you use that to submit your project please?

**Comment by dm-murphy** [comment]
Thanks @KevinMulhern 

I just uploaded my merge sort project with the new submission feature. I didn't see a split anymore for submitting merge sort and fibonacci separately. Wasn't sure if you wanted to keep that separation or not. I had already merged my fibonacci project using the old GitHub method before the changes. 

P.S. Thanks for making those Ruby course updates with splitting up OOP and Files/Serialization sections! If I can be of any assistance with reworking/editing the OOP curriculum please let me know. I'd love to help make those lessons more beginner friendly.

**Comment by KevinMulhern** [comment]
> I didn't see a split anymore for submitting merge sort and fibonacci separately.

We can only have one project with submissions per page now unfortunately. I've been splitting larger projects out to their own page but the fibonacci project was too small to be on its own.

> If I can be of any assistance with reworking/editing the OOP curriculum please let me know. I'd love to help make those lessons more beginner friendly.

Thanks @dm-murphy, this is definitely an area I want to work on updating soon. I'll post an announcement about it on discord when we're ready to get started. I'd definitely welcome your help 😄

**Comment by dm-murphy** [comment]
Sounds great @KevinMulhern! Thanks so much for all the work you're doing here!

**Pull request closed without merging**
