### PR TITLE
Form Basics: Corrected the link and provided more accessible, descriptive links

### PR DESCRIPTION
**Pull request by nithindante**
## Because

Links of the mentioned text in our lessons is not sufficiently descriptive to improve accessibility. As per the [layout style guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md#links), link text should both concisely describe its purpose (or where the link will redirect a user), and must not include the words this nor here.  Thus changing the links to make it more descriptive

## This PR

- Changed "But there are many [guides](https://moderncss.dev/pure-css-custom-checkbox-style) out there you can use to achieve your desired design." to  "But there are many guides out there you can use to achieve your desired design, such as this [guide on custom checkbox styling](https://moderncss.dev/pure-css-custom-checkbox-style)."

## Issue

Related to #27819

## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project curriculum contributing guide](https://github.com/TheOdinProject/curriculum/blob/main/CONTRIBUTING.md)
-   [x ] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [x] The `Because` section summarizes the reason for this PR
-   [x] The `This PR` section has a bullet point list describing the changes in this PR
-   [x] If this PR addresses an open issue, it is linked in the `Issue` section
-   [x] If any lesson files are included in this PR, they have been previewed with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure it is formatted correctly
-   [x] If any lesson files are included in this PR, they follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

### CODE REVIEW

**Comment by nithindante** [comment]
I am not entirely sure, if this is the right way, cause this sis my first ever open source contribution

**Review by MaoShizhong — APPROVED** [review]
Great job, @nithindante! Congratulations on your first PR here :rocket:

I've just edited your PR description so that it says `Relation to #XXXXX` as opposed to `Closes #XXXXX`, as this PR is not meant to close that linked issue. If you use the `Closes` keyword, then it'll auto-close the linked issue if this gets merged. If you want this to be the case, then definitely use that keyword. But since we don't want to in this case, we need to just say `Related to`.

Otherwise, all good! :rocket:

**Comment by nithindante** [comment]
ooh thanks for explaining that, Hoping to contribute more

**Comment by MaoShizhong** [comment]
Looking forward to it! :muscle:

**Pull request merged**
