### PR TITLE
Transforms: Reword outdated paragraph

### LINKED ISSUE #27985: Transforms: Reword some paragraphs
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

While reading the lesson about transforms I saw something that could need an improvement:

image
image

The paragraph in the first screenshot(location: Three-dimensional transforms) should be replaced(and/or completely removed) with the paragraph in the second screenshot(location: Matrix) as they conflict with each other - one states you should get comfortable with the specified functions while the other states that you needn't feel comfortable with them. Additionally the first paragraph states that there are many external resources from here on out, but there aren't many external resources until the Assignment section.

But as English is not my first language I may have misunderstood the meanings of these 2 paragraphs so this is just a suggestion.

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-advanced-html-and-css-transforms

### (Optional) Discord Name

_No response_

### (Optional) Additional Comments

_No response_

### PR DESCRIPTION
**Pull request by T0nci**
## Because

Rewords paragraph because it is outdated as it points to links that have been moved/removed.

## This PR

- Rewords paragraph, removing a sentence

## Issue

Closes #27985

## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project curriculum contributing guide](https://github.com/TheOdinProject/curriculum/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [x] The `Because` section summarizes the reason for this PR
-   [x] The `This PR` section has a bullet point list describing the changes in this PR
-   [x] If this PR addresses an open issue, it is linked in the `Issue` section
-   [ ] If any lesson files are included in this PR, they have been previewed with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure it is formatted correctly
-   [ ] If any lesson files are included in this PR, they follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

### CODE REVIEW

**Comment by T0nci** [comment]
@MaoShizhong Codepens aren't able to render in the lesson preview tool right? Since they only appeared as text.

Also am I supposed to also check the last 2 checkboxes in the PR template or are they meant for new lesson files?

**Review by MaoShizhong — APPROVED** [review]
:rocket:

The last 2 checkboxes apply if lesson files are included in the PR at all, not just new files. And yes, embeds don't render in the preview tool because they use `<script>` which are sanitised as a security measure. What you're seeing is essentially the "alt text" for them.

**Comment by T0nci** [comment]
Does MarkdownLint check the layout style aswell? Or does it have to be manually checked?

**Comment by MaoShizhong** [comment]
> Does MarkdownLint check the layout style aswell? Or does it have to be manually checked?

We've set markdownlint's built-ins to match our style guide, and have written custom rules for anything that the built-ins don't cover but should. So everything it reports should be according to our style guide.

**Pull request merged**
