### PR TITLE
Spacing & Windows inclusion

### PR DESCRIPTION
**Pull request by JonMikelV**
Added some missing spaces and minimal Windows commands

```
This is a PR template, If you are adding a solution link to the curriculum leave this as is. If you are not, then delete it and write the message you wish.
Thank you,
The Odin Project team.

```

### CODE REVIEW

**Comment by KevinMulhern** [comment]
Thanks for the pull request, this looks great @JonMikelV 😄 

My only concern is the inclusion of windows commands in the learning outcomes, we don't have any resources in the assignment which covers Windows.

**Comment by JonMikelV** [comment]
Agreed - I didn't realize we were heading into a non-Window zone until I got to the next topic.  Do you want me to edit back out the Windows stuff so only the general fix are in there?

**Comment by KevinMulhern** [comment]
Yeah I think its best to leave it out for now. 

We are planning on introducing tracks later this year, the frontend track won't really require linux so we can have a version of this lesson with windows then.

**Comment by JonMikelV** [comment]
OK - I think I've got the Windows stuff out and committed (sorry, haven't finished the Git course yet).  :-)

**Comment by KevinMulhern** [comment]
No problem, thanks for all your contributions @JonMikelV 😄

**Pull request merged**
