### PR TITLE
Add Personal Solution for Project HTML CSS project

### PR DESCRIPTION
**Pull request by Cthulian**
```
This is a PR template, If you are adding a solution link to the curriculum leave this as is. If you are not, then delete it and write the message you wish.
Thank you,
The Odin Project team.

```

### CODE REVIEW

**Comment by ryanford-frontend** [comment]
Looks good, but you have a typo in the link to your repo:

`https://github.io/cthulian/google-homepage/` 

should be 

`https://github.com/cthulian/google-homepage/`

Can you push another commit with the correction?

**Comment by Cthulian** [comment]
OK commited the updated url!

**Comment by ryanford-frontend** [comment]
Looks like you're getting some practice git experience :laughing: *Unfortunately*, someone snuck another solution between your commits and you have a merge conflict. You pushed your version with the debugging lines for the merge conflict.

```
+<<<<<<< HEAD
+* [Julian Selody's Solution (Easy)](https://github.com/cthulian/google-homepage/) [View in Browser](https://cthulian.github.io/google-homepage/)
+=======
 * [Dima Konoval's Solution (Difficult)(https://github.com/DimaKonoval/google-resultpage) [View in Browser](https://cdn.rawgit.com/DimaKonoval/google-resultpage/66f4cc04/index.html)
 * [Dima Konoval's Solution (Difficult)(https://github.com/DimaKonoval/google-resultpage) [View in Browser](https://cdn.rawgit.com/DimaKonoval/google-resultpage/66f4cc04/index.html)
+>>>>>>> f07e3bd2c510c9cd645b5e1dda6180d8057c5ef4
```

Can you remove those debugging lines and push another commit?

**Comment by Cthulian** [comment]
Phewf, ok much more familiar with merging in git now haha!
I think I've got everything correct now! Let me know if I've done anything wrong.

**Comment by KevinMulhern** [comment]
Looks good to me @Cthulian, thanks for sorting it out 😄

**Pull request merged**
