### PR TITLE
swapped link for "list of term definitions" #1430

### PR DESCRIPTION
**Pull request by lingawakad**
changed the link from the non-working Flatiron School link, to the Viking Code School Prep page.

### CODE REVIEW

**Comment by KevinMulhern** [comment]
Hi @lingawakad, The Flatiron link is working for me.

**Comment by lingawakad** [comment]
Sorry, guess I wasn't specific - the Flatiron page is there, but when you click through to the definitions, that page redirects to a category page http://skillcrush.com/category/blog/resources/tech-term/ .

**Comment by KevinMulhern** [comment]
Thanks @lingawakad.

**Comment by lingawakad** [comment]
Sorry for the confusion

**Pull request merged**
