### PR TITLE
removed 128 expired github links

### PR DESCRIPTION
**Pull request by RolandStuder**
Noticing a lot of expired unavailable github links I took it upon me, to do some cleanup.

This pull request removes 128 "expired" links.
using a little script I put together as an exercise: https://github.com/RolandStuder/link_cleaner_for_odin_project

All removed links were manually checked, I opened all with one command in google chrome.

If this is appreciated, I will gladly to it for the other pages I come across during learning.

List of the removed links, white space separated, so I you want to check you can use 

open -a Google\ Chrome ...

https://github.com/cjsweeten101/OdinProjects/blob/master/ruby-building-blocks/caesar_cipher.rb https://github.com/holdercp/ruby-building-blocks/blob/master/caesar_cipher.rb https://github.com/mindovermiles262/ruby-building-blocks/tree/master/caesar-cipher https://github.com/NicolayD/ruby-building-blocks/blob/master/caesar_cipher.rb https://github.com/ToTenMilan/the_odin_project/blob/master/ruby/building_blocks/caesar_cipher.rb https://github.com/joeyzaozaoli/the_odin_project/blob/master/caesar_cipher.rb https://github.com/neekburm/odinproject/blob/master/caesar_cypher.rb https://github.com/muzfuz/CodeLessons/blob/master/RubyBuildingBlocks/caesar.rb https://github.com/treiff/odin-project-ruby/blob/master/cipher.rb https://github.com/thurst306/the_odin_projects/blob/master/caesar_cipher.rb https://github.com/Hawkeye000/Odin-Building-Blocks/blob/master/caesar.rb https://github.com/wingyu/ruby_building_blocks/blob/master/caesar.rb https://github.com/hiendinhngoc/TheOdinProject/blob/master/ceasar_cipher.rb https://github.com/ttravers17/the_odin_project/blob/master/ruby_building_blocks/project1/caesar_cipher.rb https://github.com/sami/ruby-building-blocks/blob/master/caesar_cipher.rb https://github.com/cvorak/ruby_project_caesar_cypher/blob/master/caesar_cypher.rb https://github.com/poctek/CaesarCipher_TheOdinProject/blob/master/CaesarCipher.rb https://github.com/gregoryjpark/ruby_building_blocks/blob/master/caesar_cipher.rb https://github.com/Concretechris/ceaser_cipher/blob/master/ceasercipher/Ceaser_Cipher.rb https://github.com/antrix1/The-Odin-Project/blob/master/Ruby%20Programming/Caesar%27s%20cipher/caesar_cipher.rb https://github.com/EdmundLeex/ruby_algorithm_practice/blob/master/some_fun_challeges/stock_picker.rb https://github.com/salexzee/TOProject/blob/master/caesar_cipher/caesar.rb https://github.com/varvara15/The_Odin_Project/blob/master/Caesar_Cipher.rb https://github.com/TwiddleStick/Ruby-Playground/blob/master/Caesar_Cipher/caesar_cipher.rb https://github.com/xreid/ruby_building_blocks/blob/master/caesar_cipher.rb https://github.com/PiotrAleksander/Ruby/blob/master/szyfr_cezara.rb https://github.com/tadeve96/ruby_programming_odin/blob/master/ceaser_cipher.rb https://github.com/sanora/Ruby-Building-Blocks/blob/master/Caesar%20Cipher/caesar_cipher.rb https://github.com/larson004/the-odin-project/blob/master/Chap-03-Advanced-Ruby/Ruby_building_blocks/ceasar.rb https://github.com/jsymons/the-odin-project/blob/master/ruby-building-blocks/caesar_cipher.rb https://github.com/ashleymichal/the_odin_project/blob/master/the-odin-project/ruby/caesar-1.rb https://github.com/AdManteza/CaesarCipher/blob/master/CaesarCipher.rb https://github.com/navies/learnding-ruby/blob/master/The%20Odin%20Project/Projects:%20Ruby%20Building%20Blocks/project_building_blocks.rb https://github.com/kennyfrc/toy_programs/blob/master/caesar_cipher.rb https://github.com/mbarts/caesar_cipher/blob/master/caesar_cipher.rb https://github.com/OlehZiniak/ruby_bb/blob/master/caesar_cipher.rb https://github.com/dvislearning/caesar_cipher/blob/master/cipher.rb https://github.com/johnTheDudeMan/the_odin_project/blob/master/building_blocks/caesar_cipher.rb https://github.com/bcontant/the_odin_project/blob/master/caesar_cipher/caesar.rb https://github.com/TriKit/caesar_cipher https://github.com/j-campbell/ruby-building-blocks/blob/master/caesar.rb https://github.com/tholymap/Caesar-Cipher/blob/master/Caesar_cipher.rb https://github.com/emo1/ruby-building-blocks/blob/master/ceasar_cipher.rb https://github.com/leosoaivan/rubybuildingblocks/blob/master/caesarcipher.rb https://github.com/neelotpal97/learning_programming/blob/master/Projects/Caesar%20Cipher/Caesar_Cipher.rb https://github.com/exosty/the-odin-project/blob/master/3-ruby-programming/basic-ruby/building-blocks/caesar_cipher.rb https://github.com/austinsley/misc/blob/master/ruby-building-blocks/caesar.rb https://github.com/SimonSomlai/Odin/blob/master/ruby/cypher.rb https://github.com/evanburkey/odinproject/blob/master/rubyProjects/caesar_cipher.rb https://github.com/Cypher0/ruby-building-blocks/blob/master/caesar.rb https://github.com/zacharyvacek/caesar_cipher/blob/master/cipher.rb https://github.com/nmacawile/ruby_building_blocks/blob/master/caesar_cipher.rb https://github.com/cjsweeten101/OdinProjects/blob/master/ruby-building-blocks/stock_picker.rb https://github.com/holdercp/ruby-building-blocks/blob/master/stock_picker.rb https://github.com/NicolayD/ruby-building-blocks/blob/master/stock_picker.rb https://github.com/ToTenMilan/the_odin_project/blob/master/ruby/building_blocks/stock_picker.rb https://github.com/muzfuz/CodeLessons/blob/master/RubyBuildingBlocks/stock_picker.rb https://github.com/treiff/odin-project-ruby/blob/master/stock_picker.rb https://github.com/thurst306/the_odin_projects/blob/master/stock_picker.rb https://github.com/Hawkeye000/Odin-Building-Blocks/blob/master/stock_picker.rb https://github.com/wingyu/ruby_building_blocks/blob/master/stock.rb https://github.com/hiendinhngoc/TheOdinProject/blob/master/stock_picker.rb https://github.com/ttravers17/the_odin_project/blob/master/ruby_building_blocks/project2/stock_picker.rb https://github.com/sami/ruby-building-blocks/blob/master/stock_picker.rb https://github.com/cvorak/ruby_project_caesar_cypher/blob/master/stock_picker.rb https://github.com/poctek/stock_picker_the_odin_project/blob/master/stockPicker.rb https://github.com/gregoryjpark/ruby_building_blocks/blob/master/stock_picker.rb https://github.com/salexzee/TOProject/blob/master/stock/stock.rb https://github.com/varvara15/The_Odin_Project/blob/master/Stock_Picker.rb https://github.com/tadeve96/ruby_programming_odin/blob/master/stock.rb https://github.com/sanora/Ruby-Building-Blocks/tree/master/Stock%20Picker https://github.com/larson004/the-odin-project/blob/master/Chap-03-Advanced-Ruby/Ruby_building_blocks/stockpicker.rb https://github.com/jsymons/the-odin-project/blob/master/ruby-building-blocks/stock_picker.rb https://github.com/ashleymichal/the_odin_project/blob/master/the-odin-project/ruby/stock_picker.rb https://github.com/AdManteza/StockPicker/blob/master/stockpicker.rb https://github.com/navies/learnding-ruby/blob/master/The%20Odin%20Project/Projects:%20Ruby%20Building%20Blocks/project_building_blocks.rb https://github.com/pilauPro/caesar_cipher/blob/master/caesar_cipher.rb https://github.com/OlehZiniak/ruby_bb/blob/master/stock_picker.rb https://github.com/mbarts/stock_picker/blob/master/stock_picker.rb https://github.com/johnTheDudeMan/the_odin_project/blob/master/building_blocks/stock_picker.rb https://github.com/j-campbell/ruby-building-blocks/blob/master/stock.rb https://github.com/emo1/ruby-building-blocks/blob/master/stock_picker.rb https://github.com/leosoaivan/rubybuildingblocks/blob/master/stockpicker.rb https://github.com/exosty/the-odin-project/blob/master/3-ruby-programming/basic-ruby/building-blocks/stock_picker.rb https://github.com/austinsley/misc/blob/master/ruby-building-blocks/stock_picker.rb https://github.com/SimonSomlai/Odin/blob/master/ruby/stock_picker.rb https://github.com/cloudtemplar/odin_ruby_projects/blob/master/stock-picker/stock_picker.rb https://github.com/evanburkey/odinproject/blob/master/rubyProjects/stock_picker.rb https://github.com/Cypher0/ruby-building-blocks/blob/master/stock_picker.rb https://github.com/nmacawile/ruby_building_blocks/blob/master/stock_picker.rb https://github.com/cjsweeten101/OdinProjects/blob/master/ruby-building-blocks/substrings.rb https://github.com/holdercp/ruby-building-blocks/blob/master/substring.rb https://github.com/NicolayD/ruby-building-blocks/blob/master/substrings.rb https://github.com/ToTenMilan/the_odin_project/blob/master/ruby/building_blocks/substrings.rb https://github.com/muzfuz/CodeLessons/blob/master/RubyBuildingBlocks/substrings.rb https://github.com/treiff/odin-project-ruby/blob/master/substrings.rb https://github.com/lightcast/the_odin_project/blob/master/sub_strings.rb https://github.com/Hawkeye000/Odin-Building-Blocks/blob/master/substrings.rb https://github.com/wingyu/ruby_building_blocks/blob/master/substrings.rb https://github.com/hiendinhngoc/TheOdinProject/blob/master/substrings.rb https://github.com/ttravers17/the_odin_project/blob/master/ruby_building_blocks/project3/substrings.rb https://github.com/sami/ruby-building-blocks/blob/master/substrings.rb https://github.com/cvorak/ruby_project_caesar_cypher/blob/master/substrings.rb https://github.com/poctek/Occurances_The_Odin_Project https://github.com/gregoryjpark/ruby_building_blocks/blob/master/substrings.rb https://github.com/Concretechris/odin---substring_challenge/blob/master/substrings.rb https://github.com/salexzee/TOProject/blob/master/substrings/sub.rb https://github.com/varvara15/The_Odin_Project/blob/master/Substrings.rb https://github.com/tadeve96/ruby_programming_odin/blob/master/dict.rb https://github.com/sanora/Ruby-Building-Blocks/tree/master/Substrings https://github.com/larson004/the-odin-project/blob/master/Chap-03-Advanced-Ruby/Ruby_building_blocks/substrings.rb https://github.com/jsymons/the-odin-project/blob/master/ruby-building-blocks/substrings.rb https://github.com/ashleymichal/the_odin_project/blob/master/the-odin-project/ruby/substrings.rb https://github.com/AdManteza/SubString/blob/master/SubString.rb https://github.com/navies/learnding-ruby/blob/master/The%20Odin%20Project/Projects:%20Ruby%20Building%20Blocks/project_building_blocks.rb https://github.com/OlehZiniak/ruby_bb/blob/master/substrings.rb https://github.com/mbarts/substrings/blob/master/substrings.rb https://github.com/johnTheDudeMan/the_odin_project/blob/master/building_blocks/substrings.rb https://github.com/j-campbell/ruby-building-blocks/blob/master/substrings.rb https://github.com/emo1/ruby-building-blocks/blob/master/substrings.rb https://github.com/leosoaivan/rubybuildingblocks/blob/master/substrings.rb https://github.com/chrisgchambers/ruby_exercies/blob/master/caesar_cipher/program.rb https://github.com/exosty/the-odin-project/blob/master/3-ruby-programming/basic-ruby/building-blocks/substrings.rb https://github.com/austinsley/misc/blob/master/ruby-building-blocks/substrings.rb https://github.com/SimonSomlai/Odin/blob/master/ruby/splitter.rb https://github.com/evanburkey/odinproject/blob/master/rubyProjects/substrings.rb https://github.com/Cypher0/ruby-building-blocks/blob/master/substrings.rb https://github.com/nmacawile/ruby_building_blocks/blob/master/substrings.rb

### CODE REVIEW

**Comment by 105ron** [comment]
This looks like a good idea @RolandStuder . Good idea, I'll leave it to @KevinMulhern to review. It would be good to have a clean up...

**Comment by KevinMulhern** [comment]
Thank You for this @RolandStuder, we will soon be rolling out a feature to allow students to upload their solution to the main site instead of adding it to a lesson page directly as a part of that roll out we will have to remove the student solutions from the lesson files.

With all that in mind, I wouldn't want you going to all the effort of cleaning up all the broken solution links when they will be removed soon.

**Comment by RolandStuder** [comment]
@KevinMulhern Ok, I understand. It was a really good exercise for me, to automate the process 😄
 
> we will have to remove the student solutions from the lesson files

So for a time, some lessons might not have any solutions? Especially in the later stages like the final project that might be a big loss. I would recommend at least linking to the old list or otherwise make sure, there are a few examples available.

**Comment by KevinMulhern** [comment]
@RolandStuder you raise a excellent point about the later stages. Your suggestion for linking to the old list sounds like a really good solution, thank you so much for your input on this 😄

**Pull request merged**
