### PR TITLE
Node Battleships: Remove mobile device reference

### LINKED ISSUE #27752: Battleship: Responsive design in extra credit
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

In the extra credit section, it states you can make a two player mode, with a pass over screen, but more importantly, "Make sure the game is playable on a mobile screen". However Battleships is before Advanced HTML/CSS where the concepts required to do this effectively are taught. This runs against much of the rhetoric of trusting the process and the order things are laid out in

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-javascript-battleship

### (Optional) Discord Name

_No response_

### (Optional) Additional Comments

_No response_

### PR DESCRIPTION
**Pull request by damon314159**
## Because
The project suggests users should implement a mobile friendly design even though this sits before the lessons on responsive design.

## This PR
Alters that section to specify laptops instead

## Issue

Closes #27752

## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [x] The `Because` section summarizes the reason for this PR
-   [x] The `This PR` section has a bullet point list describing the changes in this PR
-   [x] If this PR addresses an open issue, it is linked in the `Issue` section
-   [x] If any lesson files are included in this PR, they have been previewed with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure it is formatted correctly
-   [x] If any lesson files are included in this PR, they follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

### CODE REVIEW

**Review by MaoShizhong — COMMENTED** [review]
While we're at it, what do you think about converting the whole list to an unordered list (and making the nesting list item just a part of its parent item as a second sentence)?

An ordered list to me implies sequential progression, which can be taken to mean "do all preceding if you wish to do step 2 or 3", even with the last sentence (which I don't like the wording of, as it kinda implies doing 0 isn't an option) which I feel we can omit too.

e.g. 
```
Make your battleship project more impressive by introducing any of these modifications.

- Implement drag and drop to allow players to place their ships.
- Create a 2-player option that lets users take turns by passing the laptop back and forth, or by spinning the monitor around on a desktop. Implement a 'pass device' screen so that players don't see each others boards!
- Polish the intelligence of the computer player by having it try adjacent slots after getting a 'hit'.
```

**Comment by damon314159** [comment]
I think it's fair to take out the inner list, but I see the ordering differently. 
Like "here's a list of features, in order, that would make the experience more rounded. Keep going until you're bored of it"
IMO it makes sense to polish the placement before worrying about how smart the computer moves are for example

**Comment by MaoShizhong** [comment]
I'm not too sure that implementing drag&drop will always make more sense to do before considering the computer intelligence. I think one can implement a very polished non-drag&drop placement system (since the spec is loose on that) so that it'd be perfectly reasonable to want to improve computer intelligence without wanting to implement an additional placement method.
i.e. I'm don't really think any one of those individual features makes more sense to need to be after any other feature.

**Comment by damon314159** [comment]
Alrighty then, unordered it is :)

**Review by MaoShizhong — COMMENTED** [review]
Mind also amending line 41 as per the above, and removing line 47? Thanks for cooperating with my nit-ness XD

**Review by MaoShizhong — APPROVED** [review]
Force pushing :eyes: 
Thanks for doing this! :rocket:

**Comment by damon314159** [comment]
They get squashed anyways, not too fussed about pushing over patches

**Pull request merged**
