### PR TITLE
Foundations/CSS Foundations: Update lists per layout style guide

### PR DESCRIPTION
**Pull request by rosecodez**
## Because

- This PR changes [cascade lesson](https://www.theodinproject.com/lessons/foundations-the-cascade) `lists` according to TOP layout style.
## This PR

- Change list items to lazy numbering.

## Issue

Related to #27118

## Additional Information

- All list items already start with a hyphen `-`.
- All list items already have only a single space before it.
- Capitalization and end punctuation well applied already.
## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [x] The `Because` section summarizes the reason for this PR
-   [x] The `This PR` section has a bullet point list describing the changes in this PR
-   [x] If this PR addresses an open issue, it is linked in the `Issue` section
-   [x] If any lesson files are included in this PR, they have been previewed with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure it is formatted correctly
-   [x] If any lesson files are included in this PR, they follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

### CODE REVIEW

**Review by thatblindgeye — COMMENTED** [review]
Thanks for the updates! Would you mind also fixing the listed errors regarding the code blocks? It should just require adding a blank line between a couple of codeblocks that are one after the other. So instead of:

~~~
```html
  ...code
```
```css
  ...code
```
~~~

We want:


~~~
```html
  ...code
```
[this should be an empty/blank line, just putting text to make it stand out]
```css
  ...code
```
~~~

**Comment by rosecodez** [comment]
> Thanks for the updates! Would you mind also fixing the listed errors regarding the code blocks? It should just require adding a blank line between a couple of codeblocks that are one after the other. So instead of:
> 
> ```
> ```html
>   ...code
> ```
> ```css
>   ...code
> ```
> ```
> 
> We want:
> 
> ```
> ```html
>   ...code
> ```
> [this should be an empty/blank line, just putting text to make it stand out]
> ```css
>   ...code
> ```
> ```

Thank you for the tip!

**Comment by rosecodez** [comment]
Thank you for the tip!

**Review by thatblindgeye — APPROVED** [review]
Thanks for making those updates. And re: that little red x, yep! If the build fails there'll be that red x as well as the list of checks that ran at the bottom of the PR, which you can usually view more details for any failures (such as what/where the failure(s) came from, though in this case you can just view the "Files changed" tab for the same info).

**Pull request merged**
