### PR TITLE
Add student solution

### PR DESCRIPTION
**Pull request by AlmirBunjaku**
This is a PR template. If you are adding a solution link to the curriculum, leave this as is. If not, delete it and write the message you wish.

Thank you,

The Odin Project team.

### CODE REVIEW

**Comment by miawallace83** [comment]
https://miawallace83.github.io/google-homepage/

https://github.com/miawallace83/google-homepage.git

**Comment by AlmirBunjaku** [comment]
miawallace83, I'm pretty sure you just commented your solution, instead of making your own pull request. To do that, you need to [open this link](https://github.com/TheOdinProject/curriculum/blob/master/web_development_101/the_front_end/project_html_css.md) and follow these steps:

- Click on the pen in the top right corner to edit the file
- Add your links to the bottom of the "Student solutions" section (follow the same format as the rest. You can just copy-paste one of them and replace the links and text with your own).
- Click on the "Propose changes" button at the bottom.
- After that, just confirm you want to Create a pull request.

After some time, usually a couple of hours, you'll get a reply that your request was merged successfully.

**Comment by marvingay** [comment]
@AlmirBunjaku  Thank you 👍

**Comment by miawallace83** [comment]
Thanks You!
________________________________

**Pull request merged**
