### PR TITLE
Scrimba embed branch

### PR DESCRIPTION
**Pull request by michaella23**
## Because

Interactive embeds from [Scrimba](https://www.scrimba.com) for JavaScript section.

## This PR

- Added [Objects and Constructors](https://scrimba.com/scrim/co2624f87981575448091d5a2) scrim to Objects and Object constructors lesson.
- Added [Factory Functions](https://scrimba.com/scrim/c2aaKzcV) scrim to Factory Functions & Module Pattern lesson.
- Added [Asynchronous code](https://scrimba.com/scrim/cof4e4fb797a2d0a236ea38ce) scrim to Asynchronous Code lesson.
- Added [Async & Await](https://scrimba.com/scrim/crd4eMc6) scrim to Async and Await lesson.

## Issue

Closes #XXXXX

## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [x] The `Because` section summarizes the reason for this PR
-   [x] The `This PR` section has a bullet point list describing the changes in this PR
-   [x] If this PR addresses an open issue, it is linked in the `Issue` section
-   [x] If any lesson files are included in this PR, they have been previewed with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure it is formatted correctly
-   [x] If any lesson files are included in this PR, they follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

### CODE REVIEW

**Comment by michaella23** [comment]
I am sending this pull request on behalf of Per Borgen at [Scrimba](https://www.scrimba.com). He did not mention that I should create an issue, as I believe he had already had discussions with someone on the team about these contributions. Thank you.

**Comment by perborgen** [comment]
Thanks a lot @michaella23, this looks good!

**Review by LeoKirasic — APPROVED** [review]
Really well done, thanks!

**Comment by michaella23** [comment]
Happy to contribute! Thank you!

**Pull request merged**
