### PR TITLE
Steps for euler problem 1

### PR DESCRIPTION
**Pull request by kriox26**
@KevinMulhern @csrail what do you think?

### CODE REVIEW

**Comment by KevinMulhern** [comment]
Much better, 👍 from me

**Comment by grzegorzzajac1989** [comment]
image

**Comment by kriox26** [comment]
Ready to merge then? @KevinMulhern

**Comment by KevinMulhern** [comment]
Hey @kriox26, yeah it is ready to merge. Sorry, I thought you were doing the same thing on the ruby lesson. That's why I didn't merge it straight away 😄

**Comment by kriox26** [comment]
Haha, actually I am. But I'm gonna do it on a different PR 👍

**Comment by KevinMulhern** [comment]
No worries 👍

**Pull request merged**
