### PR TITLE
Javascript Fundamental Part 1  : add a stackoverflow link in additional resources

### PR DESCRIPTION
**Pull request by Tribhuwan-Joshi**
stackoverflow answer on "What's the difference between "let" and "var" ?

Complete the following REQUIRED checkboxes:

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`

Complete the following checkboxes ONLY IF they are applicable to your PR. You can complete them later if they are not currently applicable:
-   [x] I have previewed all lesson files included in this PR with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure the Markdown content is formatted correctly
-   [x] I have ensured all lesson files included in this PR follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

<hr>

**1. Because:**

Closes #XXXXX

**2. This PR:**

**3. Additional Information:**

### CODE REVIEW

**Review by rustyxlol — COMMENTED** [review]
Link seems to be missing, please add the link and this should be good to go. :)

**Comment by wise-king-sullyman** [comment]
> and this should be good to go

@rustyxlol thank you for pointing out that the link is missing, but statements like the above can cause people to believe that you represent the maintainer team. Please be considerate of that in the future and refrain from such statements to prevent confusion.

**Comment by rustyxlol** [comment]
Sincerest apologies. Will be mindful :)

**Comment by Tribhuwan-Joshi** [comment]
> Link seems to be missing, please add the link and this should be good to go. :)

Thank you for pointing it out.

**Comment by wise-king-sullyman** [comment]
@Tribhuwan-Joshi rather than adding this resource to fundamentals one we think it would fit better as an additional resource in the fundamentals three lesson. We also think the current hackernoon resource on the fundamentals one lesson should be completely removed at the same time as your new resources covers the same material much more succinctly.

Would you like to make those changes?

**Comment by Tribhuwan-Joshi** [comment]
@wise-king-sullyman  ok I will do that.  I am new to open source , don't mind if its sounds a childhish question ,should I open a new pr for that ?

**Comment by wise-king-sullyman** [comment]
Closing this PR since you opened a new one 🙂

**Pull request closed without merging**
