### PR TITLE
Adding project to the odin project webpage

### PR DESCRIPTION
**Pull request by DylanJamesMaloney**
This is a PR template. If you are adding a solution link to the curriculum, leave this as is. If not, delete it and write the message you wish.

Thank you,

The Odin Project team.

### CODE REVIEW

**Comment by leila-alderman** [comment]
Congratulations! You're pull request #10000!

The second link here for "View in Browser" is supposed to be a link to actually view your project. You can set that up easily using GitHub Pages and the first set of [instructions here](https://towardsdatascience.com/how-to-create-a-free-github-pages-website-53743d7524e1).

**Comment by leila-alderman** [comment]
You need to do more than just add a forward slash to the URL. Look at the link for "View in Browser" for the solution right after yours. Do you see how it looks different and how it takes you directly to seeing their finished project in the browser? Right now, you just have two links that both show your GitHub repository instead one to your repo and one to your finished product.

**Comment by DylanJamesMaloney** [comment]
Hi Leila, thanks for helping! I first sent the pull request and was in and out of the house for a bit.  I reazlize now what I was doing wrong, and set my github to publish the page.  Hopefully it is working now,

**Comment by DylanJamesMaloney** [comment]
I'm very new to this, so sometimes those little details are perplexing.  Just to check, the forward slash is required on the link so it opens the containing html?

**Comment by 105ron** [comment]
It works fine for me.. Merged 😃

**Pull request merged**
