### PR TITLE
Update project_final_js.md

### PR DESCRIPTION
**Pull request by davidchappy**
I'm asking to add as my final Odin project something that departs a little from the stated instructions. It's not a remake of my favorite site, but is a web app I built on Rails and ReactJS for scheduling lessons, so it definitely incorporates the skills I've learned from completing (98%) the Odin Project. It was mostly a personal project, so I thought it may qualify. I'd like to finish the entire Odin curriculum but not sure I have time to do a site remake at this point. But I understand if this doesn't qualify.:)

### CODE REVIEW

**Comment by davidchappy** [comment]
Just noticed a typo in my last submission - final parentheses needs to be added to the 2nd link (view in browser). My apologies.

**Comment by codyloyd** [comment]
dude... that's pretty slick.  don't see why we can't add it.

**Comment by davidchappy** [comment]
Great—thanks!

**Comment by KevinMulhern** [comment]
Great work @davidchappy 😄

**Comment by davidchappy** [comment]
Thanks!

**Pull request merged**
