### PR TITLE
Flexbox Axes: Update resource

### PR DESCRIPTION
**Pull request by i4pg**
## Because

To enhance the learning experience, it is advantageous to switch the placement of resources. The old resource, a cheat sheet encompassing all Flex-box properties, is better suited for the final lesson before the project. Meanwhile, the new resource, originally intended for the next lesson, has been moved here, allowing for a more detailed examination of the concepts discussed in the current lesson on "flex-box axes".

## This PR

- Move Flex-box cheat sheet resource to the next lesson
- Move MDN resource from the next lesson to this lesson

## Issue

Related to #25494

## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [x] The `Because` section summarizes the reason for this PR
-   [x] The `This PR` section has a bullet point list describing the changes in this PR
-   [x] If this PR addresses an open issue, it is linked in the `Issue` section
-   [x] If any lesson files are included in this PR, they have been previewed with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure it is formatted correctly
-   [x] If any lesson files are included in this PR, they follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

### CODE REVIEW

**Comment by rlmoser99** [comment]
Thank you for taking the time to update this lesson, but this new resource does not belong in this lesson. It goes over way more information than I think is needed in this lesson, even as an additional resource.

**Comment by i4pg** [comment]
> Thank you for taking the time to update this lesson, but this new resource does not belong in this lesson. It goes over way more information than I think is needed in this lesson, even as an additional resource.

Hey @rlmoser99 do you mind telling me why you think it's over way more information ? Is it because of last section? Thank you

**Comment by i4pg** [comment]
> Thank you for taking the time to update this lesson, but this new resource does not belong in this lesson. It goes over way more information than I think is needed in this lesson, even as an additional resource.

Hey @rlmoser99, could you please share your thoughts on why you think there is an excessive amount of information in this PR? Is it because of the additional alignment information it includes, particularly the last section?

**Comment by rlmoser99** [comment]
@i4pg Your reasoning for removing the cheat sheet was that it belongs in the last lesson, to me applies to this resource even more. And yes it going over the alignment information means that it fits better where it is.

**Comment by i4pg** [comment]
> @i4pg Your reasoning for removing the cheat sheet was that it belongs in the last lesson, to me applies to this resource even more. And yes it going over the alignment information means that it fits better where it is.

Understood. I had the impression that the Alignment section primarily addresses 10% to 20% of the content, with the remaining portion focused on the concepts related to Flex-box Axes. Additionally, I believed it would be more appropriate for the comprehensive guide on Flex-box properties to be presented in the final lesson of the course. However, I acknowledge your expertise in this matter, and I have complete confidence in accepting your decision to close my pull request. Thank you for your assistance regardless.

**Pull request closed without merging**
