### PR TITLE
Add clarifications to step 11 for installing guest additions

### PR DESCRIPTION
**Pull request by FriskySaga**
- [X] You have read [The Odin Projects Contributing Guide](https://github.com/TheOdinProject/curriculum/blob/master/CONTRIBUTING.md).

#### 1.Describe the changes made:

I updated step 11 for installing and enabling guest additions to be more clear. When I was following the guide, I initially found myself confused because I failed to recognize that to find the CD icon on the VM desktop, that meant I would need to literally navigate to the desktop folder.

#### 2. If this PR is related to an open issue please reference it with the `#` operator and the issue number below:

#22176

### CODE REVIEW

**Review by xandora — APPROVED** [review]
Looks good to me, I think we can accept this with a minor change:

Most of the time the File Explorer window should pop up on top, perhaps just reword this slightly to say "in case the CD folder *doesn't* open, [go looking for it this way]".

**Review by xandora — COMMENTED** [review]
whoops, please ignore.

**Comment by FriskySaga** [comment]
> Looks good to me, I think we can accept this with a minor change:
>
> Most of the time the File Explorer window should pop up on top, perhaps just reword this slightly to say "in case the CD folder _doesn't_ open, [go looking for it this way]".

I took your suggestion to reword step 11.

I interpreted the suggestion to mean to write the "common case" first, meaning: "Hey user, if you see a File Manager window, then you're good."

Then I wrote the "plan B" case last, which is: "But hey, if you don't see a File Manager window, then go to the desktop."

Please review my updated code changes to see if I correctly understood the intent of your suggestion.

**Review by xandora — APPROVED** [review]
You nailed it. Looks good, approved.

**Pull request merged**
