### PR TITLE
Using Git in the Real World: Fix step 5 in "Ongoing workflow"

### LINKED ISSUE #27976: Using Git in the Real World: Fix step 5 in "Ongoing workflow"
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

A lesson is misreferenced in step 5 in "Ongoing workflow". The learner doesn't encounter how to fix merge conflicts until the next lesson - "Working with Remotes" in the Assignment section.

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/javascript-using-git-in-the-real-world

### (Optional) Discord Name

_No response_

### (Optional) Additional Comments

_No response_

### PR DESCRIPTION
**Pull request by T0nci**
## Because

It points the user to the right lesson when needing to reference material connected to merge conflicts.

## This PR

- Changes the link to the "Working with Remotes" lesson
- Changes the link text to the "Working with Remotes" lesson

## Issue

Closes #27976

## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project curriculum contributing guide](https://github.com/TheOdinProject/curriculum/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [x] The `Because` section summarizes the reason for this PR
-   [x] The `This PR` section has a bullet point list describing the changes in this PR
-   [x] If this PR addresses an open issue, it is linked in the `Issue` section
-   [ ] If any lesson files are included in this PR, they have been previewed with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure it is formatted correctly
-   [ ] If any lesson files are included in this PR, they follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

### CODE REVIEW

**Comment by T0nci** [comment]
I was searching but could not find the curriculum contributing guide to correctly and successfully run MarkdownLint.

**Comment by T0nci** [comment]
@MaoShizhong I was searching but could not find the curriculum contributing guide to correctly and successfully run MarkdownLint.

**Comment by MaoShizhong** [comment]
@T0nci For future reference, the instructions are in the [curriculum repo contributing guide](https://github.com/TheOdinProject/curriculum/blob/main/CONTRIBUTING.md) which is linked in the first PR checklist item. It's also linked in the general contributing guide in the [repo-specific guides section](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md#repo-specific-contribution-guides).

No action needed this time because the only linting error is something unrelated to this and would need a separate PR.

**Review by MaoShizhong — APPROVED** [review]

**Comment by T0nci** [comment]
@MaoShizong Darn it, my bad! I was seaching for it in the issues checklist as I thought I had seen it in a checklist, but didn't notice it was in the PR template.

**Pull request merged**
