### PR TITLE
Add my solution to HTML/CSS exercise.

### PR DESCRIPTION
**Pull request by mawil583**
This is a PR template. If you are adding a solution link to the curriculum, leave this as is. If not, delete it and write the message you wish.

Thank you,

The Odin Project team.

### CODE REVIEW

**Comment by leila-alderman** [comment]
Please follow the format of all of the other student solutions to add yours:

```
[Mawil's solution](GitHub link) - [View in Browser](GitHub Pages link)
```

**Comment by mawil583** [comment]
> Please follow the format of all of the other student solutions to add yours:
> 
> ```
> [Mawil's solution](GitHub link) - [View in Browser](GitHub Pages link)
> ```

How do I go back and make those changes?

**Comment by leila-alderman** [comment]
You can either go in and edit the file and make another commit on this branch or you can create a completely new pull request with the correct format.

If you have more questions, you're also free to ask in the forum or on our Discord channel.

**Comment by 105ron** [comment]
Closed due to inactivity. Please make a new PR if you still would like your solution to appear on the website. Thanks.

**Pull request closed without merging**
