### PR TITLE
added addtional content to foundation/introduction_to_framework

### PR DESCRIPTION
**Pull request by sumitshinde-84**
## Because

i have added additonal content to foundation/ introduction to framework,

me and my friend have also learned frontend development from odin , and  I appreciate to the Odin resources  but when I was at that stage of odin (introduction to framework)  I was confused even I have read all those articals to understand what is framework  but still I haven't understand , 
To understand what is framework I had read this article and other articles which is on internet .

But in that article you can see they have explained framework in different-different perceptive like - Why do we use frameworks?,
What are the benefits of a framework?,What are the challenges of a framework?,How do you pick the right framework?,The value of framework.
So now I have added this article

the article which i have added - https://www.contentful.com/blog/what-is-a-framework/

## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [x] The `Because` section summarizes the reason for this PR
-   [ ] The `This PR` section has a bullet point list describing the changes in this PR
-   [ ] If this PR addresses an open issue, it is linked in the `Issue` section
-   [ ] If any lesson files are included in this PR, they have been previewed with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure it is formatted correctly
-   [x] If any lesson files are included in this PR, they follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

### CODE REVIEW

**Comment by sumitshinde-84** [comment]
@CouchofTomato request for review

**Review by KevinMulhern — CHANGES_REQUESTED** [review]
> i have added additonal content to foundation/ introduction to framework,

Please tell us **why** you've added this resource in the PR description.

What value does this resource add to the lesson? what will learners get from it, they aren't getting from the other resources already?

From a glance this seems to be a rehash of what the dev.to article explains.

**Comment by sumitshinde-84** [comment]
@KevinMulhern Sir me and my friend have also learned frontend development from odin , and  I appreciate to the Odin resources  but when I was at that stage of odin (introduction to framework)  I was confused even I have read all those articals to understand what is framework  but still I haven't understand , 
To understand what is framework I had read this article and other articles which is on internet .
So now I have added this article

**Comment by KevinMulhern** [comment]
@sumitshinde-84, thank you for updating the description.

I've reviewed the resource and compared it the resources already there. I don't think it adds enough of a different perspective to warrant being added.

The 3 assignment links and additional resource go over largely the same topics and are already probably getting into the too repetitive territory. Another resource with similar content would only frustrate learners instead of help them imo.

What confused you about this lesson? is there something we could improve in the lesson content on Odin instead of  introducing another third party link we will have to depend on?

**Comment by sumitshinde-84** [comment]
@KevinMulhern  
Ok sir but if you  found another brief article then please add it in that section ,
Because  at that stage student mindset cant understand framework concept , they confuse and also get frustrated that time student cant understand what is framework, what is library but why we want it and lot of similar question.

**Comment by sumitshinde-84** [comment]
Now i am about to complete frontend development  and in last few weeks I
have started contributing in open source project,
I have also contributed in odin.
But now I wanna be member of odin organisation . if I will become part of
odin organisation I  will learn lot many things .

So please if you can send me invitation to odin organisation It will be
golden opportunity for me to learning with highly skilled developer (for me
mine Teachers)

**Comment by sumitshinde-84** [comment]
@KevinMulhern Now i am about to complete frontend development  and in last few weeks I have started contributing in open source project, 
I have also contributed in odin.
But now I wanna be member of odin organisation . if I will become part of odin organisation I  will learn lot many things .

So please if you can send me invitation to odin organisation It will be golden opportunity for me to learning with highly skilled developer (for me mine Teachers)

**Comment by KevinMulhern** [comment]
Thank you for the PR's you've submitted these past couple of weeks @sumitshinde-84. We appreciate every contribution we get. It all makes TOP better. 

But we look for a longer history of quality contributions before inviting someone to the maintainer team I'm afraid. Typically many months of contributing. While not being a hard requirement, being an active and helpful community member in Discord is a big plus too.

**Comment by sumitshinde-84** [comment]
@KevinMulhern sir dont worry 
If I became member of odin organisation I will not merge any PR  without asking to you and other member  but really sir I wanna be member of odin project 
And if you will found any mistake you can remove me or I will leave organisation by self
You can trust on me sir and I promise I will maintain our relation for long time

**Comment by KevinMulhern** [comment]
It doesn't work that way for most open source projects unfortunately @sumitshinde-84. A place on the maintainer team is earned not given.

I've started a discussion with the team about the placement of this lesson. I should have something to update you with in a day or so.

Thanks again!

**Comment by sumitshinde-84** [comment]
@KevinMulhern  ok sir ,
i will try to earned it ,
but whenever i need guidence in my  coding journy could i came toward you ? .

**Comment by KevinMulhern** [comment]
> but whenever i need guidence in my coding journy could i came toward you ? .
If you're going through The Odin Project, you can get help in our Discord from the community at any time.

**Comment by sumitshinde-84** [comment]
> 
ok sir

**Comment by KevinMulhern** [comment]
Hey @sumitshinde-84, we're going to remove the backend section from Foundations and probably move it to the backend courses in each path. Thanks for getting the discussion going by pointing this out.

**Comment by sumitshinde-84** [comment]
> Hey @sumitshinde-84, we're going to remove the backend section from Foundations and probably move it to the backend courses in each path. Thanks for getting the discussion going by pointing this out.

Its my pleasure sir

**Pull request closed without merging**
