### PR TITLE
How Does The Web Work: remove duplicate link

### PR DESCRIPTION
**Pull request by KristinaRiabova**
Remove duplicate link "What is a web server"

Complete the following REQUIRED checkboxes:

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`

Complete the following checkboxes ONLY IF they are applicable to your PR. You can complete them later if they are not currently applicable:
-   [x] I have previewed all lesson files included in this PR with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure the Markdown content is formatted correctly
-   [x] I have ensured all lesson files included in this PR follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

<hr>

**1. Because:**

Closes #XXXXX

**2. This PR:**

**3. Additional Information:**

### CODE REVIEW

**Review by SauravJalui — COMMENTED** [review]
Hey @KristinaRiabova,

Thank you for your changes. 

There are 3 "What is a web server?" link in total. There is one more "What is a web server?" link below. Could you please remove that as well?

Best,
Saurav

**Comment by KristinaRiabova** [comment]
Hey @SauravJalui,

Done.

Best,
Kristina

**Review by SauravJalui — COMMENTED** [review]
Perfect! thanks @KristinaRiabova

**Review by KevinMulhern — APPROVED** [review]
Good catch! thanks @KristinaRiabova

**Pull request merged**
