### PR TITLE
Intro to Flexbox:update note for external codepens

### PR DESCRIPTION
**Pull request by antekrtalic**
- [x] You have read [The Odin Projects Contributing Guide](https://github.com/TheOdinProject/curriculum/blob/main/CONTRIBUTING.md).
 - [x] The title summarizes the change and where it happened, for example: "Fixes punctuation in Clean Code lesson".
 - [x] If the PR is related to an open issue, use a [relevant keyword](https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests) and reference it with the `#` sign and the issue number.
 - [x] You have previewed your markdown (if any) in the [Odin Markdown Preview Tool](https://www.theodinproject.com/lessons/preview)
 - [x] If changes are requested, please make the changes in a timely manner. After you submit the changes, request another review from the maintainer (top right).

#### 1. Describe the changes made and include why they are necessary or important:

Codepen embeds may have a button "Fork on Codepen"

#### 2. Related Issue

Closes #XXXXX

### CODE REVIEW

**Comment by zachmmeyer** [comment]
Going through the lessons, I do not see a "Fork on Codepen" button on the embeds. This might make things confusing for others.

**Comment by antekrtalic** [comment]
It did for me
https://cdn.discordapp.com/attachments/540903304046182425/936183042349858856/Screenshot_2022-01-27_09-54-15.png

čet, 27. sij 2022. u 15:20 Zach Meyer ***@***.***> napisao je:

**Review by zachmmeyer — APPROVED** [review]
Fair enough. If it exists for you, it must exist for others as well. Not sure why it comes up for you and not me, other than maybe because you might be logged into codepen and I am not.

Either way, thank you for making a contribution AND thank you for filling out the PR template correctly! I also appreciate your patience with this one.

**Comment by antekrtalic** [comment]
No, actually as far as I remember I wasn't logged in CodePen. I'm glad we
managed to solve it and maybe better understand current or future learners.
Thank you for your patience and understanding.

Best regards,
Ceki

pet, 28. sij 2022. u 11:16 Zach Meyer ***@***.***> napisao je:

**Pull request merged**
