### PR TITLE
Thinking in React.

### PR DESCRIPTION
**Pull request by arbob**
Thought process before building any react application. This article helped me a lot in thinking about the react way of doing things. Hope it helps other students too.

 - [x] You have read [The Odin Projects Contributing Guide](https://github.com/TheOdinProject/curriculum/blob/main/CONTRIBUTING.md).

#### 1.Describe the changes made:

...your text here

#### 2. If this PR is related to an open issue please reference it with the `#` operator and the issue number below:

#XXXXX

### CODE REVIEW

**Comment by CatQueenCodes** [comment]
I like this section of the React docs as well and found it helpful. I do think it would be beneficial to have it more towards the beginning of the react section before the first react project. Possibly in the additional resources of this section (right before CV project) https://www.theodinproject.com/paths/full-stack-javascript/courses/javascript/lessons/handle-inputs-and-render-lists

Anyone else have any opinions on that?

**Comment by twalton83** [comment]
I agree with that sentiment.

**Review by CatQueenCodes — CHANGES_REQUESTED** [review]
I like this section of the React docs as well and found it helpful. I do think it would be beneficial to have it more towards the beginning of the react section before the first react project. Possibly in the additional resources of this section (right before CV project) https://www.theodinproject.com/paths/full-stack-javascript/courses/javascript/lessons/handle-inputs-and-render-lists

**Comment by arbob** [comment]
Agreed. I believe it'd be better to put it in the State and Props section of TOP.

**Pull request closed without merging**
