### PR TITLE
Update Blog-Project.md

### PR DESCRIPTION
**Pull request by nima-m-git**
- [x] You have read [The Odin Projects Contributing Guide](https://github.com/TheOdinProject/curriculum/blob/master/CONTRIBUTING.md).

#### 1.Describe the changes made:

Markdown linebreaks added with backslash \ to hyphenated points. Grammatical fixes.

#### 2. If this PR is related to an open issue please reference it with the `#` operator and the issue number below:

#XXXXX

### CODE REVIEW

**Review by CatQueenCodes — CHANGES_REQUESTED** [review]
The `\` are not necessary for this to load correctly (as you can see with the original version). Looks good aside from that! Once you remove all the added `\` we can approve this.

**Comment by nima-m-git** [comment]
Are you sure? There appears to be no linebreaks where the hyphens are when the markdown is formatted on the website at https://www.theodinproject.com/courses/nodejs/lessons/blog-api

**Comment by CatQueenCodes** [comment]
@nima-m-git  Ah! I see. You are right, *but* the rest of our .md files use a blank line (enter 2x) after each bullet point sentence. 

Removing the `\` and adding an extra line between each thing should fix it!

you can copy and paste your md code https://www.theodinproject.com/lessons/preview here to see how it'll render on the site

**Comment by CatQueenCodes** [comment]
@nima-m-git  did you see my above comment? https://github.com/TheOdinProject/curriculum/pull/21991#issuecomment-743431139

**Comment by CatQueenCodes** [comment]
Thank you for the changes! We appreciate it!  (sorry for the confusion earlier!)

**Pull request merged**
