### PR TITLE
Add my Where's Waldo solutions

### PR DESCRIPTION
**Pull request by SophiaLWu**
```
This is a PR template, If you are adding a solution link to the curriculum leave this as is. If you are not, then delete it and write the message you wish.
Thank you,
The Odin Project team.

```

### CODE REVIEW

**Comment by codyloyd** [comment]
Great Job!

**Comment by codyloyd** [comment]
@SophiaLWu do you mind if we tweet your where's waldo solution from @TheOdinProject ?

**Comment by SophiaLWu** [comment]
Not at all! Go for it :)

Thanks,
Sophia Wu

**Comment by codyloyd** [comment]
https://twitter.com/TheOdinProject/status/858873514669088768

**Comment by SophiaLWu** [comment]
Very cool! Thank you :)

**Pull request merged**
