### PR TITLE
Project: Custom Enumerables: Added link to Additional resources list

### PR DESCRIPTION
**Pull request by MidlifeMechanicus**
Added a link to an article that I found very helpful in getting me started on the project.

## Issue

Closes #XXXXX

## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project curriculum contributing guide](https://github.com/TheOdinProject/curriculum/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [x] The `Because` section summarizes the reason for this PR
-   [x] The `This PR` section has a bullet point list describing the changes in this PR
-   [x] If this PR addresses an open issue, it is linked in the `Issue` section
-   [x] If any lesson files are included in this PR, they have been previewed with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure it is formatted correctly
-   [x] If any lesson files are included in this PR, they follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

### CODE REVIEW

**Review by CouchofTomato — APPROVED** [review]

**Comment by CouchofTomato** [comment]
There's a few linting issues with this lesson. Are you happy to try and address them?

**Comment by MidlifeMechanicus** [comment]
Attempted to address the preexisting linting issues.

**Comment by MidlifeMechanicus** [comment]
Is there something more that I need to do in order to complete the pull request? Not trying to be impatient - I'm just clueless, and don't want to be making other people wait on me!

**Comment by SumonGFC** [comment]
@MidlifeMechanicus Don't worry, just need to give it time for the reviewer/maintainer to review your changes. Your commits look good to me so they will probably be merged soon (keep in mind I am also new to github and oss). Maintainers here are doing this voluntarily and it's a lot of work, so don't stress if it is taking a long time (days-weeks) for your PR to get reviewed or merged (or rejected lol).

**Comment by CouchofTomato** [comment]
All looks good. Thanks

**Pull request merged**
