### PR TITLE
Update Functional Component to a Class Component

### PR DESCRIPTION
**Pull request by portareset1**
- [x] You have read [The Odin Projects Contributing Guide](https://github.com/TheOdinProject/curriculum/blob/main/CONTRIBUTING.md).
 - [x] The title summarizes the change and where it happened, for example: "Fixes punctuation in Clean Code lesson".
 - [x] If the PR is related to an open issue, use a [relevant keyword](https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests) and reference it with the `#` sign and the issue number.
 - [x] You have previewed your markdown (if any) in the [Odin Markdown Preview Tool](https://www.theodinproject.com/lessons/preview)
 - [x] If changes are requested, please make the changes in a timely manner. After you submit the changes, request another review from the maintainer (top right).

#### 1. Describe the changes made and include why they are necessary or important:

At the beginning of the lesson is stated that we were going to work with Class Components only for the sake of the course to know how to do things in both ways, so I'm proposing this change to follow the Class Components only rule stated earlier in the same assignment, thanks.

#### 2. Related Issue

NA

### CODE REVIEW

**Comment by zachmmeyer** [comment]
@portareset1 A bit of feedback on your PR body: The related issue number is not supposed to be the same number as the PR itself. It is supposed to be the number of an Issue that is created, which is usually made before the PR. The PR would be addressing the Issue, and you can use a keyword like you did to automatically close said Issue once the PR is merged.

In this case, there would be no Issue number.

**Comment by portareset1** [comment]
> @portareset1 A bit of feedback on your PR body: The related issue number is not supposed to be the same number as the PR itself. It is supposed to be the number of an Issue that is created, which is usually made before the PR. The PR would be addressing the Issue, and you can use a keyword like you did to automatically close said Issue once the PR is merged.
> 
> In this case, there would be no Issue number.

ahhhh, that definitively have sense, thanks for pointing that

**Comment by zachmmeyer** [comment]
@portareset1 You only have to open an issue to report something. If you point it out in the chat and get approved for it, it doesn't need an issue.
Also, making an issue allows other people, or yourself, to get assigned to it and solve the issue.
It's probably more formal to make an issue for every problem, but if you get the go-ahead in the chat, you're better off making a PR if you want to fix it yourself.

**Comment by portareset1** [comment]
> @portareset1 You only have to open an issue to report something. If you point it out in the chat and get approved for it, it doesn't need an issue. Also, making an issue allows other people, or yourself, to get assigned to it and solve the issue. It's probably more formal to make an issue for every problem, but if you get the go-ahead in the chat, you're better off making a PR if you want to fix it yourself.

I see, well I've anyways removed the related issue # from the body of my PR, nice to know that info again

**Review by wise-king-sullyman — COMMENTED** [review]
This PR looks great, but we are actually currently debating changing our React course to lead with functional components rather than class based. If we decide to keep this lesson class based though I will come back and merge it 🙂

**Comment by thatblindgeye** [comment]
Due to the age of this PR  I will be closing it.

**Pull request closed without merging**
