### PR TITLE
Update project_html_css.md

### PR DESCRIPTION
**Pull request by chanjman**
```
This is a PR template, If you are adding a solution link to the curriculum leave this as is. If you are not, then delete it and write the message you wish.
Thank you,
The Odin Project team.

```

### CODE REVIEW

**Comment by ChadKreutzer** [comment]
Your "view in browser" link does not seem to be working.

**Comment by chanjman** [comment]
How about now?

**Comment by KevinMulhern** [comment]
Yup its working 😄 nice touch with the Santa animation

**Comment by chanjman** [comment]
Thanks, I tried my best :)

**Pull request merged**
