### PR TITLE
Ruby-on-Rails: Fix 'knowledge check' sections to align with style gui…

### LINKED ISSUE #27090: All: Update the 'Knowledge check' questions to be contained inside the details element
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

I really liked the Knowledge check section on the Turbo lesson. And to be consistent, I thought we should update all of them to be like it.

Most lessons:
Screenshot 2024-01-08 at 11 41 55 PM

Turbo and Stimulus lessons:
Screenshot 2024-01-08 at 11 41 30 PM

### Path

Foundations, Ruby / Rails, Node / JS

### Lesson Url

All the lessons that contain the 'Knowledge check' section

### (Optional) Discord Name

dreamvenerable

### (Optional) Additional Comments

I'm not sure if it used to all be like the Turbo lesson and it was changed to be links, and those 2 lessons were missed, if so then this issue would be to change them into links.

### PR DESCRIPTION
**Pull request by rubicon2**
Closes #27090

## Because

On the Ruby-on-Rails course, Turbo and Stimulus lessons, fix 'knowledge check' sections to align with the style guide.

## This PR

- Replaced drop down quiz with links to relevant lesson sections
- Replaced 'knowledge check' intro text as per markdownlint rule (TOP003/default-section-content)

## Issue

Closes #27090 

## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [x] The `Because` section summarizes the reason for this PR
-   [x] The `This PR` section has a bullet point list describing the changes in this PR
-   [x] If this PR addresses an open issue, it is linked in the `Issue` section
-   [x] If any lesson files are included in this PR, they have been previewed with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure it is formatted correctly
-   [x] If any lesson files are included in this PR, they follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

### CODE REVIEW

**Review by JoshDevHub — COMMENTED** [review]
Looks great @rubicon2  :raised_hands: 

Before I merge, there are a number of lint errors in this file. They weren't introduced by you, and you shouldn't feel obligated to fix them if you don't want to. But if you do want to, you can find them by clicking the 'Files changed' tab and looking through the right column of the diff. You can also read [the section on linting](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md#curriculum-linting) in our contributing guide if you want to learn how to view these errors in your local environment.

If you do want to make the changes, you can ignore the heading structure problem in the stimulus lesson. Fixing that will require a deeper change to the structure of the lesson, and we're not gonna bother with fixing that in this PR.

**Comment by rubicon2** [comment]
Thanks Josh! I have made another commit that fixes all the linting errors in the Turbo lesson. 

I worked on it in my local environment with the vscode plugin and it shows one more error: MD024/no-duplicate-heading, since there are two separate headings for "Hotwire" (lines 27 & 325). However this error isn't showing up on the github 'files changed' tab?

**Comment by JoshDevHub** [comment]
Awesome! Thanks for fixing these issues. There are two items left.

1. As you've noticed locally, there's the duplicate heading issue in the Turbo lesson. The "Files changed" tab may be unreliable sometimes. One reason is that because you're new to contributing, the workflows don't automatically run for each commit you make, and a maintainer must manually approve them. This is to keep malicious users from spamming the repo and using up a bunch GitHub's computing resources to run the actions. This restriction will go away as you contribute more. Anyways, I think we can just get rid of the subheadings in the Assignment section (which I don't think are very useful). This should fix this problem.
  ```md
<!-- instead of this -->
#### Single-page applications

1. Read sections 1, 2, and 3 of Bloomreach's [What Are Single Page Applications and Why Do People Like Them So Much?](https://www.bloomreach.com/en/blog/2018/07/what-is-a-single-page-application.html#whatssingle-page-application)
   article

#### Hotwire

1. Watch the [Hotwire Demo Video](https://www.youtube.com/watch?v=eKY-QES1XQQ)
    - We have only covered content up until the 5:40 mark, but you may continue watching past that point to become more familiar with
      other aspects of Hotwire that we will be covering in upcoming lessons.
    - The video is edited to be a very quick showcase. Don't worry about trying to pause and use this video as a tutorial. Just sit back
      and use this demo to watch how Turbo Drive, Frames, & Streams come together visually.
1. Skim through sections 1-4 of the [Turbo Handbook](https://turbo.hotwired.dev/handbook/introduction)
    - This Handbook is written to be backend-agnostic, meaning that the code you will see is pure HTML and not Rails tags, but it still
      is a useful resource for referencing how Turbo works.
1. Take a quick glance at the Turbo-Rails gem [RubyDoc info page](https://www.rubydoc.info/gems/turbo-rails/1.0.0)
    - This resource covers the Rails-specific syntaxes and tags you can use for Turbo. You don't need to read anything now, just know that
      it exists so you can come back to it when you need to figure out how to use a specific piece of Turbo in your applications.

<!-- Just do this -->
1. Read sections 1, 2, and 3 of Bloomreach's [What Are Single Page Applications and Why Do People Like Them So Much?](https://www.bloomreach.com/en/blog/2018/07/what-is-a-single-page-application.html#whatssingle-page-application)
   article
1. Watch the [Hotwire Demo Video](https://www.youtube.com/watch?v=eKY-QES1XQQ)
    - We have only covered content up until the 5:40 mark, but you may continue watching past that point to become more familiar with
      other aspects of Hotwire that we will be covering in upcoming lessons.
    - The video is edited to be a very quick showcase. Don't worry about trying to pause and use this video as a tutorial. Just sit back
      and use this demo to watch how Turbo Drive, Frames, & Streams come together visually.
1. Skim through sections 1-4 of the [Turbo Handbook](https://turbo.hotwired.dev/handbook/introduction)
    - This Handbook is written to be backend-agnostic, meaning that the code you will see is pure HTML and not Rails tags, but it still
      is a useful resource for referencing how Turbo works.
1. Take a quick glance at the Turbo-Rails gem [RubyDoc info page](https://www.rubydoc.info/gems/turbo-rails/1.0.0)
    - This resource covers the Rails-specific syntaxes and tags you can use for Turbo. You don't need to read anything now, just know that
      it exists so you can come back to it when you need to figure out how to use a specific piece of Turbo in your applications.
  ```
2. The other problem is related to heading structure in the Stimulus lesson. You can see this in the 'Files changed' tab now because I've forced the actions to run. This probably doesn't appear for you locally in vscode because the heading structure is set in a way where the vscode extension can't properly understand it. Anyways, we should be able to clean this one up by making the `Exercises` heading on line 284 a level 4 heading instead of a level 3 heading.

After these two changes, we should be good to merge.

**Comment by rubicon2** [comment]
Well, I made an unbelievable hash of trying to integrate the upstream changes into my repository, and the whole thing ended up a mess, as you can see from all the unrelated commits above. I'll start fresh and try again!

**Pull request closed without merging**
